Repository openshift/installer, pull requests merged in 2018-10, with the labels that each got.

#357 pkg/types/config: Prefix "pull secret" in validatePullSecret
  pkg/types/config/validate.go
Labels: approved, lgtm, size/XS

#384 Update libvirt how to doc
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/XS

#387 pkg/destroy/libvirt: Add behind a libvirt_destroy build tag
  cmd/openshift-install/main.go
  docs/dev/dependencies.md
  docs/dev/libvirt-howto.md
  hack/build.sh
  pkg/destroy/aws.go
  pkg/destroy/destroyer.go
  pkg/destroy/libvirt/doc.go
  pkg/destroy/libvirt/libvirt_prefix_deprovision.go
  pkg/destroy/libvirt/register.go
  pkg/types/clustermetadata.go
Labels: approved, lgtm, size/L

#144 OpenStack provider support
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/topology/common.tf
  data/data/openstack/topology/outputs.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/sg-lb.tf
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platform.go
  pkg/asset/manifests/machine-api-operator.go
  pkg/asset/metadata/metadata.go
  pkg/types/clustermetadata.go
  pkg/types/config/cluster.go
  pkg/types/config/openstack/openstack.go
  pkg/types/config/validate.go
  pkg/types/installconfig.go
  pkg/types/machinepools.go
Labels: approved, lgtm, size/XXL

#389 build: read go path from go env
  hack/build.sh
Labels: approved, lgtm, size/XS

#353 *: Copy route53 baseDomain advice to openshift-install locations
  docs/user/environment-variables.md
  pkg/asset/installconfig/stock.go
Labels: approved, lgtm, size/M

#356 hack/get-terraform: Use 'go env ...' to support other platforms
  hack/get-terraform.sh
Labels: approved, lgtm, size/S

#392 pkg/asset/installconfig/ssh: Fix OPENSHIFT_INSTALL_SSH_PUB_KEY injection
  pkg/asset/installconfig/ssh.go
Labels: approved, lgtm, size/S

#390 cmd/openshift-install: Add a 'version' subcommand
  CHANGELOG.md
  cmd/openshift-install/main.go
  hack/build.sh
Labels: approved, lgtm, size/M

#398 .github/ISSUE_TEMPLATE: Bring this back up to speed
  .github/ISSUE_TEMPLATE.md
Labels: approved, lgtm, size/M

#401 README.md: Document supported platforms.
  README.md
Labels: approved, lgtm, size/XS

#395 pkg/types/config/libvirt/cache: Cache unpacked files as well
  pkg/types/config/libvirt/cache.go
Labels: approved, lgtm, size/L

#399 cmd/openshift-install: Add Terraform version to 'version' output
  .github/ISSUE_TEMPLATE.md
  cmd/openshift-install/main.go
  pkg/terraform/executor.go
Labels: approved, lgtm, size/M

#407 openstack: Adds egresses to the worker and master
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, lgtm, size/S

#408 libvirt: increase master memory to 3GB
  data/data/libvirt/main.tf
Labels: approved, lgtm, size/XS

#415 manifests: add cvo-overrides
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
Labels: approved, lgtm, size/M

#400 Wrap all errors with context
  Gopkg.lock
  Gopkg.toml
  cmd/openshift-install/main.go
  pkg/asset/asset.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platform.go
  pkg/asset/installconfig/ssh.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/kubeconfig/kubeconfig_test.go
  pkg/asset/manifests/kube-addon-operator.go
  pkg/asset/manifests/kube-core-operator.go
  pkg/asset/manifests/machine-api-operator.go
  pkg/asset/manifests/network-operator.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/tectonic.go
  pkg/asset/metadata/metadata.go
  pkg/asset/state.go
  pkg/asset/store.go
  pkg/asset/tls/certkey.go
  pkg/asset/tls/certkey_test.go
  pkg/asset/tls/keypair.go
  pkg/asset/tls/root.go
  pkg/asset/tls/tls.go
  pkg/asset/tls/utils.go
  pkg/asset/userprovided.go
  pkg/destroy/destroyer.go
  pkg/destroy/libvirt/libvirt_prefix_deprovision.go
  pkg/ipnet/ipnet.go
  pkg/rhcos/ami.go
  pkg/terraform/executor.go
  pkg/terraform/terraform.go
  pkg/types/config/cluster.go
  pkg/types/config/parser.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, lgtm, size/XL

#410 Change default tt0 cidr
  docs/dev/libvirt-howto.md
  pkg/asset/installconfig/platform.go
Labels: approved, lgtm, size/S

#322 Start rendering assets using cluster-kube-apiserver operator renderer
  pkg/asset/ignition/content/bootkube.go
Labels: approved, lgtm, size/M

#381 Render openshift-cluster-kube-scheduler-operator assets
  pkg/asset/ignition/content/bootkube.go
Labels: approved, lgtm, size/S

#402 README: Add console and cleanup information
  README.md
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/M

#403 pkg/types/config: Drop ParseConfig and other Parse* methods
  pkg/types/config/parser.go
Labels: approved, lgtm, size/M

#418 Fix OpenStack platform survey prompts.
  pkg/asset/installconfig/platform.go
Labels: approved, lgtm, size/S

#412 pkg/types/config: Break into pkg/validate and pkg/tfvars
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/node.go
  pkg/asset/installconfig/stock.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/manifests/kube-addon-operator.go
  pkg/asset/manifests/kube-core-operator.go
  pkg/asset/manifests/machine-api-operator.go
  pkg/asset/metadata/metadata.go
  pkg/asset/tls/helper.go
  pkg/tfvars/aws/aws.go
  pkg/tfvars/libvirt/cache.go
  pkg/tfvars/libvirt/libvirt.go
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/tfvars.go
  pkg/types/config/cluster.go
  pkg/types/config/fixtures/ign.ign
  pkg/types/config/fixtures/invalid-ign.ign
  pkg/types/config/types.go
  pkg/types/config/validate.go
  pkg/types/config/validate_test.go
  pkg/types/installconfig.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/XXL

#425 asset/manifests: disable olm api server
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
Labels: approved, lgtm, size/XS

#423 cmd/openshift-install: Log Terraform errors when not in debug mode
  cmd/openshift-install/main.go
  pkg/terraform/executor.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, size/S

#424 pkg/asset/cluster: Drop duplicate path from "Failed to read tfstate"
  pkg/asset/cluster/cluster.go
Labels: approved, lgtm, size/XS

#422 *: removed unneeded configuration
  .dockerignore
  .editorconfig
  .gitignore
Labels: approved, lgtm, size/M

#419 Revert "Adds egresses to the worker and master"
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, lgtm, size/S

#421 pkg/asset: update tectonic-operators to drop all openshift apis
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/content/tectonic.go
  pkg/asset/manifests/content/tectonic/tectonic-system-02-pull.go
  pkg/asset/manifests/content/tectonic/tectonic-system-03-privileged-scc.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/tectonic.go
Labels: approved, lgtm, size/S

#429 Switch cli to github.com/spf13/cobra
  Gopkg.lock
  Gopkg.toml
  cmd/openshift-install/destroy.go
  cmd/openshift-install/main.go
  cmd/openshift-install/targets.go
  cmd/openshift-install/version.go
  vendor/github.com/alecthomas/template/LICENSE
  vendor/github.com/alecthomas/template/doc.go
  vendor/github.com/alecthomas/template/exec.go
  vendor/github.com/alecthomas/template/funcs.go
  vendor/github.com/alecthomas/template/helper.go
  vendor/github.com/alecthomas/template/parse/lex.go
  vendor/github.com/alecthomas/template/parse/node.go
  vendor/github.com/alecthomas/template/parse/parse.go
  vendor/github.com/alecthomas/template/template.go
  vendor/github.com/alecthomas/units/COPYING
  vendor/github.com/alecthomas/units/bytes.go
  vendor/github.com/alecthomas/units/doc.go
  vendor/github.com/alecthomas/units/si.go
  vendor/github.com/alecthomas/units/util.go
  vendor/gopkg.in/alecthomas/kingpin.v2/COPYING
  vendor/gopkg.in/alecthomas/kingpin.v2/actions.go
  vendor/gopkg.in/alecthomas/kingpin.v2/app.go
  vendor/gopkg.in/alecthomas/kingpin.v2/args.go
  vendor/gopkg.in/alecthomas/kingpin.v2/cmd.go
  vendor/gopkg.in/alecthomas/kingpin.v2/completions.go
  vendor/gopkg.in/alecthomas/kingpin.v2/doc.go
  vendor/gopkg.in/alecthomas/kingpin.v2/envar.go
  vendor/gopkg.in/alecthomas/kingpin.v2/flags.go
  vendor/gopkg.in/alecthomas/kingpin.v2/global.go
  vendor/gopkg.in/alecthomas/kingpin.v2/guesswidth.go
  vendor/gopkg.in/alecthomas/kingpin.v2/guesswidth_unix.go
  vendor/gopkg.in/alecthomas/kingpin.v2/model.go
  vendor/gopkg.in/alecthomas/kingpin.v2/parser.go
  vendor/gopkg.in/alecthomas/kingpin.v2/parsers.go
  vendor/gopkg.in/alecthomas/kingpin.v2/templates.go
  vendor/gopkg.in/alecthomas/kingpin.v2/usage.go
  vendor/gopkg.in/alecthomas/kingpin.v2/values.go
  vendor/gopkg.in/alecthomas/kingpin.v2/values_generated.go
Labels: approved, lgtm, size/XXL

#430 update to allow openshift operator to run
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
Labels: approved, lgtm, size/XS

#436 fix copy statement
  pkg/asset/ignition/content/bootkube.go
Labels: approved, lgtm, size/XS

#434 remove unnecessary scc
  pkg/asset/manifests/content/tectonic/tectonic-system-03-privileged-scc.go
  pkg/asset/manifests/tectonic.go
Labels: approved, lgtm, size/M

#431 assets/bootkube: add etcd service and endpoints for apiservers.
  pkg/asset/manifests/content/bootkube/etcd-service-endpoints.go
  pkg/asset/manifests/content/bootkube/etcd-service.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
Labels: approved, lgtm, size/M

#437 Add the service-serving-cert-signer CA secret
  pkg/asset/manifests/content/bootkube/09-openshift-service-cert-signer-namespace.go
  pkg/asset/manifests/content/bootkube/openshift-service-cert-signer-ca-secret.go
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/M

#432 add graph subcommand that ouputs the installer's internal dependency graph
  Gopkg.lock
  Gopkg.toml
  cmd/openshift-install/graph.go
  cmd/openshift-install/main.go
  cmd/openshift-install/targets.go
  docs/design/assetgeneration.md
  docs/design/resource_dep.dot
  docs/design/resource_dep.svg
  vendor/github.com/awalterschulze/gographviz/AUTHORS
  vendor/github.com/awalterschulze/gographviz/CONTRIBUTORS
  vendor/github.com/awalterschulze/gographviz/LICENSE
  vendor/github.com/awalterschulze/gographviz/analyse.go
  vendor/github.com/awalterschulze/gographviz/ast/ast.go
  vendor/github.com/awalterschulze/gographviz/attr.go
  vendor/github.com/awalterschulze/gographviz/attrs.go
  vendor/github.com/awalterschulze/gographviz/catch.go
  vendor/github.com/awalterschulze/gographviz/edges.go
  vendor/github.com/awalterschulze/gographviz/escape.go
  vendor/github.com/awalterschulze/gographviz/gographviz.go
  vendor/github.com/awalterschulze/gographviz/graph.go
  vendor/github.com/awalterschulze/gographviz/internal/errors/errors.go
  vendor/github.com/awalterschulze/gographviz/internal/lexer/acttab.go
  vendor/github.com/awalterschulze/gographviz/internal/lexer/lexer.go
  vendor/github.com/awalterschulze/gographviz/internal/lexer/transitiontable.go
  vendor/github.com/awalterschulze/gographviz/internal/parser/action.go
  vendor/github.com/awalterschulze/gographviz/internal/parser/actiontable.go
  vendor/github.com/awalterschulze/gographviz/internal/parser/gototable.go
  vendor/github.com/awalterschulze/gographviz/internal/parser/main.go
  vendor/github.com/awalterschulze/gographviz/internal/parser/parser.go
  vendor/github.com/awalterschulze/gographviz/internal/parser/productionstable.go
  vendor/github.com/awalterschulze/gographviz/internal/token/token.go
  vendor/github.com/awalterschulze/gographviz/nodes.go
  vendor/github.com/awalterschulze/gographviz/relations.go
  vendor/github.com/awalterschulze/gographviz/subgraphs.go
  vendor/github.com/awalterschulze/gographviz/write.go
Labels: approved, lgtm, size/XXL

#439 pkg/manifests: drop old operatorstatus crd
  pkg/asset/manifests/content/bootkube/operatorstatus-crd.go
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/M

#443 assets/manifests: switch from image source for mco bootstrap
  pkg/asset/ignition/content/bootkube.go
  pkg/asset/manifests/content/bootkube/machine-config-operator-01-images-configmap.go
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/M

#446 bootkube: use etcd-client-ca as serving CA of etcd
  pkg/asset/ignition/content/bootkube.go
Labels: approved, lgtm, size/XS

#445 remove mao appVersion
  pkg/asset/manifests/content/bootkube/app-version-mao.go
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/S

#450 add etcd prometheus scraping label and remove old etcd port
  pkg/asset/manifests/content/bootkube/etcd-service.go
Labels: approved, lgtm, size/XS

#377 New doc on how to integrate an operator
  docs/dev/operators.md
Labels: approved, lgtm, size/M

#435 stop creating cvo static pod
  pkg/asset/ignition/content/bootkube.go
Labels: approved, lgtm, size/XS

#454 pkg/asset/cluster: Pull metadata into the Cluster asset
  cmd/openshift-install/main.go
  cmd/openshift-install/targets.go
  docs/design/resource_dep.svg
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/manifests/kube-addon-operator.go
  pkg/asset/manifests/kube-core-operator.go
  pkg/asset/metadata/doc.go
  pkg/asset/metadata/metadata.go
  pkg/destroy/destroyer.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, size/XXL

#456 docs/dev/libvirt-howto: Fix "firewalld-cmd" -> "firewall-cmd" typo
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/XS

#388 Save assets in a state file on disk
  cmd/openshift-install/main.go
  cmd/openshift-install/targets.go
  pkg/asset/asset_test.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/installconfig/basedomain.go
  pkg/asset/installconfig/clusterid.go
  pkg/asset/installconfig/clustername.go
  pkg/asset/installconfig/emailaddress.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/password.go
  pkg/asset/installconfig/platform.go
  pkg/asset/installconfig/pullsecret.go
  pkg/asset/installconfig/ssh.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/manifests/kube-addon-operator.go
  pkg/asset/manifests/kube-core-operator.go
  pkg/asset/manifests/machine-api-operator.go
  pkg/asset/manifests/network-operator.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/tectonic.go
  pkg/asset/store.go
  pkg/asset/tls/certkey.go
  pkg/asset/tls/keypair.go
  pkg/asset/tls/root.go
Labels: approved, lgtm, size/L

#461 CHANGELOG: Document changes since v0.1.0
  CHANGELOG.md
Labels: approved, lgtm, size/M

#462 CHANGELOG: Remove redundant 'emacs'
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#460 pkg/asset/store: Use '%q' for formatting quoted strings
  pkg/asset/store.go
Labels: approved, lgtm, size/XS

#464 pkg/tfvars/libvirt/cache: Close before renaming
  pkg/tfvars/libvirt/cache.go
Labels: approved, lgtm, size/S

#466 pkg/tfvars: Drop AWS.Profile
  data/data/aws/main.tf
  data/data/aws/variables-aws.tf
  pkg/tfvars/aws/aws.go
  pkg/tfvars/tfvars.go
Labels: approved, lgtm, size/S

#463 cmd/openshift-install: Fix "intall" -> "install" typo
  cmd/openshift-install/main.go
Labels: approved, lgtm, size/XS

#459 asset/ignition: add event on bootstrap completion
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/content/bootkube.go
  pkg/asset/ignition/bootstrap/content/doc.go
  pkg/asset/ignition/bootstrap/content/kubelet.go
  pkg/asset/ignition/bootstrap/content/report.go
  pkg/asset/ignition/bootstrap/content/tectonic.go
Labels: approved, lgtm, size/L

#457 bootkube: remove wrong optional override files
  pkg/asset/ignition/bootstrap/content/bootkube.go
Labels: approved, lgtm, size/XS

#471 ignition assets: fix progress event creation
  pkg/asset/ignition/bootstrap/content/report.go
Labels: approved, lgtm, size/XS

#469 bootstrap assets: remove secret copy for kube-controller-manager and kube-scheduler
  pkg/asset/ignition/bootstrap/content/bootkube.go
Labels: approved, lgtm, size/XS

#468 pkg/asset: Add asset for Worker machinesets
  pkg/asset/machines/aws/aws.go
  pkg/asset/machines/cluster_k8s_io.go
  pkg/asset/machines/doc.go
  pkg/asset/machines/libvirt/libvirt.go
  pkg/asset/machines/userdata.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/machine-api-operator.go
  pkg/asset/manifests/tectonic.go
  pkg/types/machinepools.go
Labels: approved, lgtm, size/L

#480 pkg/asset: add OpenStack machines.Worker assets
  pkg/asset/machines/openstack/openstack.go
  pkg/asset/machines/worker.go
  pkg/types/installconfig.go
Labels: approved, lgtm, size/L

#420 replace kube-core rendering with openshift operators render
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/content/bootkube.go
  pkg/asset/ignition/bootstrap/content/bootkube_temporary.go
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
  pkg/asset/manifests/content/tectonic/kube-core-00-appversion.go
  pkg/asset/manifests/content/tectonic/kube-core-00-operator.go
  pkg/asset/manifests/kube-core-operator.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/tectonic.go
  pkg/asset/tls/kubeletcertkey.go
Labels: approved, lgtm, size/XL

#489 data/aws: Drop the bucket name
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/M

#479 Tag master machines for adoption by machine controller
  data/data/aws/master/main.tf
Labels: approved, lgtm, size/XS

#492 pkg/asset/cluster: Drop redundant os.TempDir()
  pkg/asset/cluster/cluster.go
Labels: approved, lgtm, size/XS

#374 pkg/asset: Introduce Load() into the Asset interface that loads assets (from disk)
  cmd/openshift-install/targets.go
  docs/design/assetgeneration.md
  pkg/asset/asset.go
  pkg/asset/asset_test.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/filefetcher.go
  pkg/asset/filefetcher_test.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/kubeconfig/admin.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/kubeconfig/kubeconfig_test.go
  pkg/asset/kubeconfig/kubelet.go
  pkg/asset/manifests/kube-addon-operator.go
  pkg/asset/manifests/machine-api-operator.go
  pkg/asset/manifests/network-operator.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/tectonic.go
  pkg/asset/store.go
  pkg/asset/store_test.go
  pkg/asset/tls/certkey.go
  pkg/asset/tls/serviceaccountkeypair.go
Labels: approved, lgtm, size/XL

#496 Re-disable the cluster-ingress-operator
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
Labels: approved, lgtm, size/XS

#490 data/aws/vpc/vpc-private: Set worker subnet availability_zone
  data/data/aws/vpc/vpc-private.tf
Labels: approved, lgtm

#498 assets: disable pod-checkpointer-operator during bringup phase
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
Labels: approved, lgtm, size/XS

#474 hack/build.sh: Check that source is in GOPATH.
  hack/build.sh
Labels: approved, lgtm, size/S

#499 pkg/asset: Fix name of libvirt master machine
  pkg/asset/machines/libvirt/master.go
Labels: approved, lgtm, size/XS

#497 pkg/asset/filefetcher: Only load files on demand
  docs/design/assetgeneration.md
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/filefetcher.go
  pkg/asset/filefetcher_test.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/tectonic.go
  pkg/asset/store.go
Labels: approved, lgtm, size/L

#500 Docfix: fix libvirt destroy link
  docs/dev/dependencies.md
Labels: approved, lgtm, size/XS

#503 docs: add initial documentation for end users
  docs/user/overview.md
Labels: approved, lgtm, size/M

#505 */BUILD.bazel: Remove leftover Bazel files
  pkg/asset/manifests/content/tectonic/BUILD.bazel
  tests/smoke/vendor/k8s.io/kubernetes/BUILD.bazel
Labels: approved, lgtm, size/S

#511 dev-dependencies: Just use `yum` on Fedora too
  docs/dev/dependencies.md
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/S

#501 manifests: stripe workers across machinesets in each AZ for aws.
  pkg/asset/machines/aws/worker.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/L

#483 Update libvirt how to guide.
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/XS

#512 docs: add IP forwarding to libvirt doc
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/M

#504 CHANGELOG: Document changes since v0.2.0
  CHANGELOG.md
Labels: approved, lgtm, size/M

#514 Docs: update instructions to install libvirt and libvirt-devel packages
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/XS

#513 cmd/openshift-install: Push creation under 'openshift create'
  README.md
  cmd/openshift-install/create.go
  cmd/openshift-install/main.go
  docs/design/assetgeneration.md
Labels: approved, lgtm, size/M

#515 asset/ignition: remove bootstrap node from cluster
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/content/kubelet.go
Labels: approved, lgtm, size/M

#524 cvo-overrides: fix namespace for openshift-pod-checkpointer
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
Labels: approved, lgtm, size/XS

#509 pkg/destroy/bootstrap: Fix cross-filesystem tfstate recovery
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, kind/bug, lgtm, size/XS

#519 add explicit machineset label
  pkg/asset/machines/aws/worker.go
  pkg/asset/machines/libvirt/worker.go
  pkg/asset/machines/openstack/worker.go
Labels: approved, lgtm, size/S

#527 pkg/asset/store: Use the asset directory in StoreImpl.Purge
  pkg/asset/store.go
Labels: approved, lgtm, size/XS

#525 asset/ignition: properly signal bootstrap complete
  pkg/asset/ignition/bootstrap/content/bootkube.go
  pkg/asset/ignition/bootstrap/content/tectonic.go
Labels: approved, lgtm, size/S

#531 CONTRIBUTING: Update the security contact for CoreOS -> Red Hat
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#534 asset/store: clean up logging and logic
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/store.go
Labels: approved, lgtm, size/M

#536 asset/store: try to reuse assets from state file
  pkg/asset/store.go
Labels: approved, lgtm, size/S

#467 Re-enable cluster ingress operator (remove from overriden set)
  pkg/asset/manifests/content/bootkube/02-ingress-namespace.go
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
  pkg/asset/manifests/content/tectonic/tectonic-ingress-00-appversion.go
  pkg/asset/manifests/content/tectonic/tectonic-ingress-01-cluster-config.go
  pkg/asset/manifests/content/tectonic/tectonic-ingress-02-tls.go
  pkg/asset/manifests/content/tectonic/tectonic-ingress-03-pull.go
  pkg/asset/manifests/content/tectonic/tectonic-ingress-04-svc-account.go
  pkg/asset/manifests/content/tectonic/tectonic-ingress-05-operator.go
  pkg/asset/manifests/content/tectonic/tectonic-system-01-ca-cert.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/tectonic.go
  pkg/asset/manifests/template.go
Labels: approved, lgtm, size/L

#541 cvo-override: disable checkpointer operator on new namespace
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
Labels: approved, lgtm, size/XS

#533 asset/ignition: Drop binaries in /usr/local/bin
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/content/bootkube.go
  pkg/asset/ignition/bootstrap/content/report.go
  pkg/asset/ignition/bootstrap/content/tectonic.go
Labels: approved, lgtm, size/S

#555 docs/design/cluster-bootstrap-flow: Drop obsolete docs
  docs/design/cluster-bootstrap-flow.md
Labels: approved, lgtm, size/S

#544 Add OpenStack to clustermetadata.go
  pkg/types/clustermetadata.go
Labels: approved, lgtm, size/XS

#526 Add SRV records for bootstrapping etcd using DNS.
  data/data/aws/main.tf
  data/data/libvirt/main.tf
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/S

#559 Revert "docs: update libvirt provider repo"
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/XS

#518 drop deprecated mao config
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/content/bootkube/cluster-apiserver-certs.go
  pkg/asset/manifests/machine-api-operator.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/tls/clusterapiservercertkey.go
Labels: approved, lgtm, size/L

#561 vendor: bump github.com/openshift/hive
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/hive/contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: approved, lgtm, size/M

#568 pkg/asset/manifests: Drop oidc-ca.crt
  pkg/asset/manifests/content/bootkube/kube-apiserver-secret.go
  pkg/asset/manifests/content/bootkube/openshift-apiserver-secret.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
Labels: approved, lgtm, size/XS

#563 pkg/validate/validate: Move SSH validation into pkg/validate
  pkg/asset/installconfig/ssh.go
  pkg/asset/installconfig/ssh_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#562 allow missing creds file when getting data for aws-creds secret
  pkg/asset/manifests/tectonic.go
Labels: approved, lgtm, size/XS

#572 pkg/rhcos/ami: Update name filter to "redhat-coreos-*"
  pkg/rhcos/ami.go
Labels: approved, lgtm, size/XS

#528 Docs/installer:update directory explaination for repo clone to avoid confuse when build
  README.md
Labels: approved, lgtm, size/XS

#583 bootkube: remove apiserver --disable-phase-2 after default change
  pkg/asset/ignition/bootstrap/content/bootkube.go
Labels: approved, lgtm, size/XS

#584 cvo-overrides: remove pod checkpointer operator
  pkg/asset/manifests/content/bootkube/cvo-overrides.go
Labels: approved, lgtm, size/XS

#554 rhcos: implement image discovery for new pipeline
  pkg/asset/installconfig/platform.go
  pkg/rhcos/ami.go
  pkg/rhcos/builds.go
  pkg/rhcos/qemu.go
Labels: approved, lgtm, size/L

#571 bootkube: remove unused kube-core secrets
  pkg/asset/manifests/content/bootkube/kube-apiserver-secret.go
  pkg/asset/manifests/content/bootkube/kube-controller-manager-secret.go
  pkg/asset/manifests/content/bootkube/openshift-apiserver-secret.go
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/M
