Repository openshift/installer, pull requests merged in 2018-07, with the labels that each got.

#8 update README
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: run-smoke-tests, size/M

#9 cleanup names in jenkins files and in readme
  tests/jenkins-jobs/README.md
  tests/jenkins-jobs/openshift_installer_nightly_trigger.groovy
  tests/jenkins-jobs/openshift_installer_public_pr_trigger.groovy
Labels: size/S

#10 installer/pkg/config-generator/tls: generate intermediate CAs
  installer/pkg/config-generator/tls.go
  installer/pkg/config-generator/utils.go
  installer/pkg/tls/BUILD.bazel
  installer/pkg/tls/tls.go
  installer/pkg/tls/tls_test.go
  installer/pkg/tls/utils.go
  installer/pkg/validate/validate_test.go
Labels: lgtm, size/L

#11 disable killAPI test
  tests/smoke/cluster_test.go
Labels: run-smoke-tests, size/XS

#12 installer/tls: Add isCA as a tls flag
  installer/pkg/config-generator/tls.go
  installer/pkg/tls/tls.go
  installer/pkg/tls/tls_test.go
Labels: lgtm, needs-ok-to-test, size/S

#13 Fix gitignore
  .gitignore
Labels: size/XS

#14 installer/tls: more general generateCert func
  installer/pkg/config-generator/tls.go
Labels: needs-ok-to-test, size/S

#17 installer/pkg/config-generator/tls: add certificate validity
  installer/pkg/config-generator/tls.go
Labels: lgtm, size/XS

#19 Update smoke tests readme
  tests/smoke/README.md
Labels: size/S

#20 installer/pkg/tls: add missing cert flags
  installer/pkg/tls/tls.go
Labels: lgtm, size/M

#23 config-generator: add etcd TLS
  installer/pkg/config-generator/tls.go
Labels: lgtm, size/M

#21 Change workdir in Dockerfile for prow CI
  images/tectonic-installer/Dockerfile.ci
Labels: size/XS

#24 update tectonic-installer -> openshift installer in docs and builder img
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  Documentation/dev/libvirt-howto.md
  builder-run
  images/tectonic-builder/Dockerfile
Labels: size/S

#29 *: Remove remaining tectonic-torcx references
  Documentation/dev/node-bootstrap-flow.md
  modules/ignition/variables.tf
Labels: lgtm, size/XS

#26 DCO: Update Linux Foundation address (to Letterman Drive)
  DCO
Labels: lgtm, needs-ok-to-test, size/XS

#27 docs: Consistent sh vs. console syntax highlighting
  CONTRIBUTING.md
  Documentation/dev/libvirt-howto.md
  README.md
  tests/smoke/aws/README.md
Labels: lgtm, size/M

#28 WORKSPACE: Get back to bazelbuild/rules_go releases
  Documentation/dev/build.md
  WORKSPACE
Labels: lgtm, size/S

#36 installer/pkg/workflow/workflow: Fix "taked" -> "take" comment typo
  installer/pkg/workflow/workflow.go
Labels: lgtm, needs-ok-to-test, size/XS

#22 installer/pkg/config-generator/tls: add kube + tnc tls certs
  installer/pkg/config-generator/generator_test.go
  installer/pkg/config-generator/tls.go
Labels: size/L

#42 installer/pkg: Replace writeFile with ioutil.WriteFile
  installer/pkg/config-generator/ignition.go
  installer/pkg/config-generator/tls.go
  installer/pkg/config-generator/utils.go
  installer/pkg/workflow/init.go
  installer/pkg/workflow/init_test.go
  installer/pkg/workflow/utils.go
Labels: lgtm, size/M

#49 Documentation/design: add render design
  Documentation/design/renderphase.md
Labels: lgtm, retest-not-required-docs-only, size/L

#44 Documentation/design: add high-level workflow diagram
  Documentation/design/workflow.md
  Documentation/design/workflow.svg
Labels: lgtm, retest-not-required-docs-only, size/XS

#47 Documentation/design: add init phase design
  Documentation/design/initphase.md
Labels: lgtm, retest-not-required-docs-only, size/M

#54 BUILD.bazel: Explicitly set file modes
  BUILD.bazel
Labels: lgtm, size/XS

#57 README: Document console URL
  Documentation/dev/libvirt-howto.md
  README.md
Labels: lgtm, retest-not-required-docs-only, size/S

#56 README: Document ~/.aws/credentials requirement
  README.md
Labels: needs-ok-to-test, retest-not-required-docs-only, size/S

#50 Documentation/design: add prepare design
  Documentation/design/preparephase.md
Labels: lgtm, retest-not-required-docs-only, size/M

#40 installer/pkg/workflow/utils: Format quoted paths with %q
  installer/pkg/workflow/utils.go
Labels: lgtm, size/XS

#59 modules/ignition: add initial support for rhcos
  config.tf
  modules/ignition/assets.tf
  modules/ignition/outputs.tf
  modules/ignition/resources/services/kubelet-workaround.service
  modules/ignition/resources/services/kubelet.service
Labels: lgtm, run-smoke-tests, size/M

#58 installer workflow: switch tls generation from terraform to go
  installer/cmd/tectonic/main.go
  installer/pkg/config-generator/generator_test.go
  installer/pkg/config-generator/tls.go
  installer/pkg/workflow/destroy.go
  installer/pkg/workflow/init.go
  installer/pkg/workflow/install.go
  installer/pkg/workflow/utils.go
  modules/tls/ca/assets.tf
  modules/tls/ca/main.tf
  modules/tls/ca/outputs.tf
  modules/tls/ca/variables.tf
  modules/tls/etcd/assets.tf
  modules/tls/etcd/main.tf
  modules/tls/etcd/outputs.tf
  modules/tls/etcd/variables.tf
  modules/tls/ingress/assets.tf
  modules/tls/ingress/main.tf
  modules/tls/ingress/output.tf
  modules/tls/ingress/variables.tf
  modules/tls/kube/admin.tf
  modules/tls/kube/api.tf
  modules/tls/kube/api_proxy.tf
  modules/tls/kube/assets.tf
  modules/tls/kube/kubelet.tf
  modules/tls/kube/outputs.tf
  modules/tls/kube/variables.tf
  modules/tls/tnc/assets.tf
  modules/tls/tnc/main.tf
  modules/tls/tnc/outputs.tf
  modules/tls/tnc/variables.tf
  steps/tls/config.tf
  steps/tls/main.tf
Labels: lgtm, run-smoke-tests, size/XXL

#39 installer/pkg/workflow/utils: Simplify findStepTemplates path logic
  installer/pkg/workflow/utils.go
Labels: lgtm, size/S

#46 installer/pkg/config-generator/tls: Don't Sprintf string literals
  installer/pkg/config-generator/tls.go
Labels: lgtm, size/XS

#62 Documentation/variables: Drop stale docs
  CONTRIBUTING.md
  Documentation/variables/aws.md
  Documentation/variables/config.md
Labels: lgtm, retest-not-required-docs-only, size/M

#65 modules/aws/etcd/ignition: Drop hard-coded ignition_etcd_keys
  modules/aws/etcd/ignition.tf
Labels: lgtm, size/XS

#35 images: Remove references to CoreOS Terraform
  images/tectonic-builder/Dockerfile
  images/tectonic-builder/README.md
  images/tectonic-installer/Dockerfile.ci
Labels: lgtm, size/M

#64 installer/pkg/config/fixtures: Bump to version 2.2.0
  installer/pkg/config/fixtures/ign.ign
  installer/pkg/config/fixtures/invalid-ign.ign
Labels: lgtm, size/XS

#53 Documentation/dev/build: "tectonic-installer" -> "installer"
  Documentation/dev/build.md
Labels: lgtm, retest-not-required-docs-only, size/S

#71 OWNERS: Configure Prow with approver and reviewer information
  CONTRIBUTING.md
  OWNERS
Labels: lgtm, retest-not-required-docs-only, size/M

#67 modules/container_linux: Add a README
  modules/container_linux/README.md
  modules/container_linux/variables.tf
Labels: lgtm, size/M

#68 modules/aws/vpc/outputs: Drop join/split comment
  modules/aws/vpc/outputs.tf
Labels: lgtm, size/XS

#74 modules/*/target-defaults: Consolidate default counts for etcd
  modules/aws/target-defaults/README.md
  modules/aws/target-defaults/main.tf
  modules/aws/target-defaults/outputs.tf
  modules/aws/target-defaults/variables.tf
  modules/libvirt/target-defaults/README.md
  modules/libvirt/target-defaults/main.tf
  modules/libvirt/target-defaults/outputs.tf
  modules/libvirt/target-defaults/variables.tf
  steps/assets/aws/main.tf
  steps/assets/libvirt/main.tf
  steps/etcd/aws/etcd.tf
  steps/etcd/libvirt/main.tf
Labels: lgtm, size/L

#66 modules/aws/etcd: Add a README
  modules/aws/etcd/README.md
  modules/aws/etcd/nodes.tf
  modules/aws/etcd/variables.tf
Labels: lgtm, size/M

#75 scripts/maintenance: Support ~/.aws configs for region
  scripts/maintenance/clean-aws.sh
  scripts/maintenance/tag-aws.sh
Labels: lgtm, size/M

#78 modules/aws/vpc/vpc-public: Tag new EIPs with tectonicClusterID
  modules/aws/vpc/vpc-public.tf
Labels: lgtm, size/XS

#76 scripts/maintenance/clean-aws.sh: Skip $tag_file for unset --tag-file
  scripts/maintenance/clean-aws.sh
Labels: lgtm, size/XS

#79 Add tls assets for the clusterapi-operator
  installer/pkg/config-generator/tls.go
  modules/bootkube/manifests.tf
  modules/bootkube/resources/manifests/cluster-apiserver-secret.yaml
  modules/bootkube/variables.tf
  steps/assets/base/ignition-tls.tf
  steps/assets/base/inputs.tf
  steps/assets/base/tectonic.tf
Labels: lgtm, run-smoke-tests, size/M

#82 steps/etcd/libvirt: Fix obsolete local.etcd_count reference
  steps/etcd/libvirt/main.tf
Labels: approved, lgtm, size/XS

#85 Documentation/design/installconfig: Reword embedding subsection
  Documentation/design/installconfig.md
Labels: approved, lgtm, retest-not-required-docs-only, run-smoke-tests, size/XS

#83 steps/topology/aws: Remove container_linux import
  steps/topology/aws/main.tf
Labels: approved, lgtm, size/XS
