Repository openshift/installer, pull requests merged in 2018-12, with the labels that each got.

#737 aws: Increase default master disk size to 120GB for IO
  data/data/aws/variables-aws.tf
Labels: approved, lgtm, size/XS

#769 data/aws/vpc: Drop aws_route_table data blocks
  data/data/aws/vpc/common.tf
Labels: approved, lgtm, size/M

#756 data/libvirt: Single coreos_ignition for libvirt_domain.master
  data/data/libvirt/main.tf
Labels: approved, lgtm, size/XS

#759 pkg/tfvars: Drop unused libvirt.DefaultIfName and similar
  pkg/tfvars/aws/aws.go
  pkg/tfvars/libvirt/libvirt.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, lgtm, size/S

#730 pkg/lineprinter: Add a wrapper for Write -> Print
  pkg/lineprinter/lineprinter.go
  pkg/lineprinter/lineprinter_test.go
  pkg/lineprinter/trimmer.go
  pkg/lineprinter/trimmer_test.go
  pkg/terraform/executor.go
Labels: approved, lgtm, size/L

#766 Add validation and choices to OpenStack installconfig
  Gopkg.lock
  pkg/asset/installconfig/openstack/openstack.go
  vendor/github.com/gophercloud/gophercloud/internal/pkg.go
  vendor/github.com/gophercloud/gophercloud/internal/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/urls.go
Labels: approved, lgtm, size/XXL

#775 pkg/asset/ignition/bootstrap: Add /root/.docker/config.json
  data/data/bootstrap/files/root/.docker/config.json.template
  data/data/manifests/bootkube/pull.yaml.template
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
Labels: approved, lgtm, size/XS

#779 CHANGELOG: Add a closing paren to AWS instance types
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#781 data: do not use kubelet lock file and boost log level
  data/data/bootstrap/systemd/units/kubelet.service.template
Labels: approved, lgtm, size/XS

#780 bootstrap: Resolve the release image to a digest early in install
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/M

#778 Log more verbosely when waiting for bootstrap completion
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/S

#771 Add secret for kubeadmin pre-idp user
  Gopkg.lock
  README.md
  cmd/openshift-install/create.go
  data/data/manifests/tectonic/kubeadmin-password-secret.yaml.template
  docs/user/environment-variables.md
  pkg/asset/cluster/cluster.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/node.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/password.go
  pkg/asset/manifests/tectonic.go
  pkg/asset/manifests/template.go
  pkg/asset/password/password.go
  pkg/asset/templates/content/tectonic/kubeadmin-password-secret.go
  pkg/asset/templates/templates.go
  pkg/types/installconfig.go
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
Labels: approved, lgtm, size/XXL

#690 Install qemu-kvm as part of Libvirt flow
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#787 fix typo with kubeadmin password
  pkg/asset/password/password.go
Labels: approved, lgtm, size/XS

#644 Replace references to tectonic with openshift
  cmd/openshift-install/create.go
  data/data/aws/main.tf
  data/data/aws/route53/base.tf
  data/data/aws/route53/master.tf
  data/data/aws/route53/worker.tf
  data/data/aws/variables-aws.tf
  data/data/bootstrap/files/opt/openshift/bootkube-config-overrides/kube-apiserver-config-overrides.yaml
  data/data/bootstrap/files/opt/openshift/bootkube-config-overrides/kube-controller-manager-config-overrides.yaml
  data/data/bootstrap/files/opt/openshift/bootkube-config-overrides/kube-scheduler-config-overrides.yaml
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/openshift.sh
  data/data/bootstrap/systemd/units/bootkube.service
  data/data/bootstrap/systemd/units/openshift.service
  data/data/bootstrap/systemd/units/progress.service
  data/data/bootstrap/systemd/units/tectonic.service
  data/data/config.tf
  data/data/libvirt/main.tf
  data/data/libvirt/variables-libvirt.tf
  data/data/manifests/openshift/binding-discovery.yaml
  data/data/manifests/openshift/cloud-creds-secret.yaml.template
  data/data/manifests/openshift/kubeadmin-password-secret.yaml.template
  data/data/manifests/openshift/role-cloud-creds-secret-reader.yaml.template
  data/data/openstack/main.tf
  data/data/openstack/variables-openstack.tf
  docs/design/assetgeneration.md
  docs/design/resource_dep.svg
  docs/dev/libvirt-howto.md
  docs/dev/operators.md
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/template.go
  pkg/asset/manifests/utils.go
  pkg/asset/templates/content/bootkube/cvo-overrides.go
  pkg/asset/templates/content/helper.go
  pkg/asset/templates/content/openshift/binding-discovery.go
  pkg/asset/templates/content/openshift/cloud-creds-secret.go
  pkg/asset/templates/content/openshift/kubeadmin-password-secret.go
  pkg/asset/templates/content/openshift/role-cloud-creds-secret-reader.go
  pkg/asset/templates/templates.go
  pkg/tfvars/aws/aws.go
  pkg/tfvars/libvirt/libvirt.go
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/tfvars.go
  version.bzl
Labels: approved, lgtm, size/XXL

#785 libvirt: Add Terraform variables for memory/CPU, bump master to 4GiB
  data/data/libvirt/main.tf
  data/data/libvirt/variables-libvirt.tf
Labels: approved, lgtm, size/S

#800 Remove openshift-web-console namespace
  data/data/manifests/bootkube/03-openshift-web-console-namespace.yaml
  pkg/asset/manifests/operators.go
  pkg/asset/templates/content/bootkube/03-openshift-web-console-namespace.go
  pkg/asset/templates/templates.go
Labels: approved, lgtm, size/M

#688 pkg/asset/installconfig: Pull AWS region default from usual places
  docs/user/environment-variables.md
  pkg/asset/installconfig/aws/aws.go
Labels: approved, lgtm, size/S

#798 pkg/asset/installconfig/aws: Ask for AWS access key and secret
  pkg/asset/installconfig/aws/aws.go
Labels: approved, lgtm, size/M

#777 Remove some unused OpenStack volume config.
  pkg/types/openstack/machinepool.go
Labels: approved, lgtm, size/S

#621 add go version check to build script.
  hack/build.sh
Labels: approved, lgtm, size/S

#850 docs/user/environment-variables: fix typo
  docs/user/environment-variables.md
Labels: approved, lgtm, size/XS

#832 Provide the correct console URL
  README.md
Labels: approved, lgtm, size/S

#791 Scheduler and controller-manager ports for metrics
  data/data/aws/vpc/sg-master.tf
  data/data/openstack/topology/sg-master.tf
Labels: approved, lgtm, size/M

#793 README: Consolidate supported-platform documentation
  README.md
  docs/user/overview.md
Labels: approved, lgtm, size/S

#849 cmd/openshift-install/create: Drop newline from "Route found..." log
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/XS

#851 cvo: remove packages apiserver override
  data/data/manifests/bootkube/cvo-overrides.yaml.template
  data/data/manifests/bootkube/legacy-cvo-overrides.yaml.template
Labels: approved, lgtm, size/XS

#853 hack/get-terraform: Remove obsolete script
  README.md
  docs/user/overview.md
  hack/get-terraform.sh
  images/installer/Dockerfile.ci
  images/nested-libvirt/Dockerfile
Labels: approved, lgtm, size/M

#834 Move variables to constants
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, ok-to-test, size/S

#840 asset/cluster: clean up logging messages
  pkg/asset/cluster/cluster.go
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm, size/XS

#817 *: mirror tectonicClusterID as openshiftClusterID
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/sg-elb.tf
  data/data/aws/vpc/sg-etcd.tf
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
  data/data/aws/vpc/vpc.tf
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/sg-lb.tf
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
  pkg/asset/cluster/aws/aws.go
  pkg/asset/cluster/openstack/openstack.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/destroy/openstack/openstack_deprovision.go
Labels: approved, lgtm, size/L

#841 CHANGELOG: Document changes since v0.5.0
  CHANGELOG.md
Labels: approved, lgtm, size/M

#865 docs: Fix supported platforms link in overview.md
  docs/user/overview.md
Labels: approved, lgtm, ok-to-test, size/XS

#858 Revert "data/aws: Switch to m4.large"
  data/data/aws/bootstrap/variables.tf
  data/data/aws/variables-aws.tf
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/XS

#875 docs: dns is required for libvirt clusters
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/XS

#859 log,return error if console URL is not obtained
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/XS

#864 pkg/asset/installconfig/aws: Suppress "Unrecognized" for empty region
  pkg/asset/installconfig/aws/aws.go
Labels: approved, lgtm, size/XS

#869 README.md: Pedantic capitalization nit.
  README.md
Labels: approved, lgtm, size/XS

#872 asset/manifests: Load Openshift asset from disk
  pkg/asset/manifests/openshift.go
Labels: approved, lgtm, size/XS

#786 cmd/openshift-install/create: Fatal Kube API wait timeouts
  cmd/openshift-install/create.go
  cmd/openshift-install/destroy.go
  cmd/openshift-install/log.go
Labels: approved, lgtm, size/M

#879 reduce permissions on bootstrap kubeconfig used by masters
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/systemd/units/kubelet.service.template
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/tls/kubeletcertkey.go
Labels: approved, lgtm, size/M

#882 Revert "Revert "data/aws: Switch to m4.large""
  data/data/aws/bootstrap/variables.tf
  data/data/aws/variables-aws.tf
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/XS

#861 *: remove support for environment variables
  docs/dev/libvirt-howto.md
  docs/user/environment-variables.md
  docs/user/tips-and-tricks.md
  pkg/asset/installconfig/aws/aws.go
  pkg/asset/installconfig/basedomain.go
  pkg/asset/installconfig/clustername.go
  pkg/asset/installconfig/emailaddress.go
  pkg/asset/installconfig/libvirt/libvirt.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/platform.go
  pkg/asset/installconfig/pullsecret.go
  pkg/asset/installconfig/ssh.go
  pkg/asset/userprovided.go
Labels: approved, lgtm, size/L

#868 cmd: drop terraform version from version subcommand
  cmd/openshift-install/create.go
  cmd/openshift-install/version.go
Labels: approved, lgtm, size/S

#886 pkg/asset/installconfig/pullsecret: Point to cloud.openshift.com
  pkg/asset/installconfig/pullsecret.go
Labels: approved, lgtm, size/XS

#892 docs: Drop 'OPENSHIFT_INSTALL_' prefix
  README.md
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, size/XS

#854 Only copy credentials for the cloud used to deploy OCP
  Gopkg.lock
  Gopkg.toml
  pkg/asset/manifests/openshift.go
  vendor/github.com/go-yaml/yaml/LICENSE
  vendor/github.com/go-yaml/yaml/LICENSE.libyaml
  vendor/github.com/go-yaml/yaml/NOTICE
  vendor/github.com/go-yaml/yaml/apic.go
  vendor/github.com/go-yaml/yaml/decode.go
  vendor/github.com/go-yaml/yaml/emitterc.go
  vendor/github.com/go-yaml/yaml/encode.go
  vendor/github.com/go-yaml/yaml/parserc.go
  vendor/github.com/go-yaml/yaml/readerc.go
  vendor/github.com/go-yaml/yaml/resolve.go
  vendor/github.com/go-yaml/yaml/scannerc.go
  vendor/github.com/go-yaml/yaml/sorter.go
  vendor/github.com/go-yaml/yaml/writerc.go
  vendor/github.com/go-yaml/yaml/yaml.go
  vendor/github.com/go-yaml/yaml/yamlh.go
  vendor/github.com/go-yaml/yaml/yamlprivateh.go
Labels: approved, lgtm, size/XXL

#896 vendor: remove github.com/go-yaml/yaml
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/go-yaml/yaml/LICENSE
  vendor/github.com/go-yaml/yaml/LICENSE.libyaml
  vendor/github.com/go-yaml/yaml/NOTICE
  vendor/github.com/go-yaml/yaml/apic.go
  vendor/github.com/go-yaml/yaml/decode.go
  vendor/github.com/go-yaml/yaml/emitterc.go
  vendor/github.com/go-yaml/yaml/encode.go
  vendor/github.com/go-yaml/yaml/parserc.go
  vendor/github.com/go-yaml/yaml/readerc.go
  vendor/github.com/go-yaml/yaml/resolve.go
  vendor/github.com/go-yaml/yaml/scannerc.go
  vendor/github.com/go-yaml/yaml/sorter.go
  vendor/github.com/go-yaml/yaml/writerc.go
  vendor/github.com/go-yaml/yaml/yaml.go
  vendor/github.com/go-yaml/yaml/yamlh.go
  vendor/github.com/go-yaml/yaml/yamlprivateh.go
Labels: approved, lgtm, size/XXL

#897 asset/installconfig: fix survey for aws access key id
  pkg/asset/installconfig/aws/aws.go
Labels: approved, lgtm, size/XS

#900 destroy/bootstrap: explicit pass `disable-bootstrap.tfvars` for libvirt
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm, size/XS

#745 data/aws/vpc: Add an S3 endpoint to new VPCs
  Gopkg.lock
  Gopkg.toml
  data/data/aws/main.tf
  data/data/aws/vpc/variables.tf
  data/data/aws/vpc/vpc.tf
  vendor/github.com/openshift/hive/contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: approved, lgtm, size/M

#912 OpenStack Destroy, break after matching swift container metadata
  pkg/destroy/openstack/openstack_deprovision.go
Labels: approved, lgtm, size/XS

#905 cmd/openshift-install/create: Drop dead-code "no routes found" error
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/XS

#907 .github/ISSUE_TEMPLATE: Explicitly mention .openshift_install.log
  .github/ISSUE_TEMPLATE.md
  .gitignore
  docs/user/troubleshooting.md
Labels: approved, lgtm, size/XS

#906 CHANGELOG: Document changes since 2018-12-07
  CHANGELOG.md
Labels: approved, lgtm, size/M

#913 Fix a typo in libvirt-howto.md
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, ok-to-test, size/XS

#654 terraform/aws: remove option to use an existing vpc in aws
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/master/variables.tf
  data/data/aws/route53/base.tf
  data/data/aws/route53/master.tf
  data/data/aws/route53/variables.tf
  data/data/aws/route53/worker.tf
  data/data/aws/variables-aws.tf
  data/data/aws/vpc/common.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/variables.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
  data/data/aws/vpc/vpc.tf
  pkg/tfvars/aws/aws.go
  pkg/tfvars/tfvars.go
  pkg/types/aws/platform.go
Labels: approved, lgtm, size/L

#911 OpenStack Destroy, tolerate temporary router delete failure
  pkg/destroy/openstack/openstack_deprovision.go
Labels: approved, lgtm, size/XS

#757 Pin OS image for release builds
  hack/build.sh
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/rhcos/builds.go
Labels: approved, lgtm, size/M

#920 Revert "OpenStack Destroy, tolerate temporary router delete failure"
  pkg/destroy/openstack/openstack_deprovision.go
Labels: approved, lgtm, size/XS

#835 terraform: remove tectonicClusterID tag on resources
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/sg-elb.tf
  data/data/aws/vpc/sg-etcd.tf
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
  data/data/aws/vpc/vpc.tf
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/lb/main.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/sg-lb.tf
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
  pkg/asset/cluster/aws/aws.go
  pkg/asset/cluster/openstack/openstack.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/M

#927 pkg/asset/machines/aws/machinesets: Give workers public IPs (for now)
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/S

#916 openstack: Fix haproxy config.
  data/data/openstack/lb/main.tf
Labels: approved, lgtm, size/XS

#922 asset/ignition: fix error when marshaling ignition config
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/worker.go
Labels: approved, lgtm, size/XS

#931 asset/installconfig: rename install-config.yml to install-config.yaml
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/installconfig_test.go
Labels: approved, lgtm, size/L

#932 openstack: Assign floating IP to service VM.
  Gopkg.lock
  Gopkg.toml
  data/data/openstack/topology/private-network.tf
  pkg/destroy/openstack/openstack_deprovision.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/urls.go
Labels: approved, lgtm, size/L

#936 README: Replace stale environment variable reference
  README.md
Labels: approved, lgtm, size/XS

#934 Add asset for DNS config
  Gopkg.lock
  Gopkg.toml
  data/data/manifests/bootkube/cluster-dns-01-crd.yaml
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/operators.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
Labels: approved, lgtm, size/L

#941 Gopkg: Lock aws/request
  Gopkg.lock
Labels: approved, lgtm, size/XS

#942 pkg/types/aws/validation: Move ValidRegions into this package
  pkg/asset/installconfig/aws/aws.go
  pkg/types/aws/platform.go
  pkg/types/aws/validation/platform.go
Labels: approved, lgtm, size/M

#939 pkg/asset/installconfig/aws: Make base-domain a select widget
  pkg/asset/installconfig/aws/aws.go
  pkg/asset/installconfig/aws/basedomain.go
  pkg/asset/installconfig/basedomain.go
Labels: approved, lgtm, size/L

#951 data/data/aws: use vpc configuration block for route53 zone `int`
  data/data/aws/main.tf
Labels: approved, lgtm, size/XS

#949 terraform: only use embedded plugins when `release` tag is set
  pkg/terraform/exec/exec.go
  pkg/terraform/exec/plugin.go
  pkg/terraform/exec/plugin_release.go
Labels: approved, lgtm, size/M

#960 asset/installconfig: fallback to freeform basedomain on aws on throttle error
  pkg/asset/installconfig/basedomain.go
Labels: approved, lgtm, size/XS

#962 script for generating mock
  CONTRIBUTING.md
  hack/go-genmock.sh
  images/mock/Dockerfile
  pkg/asset/mock/filefetcher_generated.go
  pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
Labels: approved, lgtm, size/M

#956 pkg/terraform/exec/plugins/vendor: Roll back libvirt to 2ad0228349
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/cloudinit_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/config.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/coreos_ignition_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_volume.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/utils_volume.go
Labels: approved, lgtm, size/M

#961 add libvirt tag to libvirt-ci Dockerfile
  images/nested-libvirt/Dockerfile
Labels: approved, lgtm, size/XS

#959 *: change references to install-config.yml with install-config.yaml
  docs/design/assetgeneration.md
  docs/user/tips-and-tricks.md
  pkg/asset/installconfig/installconfig.go
  pkg/asset/store.go
Labels: approved, lgtm, size/S

#970 Revert "pkg/asset/machines/aws/machinesets: Give workers public IPs (for now)"
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/S

#971 CHANGELOG: Document changes since v0.7.0
  CHANGELOG.md
Labels: approved, lgtm, size/M
