Repository openshift/installer, pull requests merged in 2019-10, with the labels that each got.

#2432 data/aws/vpc/common: Drop unused (private|public)_subnet_count variables
  data/data/aws/vpc/common.tf
Labels: approved, lgtm, size/XS

#1381 Bug 1748452: data/bootstrap: Replace openshift.sh with cluster-bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/openshift.sh
  data/data/bootstrap/files/usr/local/bin/report-progress.sh
  data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh
  data/data/bootstrap/systemd/units/openshift.service
  data/data/bootstrap/systemd/units/progress.service
  pkg/asset/machines/master.go
  pkg/asset/machines/userdata.go
  pkg/asset/machines/worker.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2435 data/bootstrap/files/usr/local/bin/installer-masters-gather: Gather MCD logs
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, size/XS

#2436 gcp/destroy: Fix typo on failure to create aim service.
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, size/XS

#2320 baremetal: Add validation for provisioning network IPs
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, lgtm, platform/baremetal, size/L

#2437 data/aws/vpc: Drop new_az_count and vpc_id locals
  data/data/aws/vpc/common.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
Labels: approved, lgtm, size/M

#2443 upi/aws/cloudformation/02_cluster_infra: "the External" -> "the external", etc.
  upi/aws/cloudformation/02_cluster_infra.yaml
Labels: approved, lgtm, size/S

#2442 docs/user/versioning: Drop obsolete versioning claims
  docs/user/customization.md
  docs/user/overview.md
  docs/user/versioning.md
Labels: approved, lgtm, size/M

#2445 upi/gcp: control plane to use pd-ssd
  upi/gcp/05_control_plane.py
Labels: approved, lgtm, size/XS

#2444 add customizable num_cpu for vsphere UPI installation
  upi/vsphere/machine/main.tf
  upi/vsphere/machine/variables.tf
  upi/vsphere/main.tf
Labels: approved, lgtm, size/XS

#2439 Remove quotes from installer log.
  pkg/asset/store/store.go
Labels: approved, lgtm, size/S

#2440 Bug 1755073: docs/user/*/install_upi: explicitly-set-control-plane-unschedulable
  docs/user/aws/install_upi.md
  docs/user/gcp/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2448 Add internal load balancer to GCP.
  data/data/gcp/bootstrap/output.tf
  data/data/gcp/dns/base.tf
  data/data/gcp/dns/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  data/data/gcp/master/outputs.tf
  data/data/gcp/master/variables.tf
  data/data/gcp/network/firewall.tf
  data/data/gcp/network/lb-private.tf
  data/data/gcp/network/lb-public.tf
  data/data/gcp/network/lb.tf
  data/data/gcp/network/network.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/network/variables.tf
  docs/user/gcp/limits.md
  pkg/asset/machines/gcp/machines.go
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, size/L

#2454 Bug 1758312: data/rhcos: Bump to rhcos-4.2/42.80.20191002.0
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#2457 data/bootstrap: allow for missing keepalived image
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#2459 bootstrap: Remove --allow-privileged from kubelet flags
  data/data/bootstrap/systemd/units/kubelet.service.template
Labels: approved, lgtm, size/XS

#2455 Bug 1758306: data/rhcos: Bump to rhcos-4.3/43.80.20191002.1
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2453 pkg/destroy/aws: Dynamic partitions, fixing hard-coded 'aws'
  Gopkg.lock
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/XS

#2460 pkg/destroy/aws: Stop skipping direct network-interface deletion
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/XS

#2462 Bug 1759146: data/rhcos: fix base url to use correct baseURI
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/baremetal, size/XS

#2463 hack/update-rhcos-bootimage: Require ART endpoint
  hack/update-rhcos-bootimage.py
Labels: approved, lgtm, size/XS

#2466 docs/user/gcp/install_upi: "create ... to" -> "add ... to" typo fix
  docs/user/gcp/install_upi.md
Labels: approved, lgtm, size/XS

#2425 Fixes Bug 1757975: asset/manifests: Removes external api server from default noProxy
  pkg/asset/manifests/proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2438 data/aws/vpc: Lay the groundwork for bring-your-own VPC/subnets
  data/data/aws/main.tf
  data/data/aws/variables-aws.tf
  data/data/aws/vpc/common.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/variables.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
  data/data/aws/vpc/vpc.tf
Labels: approved, lgtm, size/L

#2469 upi/gcp: increase the NAT ports for control plane to 7168
  upi/gcp/01_vpc.py
Labels: approved, lgtm, size/XS

#2470 Use PrivateDNSZones instead of DNSZones type Private for clusters
  Gopkg.lock
  data/data/azure/bootstrap/variables.tf
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/variables.tf
  data/data/azure/vnet/common.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/variables.tf
  data/data/azure/vnet/vnet.tf
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/manifests/dns.go
  pkg/destroy/azure/azure.go
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/azureprivatedns.go
  pkg/terraform/exec/plugins/azureprivatedns/client.go
  pkg/terraform/exec/plugins/azureprivatedns/provider.go
  pkg/terraform/exec/plugins/azureprivatedns/resource_private_dns_a_record.go
  pkg/terraform/exec/plugins/azureprivatedns/resource_private_dns_srv_record.go
  pkg/terraform/exec/plugins/azureprivatedns/resource_private_dns_zone.go
  pkg/terraform/exec/plugins/azureprivatedns/resource_private_dns_zone_virtual_network_link.go
  pkg/terraform/exec/plugins/azureprivatedns/tags.go
  pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/client.go
  pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/models.go
  pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/privatezones.go
  pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/recordsets.go
  pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/version.go
  pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/virtualnetworklinks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/privatezones.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/recordsets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/virtualnetworklinks.go
Labels: approved, lgtm, size/XXL

#2480 Bug 1759965: data/gcp/network/firewall.tf: allow complete health check range for ILBs and NLBs
  data/data/gcp/network/firewall.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2481 Bug 1759966: data/gcp/network/firewall-control.tf: allow complete health check range for ILBs and NLBs
  data/data/gcp/network/firewall-control.tf
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#2475 docs/user/overview: OpenShift-specific components before bootstrap control-plane teardown
  docs/user/overview.md
Labels: approved, lgtm, size/XS

#2478 data/azure/main: Set metadata to URL, not the string "var.azure_image_url"
  data/data/azure/main.tf
Labels: approved, lgtm, size/XS

#2476 azure: set the os disk type based on machine objects
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/master/variables.tf
  data/data/azure/variables-azure.tf
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm, size/M

#2308 pkg/types/aws/validation/platform: Include eu-north-1
  pkg/types/aws/defaults/platform.go
  pkg/types/aws/validation/platform.go
  pkg/types/validation/installconfig_test.go
  platformtests/aws/default_instance_class_test.go
Labels: approved, lgtm, size/S

#2403 pkg/gather/ssh: Add logging for agent generation
  pkg/gather/ssh/agent.go
  pkg/gather/ssh/ssh.go
Labels: approved, lgtm, size/S

#2283 data/aws/vpc/master-elb: Drop idle_timeout from aws_lb resources
  data/data/aws/vpc/master-elb.tf
Labels: approved, lgtm, size/XS

#2491 data/manifests/bootkube/cvo-overrides: Move to stable-4.3
  data/data/manifests/bootkube/cvo-overrides.yaml.template
  docs/user/troubleshooting.md
Labels: approved, lgtm, size/XS

#2489 Bug 1760425: Change GCP UPI firewall rules for network LB health check.
  upi/gcp/03_security.py
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2496 docs/user/aws/install_upi: Wait for install-complete after manual DNS creation
  docs/user/aws/install_upi.md
Labels: approved, lgtm, size/M

#2390 Bug 1754452: OpenStack: reduce the timeout for deleting the cluster
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/XS

#2494 docs/user/vsphere/install_upi: Fix [...][#...] references, etc.
  docs/user/metal/install_upi.md
  docs/user/vsphere/install_upi.md
Labels: approved, lgtm, size/S

#2497 pkg/destroy/aws: Fix fail-slow error handling in deleteEC2SubnetByVPC
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/XS

#1836 cmd/openshift-install/gather: Guard against cluster-side artifact collisions
  cmd/openshift-install/gather.go
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, size/M

#2467 pkg/destroy/aws: Untag shared resources
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/M

#2420 docs/user/aws/install_upi: Explain DNS-zone lookup
  docs/user/aws/install_upi.md
Labels: approved, lgtm, size/M

#2441 Azure: Allow customer provisioned virtual networks & subnets
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/common.tf
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/nsg.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/variables.tf
  data/data/azure/vnet/vnet.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/platform.go
Labels: approved, lgtm, size/L

#2512 pkg/asset/installconfig/aws/metadata: Store AWS metadata
  pkg/asset/installconfig/aws/availabilityzones.go
  pkg/asset/installconfig/aws/doc.go
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/platform.go
  pkg/asset/installconfig/aws/session.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/machines/aws/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/L

#2473 OpenStack: automatically populate RHCOS image
  Gopkg.lock
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/rhcos/image.go
  pkg/destroy/openstack/openstack.go
  pkg/rhcos/openstack.go
  pkg/tfvars/openstack/openstack.go
  vendor/github.com/gophercloud/gophercloud/internal/pkg.go
  vendor/github.com/gophercloud/gophercloud/internal/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
Labels: approved, lgtm, size/XXL

#2515 docs: clarify enabling GCP service APIs
  docs/user/gcp/README.md
  docs/user/gcp/apis.md
  docs/user/gcp/iam.md
Labels: approved, lgtm, size/M

#2450 Bug 1754939: cmd/openshift-install/gather: Gather ClusterOperator errors
  cmd/openshift-install/create.go
  cmd/openshift-install/gather.go
  cmd/openshift-install/waitfor.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2493 BYO VPC Validation
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/dns.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
Labels: approved, lgtm, size/XL

#2511 Document: podman was requested by local dev environment.
  CONTRIBUTING.md
Labels: approved, lgtm, ok-to-test, size/XS

#2518 cmd/openshift-install/gather: Fix '{}' -> %s formatting
  cmd/openshift-install/gather.go
Labels: approved, lgtm, size/XS

#2501 Update terraform-provider-libvirt version to v0.6.0.
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_volume.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/volume_def.go
Labels: approved, lgtm, ok-to-test, platform/baremetal, size/L

#2520 Update GCP internal load balancers to use custom-provided networks.
  data/data/gcp/network/common.tf
  data/data/gcp/network/lb-private.tf
  data/data/gcp/network/outputs.tf
Labels: approved, lgtm, size/XS

#2477 pkg: AWS shared-subnet handling in Go
  pkg/asset/cluster/aws/aws.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/subnet.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/platform.go
Labels: approved, lgtm, size/XL

#2474 OpenStack: Remove cloud-creds-secret-reader rolebinding
  data/data/manifests/openshift/rolebinding-cloud-creds-secret-reader.yaml.template
  pkg/asset/manifests/openshift.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/openshift/rolebinding-cloud-creds-secret-reader.go
Labels: approved, lgtm, size/L

#2495 docs/user/aws/install_upi: Fix "machinesets" -> "machineset" typo
  docs/user/aws/install_upi.md
Labels: approved, lgtm, ok-to-test, size/S

#2525 data/bootstrap/files/usr/local/bin/installer-*gather: Gather failed systemd units
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, size/S

#2527 docs/user/aws/customization: Document platform subnets
  docs/user/aws/customization.md
Labels: approved, lgtm, size/XS

#2530 asset/manifests/gcp: update the config to inlude master and worker node-tags
  pkg/asset/manifests/gcp/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig_test.go
Labels: approved, lgtm, size/M

#2533 data/azure/vnet/variables: Drop *_master_endpoints
  data/data/azure/vnet/variables.tf
Labels: approved, lgtm, size/S

#2526 AWS: Enable clusters with no public endpoints
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/master/variables.tf
  data/data/aws/route53/base.tf
  data/data/aws/route53/variables.tf
  data/data/aws/variables-aws.tf
  data/data/aws/vpc/common.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/variables.tf
  docs/user/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/installconfig_test.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/master.go
  pkg/asset/manifests/dns.go
  pkg/tfvars/aws/aws.go
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/L

#2523 Enable user defined default ingresscontroller
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/S

#2503 Adding docs on running via libvirt on Debian/Ubuntu
  docs/dev/libvirt/README.md
Labels: approved, lgtm, size/XS

#2488 Bug 1760197: Change GCP UPI firewall rules for network LB health check.
  upi/gcp/03_security.py
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#2545 Bug 1763927: asset/installconfig/aws: configure region when listing subnets
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/subnet.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2540 pkg/terraform/gather/aws: fallback to private_ip when public_ip is empty for bootstrap instance
  pkg/terraform/gather/aws/ip.go
Labels: approved, lgtm, size/S

#2492 OpenStack: Image name validations
  pkg/tfvars/openstack/openstack.go
Labels: approved, lgtm, platform/openstack, size/M

#2311 OpenStack: get rid of swift temp urls
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/README.md
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-random/random/provider.go
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-random/random/resource_password.go
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-random/random/resource_string.go
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-random/random/string.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, lgtm, size/XL

#2529 Bump golang version to 1.12
  hack/build.sh
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-test.sh
  hack/go-vet.sh
  hack/run-bdd-suite.sh
  hack/verify-vendor.sh
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.ci.rhel7
  images/installer/Dockerfile.upi.ci
  images/mock/Dockerfile
  images/nested-libvirt/Dockerfile
  images/openstack/Dockerfile.ci
  pkg/asset/cluster/tfvars.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/tls/tls.go
  pkg/tfvars/aws/aws.go
  pkg/types/azure/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/M

#2447 add cloud-cred-operator as static pod
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/S

#2538 Use an internal ingress by default when the cluster is marked internal
  Gopkg.lock
  pkg/asset/manifests/ingress.go
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_kubestorageversionmigrator.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XXL

#2490 OpenStack: clean-up cloud provider config
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Labels: approved, lgtm, size/XS

#2550 GCP: restrict MCS access to control plane & nodes
  data/data/gcp/network/firewall.tf
Labels: approved, lgtm, size/S

#1768 bootkube: Run before kubelet.service, start it during script
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
  data/data/bootstrap/systemd/units/bootkube.service
  data/data/bootstrap/systemd/units/crio-configure.service.template
  data/data/bootstrap/systemd/units/kubelet.service.template
Labels: approved, lgtm, size/M

#2557 Fix OpenStack QCOW2 download command
  docs/user/openstack/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#2558 openstack: Remove reference to tempurl known issue
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, platform/openstack, size/XS

#2560 data/bootstrap/files/usr/local/bin/installer-gather: Make ${ARTIFACTS}
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, lgtm, size/XS

#2564 pkg/validate: '%s' -> %q for IP quoting
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
Labels: approved, lgtm, size/S

#2531 Openstack UPI docs
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, platform/openstack, size/XL

#2132 Bug 1734539: Openstack: Option to set multiple external DNS IP Addresses
  data/data/openstack/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/M

#2572 Update OpenStack Platform Comments to fit best practices
  pkg/types/openstack/platform.go
Labels: approved, lgtm, platform/openstack, size/S

#2576 Openstack external dns doc
  docs/user/openstack/customization.md
  docs/user/openstack/install_upi.md
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, size/S

#2565 GCP: Add install-config.yaml customization doc & document cluster isolation
  docs/user/customization.md
  docs/user/gcp/customization.md
Labels: approved, lgtm, size/L

#2578 Libvirt: start using os.UserCacheDir to find the cache folder
  pkg/tfvars/libvirt/cache.go
Labels: approved, lgtm, size/S

#2506 Introduce gosec for security checks
  hack/go-sec.sh
Labels: approved, lgtm, size/S

#2547 data/rhcos: Bump to rhcos-4.3/ 43.81.20191028.2
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#2573 Azure: document custom VNets & cluster isolation
  docs/user/azure/customization.md
Labels: approved, lgtm, size/M

#2522 gcp: Enable clusters with no public endpoints
  data/data/gcp/bootstrap/common.tf
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/variables.tf
  data/data/gcp/dns/base.tf
  data/data/gcp/dns/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/network/firewall.tf
  data/data/gcp/network/lb-public.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/network/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/manifests/dns.go
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm, size/L

#2585 OpenStack: document cluster destruction if its metadata has been lost
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, size/M

#2521 Azure: Create clusters with no public endpoints
  data/data/azure/bootstrap/main.tf
  data/data/azure/bootstrap/variables.tf
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/master/variables.tf
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/public-lb.tf
  data/data/azure/vnet/variables.tf
  data/data/manifests/openshift/private-cluster-outbound-service.yaml
  pkg/asset/cluster/tfvars.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/openshift.go
  pkg/asset/templates/content/openshift/private-cluster-outbound-service.go
  pkg/terraform/gather/azure/ip.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, size/L

#2561 OpenStack: do not interrupt the deletion process in case of an error
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, platform/openstack, size/L

#2580 openstack UPI: Ansible scripts
  upi/openstack/OWNERS
  upi/openstack/README.md
Labels: approved, lgtm, size/XS

#2582 Bug 1738360: asset/installconfig: use new link to OCM pull-secret page
  pkg/asset/installconfig/pullsecret.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2598 pkg/asset/machines/baremetal: Drop unused networkInterfaceAddress from provider()
  pkg/asset/machines/baremetal/machines.go
  pkg/asset/machines/baremetal/machinesets.go
Labels: approved, lgtm, size/XS

#2575 Add Kuryr UPI Documentation
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, platform/openstack, size/L

#2601 [fcos] Add vrutkovs and LorbusChris to OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, retest-not-required, size/XS

#2395 pkg/tfvars/baremetal: don't hardcode external and provision interfaces
  pkg/asset/cluster/tfvars.go
Labels: approved, lgtm, platform/baremetal, size/XS

#2594 Add a `fips` flag to install-config.yaml
  Gopkg.lock
  Gopkg.toml
  docs/user/customization.md
  pkg/asset/machines/machineconfig/fips.go
  pkg/asset/machines/machineconfig/manifest.go
  pkg/asset/machines/master.go
  pkg/asset/machines/master_test.go
  pkg/asset/machines/worker.go
  pkg/asset/machines/worker_test.go
  pkg/types/installconfig.go
  vendor/github.com/openshift/machine-config-operator/README.md
  vendor/github.com/openshift/machine-config-operator/pkg/apis/apis.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/machineconfig.deepcopy.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/register.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/types.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#2587 Bug 1735192: OpenStack Self Signed Certs Fix
  Gopkg.lock
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/cluster/tfvars.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/destroy/openstack/swift.go
  pkg/tfvars/openstack/bootstrap_ignition.go
  pkg/tfvars/openstack/openstack.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/kubernetes/apimachinery/LICENSE
  vendor/github.com/kubernetes/apimachinery/pkg/util/rand/rand.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/XL
