Repository openshift/installer, pull requests merged in 2019-03, with the labels that each got.

#1344 CHANGELOG: Document changes since 0.13.0
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1333 pkg/asset/installconfig/aws/permissions: If we can mint, skip passthrough check
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, size/S

#1332 hack/release: Compute release.sha256(.sig)
  hack/release.sh
Labels: approved, lgtm, size/XS

#1338 openstack: Security groups update
  Gopkg.lock
  pkg/asset/machines/openstack/machines.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#1346 destroy: delete snapshots used in ami copies
  pkg/asset/installconfig/aws/permissions.go
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/M

#1347 *: Wrapf(err, "...") -> Wrap(err, "...")
  cmd/openshift-install/create.go
  cmd/openshift-install/destroy.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/manifests/cluster_k8s_io.go
  pkg/asset/manifests/operators.go
  pkg/asset/store/store.go
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/S

#1292 Add infra-image to MCO bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1348 data/aws: create bootstrap machine in first public subnet
  data/data/aws/main.tf
  data/data/aws/vpc/outputs.tf
Labels: approved, lgtm, size/XS

#1355 Revert "image: Take explicit dependency on util-linux for uuidgen and gzip"
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.ci.rhel7
Labels: approved, lgtm, size/XS

#1331 Document entry-point for user-provided custom MachineConfig
  docs/user/customization.md
Labels: approved, lgtm, size/L

#1334 aws, openstack: open ports 9000-9999 between nodes on UDP too.
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
  data/data/openstack/topology/sg-master.tf
Labels: approved, lgtm, size/M

#1359 Update code references to rhcos
  pkg/rhcos/ami.go
  pkg/rhcos/qemu.go
Labels: approved, lgtm, size/XS

#1358 Update name of RHCOS
  docs/user/openstack/README.md
  docs/user/troubleshooting.md
Labels: approved, lgtm, size/S

#1361 data/aws: explicitly create the network interface for masters to speed up DNS
  data/data/aws/master/main.tf
  data/data/aws/master/outputs.tf
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/M

#1243 openstack: Prefix all openstack resources with the cluster name
  data/data/openstack/service/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/sg-lb.tf
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, lgtm, size/M

#1351 openstack: Use external's network DNS by default
  data/data/openstack/topology/private-network.tf
Labels: approved, lgtm, size/S

#1366 openstack: Prefix subnet name used in filter with clusterID
  pkg/asset/machines/openstack/machines.go
Labels: approved, lgtm, size/XS

#1291 pkg/asset/tls: add etcd metrics assets
  data/data/manifests/bootkube/etcd-service.yaml
  data/data/manifests/bootkube/openshift-config-configmap-etcd-metrics-serving-ca.yaml.template
  data/data/manifests/bootkube/openshift-config-secret-etcd-metrics-client.yaml.template
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/openshift-config-configmap-etcd-metrics-serving-ca.go
  pkg/asset/templates/content/bootkube/openshift-config-secret-etcd-metrics-client.go
  pkg/asset/tls/etcdmetrics.go
Labels: approved, lgtm, size/L

#1356 types: rename network type to match Network.config.openshift.io.
  docs/user/aws/customization.md
  pkg/asset/ignition/machine/master_test.go
  pkg/asset/ignition/machine/worker_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/installconfig_test.go
  pkg/asset/manifests/network.go
  pkg/asset/tls/apiserver.go
  pkg/types/conversion/installconfig.go
  pkg/types/conversion/installconfig_test.go
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/XL

#1281 Add credentials secret to AWS provider config in order to support CredentialsRequest
  pkg/asset/machines/aws/machines.go
Labels: approved, lgtm, size/XS

#1210 pkg/asset/machines/aws: Only return available zones
  data/data/aws/vpc/common.tf
  pkg/asset/machines/aws/zones.go
Labels: approved, lgtm, platform/aws, size/S

#1352 pkg/destroy/aws: 10-second lower bound for deletion period
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/L

#1369 CHANGELOG: Document changes since 0.13.1
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1374 update vendoring of cloud-credential-operator
  Gopkg.lock
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/aws_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/codec.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/doc.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/register.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/aws/client.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/controller/assets/bindata.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/controller/utils/condition_utils.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/controller/utils/utils.go
  vendor/github.com/openshift/cloud-credential-operator/version/version.go
Labels: approved, lgtm, size/L

#1375 cmd/openshift-install: switch bootstrap-complete watcher to UntilWithSync
  cmd/openshift-install/create.go
  cmd/openshift-install/watch.go
Labels: approved, lgtm, size/L

#1373 openstack: Set hostnames for nodes
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/service/main.tf
Labels: approved, lgtm, size/M

#1380 cmd/openshift-install/create: Use NewListWatchFromClient
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/M

#1384 update openshift/api for network config changes
  Gopkg.lock
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/type_features.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_features.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_registries.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/registry.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduling.go
Labels: approved, lgtm, size/XXL

#1388 assets: no worker machinesets file for None
  pkg/asset/machines/worker.go
  pkg/asset/manifests/openshift.go
Labels: approved, lgtm, size/XS

#1390 openstack: Use the right security group name for machines
  pkg/asset/machines/openstack/machines.go
Labels: approved, lgtm, size/XS

#1379 asset/manifests: redact the pull-secret from the cluster object of the install-config
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/S

#1396 [AWS] Remove unused/legacy boostrap etcd ports in master security group
  data/data/aws/vpc/sg-master.tf
Labels: approved, lgtm, size/S

#1405 asset/manifests: add Scheduler cluster config
  pkg/asset/manifests/scheduler.go
Labels: approved, lgtm, size/M

#1403 pkg/destroy/aws: Destroy all instances not terminated
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/S

#1268 pkg/destroy: data/aws: delete instance profiles even if they are detached
  pkg/destroy/aws.go
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/M

#1407 hack/build: Pin to RHCOS 400.7.20190306.0
  hack/build.sh
  pkg/types/aws/validation/platform.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/M

#1376 pkg/version: Include the commit hash
  cmd/openshift-install/log.go
  cmd/openshift-install/version.go
  hack/build.sh
  pkg/version/version.go
Labels: approved, lgtm, size/S

#1393 cmd/openshift-install/upi: Add a user-provided-infrastructure subcommand
  cmd/openshift-install/create.go
  cmd/openshift-install/main.go
  cmd/openshift-install/upi.go
  docs/user/aws/install.md
  docs/user/customization.md
Labels: approved, lgtm, size/L

#1387 adding initial vsphere tf files
  upi/vsphere/bootstrap/README.md
  upi/vsphere/bootstrap/main.tf
  upi/vsphere/main.tf
  upi/vsphere/masters/README.md
  upi/vsphere/masters/main.tf
  upi/vsphere/resource_pool/README.md
  upi/vsphere/resource_pool/main.tf
  upi/vsphere/resource_pool/output.tf
  upi/vsphere/resource_pool/variables.tf
  upi/vsphere/route53/README.md
  upi/vsphere/route53/main.tf
  upi/vsphere/route53/variables.tf
  upi/vsphere/variables.tf
  upi/vsphere/workers/README.md
  upi/vsphere/workers/main.tf
  upi/vsphere/workers/variables.tf
Labels: approved, lgtm, size/XL, version/4.1

#1415 openstack: name swift container according to cluster_id
  data/data/openstack/main.tf
Labels: approved, lgtm, size/XS

#1417 create cluster: change Creating cluster to Creating infrastructure resources
  pkg/asset/cluster/cluster.go
Labels: approved, lgtm, size/XS

#1335 tls: remove deprecated kubelet.kubeconfig
  docs/design/resource_dep.svg
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/kubeconfig/kubelet.go
  pkg/asset/tls/kubelet.go
Labels: approved, lgtm, size/XXL

#1401 Bug 1684670: data/data/bootstrap: add kube-client-agent-image flag
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1424 Revert "data/data/bootstrap: add kube-client-agent-image flag"
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1421 Switch api ELBs to /readyz for healthz checks
  data/data/aws/vpc/master-elb.tf
Labels: approved, lgtm, size/XS

#1429 Bug 1684670: data/data/bootstrap: add kube-client-agent-image flag
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1434 pkg/destroy/aws: Add deleteEC2NetworkInterfaceByVPC
  pkg/destroy/aws/aws.go
Labels: approved, kind/bug, lgtm, platform/aws

#1408 Adding initial user doc/guide & materials for UPI AWS installation
  docs/user/aws/README.md
  docs/user/aws/images/install_upi_vpc.png
  docs/user/aws/install.md
  docs/user/aws/install_upi.md
  upi/aws/cloudformation/01_vpc.yaml
  upi/aws/cloudformation/02_cluster_infra.yaml
  upi/aws/cloudformation/03_cluster_security.yaml
  upi/aws/cloudformation/04_cluster_bootstrap.yaml
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, size/XXL

#1420 openstack: Always set the api DNS entry
  data/data/openstack/main.tf
  data/data/openstack/service/main.tf
  data/data/openstack/service/variables.tf
  data/data/openstack/topology/outputs.tf
Labels: approved, lgtm, size/S

#1438 fixes a grammatical typo
  docs/user/overview.md
Labels: approved, lgtm, size/XS

#1432 cmd/openshift-install/create: Log progressing messages
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/XS

#1414 libvirt CI Dockerfile fix
  images/nested-libvirt/Dockerfile
Labels: approved, lgtm, size/XS

#1439 pkg/destroy/aws: Remove lastError value masking
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/L

#1446 upi/vshpere: Add initial support for vSphere UPI
  upi/vsphere/README.md
  upi/vsphere/machine/main.tf
  upi/vsphere/machine/variables.tf
  upi/vsphere/main.tf
  upi/vsphere/resource_pool/main.tf
  upi/vsphere/resource_pool/output.tf
  upi/vsphere/resource_pool/variables.tf
  upi/vsphere/route53/main.tf
  upi/vsphere/route53/variables.tf
  upi/vsphere/terraform.tfvars.example
  upi/vsphere/variables.tf
Labels: approved, lgtm, size/XL

#1425 docs/user/customization: Catch up with "Creating infrastructure resources"
  docs/user/customization.md
Labels: approved, lgtm, size/XS

#1451 upi/vsphere: support rhcos-latest template
  upi/vsphere/machine/main.tf
  upi/vsphere/machine/variables.tf
  upi/vsphere/main.tf
  upi/vsphere/terraform.tfvars.example
  upi/vsphere/variables.tf
Labels: approved, lgtm, size/L

#1447 cmd/openshift-install/create: Log progress on timeout too
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/M

#1445 bootstrap: Work around systemd-journal-gateway DynamicUser=yes
  data/data/bootstrap/systemd/units/chown-gatewayd-key.service
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, size/S

#1456 images/installer: add image that can be used to instal UPI platforms
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, size/M

#1449 Remove cluster-api cluster object dependency
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  pkg/asset/manifests/cluster_k8s_io.go
  pkg/asset/manifests/network.go
  pkg/asset/manifests/openshift.go
Labels: approved, lgtm, size/M

#1422 release: Allow release image to be directly substituted into binary
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/release_image.go
Labels: approved, lgtm, size/M

#1462 CHANGELOG: Document changes since 0.14.0
  CHANGELOG.md
  docs/design/resource_dep.svg
Labels: approved, lgtm, size/XXL

#1431 Re-add support for trunk ports
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
Labels: approved, lgtm, size/S

#1453 [openstack] Support for tagging workers
  Gopkg.lock
  pkg/asset/machines/openstack/machines.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#1459 rhcos: Bump bootimage to 410.8.20190325.0
  hack/build.sh
  pkg/rhcos/builds.go
Labels: approved, lgtm, size/XS

#1458 pkg/types: add vsphere platform
  pkg/asset/cluster/metadata.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platform.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/rhcos/image.go
  pkg/asset/store/assetcreate_test.go
  pkg/types/installconfig.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig_test.go
  pkg/types/vsphere/defaults/platform.go
  pkg/types/vsphere/defaults/platform_test.go
  pkg/types/vsphere/doc.go
  pkg/types/vsphere/machinepool.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/machinepool.go
  pkg/types/vsphere/validation/machinepool_test.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  upi/vsphere/README.md
Labels: approved, lgtm, size/L

#1410 Re-group the network operator crd.
  data/data/manifests/openshift/cluster-networkconfig-crd.yaml
Labels: approved, lgtm, size/S

#1416 Add initial docs and example implementation for UPI bare-metal
  docs/user/metal/install_upi.md
  upi/metal/.gitignore
  upi/metal/README.md
  upi/metal/bootstrap/matchbox.tf
  upi/metal/bootstrap/outputs.tf
  upi/metal/bootstrap/packet.tf
  upi/metal/bootstrap/variables.tf
  upi/metal/config.tf
  upi/metal/main.tf
  upi/metal/outputs.tf
  upi/metal/terraform.tfvars.example
Labels: approved, lgtm, size/XL

#1469 pkg/types/aws/validation: Require machine-pool zones in platform region
  pkg/types/aws/validation/machinepool.go
  pkg/types/aws/validation/machinepool_test.go
  pkg/types/aws/validation/platform.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/machinepools.go
  pkg/types/validation/machinepools_test.go
Labels: approved, lgtm, size/L

#1482 chore: Bumping protobuf version to 1.3.1
  Gopkg.lock
  vendor/github.com/golang/protobuf/proto/decode.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/golang/protobuf/proto/equal.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/message_set.go
  vendor/github.com/golang/protobuf/proto/pointer_reflect.go
  vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/duration.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
Labels: approved, lgtm, ok-to-test, size/XL

#1435 Fixed DNS record description for OpenStack
  docs/user/openstack/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1476 upi/vsphere: create apps dns entry
  upi/vsphere/route53/main.tf
Labels: approved, lgtm, size/S

#1481 pkg/asset/machines/worker: Structured workers
  data/data/aws/main.tf
  data/data/aws/variables-aws.tf
  data/data/aws/vpc/common.tf
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/variables.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
  docs/user/aws/limits.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/machines/machineconfig/manifest.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/openshift.go
  pkg/asset/store/assetcreate_test.go
  pkg/asset/targets/targets.go
  pkg/tfvars/aws/aws.go
Labels: approved, lgtm, size/L

#1493 machines: fix machine asset for None, VSphere platform
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/M

#1491 aws/permissions: Add s3:GetBucketObjectLockConfiguration to pre-flight checks
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, size/S

#1486 Openstack doc
  docs/dev/openstack-howto.md
  docs/user/openstack/README.md
Labels: approved, lgtm, size/S

#1497 Dockerfile.upi.ci: declari cli image as input image
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, size/XS

#1483 BUG 1670700: data/data/bootstrap: set metric-ca flags for kube-etcd-signer-server
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1499 types: move vsphere out of tui
  pkg/types/installconfig.go
Labels: approved, lgtm, size/XS

#1470 vSphere UPI - Use a folder for virtual machines
  upi/vsphere/folder/main.tf
  upi/vsphere/folder/output.tf
  upi/vsphere/folder/variables.tf
  upi/vsphere/machine/main.tf
  upi/vsphere/machine/variables.tf
  upi/vsphere/main.tf
Labels: approved, lgtm, size/M

#1504 cmd/openshift-install/create: remove templates
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/S
