Repository openshift/installer, pull requests merged in 2019-06, with the labels that each got.

#1794 Text edits for the CloudFormation templates
  upi/aws/cloudformation/01_vpc.yaml
  upi/aws/cloudformation/02_cluster_infra.yaml
  upi/aws/cloudformation/03_cluster_security.yaml
  upi/aws/cloudformation/04_cluster_bootstrap.yaml
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, size/L

#1781 docs: add initial docs for creating clusters on Azure
  docs/user/azure/README.md
  docs/user/azure/credentials.md
  docs/user/azure/customization.md
  docs/user/azure/dnszone.md
  docs/user/azure/images/install_console.png
  docs/user/azure/images/install_nodes.png
  docs/user/azure/images/install_resource_group.png
  docs/user/azure/install.md
Labels: approved, lgtm, platform/azure, size/L

#1809 docs/azure: add instructions for approving CSRs
  docs/user/azure/install.md
Labels: approved, lgtm, size/S

#1813 docs/azure: include step to create vhd container in storage account
  docs/user/azure/install.md
Labels: approved, lgtm, size/XS

#1818 Refresh openstack-approvers group
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1808 Fix /usr/local/bin/haproxy-watch.sh if-conditionals
  data/data/openstack/service/main.tf
Labels: approved, lgtm, ok-to-test, platform/openstack, size/XS

#1811 update default Region name
  pkg/asset/installconfig/openstack/openstack.go
Labels: approved, lgtm, ok-to-test, platform/openstack, size/XS

#1820 data/data/openstack: Remove cluster name from servers
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/masters/main.tf
Labels: approved, lgtm, size/XS

#1826 Refresh troubleshooting doc to use machine api
  docs/user/troubleshooting.md
Labels: approved, lgtm, size/S

#1822 cmd: gather the logs from bootstrap instead of printing commands
  Gopkg.lock
  Gopkg.toml
  cmd/openshift-install/gather.go
  pkg/gather/ssh/agent.go
  pkg/gather/ssh/ssh.go
  vendor/github.com/kr/fs/LICENSE
  vendor/github.com/kr/fs/filesystem.go
  vendor/github.com/kr/fs/walk.go
  vendor/github.com/pkg/sftp/CONTRIBUTORS
  vendor/github.com/pkg/sftp/LICENSE
  vendor/github.com/pkg/sftp/attrs.go
  vendor/github.com/pkg/sftp/attrs_stubs.go
  vendor/github.com/pkg/sftp/attrs_unix.go
  vendor/github.com/pkg/sftp/client.go
  vendor/github.com/pkg/sftp/conn.go
  vendor/github.com/pkg/sftp/debug.go
  vendor/github.com/pkg/sftp/match.go
  vendor/github.com/pkg/sftp/packet-manager.go
  vendor/github.com/pkg/sftp/packet-typing.go
  vendor/github.com/pkg/sftp/packet.go
  vendor/github.com/pkg/sftp/release.go
  vendor/github.com/pkg/sftp/request-attrs.go
  vendor/github.com/pkg/sftp/request-errors.go
  vendor/github.com/pkg/sftp/request-example.go
  vendor/github.com/pkg/sftp/request-interfaces.go
  vendor/github.com/pkg/sftp/request-server.go
  vendor/github.com/pkg/sftp/request-unix.go
  vendor/github.com/pkg/sftp/request.go
  vendor/github.com/pkg/sftp/request_windows.go
  vendor/github.com/pkg/sftp/server.go
  vendor/github.com/pkg/sftp/server_statvfs_darwin.go
  vendor/github.com/pkg/sftp/server_statvfs_impl.go
  vendor/github.com/pkg/sftp/server_statvfs_linux.go
  vendor/github.com/pkg/sftp/server_statvfs_stubs.go
  vendor/github.com/pkg/sftp/server_stubs.go
  vendor/github.com/pkg/sftp/server_unix.go
  vendor/github.com/pkg/sftp/sftp.go
  vendor/golang.org/x/crypto/ssh/agent/client.go
  vendor/golang.org/x/crypto/ssh/agent/forward.go
  vendor/golang.org/x/crypto/ssh/agent/keyring.go
  vendor/golang.org/x/crypto/ssh/agent/server.go
Labels: approved, lgtm, size/XXL

#1807 libvirt,docs: Make console workaround a bit easier
  docs/dev/libvirt/README.md
Labels: approved, lgtm, size/XS

#1827 Add Proxy to InstallConfig
  pkg/asset/manifests/network.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
Labels: approved, lgtm, size/L

#1835 Bug 1711533: Remove unnecessary binding to system:discovery
  data/data/manifests/openshift/binding-discovery.yaml
  docs/design/resource_dep.svg
  pkg/asset/manifests/openshift.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/openshift/binding-discovery.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#1846 restrict clustername validation to include DNS subdomain and DNS label requirements.
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/S

#1823 [openstack] enhance doc for openstack readme
  docs/user/openstack/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1849 openstack: Retrieve namespaced credentials
  pkg/asset/machines/openstack/machines.go
Labels: approved, lgtm, size/XS

#1847 bootkube: add mco image
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1833 machines/azure: Set subnets for control plane and compute machines
  Gopkg.lock
  data/data/azure/vnet/vnet.tf
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go
Labels: approved, lgtm, size/M

#1729 openstack: Generate cloud provider config
  data/data/manifests/openshift/cloud-creds-secret.yaml.template
  data/data/manifests/openshift/rolebinding-cloud-creds-secret-reader.yaml.template
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/openstack/OWNERS
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
  pkg/asset/manifests/template.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/openshift/rolebinding-cloud-creds-secret-reader.go
Labels: approved, lgtm, size/L

#1871 bootkube: fix indentation of mco image option
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1712 [AWS] Correcting UPI gp2 volumes to match IPI sizes
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, size/M

#1614 cmd/openshift-install/create: Drop "timed out waiting for the condition"
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/XS

#1861 openstack:Add log for delete unsuccessful action
  pkg/destroy/openstack/openstack_deprovision.go
Labels: approved, lgtm, ok-to-test, size/XS

#1879 pkg/gather/ssh: Attempt to use existing SSH agents
  pkg/gather/ssh/agent.go
  pkg/gather/ssh/ssh.go
Labels: approved, lgtm, size/S

#1881 bootkube: new image for kube-apiserver
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1878 openstack:update doc link
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/README.md
Labels: approved, lgtm, ok-to-test, platform/openstack, size/XS

#1877 openstack:update gophercloud
  Gopkg.lock
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/auth_result.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
Labels: approved, lgtm, ok-to-test, platform/openstack, size/XL

#1885 bootkube: pass the hyperkube image as main image
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1866 pkg/asset/manifests/proxy: Create new proxy manifest
  Gopkg.lock
  docs/design/resource_dep.svg
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/proxy.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/clientset.go
Labels: approved, lgtm, size/XXL

#1888 pkg/destroy/aws: do not fail uninstall on absent s3 bucket
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/S

#1863 Bump worker resources
  pkg/asset/machines/libvirt/machines.go
Labels: approved, lgtm, platform/libvirt, size/XS

#1870 [openstack] Remove gateway before delete router
  pkg/destroy/openstack/openstack_deprovision.go
Labels: approved, lgtm, ok-to-test, platform/openstack, size/S

#1894 Azure assets: set machine vnet and managed identity explicitly
  pkg/asset/machines/azure/machines.go
Labels: approved, lgtm, size/XS

#1896 bootkube: stop passing temporary image flag to kas
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1898 Add conversion test when no API version is specified.
  pkg/types/conversion/installconfig_test.go
Labels: approved, lgtm, size/S

#1832 Add proxy configuration to bootstrap node
  data/data/bootstrap/files/etc/profile.d/proxy.sh.template
  data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env.conf.template
  docs/dev/proxy.md
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/proxy.go
Labels: approved, lgtm, size/M

#1897 pkg/types/validation: fix proxy validations to drop incorrect requirements on scheme
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/S

#1895 rhcos: Bump to 420.8.20190624.0
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#1890 asset/cluster: inject installer info when creating
  pkg/asset/cluster/tfvars.go
Labels: approved, lgtm, size/M

#1889 Add required GCP types
  pkg/types/defaults/installconfig.go
  pkg/types/gcp/defaults/platform.go
  pkg/types/gcp/doc.go
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/gcp/validation/machinepool_test.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  pkg/types/installconfig.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/L

#1903 Bug 1722221: [release-4.1] blank api version
  pkg/types/conversion/installconfig.go
  pkg/types/conversion/installconfig_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1848 align destroyers code base for better readability
  cmd/openshift-install/destroy.go
  pkg/destroy/aws.go
  pkg/destroy/aws/aws.go
  pkg/destroy/aws/doc.go
  pkg/destroy/aws/register.go
  pkg/destroy/azure/azure.go
  pkg/destroy/bootstrap/doc.go
  pkg/destroy/libvirt/libvirt.go
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, size/L

#1867 azure: public IP for bootstrap node
  cmd/openshift-install/gather.go
  data/data/azure/bootstrap/main.tf
  data/data/azure/bootstrap/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/master/variables.tf
  data/data/azure/vnet/nsg.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/public-lb.tf
  data/data/azure/vnet/variables.tf
  pkg/terraform/gather/azure/ip.go
Labels: approved, lgtm, size/L

#1904 azure: reduce the install-config api to smallest set
  pkg/types/azure/machinepool.go
  pkg/types/azure/platform.go
Labels: approved, lgtm, size/S

#1892 issue-template: Make it easy to remove irrelevant platforms
  .github/ISSUE_TEMPLATE.md
Labels: approved, lgtm, size/XS

#1868 azure: set default machine types by region
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/defaults/machines.go
  pkg/types/azure/defaults/platform.go
Labels: approved, lgtm, size/M

#1496 openstack: delete loadbalancer resources
  Gopkg.lock
  pkg/destroy/openstack/openstack.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/urls.go
Labels: approved, lgtm, platform/openstack, size/XXL

#1917 types/azure: allow specifying the disk size for pools
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/worker.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
Labels: approved, lgtm, size/M
