Repository openshift/installer, pull requests merged in 2019-05, with the labels that each got.

#1693 pkg/asset/ignition/machine/node: Move pointer Ignition configs to api-int
  pkg/asset/ignition/machine/node.go
  pkg/asset/tls/mcscertkey.go
Labels: approved, lgtm, size/XS

#1686 BUG 1702050: Add aws role labels back (revert #1474)
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/aws/machinesets.go
Labels: approved, lgtm, size/S

#1696 Update OWNERS.
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1649 Drop AWS UPI control-plane Machines and compute MachineSets
  docs/user/aws/install_upi.md
  upi/aws/cloudformation/01_vpc.yaml
  upi/aws/cloudformation/02_cluster_infra.yaml
  upi/aws/cloudformation/03_cluster_security.yaml
  upi/aws/cloudformation/04_cluster_bootstrap.yaml
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, size/L

#1705 cmd: fix some copy in the help text
  cmd/openshift-install/gather.go
Labels: approved, lgtm, size/XS

#1700 vendor: fix inconsistent state
  Gopkg.lock
  Gopkg.toml
  hack/verify-vendor.sh
Labels: approved, lgtm, size/S

#1702 Fix broken link in libvirt doc.
  docs/dev/dependencies.md
  docs/dev/libvirt/README.md
Labels: approved, lgtm, size/XS

#1699 images/nested-libvirt/Dockerfile: Fix build to builder typo
  images/nested-libvirt/Dockerfile
Labels: approved, lgtm, size/XS

#1707 Remove myself from reviewers due to pending absence
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1704 pkg/destroy/aws: Skip direct tag deletion for network interfaces
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/M

#1706 upi/aws/cloudformation: Cap InfrastructureName at 27 chars
  upi/aws/cloudformation/02_cluster_infra.yaml
  upi/aws/cloudformation/03_cluster_security.yaml
  upi/aws/cloudformation/04_cluster_bootstrap.yaml
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, size/M

#1703 vendor: move to official openshift fork for cluster-api-provider-azure
  Gopkg.lock
  Gopkg.toml
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/azureclusterproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/azureclusterproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#1714 pkg/asset/manifests/azure: leave cloud-provider identity empty
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
Labels: approved, lgtm, size/S

#1711 openstack: Rely on the cloud configured nameservers
  data/data/openstack/topology/private-network.tf
Labels: approved, lgtm, size/S

#1720 Bug 1707573: *: remove deprecated EtcdCA and promote EtcdSigner
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/manifests/bootkube/etcd-client-secret.yaml.template
  data/data/manifests/bootkube/etcd-serving-ca-configmap.yaml.template
  data/data/manifests/bootkube/etcd-signer-client-secret.yaml.template
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/templates/content/bootkube/etcd-client-secret.go
  pkg/asset/templates/content/bootkube/etcd-signer-client-secret.go
  pkg/asset/tls/etcd.go
Labels: approved, lgtm, size/L

#1718 Bug 1706689: asset/manifests: internal api server URL for infrastructure
  Gopkg.lock
  cmd/openshift-install/create.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/utils.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
Labels: approved, lgtm, size/XL

#1730 images/installer: update upi Dockerfile to fetch matchbox using releases
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, size/S

#1731 rhcos: Bump to 410.8.20190508.1
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#1722 BUG 1707096: gather: collect secret names for failure analysis
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, lgtm, size/XS

#1733 openstack: use static .repo file for openstack client
  images/openstack/Dockerfile.ci
  images/openstack/rdo-stein.repo
Labels: approved, lgtm, size/S

#1735 Bug 1708307: bootstrap/files: installer-gather.sh to gather more rendered-assets
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, lgtm, size/XS

#1736 openstack: fix comments from 1733
  images/openstack/Dockerfile.ci
  images/openstack/rdo-stein.gpg
  images/openstack/rdo-stein.repo
Labels: approved, lgtm, size/S

#1738 Fix the UPI's Readme deploy-packet url
  upi/metal/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1723 Bug 1707096: gather: suffix container logs with container ids for uniqueness
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, size/XS

#1726 [openstack] More robust deprovision strategy
  pkg/destroy/openstack/openstack_deprovision.go
Labels: approved, lgtm, size/M

#1750 Bug 1709869: tls: add openshift service to DNS names
  pkg/asset/tls/apiserver.go
Labels: approved, lgtm, size/XS

#1691 vendor: update terraform-provider-libvirt
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/acceptance_tests_functions_helpers.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/cloudinit_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/helper/suppress/strings.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/network.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/network_dns.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/network_routes.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_cloud_init.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_coreos_ignition.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_network.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_volume.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/stream.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/utils_net.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/utils_volume.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/volume.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/volume_image.go
Labels: approved, lgtm, ok-to-test, platform/libvirt, size/XXL

#1697 Remove httpcache
  Gopkg.lock
  pkg/tfvars/libvirt/cache.go
Labels: approved, lgtm, ok-to-test, size/S

#1747 data: add approve-csr service to approve CSRs until bootstrap is complete
  data/data/bootstrap/files/usr/local/bin/approve-csr.sh
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/systemd/units/approve-csr.service
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, size/S

#1754 pkg/asset: Add filenames to "failed to unmarshal" errors
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/S

#1756 bootstrap: update default release image to track 4.2 origin
  pkg/asset/ignition/bootstrap/release_image.go
Labels: approved, lgtm, size/XS

#1454 feat: Add azure terraform
  data/data/azure/bootstrap/main.tf
  data/data/azure/bootstrap/variables.tf
  data/data/azure/bootstrap/versions.tf
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/dns/versions.tf
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/master/outputs.tf
  data/data/azure/master/variables.tf
  data/data/azure/master/versions.tf
  data/data/azure/variables-azure.tf
  data/data/azure/versions.tf
  data/data/azure/vnet/common.tf
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/nsg.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/public-lb.tf
  data/data/azure/vnet/variables.tf
  data/data/azure/vnet/versions.tf
  data/data/azure/vnet/vnet.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm, ok-to-test, size/XXL

#1761 Bug 1711844: bootkube.sh: Use pause image from payload
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/S

#1721 pkg/types: enable azure platform
  pkg/types/installconfig.go
Labels: approved, lgtm, size/XS

#1760 types/conversion: return no version provided error when trying to convert
  pkg/types/conversion/installconfig.go
Labels: approved, lgtm, size/XS

#1770 Bug 1712562: pin the 4.1 GA candidate RHCOS build boot images
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#1772 azure: pass credentials provided to installer to terraform
  data/data/azure/main.tf
  data/data/azure/variables-azure.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm, size/M

#1774 pin to the 4.1 GA candidate RHCOS images
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#1755 aws/defaults/platform: Default to m5 in ap-east-1
  pkg/types/aws/defaults/platform.go
  pkg/types/aws/validation/platform.go
  platformtests/aws/default_instance_class_test.go
Labels: approved, lgtm, size/S

#1371 docs/dev/libvirt: Add troubleshooting docs for libvirt console issue.
  docs/dev/libvirt/README.md
Labels: approved, lgtm, ok-to-test, platform/libvirt, size/M

#1778 data/azure: create an explicit dependency on private zone before VMs are created
  data/data/azure/bootstrap/variables.tf
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/variables.tf
Labels: approved, lgtm, platform/azure, size/M

#1780 data/azure: make machine object name and VM name created by terraform same
  data/data/azure/master/master.tf
Labels: approved, lgtm, platform/azure, size/XS

#1744 hack/build: Use SOURCE_GIT_COMMIT if set
  hack/build.sh
Labels: approved, lgtm, size/XS

#1779 asset/machines: set the instance type for workers on azure
  pkg/asset/machines/worker.go
Labels: approved, lgtm, platform/azure, size/XS

#1776 Doc changes for libvirt backend
  docs/dev/libvirt/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#1782 docs/user/aws/install: openshift-install-linux-amd64 -> openshift-install
  docs/user/aws/install.md
Labels: approved, lgtm, size/XS

#1786 Bug 1713157: pkg/types/aws/defaults/platform: Default us-west-2 to m5
  pkg/types/aws/defaults/platform.go
  platformtests/aws/default_instance_class_test.go
Labels: approved, lgtm, size/L

#1713 README: Reference vSphere and metal from the platform section
  README.md
  pkg/asset/installconfig/platform.go
Labels: approved, lgtm, size/XS

#1785 azure: allow installer to consume `AZURE_AUTH_LOCATION` env for credentials file
  pkg/asset/installconfig/azure/session.go
Labels: approved, lgtm, platform/azure, size/S

#1763 gather: update the state handling for terraform 0.12
  cmd/openshift-install/gather.go
  pkg/terraform/exec/state.go
  pkg/terraform/gather/aws/ip.go
  pkg/terraform/gather/libvirt/ip.go
  pkg/terraform/gather/openstack/ip.go
  pkg/terraform/state.go
Labels: approved, lgtm, size/L

#1802 asset/manifests/azure: update the azure cloud provider rate limits
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
Labels: approved, lgtm, size/S

#1803 data/approve-csr.sh: fix the exit condition to use correct file path for bootkube done
  data/data/bootstrap/files/usr/local/bin/approve-csr.sh
Labels: approved, lgtm, size/XS

#1799 data/azure: create explicit deps to internal dns zone before any resource in vnet
  data/data/azure/main.tf
  data/data/azure/vnet/common.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/variables.tf
  data/data/azure/vnet/vnet.tf
Labels: approved, lgtm, size/M

#1801 Bug 1715108: data/data/manifests/bootkube/cvo-overrides: Move to stable-4.2
  data/data/manifests/bootkube/cvo-overrides.yaml.template
  docs/user/troubleshooting.md
Labels: approved, lgtm, size/XS

#1795 gather: add support for azure
  cmd/openshift-install/gather.go
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  pkg/terraform/gather/azure/ip.go
Labels: approved, lgtm, size/M

#1798 README: remove experimental designation for bare metal and vSphere
  README.md
Labels: approved, lgtm, size/XS

#1806 data/azure: clarify that the password isn't used
  data/data/azure/bootstrap/main.tf
  data/data/azure/master/master.tf
Labels: approved, lgtm, size/S

#1628 machines/libvirt: Drop volume paths
  pkg/asset/machines/libvirt/machines.go
Labels: approved, lgtm, size/XS
