Repository openshift/installer, pull requests merged in 2019-08, with the labels that each got.

#2135 Azure: update install documentation to reflect current reality
  docs/user/azure/install.md
Labels: approved, lgtm, size/M

#2127 openstack: add tag and desc to bootstrap floating IP
  data/data/openstack/topology/private-network.tf
Labels: approved, lgtm, size/XS

#2116 [gcp] pkg/assets/manifest: add subnetwork name to cloud config
  pkg/asset/manifests/gcp/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig_test.go
Labels: approved, lgtm, platform/google, size/S

#2131 data/bootstrap/files/usr/local/bin/bootkube.sh.template: Drop OPENSHIFT_HYPERSHIFT_IMAGE
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#2138 [gcp] pkg/asset/machines - add project id to machines
  Gopkg.lock
  pkg/asset/machines/gcp/machines.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
Labels: approved, lgtm, platform/google, size/XS

#2134 [gcp] data/data: add service user role to masters
  data/data/gcp/master/main.tf
Labels: approved, lgtm, platform/google, size/XS

#2139 baremetal: Add dnsVIP to sample install-config.
  docs/user/metal/install_ipi.md
Labels: approved, lgtm, platform/baremetal, size/XS

#2120 libvirt: Assign fully-qualified domain names to master & bootstrap nodes
  data/data/libvirt/bootstrap/main.tf
  data/data/libvirt/bootstrap/variables.tf
  data/data/libvirt/main.tf
Labels: approved, lgtm, size/S

#2125 asset/cluster: inject installer info when creating
  pkg/asset/cluster/tfvars.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#2133 data/bootstrap/files/usr/local/bin/bootkube.sh.template: Quote image expansions
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/M

#2143 Bump openstack image to use cli 4.1
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, size/XS

#2001 Bug 1723798: bootkube: run all podman commands in the host network.
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2141 pkg/types/installconfig: Mention PEM and X.509 in additionalTrustBundle godoc
  docs/user/customization.md
  pkg/types/installconfig.go
Labels: approved, lgtm, size/XS

#2086 data/data/bootstrap: use loopback kubeconfig for API access
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/systemd/units/approve-csr.service
  data/data/bootstrap/systemd/units/openshift.service
Labels: approved, lgtm, size/XS

#2161 [gcp] Destroy service account role bindings
  Gopkg.lock
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/iam.go
  vendor/google.golang.org/api/cloudresourcemanager/v1/cloudresourcemanager-gen.go
Labels: approved, lgtm, platform/google, size/XXL

#2167 OpenStack: update approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2163 [gcp] pkg/destroy/gcp: Fix disk deletion
  pkg/destroy/gcp/compute.go
Labels: approved, lgtm, size/XS

#2164 Revert "data/data/azure/dns: use public ip behind internal apis"
  data/data/azure/dns/dns.tf
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/nsg.tf
  data/data/azure/vnet/public-lb.tf
Labels: approved, lgtm, size/M

#2144 OpenStack: change provider API
  Gopkg.lock
  pkg/asset/machines/openstack/machines.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#2087 register baremetal hosts
  Gopkg.lock
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
  pkg/asset/machines/master.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/doc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/register.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/zz_generated.defaults.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/access.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
Labels: approved, lgtm, platform/baremetal, size/XXL

#2140 baremetal: Validate VIPs are in MachineCIDR
  docs/user/metal/install_ipi.md
  pkg/types/baremetal/validation/platform.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, platform/baremetal, size/L

#2168 [gcp] docs/user: Add GCP installer user documentation
  docs/user/gcp/README.md
  docs/user/gcp/dns.md
  docs/user/gcp/iam.md
  docs/user/gcp/images/public_dns_zone.png
  docs/user/gcp/images/zone_nameserver_records.png
  docs/user/gcp/install.md
  docs/user/gcp/postinstall.md
Labels: approved, lgtm, platform/google, size/L

#2173 manifests/additionaltrustbundleconfig.go: move the config map to openshift-config
  Gopkg.lock
  pkg/asset/manifests/additionaltrustbundleconfig.go
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#1959 openstack: remove the service VM
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/service/main.tf
  data/data/openstack/service/variables.tf
  data/data/openstack/topology/outputs.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/sg-lb.tf
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/node.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/tls/mcscertkey.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/defaults/platform.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, platform/openstack, size/XL

#2181 [gcp] pkg/asset/machines: auto delete machine boot disks
  pkg/asset/machines/gcp/machines.go
Labels: approved, lgtm, platform/google, size/XS

#2171 bootkube.sh: remove duplicate --net args to podman.
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#2188 [gcp] docs/user/gcp: document required services
  docs/user/gcp/iam.md
Labels: approved, lgtm, size/S

#2189 OpenStack: Add region to the cloud provider config
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Labels: approved, lgtm, platform/openstack, size/M

#2117 upi/gcp: initial deployment manager templates
  docs/user/gcp/install_upi.md
  upi/gcp/01_vpc.py
  upi/gcp/02_infra.py
  upi/gcp/03_security.py
  upi/gcp/04_bootstrap.py
  upi/gcp/05_control_plane.py
  upi/gcp/06_worker.py
Labels: approved, lgtm, platform/google, size/XXL

#2191 gcp: increase the ports per VM for NAT
  data/data/gcp/network/network.tf
Labels: approved, lgtm, platform/google, size/XS

#2192 gcp: correctly wire up the root volume type/size
  data/data/gcp/main.tf
Labels: approved, lgtm, platform/google, size/XS

#2036 openstack: Add OpenStack to the platform selection
  pkg/types/installconfig.go
Labels: approved, lgtm, platform/openstack, size/XS

#2194 openstack: set up `docs/design/openstack` OWNERS
  docs/design/openstack/OWNERS
Labels: approved, lgtm, platform/openstack, size/XS

#2148 OpenStack: Doccument Admin Requirements, Post Deployment Steps, and Networking Arch
  docs/design/openstack/networking-infrastructure.md
  docs/user/openstack/README.md
Labels: approved, lgtm, size/L

#2186 Bug 1737660: data/azure/master: use ReadOnly caching for OSDisk
  data/data/azure/master/master.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2159 gcp: include all hosts in the LB backend
  data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh
  data/data/gcp/network/lb.tf
Labels: approved, lgtm, platform/google, size/S

#2184 [gcp] pkg/destroy/gcp: Fix orphan service accounts
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/iam.go
Labels: approved, lgtm, platform/google, size/S

#2198 pkg/asset/manifests/proxy: Do not inject empty-string noProxy
  pkg/asset/manifests/proxy.go
Labels: approved, lgtm, size/XS

#2201 [gcp] data/data/gcp: remove role binding to storage.objectAdmin
  data/data/gcp/master/main.tf
Labels: approved, lgtm, platform/google, size/XS

#2200 docs/user/gcp/install: Link to the UPI install docs
  docs/user/gcp/install.md
  docs/user/gcp/install_upi.md
Labels: approved, lgtm, size/S

#2206 image: fix invalid yum commands in images
  images/baremetal/Dockerfile.ci
  images/installer/Dockerfile.upi.ci
  images/nested-libvirt/Dockerfile
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, platform/baremetal, size/S

#2205 [gcp] pkg/destroy/gcp: Use email to destroy service accounts
  pkg/destroy/gcp/iam.go
Labels: approved, lgtm, platform/google, size/XS

#2079 baremetal: Enable Ironic on the bootstrap VM
  data/data/baremetal/bootstrap/main.tf
  data/data/baremetal/main.tf
  data/data/baremetal/variables-baremetal.tf
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  data/data/bootstrap/baremetal/files/usr/local/bin/stopironic.sh
  data/data/bootstrap/baremetal/systemd/units/ironic.service
  docs/user/metal/install_ipi.md
  pkg/asset/cluster/baremetal/baremetal.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/machines/baremetal/machines.go
  pkg/asset/machines/baremetal/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/destroy/baremetal/baremetal.go
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/doc.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/requests.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/results.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/urls.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/provider.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/main.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/types/baremetal/defaults/platform.go
  pkg/types/baremetal/metadata.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, platform/baremetal, size/XL

#2220 baremetal: add `libvirt-devel` dependency for building
  images/baremetal/Dockerfile.ci
Labels: approved, lgtm, size/XS

#2153 Bug 1713374: Do not use machine role and in machineset matching labels
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/gcp/machinesets.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2122 Bug 1732858: unhardcode the cloud name for openstack
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/defaults/platform.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2217 hack: remove compile time RELEASE_IMAGE override
  hack/build.sh
Labels: approved, lgtm, size/XS

#2222 fix typo in message with MastersSchedulabe
  pkg/asset/manifests/scheduler.go
Labels: approved, lgtm, size/XS

#2223 OpenStack: Add Kuryr information to the OpenStack README file
  docs/user/openstack/README.md
Labels: approved, lgtm, size/L

#2224 docs/user/azure/credential.md: add section for requesting additional required permissions
  docs/user/azure/credentials.md
Labels: approved, lgtm, size/M

#2195 Bug 1741637: openstack: Add API Floating IP survey question
  pkg/asset/installconfig/openstack/openstack.go
  pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
  pkg/types/openstack/validation/realvalidvaluesfetcher.go
  pkg/types/openstack/validation/validvaluesfetcher.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/M

#2218 openstack: Update User Documentation
  docs/user/customization.md
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  docs/user/openstack/troubleshooting.md
Labels: approved, lgtm, platform/openstack, size/XL

#2240 Enhance kuryr documentation
  docs/user/openstack/README.md
Labels: approved, lgtm, size/XS

#2239 startironic.sh uses wrong route IP for CACHEURL
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm, ok-to-test, platform/baremetal, size/XS

#2213 Bug 1725524: types/aws/default: move ap-northeast-2 to m5 instance class
  pkg/types/aws/defaults/platform.go
  platformtests/aws/default_instance_class_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#2242 Bug 1743840: data/bootstrap/files/usr/local/bin/bootkube.sh.template: Localhost keys for etcd-signer
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2245 Bug 1743871: vendor: update terraform-provider-ironic to v0.1.7
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_node_v1.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/M

#2246 pkg/destroy/gcp: ensure nextPageToken is present in response to correctly handle pages
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/dns.go
  pkg/destroy/gcp/iam.go
  pkg/destroy/gcp/network.go
  pkg/destroy/gcp/storage.go
Labels: approved, lgtm, size/M

#2212 openstack: have gather bootstrap look for FIP
  pkg/terraform/gather/openstack/ip.go
Labels: approved, lgtm, platform/openstack, size/S

#2128 Bug 1740543: Consolidate bootstrap resources to bootstrap module
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/topology/outputs.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/L

#2257 Bug 1744532: proxy: add .svc and .cluster.local to default noProxy
  pkg/asset/manifests/proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2253 OpenStack: Better Docs Organization and Linking
  docs/user/openstack/README.md
  docs/user/openstack/kuryr.md
Labels: approved, lgtm, size/L

#2252 Adding openssl for proxy ci work
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, size/XS

#2145 Bug 1737102: vSphere UPI - Use template guest_id for machines guest_id
  upi/vsphere/machine/main.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2256 Bug 1719808: openstack: change bootstrap_fip module for gather
  pkg/terraform/gather/openstack/ip.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2264 RHCOS: update to release 42.80.20190823.0
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#2259 Bug 1737802: openstack: move swift container to the bootstrap module
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2221 Bug 1715635: docs/user/aws/install_upi: Document bring-your-own-DNS
  docs/user/aws/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2234 Bug 1743873: data/bootstrap: extract ironic images from release image
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  data/data/bootstrap/baremetal/systemd/units/ironic.service
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
  data/data/bootstrap/files/usr/local/bin/release-image.sh.template
  data/data/bootstrap/systemd/units/bootkube.service
  data/data/bootstrap/systemd/units/release-image.service.template
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/M

#2275 install-gather.sh: copy bootstrap-control-plane container logs
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, lgtm, size/XS

#2244 Update error message when automatic gather boostrap fails on cluster fail.
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/XS

#2249 Bug 1745004: baremetal: Use podman inspect to check ironic service status
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2281 Bug 1745004: baremetal: Clarify comment in startironic.sh.template
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/XS

#2272 Adds support for leading dots in domain names
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/M

#1829 Bug 1715001: hack/build: Use BUILD_VERSION if non-empty
  hack/build.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2276 Bug 1746230: Add target pools to gcp masters
  Gopkg.lock
  pkg/asset/machines/gcp/machines.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2284 Bug 1746459: destroy/aws: fix error expected when snapshot not found
  pkg/destroy/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2247 OpenStack: Document Swift quota requirements in the user docs
  docs/user/openstack/README.md
Labels: approved, lgtm, size/S

#2288 OpenStack: update troubleshooting docs
  docs/user/openstack/README.md
  docs/user/openstack/troubleshooting.md
Labels: approved, lgtm, size/S

#2286 Adds additional default proxy noProxy entries
  pkg/asset/manifests/proxy.go
Labels: approved, lgtm, size/S

#2295 Bug 1733867: openstack: Open mdns port for workers
  data/data/openstack/topology/sg-worker.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2262 pkg/destroy/azure: Delete app registrations during cluster destroy
  Gopkg.lock
  pkg/asset/installconfig/azure/session.go
  pkg/destroy/azure/azure.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/applications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/deletedapplications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/domains.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/groups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/oauth2permissiongrant.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/objects.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/serviceprincipals.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/signedinuser.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/users.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/version.go
Labels: approved, lgtm, size/XXL

#2289 Bug 1745907: upi/gcp: enable manual DNS entry for *.apps
  docs/user/gcp/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2254 docs/user/azure: Update Azure documention to be on par with AWS
  README.md
  docs/user/azure/README.md
  docs/user/azure/account.md
  docs/user/azure/credentials.md
  docs/user/azure/customization.md
  docs/user/azure/images/account_Create_your_Azure_free_account.png
  docs/user/azure/images/account_Microsoft_Azure.png
  docs/user/azure/images/account_Microsoft_Azure_Cloud_Computing_Platform_Services.png
  docs/user/azure/images/account_Sign_up.png
  docs/user/azure/images/account_Sign_up_1.png
  docs/user/azure/images/account_Sign_up_2.png
  docs/user/azure/images/account_Sign_up_3.png
  docs/user/azure/images/account_Sign_up_4.png
  docs/user/azure/images/account_Welcome_to_Microsoft_Azure.png
  docs/user/azure/images/limits_Microsoft_Azure_0.png
  docs/user/azure/images/limits_Microsoft_Azure_1.png
  docs/user/azure/images/limits_Microsoft_Azure_2.png
  docs/user/azure/images/limits_Microsoft_Azure_3.png
  docs/user/azure/images/limits_Microsoft_Azure_4.png
  docs/user/azure/images/limits_Microsoft_Azure_5.png
  docs/user/azure/images/limits_Microsoft_Azure_6.png
  docs/user/azure/images/limits_Microsoft_Azure_7.png
  docs/user/azure/limits.md
  docs/user/overview.md
Labels: approved, lgtm, size/L

#2296 upi/aws/cloudformation/01_vpc: Drop PublicNetworkAcl
  upi/aws/cloudformation/01_vpc.yaml
Labels: approved, lgtm, size/M
