Repository openshift/installer, pull requests merged in 2019-11, with the labels that each got.

#2586 AWS credential validation, preexisting networking
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/platformcredscheck.go
Labels: approved, lgtm, size/L

#2605 openstack: Add detail to disk requirements
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack, size/M

#2583 openstack UPI: Automate Network creation
  upi/openstack/01_network.yaml
  upi/openstack/README.md
  upi/openstack/down-01_network.yaml
  upi/openstack/inventory.yaml
  upi/openstack/requirements.txt
Labels: approved, lgtm, platform/openstack, size/L

#2528 OpenStack: Security enhancement: RHCOS image checksum validations
  data/data/openstack/main.tf
  data/data/openstack/variables-openstack.tf
  pkg/rhcos/builds.go
  pkg/rhcos/openstack.go
  pkg/tfvars/internal/cache/cache.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, lgtm, size/L

#2604 manifests/gcp: add infra-id as prefix for external IGs
  pkg/asset/manifests/gcp/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig_test.go
Labels: approved, lgtm, size/S

#2620 Bug 1768639: OpenStack Known issues
  docs/user/openstack/customization.md
  docs/user/openstack/known-issues.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/S

#2609 Bug 1766739: rhcos: Bump to 43.81.201911011153.0
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2619 Bug 1763927: asset/cluster/aws: create resourcetaggingapi client with region
  pkg/asset/cluster/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2618 Bug 1768564: baremetal: Fix image URL generation
  pkg/asset/machines/baremetal/machines.go
  pkg/asset/machines/baremetal/machinesets.go
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/M

#2626 OpenStack: return correct error if no flavors were found
  pkg/types/openstack/validation/realvalidvaluesfetcher.go
Labels: approved, lgtm, size/XS

#2631 OpenStack: Use UTF-8 locales in CI container image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, size/XS

#2625 Remove temporary cached files
  pkg/tfvars/internal/cache/cache.go
  pkg/tfvars/libvirt/cache.go
Labels: approved, lgtm, size/S

#2636 pkg/asset/manifests/azure/cloudproviderconfig_test: node-subnet -> worker-subnet
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
Labels: approved, lgtm, size/XS

#2641 Update README for OpenStack platform status
  README.md
Labels: approved, lgtm, size/XS

#2640 Bug 1766066: Revert "Merge pull request #2471 from openshift-cherrypick-robot/cher…
  pkg/asset/manifests/proxy.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#2643 nit: fix doc link issue
  docs/user/openstack/README.md
Labels: approved, lgtm, ok-to-test, platform/openstack, size/XS

#2638 openstack: Improve the Floating IP documentation
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack, size/M

#2635 docs/customization.md: add snippet on setting kernel arguments
  docs/user/customization.md
Labels: approved, lgtm, size/M

#2642 Bug 1770006: Orphaned Swift resources
  pkg/tfvars/openstack/bootstrap_ignition.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/M

#2645 Bug 1770441: OpenStack: unpack compressed image data
  pkg/rhcos/openstack.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/M

#2651 BZ 1770101: bootstrap: Ensure we've configured crio before it's started
  data/data/bootstrap/systemd/units/crio-configure.service.template
Labels: approved, lgtm, size/XS

#2633 Bug 1768978: RHCOS: bump to 43.81.201911081536.0 for FIPS support
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2589 Bug 1762413: pkg/destroy/gcp: retry deleting previously discovered resources
  pkg/destroy/gcp/address.go
  pkg/destroy/gcp/backendservice.go
  pkg/destroy/gcp/bucket.go
  pkg/destroy/gcp/bucketobject.go
  pkg/destroy/gcp/cloudcontroller.go
  pkg/destroy/gcp/cloudresource.go
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/disk.go
  pkg/destroy/gcp/firewall.go
  pkg/destroy/gcp/forwardingrule.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/healthcheck.go
  pkg/destroy/gcp/httphealthcheck.go
  pkg/destroy/gcp/iam.go
  pkg/destroy/gcp/image.go
  pkg/destroy/gcp/instance.go
  pkg/destroy/gcp/instancegroup.go
  pkg/destroy/gcp/network.go
  pkg/destroy/gcp/policybinding.go
  pkg/destroy/gcp/route.go
  pkg/destroy/gcp/router.go
  pkg/destroy/gcp/serviceaccount.go
  pkg/destroy/gcp/storage.go
  pkg/destroy/gcp/subnetwork.go
  pkg/destroy/gcp/targetpool.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#2647 Bug 1762618: pkg/asset/ignition: bootstrap kubeconfig to use api-int
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/kubeconfig/admin_internal.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2656 Bug 1771431: pkg/asset/installconfig/aws: Serialize region and subnets
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/installconfig.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2644 openstack: Add ansible to the CI image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, platform/openstack, size/XS

#2648 openstack: Install UPI requirements using yum
  upi/openstack/README.md
Labels: approved, lgtm, platform/openstack, size/S

#2662 Bug 1772080: Strip ".gz" suffix from baremetal image vars
  pkg/asset/machines/baremetal/machines.go
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/XS

#2654 OpenStack: Remove IPI instruction to upload RHCOS
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack, size/S

#2674 Add note on Kuryr not supported with RHEL 7 nodes
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, size/XS

#2683 Fix projectID typo in GCP customization docs
  docs/user/gcp/customization.md
Labels: approved, lgtm, size/XS

#2659 Bug 1772002: manually prepare cloud provider's config
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2577 Bug 1773002: baremetal: validate interfaces through libvirt API
  pkg/types/baremetal/validation/libvirt.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/validate/validate.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/L

#2657 Bug 1772599: Handle compressed images for libvirt and baremetal IPI
  pkg/rhcos/openstack.go
  pkg/rhcos/qemu.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/internal/cache/cache.go
  pkg/tfvars/libvirt/cache.go
  pkg/tfvars/libvirt/libvirt.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2663 OpenStack CI: add awscli to the CI image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, platform/openstack, size/XS

#2690 Bug 1762413: destroy/gcp/cloudcontroller.go: cleanup the shared firewalls and health checks
  pkg/destroy/gcp/cloudcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2675 Bug 1771784: cmd/openshift-install: silence the logs from klog by setting sterrThreshold to highest
  cmd/openshift-install/main.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2684 Bug 1773686: GCP Gather: use bootstrap internal ip when missing external
  pkg/terraform/gather/gcp/ip.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2667 Add fips for bootstrap node; template ign machine config encap
  data/data/bootstrap/files/etc/ignition-machine-config-encapsulated.json.template
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, size/S

#2666 Bug 1772154: RHCOS: Bump to 43.81.201911192044.0 for CRI-O bug fix
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2691 openstack: Minor fixes to the UPI docs
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, platform/openstack, size/XS

#2668 Bug 1770223: bootstrap kubeconfig to use api-int
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/kubeconfig/admin_internal.go
  pkg/asset/manifests/proxy.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#2703 Bug 1775279: libvirt installer instructions need updating for Fedora 31
  docs/dev/libvirt/README.md
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2697 Bug 1774813: Create a bootstrap instance group in GCP.
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/output.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  data/data/gcp/master/variables.tf
  data/data/gcp/network/lb-private.tf
  data/data/gcp/network/lb-public.tf
  data/data/gcp/network/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm, size/M

#2696 Docs: OpenStack ss certs status update
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, platform/openstack, size/XS

#2709 bug 1774388: Stop setting non existent public target pool when InternalPublishingStrategy on GCP master machines
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/gcp/machines_test.go
  pkg/asset/machines/master.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1765 Fixed link to terraform/upi template
  docs/user/vsphere/install_upi.md
Labels: approved, lgtm, ok-to-test, size/XS

#2606 openstack: make dhcp files available to UPI too
  data/data/bootstrap/openstack/OWNERS
  data/data/bootstrap/openstack/files/etc/NetworkManager/conf.d/dhcp-client.conf
  data/data/bootstrap/openstack/files/etc/dhcp/dhclient.conf
  docs/user/openstack/install_upi.md
  pkg/tfvars/openstack/bootstrap_ignition.go
Labels: approved, lgtm, platform/openstack, size/M

#2707 Bug 1775531: images/openstack: add awscli to image
  images/openstack/Dockerfile.ci
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#2708 openstack: Use an invalid domain for testing
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, platform/openstack, size/XS

#2706 zvm/install_upi.md
  docs/user/zvm/install_upi.md
Labels: approved, lgtm, size/L

#2693 Docs: Add info about RHCOS image uploading to UPI docs
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, size/M

#2593 openstack UPI: Automate Security Group creation
  upi/openstack/02_security-groups.yaml
  upi/openstack/down-02_security-groups.yaml
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/L

#2571 baremetal: update terraform-provider-ironic and use newer API
  data/data/baremetal/main.tf
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go
Labels: approved, lgtm, platform/baremetal, size/M

#2719 data/bootstrap: Add -E option to make the functions inherit trap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#2718 bug 1776466: use correct length for worker node configs
  pkg/asset/cluster/tfvars.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2721 align vendor to k8s.io/apimachinery
  Gopkg.lock
  pkg/tfvars/openstack/bootstrap_ignition.go
  vendor/github.com/kubernetes/apimachinery/LICENSE
  vendor/github.com/kubernetes/apimachinery/pkg/util/rand/rand.go
Labels: approved, lgtm, size/L

#2714 Bug 1775728: rhcos: Bump to 43.81.201911221453.0
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2592 openstack UPI: Automate Bootstrap server creation
  upi/openstack/03_bootstrap.yaml
  upi/openstack/down-03_bootstrap.yaml
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/M

#2700 Bug 1775062:OpenStack: Use UTF-8 locales in CI container image
  images/openstack/Dockerfile.ci
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack, size/XS

#2731 baremetal: Use accessDetails.Driver() in terraform config
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, lgtm, platform/baremetal, size/XS
