Repository openshift/installer, pull requests merged in 2019-02, with the labels that each got.

#1013 network: move from operator-specific CRD to cluster config
  Gopkg.lock
  Gopkg.toml
  data/data/manifests/openshift/cluster-network-crd.yaml
  data/data/manifests/openshift/cluster-networkconfig-crd.yaml
  docs/user/troubleshooting.md
  pkg/asset/installconfig/installconfig_test.go
  pkg/asset/manifests/network.go
  pkg/asset/templates/content/openshift/cluster-network-crds.go
  pkg/asset/templates/templates.go
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
  vendor/github.com/openshift/cluster-network-operator/LICENSE
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/doc.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/networkconfig_types.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/register.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#1155 asset/manifests: update status of Infrastructure
  Gopkg.lock
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/utils.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
Labels: approved, lgtm, size/L

#1166 asset/bootstrap: Remove ~core/.bash_history
  data/data/bootstrap/files/home/core/.bash_history
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, size/XS

#1170 pkg/destroy/aws: remove un-used cluster_name field
  pkg/destroy/aws.go
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/S

#1171 data/aws/master: drop un-used base_domain
  data/data/aws/main.tf
  data/data/aws/master/variables.tf
Labels: approved, lgtm, size/XS

#1162 openstack: make the local DNS service more robust
  data/data/openstack/lb/main.tf
Labels: approved, lgtm, size/XS

#1065 [FIX] Validate provided addresses are network addresses
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/M

#1181 cmd/openshift-install: suppress glog output
  cmd/openshift-install/main.go
Labels: approved, lgtm, size/XS

#1154 pkg/types/aws/machinepool: Drop IAM-role overrides
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/iam/main.tf
  data/data/aws/iam/variables.tf
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/master/variables.tf
  data/data/aws/variables-aws.tf
  docs/user/aws/customization.md
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/installconfig_test.go
  pkg/tfvars/aws/aws.go
  pkg/tfvars/tfvars.go
  pkg/types/aws/machinepool.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/L

#1185 OpenStack: Automatically update haproxy config
  data/data/openstack/lb/main.tf
Labels: approved, lgtm, platform/openstack, size/M

#890 assets: add tests for validating asset fetching of targets
  cmd/openshift-install/create.go
  cmd/openshift-install/destroy.go
  docs/design/resource_dep.svg
  pkg/asset/asset.go
  pkg/asset/filefetcher.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/ingress.go
  pkg/asset/manifests/network.go
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/operators.go
  pkg/asset/store.go
  pkg/asset/store/assetcreate_test.go
  pkg/asset/store/data
  pkg/asset/store/filefetcher.go
  pkg/asset/store/filefetcher_test.go
  pkg/asset/store/store.go
  pkg/asset/store/store_test.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/04-openshift-machine-config-operator.go
  pkg/asset/templates/content/bootkube/05-openshift-cluster-api-namespace.go
  pkg/asset/templates/content/bootkube/09-openshift-service-cert-signer-namespace.go
  pkg/asset/templates/content/bootkube/cvo-overrides.go
  pkg/asset/templates/content/bootkube/etcd-service.go
  pkg/asset/templates/content/bootkube/host-etcd-service-endpoints.go
  pkg/asset/templates/content/bootkube/host-etcd-service.go
  pkg/asset/templates/content/bootkube/kube-cloud-config.go
  pkg/asset/templates/content/bootkube/kube-system-configmap-etcd-serving-ca.go
  pkg/asset/templates/content/bootkube/kube-system-configmap-root-ca.go
  pkg/asset/templates/content/bootkube/kube-system-secret-etcd-client.go
  pkg/asset/templates/content/bootkube/machine-config-server-tls-secret.go
  pkg/asset/templates/content/bootkube/openshift-service-cert-signer-ca-secret.go
  pkg/asset/templates/content/bootkube/pull.go
  pkg/asset/templates/content/openshift/binding-discovery.go
  pkg/asset/templates/content/openshift/cloud-creds-secret.go
  pkg/asset/templates/content/openshift/cluster-infrastructure-crd.go
  pkg/asset/templates/content/openshift/kubeadmin-password-secret.go
  pkg/asset/templates/content/openshift/role-cloud-creds-secret-reader.go
  pkg/asset/templates/doc.go
  pkg/asset/templates/templates.go
Labels: approved, lgtm, size/XXL

#1149 bootkube: Supply machine-os-content to MCO
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1182 data/manifests: update the upstream Cincinnati URL
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, size/XS

#1190 pkg/types/installconfig: Drop PodCIDR reference from ClusterNetworks
  pkg/types/installconfig.go
Labels: approved, lgtm, size/XS

#1173 pkg/asset/installconfig/aws: getCredentials profile handling
  Gopkg.lock
  pkg/asset/installconfig/aws/aws.go
  vendor/gopkg.in/ini.v1/LICENSE
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
Labels: approved, lgtm, platform/aws, size/XXL

#1186 OpenStack: switch to CoreDNS
  data/data/openstack/lb/main.tf
Labels: approved, lgtm, size/M

#1195 openstack: add the API and wildcard DNS entries
  data/data/openstack/lb/main.tf
  data/data/openstack/lb/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/topology/outputs.tf
  docs/user/openstack/README.md
Labels: approved, lgtm, size/M

#1199 pkg/asset/targets: Render the metadata asset before cluster
  pkg/asset/targets/targets.go
Labels: approved, kind/bug, lgtm, size/XS

#1200 Trim down the worker iam role
  data/data/aws/iam/main.tf
Labels: approved, lgtm, size/S

#1197 Remove openshift-cluster-api namespace since it's created by mao
  data/data/manifests/bootkube/05-openshift-cluster-api-namespace.yaml
  pkg/asset/manifests/operators.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/05-openshift-cluster-api-namespace.go
Labels: approved, lgtm, size/M

#1194 bootkube: Pass etcd images into MCO bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1191 CHANGELOG: Document changes since 0.11.0
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1202 data/aws/vpc/sg-master: Fix 9990 -> 9999 metrics to_port
  data/data/aws/vpc/sg-master.tf
Labels: approved, lgtm, platform/aws, size/XS

#792 pkg/tfvars: Pull from []Machine instead of InstallConfig
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/master.go
  pkg/asset/manifests/openshift.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/terraform/terraform.go
  pkg/tfvars/aws/aws.go
  pkg/tfvars/libvirt/cache.go
  pkg/tfvars/libvirt/libvirt.go
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/tfvars.go
  pkg/types/libvirt/platform.go
Labels: approved, lgtm, size/XL

#1201 aws/vpc: add CRI-O metrics sg
  data/data/aws/vpc/sg-worker.tf
Labels: approved, lgtm, size/S

#1206 Remove S3 access privilege from worker iam-instance-role
  data/data/aws/iam/main.tf
Labels: approved, lgtm, size/XS

#1208 Remove service CA
  data/data/manifests/bootkube/09-openshift-service-cert-signer-namespace.yaml
  data/data/manifests/bootkube/openshift-service-cert-signer-ca-secret.yaml.template
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/09-openshift-service-cert-signer-namespace.go
  pkg/asset/templates/content/bootkube/openshift-service-cert-signer-ca-secret.go
  pkg/asset/tls/serviceservingca.go
Labels: approved, lgtm, size/L

#1151 destroy/aws: guard against nils returned by aws
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, platform/aws, size/M

#1204 Libvirt machine api
  Gopkg.lock
  Gopkg.toml
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/libvirt/machines.go
  pkg/asset/machines/libvirt/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  vendor/github.com/openshift/cluster-api-provider-libvirt/pkg/apis/libvirtproviderconfig/v1alpha1/libvirtmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-libvirt/pkg/apis/libvirtproviderconfig/v1alpha1/register.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/common/consts.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/common/plugins.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/common_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/defaults.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/doc.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/register.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#1222 openstack: Remove hacks script from masters
  data/data/openstack/masters/main.tf
Labels: approved, lgtm, size/M

#1215 Update machines namespace
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/libvirt/machines.go
  pkg/asset/machines/libvirt/machinesets.go
  pkg/asset/machines/userdata.go
Labels: approved, lgtm, size/S

#1223 Change awsproviderconfig.k8s.io/v1alpha1 API version to awsproviderconfig.openshift.io/v1beta1
  pkg/asset/machines/aws/machines.go
Labels: approved, lgtm, size/XS

#1224 openstack: Use a service subnet for service-vm
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/service/main.tf
  data/data/openstack/service/variables.tf
  data/data/openstack/topology/outputs.tf
  data/data/openstack/topology/private-network.tf
Labels: approved, lgtm, size/M

#1230 create: When timing out, display last failing operators from CVO
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/S

#1211 pkg/asset/machines: Convert Master to a WriteableAsset
  Gopkg.lock
  Gopkg.toml
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/master.go
  pkg/asset/manifests/openshift.go
  pkg/asset/store/assetcreate_test.go
  pkg/asset/targets/targets.go
  pkg/tfvars/aws/aws.go
  vendor/github.com/openshift/cluster-api-provider-libvirt/pkg/apis/addtoscheme_libvirtproviderconfig_v1alpha1.go
  vendor/github.com/openshift/cluster-api-provider-libvirt/pkg/apis/apis.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/addtoscheme_openshiftawsprovider_v1beta1.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/apis.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/apis.go
Labels: approved, lgtm, size/L

#1180 change machine-config-server port
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/sg-elb.tf
  data/data/aws/vpc/sg-master.tf
  data/data/openstack/service/main.tf
  data/data/openstack/topology/sg-lb.tf
  data/data/openstack/topology/sg-master.tf
  docs/user/customization.md
  docs/user/openstack/README.md
  pkg/asset/ignition/machine/node.go
Labels: approved, lgtm, size/M

#1238 drop unused security group, fix naming of VXLAN rules
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/sg-etcd.tf
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
Labels: approved, lgtm, size/L

#1235 docs: rebuild dependency graph
  cmd/openshift-install/graph.go
  docs/design/resource_dep.svg
Labels: approved, lgtm, size/XXL

#1241 Fix bug where list of masters contain all same object
  pkg/asset/machines/master.go
Labels: approved, lgtm, size/XS

#1240 openstack: Change MCO port
  data/data/openstack/service/main.tf
Labels: approved, lgtm, size/M

#1244 docs/troubleshooting: update machines namespace
  docs/user/troubleshooting.md
Labels: approved, lgtm, size/S

#1233 manifest: set the public and private zones for AWS
  Gopkg.lock
  pkg/asset/installconfig/aws/basedomain.go
  pkg/asset/manifests/dns.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/type_features.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_registries.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/features.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/registry.go
Labels: approved, lgtm, size/XL

#1252 libvirt-howto: Less intrusive NetworkManager setup
  docs/dev/libvirt-howto.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1187 bootkube: render config.openshift.io resources
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/S

#1045 Remove public IPs from masters
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/vpc/common.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
  data/data/aws/vpc/vpc.tf
  docs/user/troubleshooting.md
  pkg/asset/machines/aws/machines.go
Labels: approved, lgtm, platform/aws, size/M

#1250 pkg/destroy/aws: Ignore missing instances
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/XS

#1032 Remove the double @sha256 in case the image name is already digest base
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, ok-to-test, size/XS

#1254 bootkube: remove duplicate CRD manifests
  data/data/manifests/bootkube/cluster-dns-01-crd.yaml
  data/data/manifests/bootkube/cluster-ingress-01-crd.yaml
  data/data/manifests/openshift/cluster-infrastructure-crd.yaml
  data/data/manifests/openshift/cluster-network-crd.yaml
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/ingress.go
  pkg/asset/templates/content/openshift/cluster-infrastructure-crd.go
  pkg/asset/templates/content/openshift/cluster-network-crds.go
Labels: approved, lgtm, size/L

#1156 credentials validation
  Gopkg.lock
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/platformcredscheck.go
  vendor/github.com/aws/aws-sdk-go/service/iam/iamiface/interface.go
  vendor/github.com/openshift/cloud-credential-operator/LICENSE
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1beta1/aws_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1beta1/codec.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1beta1/credentialsrequest_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1beta1/doc.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1beta1/register.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/aws/client.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/controller/assets/bindata.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/controller/utils/condition_utils.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/controller/utils/utils.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
Labels: approved, lgtm, size/XXL

#1246 openstack: complete move of OpenStack under the downstream machine api
  docs/user/openstack/README.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/master.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/asset/manifests/cluster_k8s_io.go
Labels: approved, lgtm, size/M

#1255 types: validate cluster name in InstallConfig
  pkg/asset/installconfig/basedomain.go
  pkg/asset/installconfig/clustername.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#1256 openshift-install: add version string to logs
  cmd/openshift-install/log.go
Labels: approved, lgtm, size/XS

#1226 openstack: allow external LB FIP
  data/data/openstack/main.tf
  data/data/openstack/service/main.tf
  data/data/openstack/service/variables.tf
  data/data/openstack/topology/outputs.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/README.md
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/platform.go
Labels: approved, lgtm, size/L

#1242 Append router CA to cluster CA in kubeconfig
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/M

#1128 data/aws/variables-aws: Drop aws_master_ec2_type and similar defaults
  data/data/aws/master/variables.tf
  data/data/aws/variables-aws.tf
  pkg/tfvars/aws/aws.go
Labels: approved, lgtm, platform/aws, size/S

#1157 installconfig: separate control plane and compute machine pools
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/installconfig_test.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/operators.go
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/installconfig.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
  pkg/types/validation/machinepools_test.go
Labels: approved, lgtm, size/L

#1231 *: support no worker nodes
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/libvirt/machinesets.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/asset/machines/worker.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools_test.go
Labels: approved, lgtm, size/L

#1253 bootstrap: add new names for kube apiserver and controller manager pods
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1169 Move DNS records from base_domain to cluster_domain
  data/data/aws/main.tf
  data/data/aws/route53/base.tf
  data/data/aws/vpc/vpc.tf
  data/data/libvirt/main.tf
  data/data/openstack/main.tf
  data/data/openstack/service/main.tf
  data/data/openstack/service/variables.tf
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/node.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/kubeconfig/kubeconfig_test.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/ingress.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/utils.go
  pkg/asset/tls/helper.go
  pkg/destroy/aws/aws.go
  pkg/types/installconfig.go
Labels: approved, lgtm, size/L

#1245 openstack: Update machines namespace for OpenStack
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
Labels: approved, lgtm, ok-to-test, size/XS

#1262 image: Take explicit dependency on util-linux for uuidgen and gzip
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.ci.rhel7
Labels: approved, size/XS

#1259 data/manifests: update the default update channel
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, size/XS

#1126 openstack: Switch yaml libs
  Gopkg.lock
  Gopkg.toml
  pkg/asset/manifests/openshift.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
Labels: approved, lgtm, size/L

#1179 pkg/asset/tls: self-sign kube-ca
  pkg/asset/kubeconfig/admin.go
  pkg/asset/kubeconfig/kubelet.go
  pkg/asset/tls/apiservercertkey.go
  pkg/asset/tls/kubeca.go
Labels: approved, kind/bug, lgtm, size/M

#1266 bootkube: pass --kube-ca to MCO
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1269 Revert "Remove the double @sha256 in case the image name is already digest base"
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1249 asset/machines: update API version of MAO objects
  pkg/asset/machines/libvirt/machines.go
  pkg/asset/machines/libvirt/machinesets.go
  pkg/asset/manifests/cluster_k8s_io.go
Labels: approved, lgtm, size/S

#1273 bootkube.sh: fix cluster-config operator cp commands
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1283 uninstaller: fix endless loop when no public route53 zone found
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/S

#1232 Create separate chains of trust for separate actors
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/kubeconfig/admin.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/kubeconfig/kubelet.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/tls/admincertkey.go
  pkg/asset/tls/adminkubeconfig.go
  pkg/asset/tls/aggregator.go
  pkg/asset/tls/aggregatorca.go
  pkg/asset/tls/apiserver.go
  pkg/asset/tls/apiservercertkey.go
  pkg/asset/tls/apiserverproxycertkey.go
  pkg/asset/tls/cabundle.go
  pkg/asset/tls/cabundle_test.go
  pkg/asset/tls/certkey.go
  pkg/asset/tls/certkey_test.go
  pkg/asset/tls/etcd.go
  pkg/asset/tls/etcdca.go
  pkg/asset/tls/etcdclientcertkey.go
  pkg/asset/tls/ingresscertkey.go
  pkg/asset/tls/journalcertkey.go
  pkg/asset/tls/kubeca.go
  pkg/asset/tls/kubecontrolplane.go
  pkg/asset/tls/kubelet.go
  pkg/asset/tls/kubeletcertkey.go
  pkg/asset/tls/mcscertkey.go
  pkg/asset/tls/root.go
  pkg/asset/tls/tls.go
  pkg/asset/tls/tls_test.go
Labels: approved, lgtm, size/XXL

#1279 *: increase resources for libvirt machines
  data/data/libvirt/variables-libvirt.tf
  pkg/asset/machines/libvirt/machines.go
Labels: approved, lgtm, size/XS

#1285 update doc to use new customization yaml format
  docs/user/aws/customization.md
Labels: approved, lgtm, size/XS

#1163 Support regions without m4 machines
  Gopkg.lock
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/master/variables.tf
  data/data/aws/variables-aws.tf
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/defaults/platform.go
  pkg/types/aws/validation/platform.go
  pkg/types/validation/installconfig_test.go
  platformtests/README.md
  platformtests/aws/README.md
  platformtests/aws/default_instance_class_test.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/api.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/doc.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/errors.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/service.go
Labels: approved, lgtm, size/XXL

#1280 *: use a human friendly ID to tag and name cloud resources.
  Gopkg.lock
  data/data/aws/bootstrap/README.md
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/iam/main.tf
  data/data/aws/iam/variables.tf
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/master/variables.tf
  data/data/aws/route53/base.tf
  data/data/aws/route53/variables.tf
  data/data/aws/vpc/master-elb.tf
  data/data/aws/vpc/sg-elb.tf
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
  data/data/aws/vpc/variables.tf
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
  data/data/aws/vpc/vpc.tf
  data/data/config.tf
  data/data/libvirt/bootstrap/README.md
  data/data/libvirt/bootstrap/main.tf
  data/data/libvirt/bootstrap/variables.tf
  data/data/libvirt/main.tf
  data/data/libvirt/volume/main.tf
  data/data/libvirt/volume/variables.tf
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/service/main.tf
  data/data/openstack/service/variables.tf
  data/data/openstack/topology/variables.tf
  pkg/asset/cluster/aws/aws.go
  pkg/asset/cluster/metadata.go
  pkg/asset/cluster/openstack/openstack.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/clusterid.go
  pkg/asset/installconfig/clusterid_test.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/libvirt/machines.go
  pkg/asset/machines/libvirt/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/cluster_k8s_io.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/operators.go
  pkg/destroy/libvirt/libvirt.go
  pkg/tfvars/tfvars.go
  pkg/types/clustermetadata.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
Labels: approved, lgtm, size/XL

#1276 types/validation: validate cluster network CIDRs
  pkg/ipnet/ipnet.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/L

#1301 docs/user/aws: update network type string
  docs/user/aws/customization.md
Labels: approved, lgtm, size/XS

#1302 metadata: include openshiftClusterID on AWS
  pkg/asset/cluster/aws/aws.go
  pkg/asset/cluster/metadata.go
Labels: approved, lgtm, size/XS

#1298 tls: add kube-apiserver-complete-server-ca-bundle.crt
  docs/design/resource_dep.svg
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/kubeconfig/admin.go
  pkg/asset/kubeconfig/kubelet.go
  pkg/asset/tls/adminkubeconfig.go
  pkg/asset/tls/apiserver.go
Labels: approved, lgtm, size/XXL

#1293 bootkube.sh: suppress podman output when pulling images
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/M

#1304 pkg/asset/ignition/bootstrap: bump etcdctl binary to 3.3.10
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, size/XS

#1297 aws: include installer version in AWS api calls
  cmd/openshift-install/log.go
  cmd/openshift-install/version.go
  hack/build.sh
  pkg/asset/installconfig/aws/aws.go
  pkg/destroy/aws/aws.go
  pkg/version/version.go
Labels: approved, lgtm, size/M

#1289 bootkube.sh: Print a final success message
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1303 OWNERS_ALIASES: remove Rajat
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1307 tls: create a client-ca bundle for the bootstrap KAS to use
  docs/design/resource_dep.svg
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/tls/apiserver.go
Labels: approved, lgtm, size/XXL

#1270 CHANGELOG: Document changes since v0.12.0
  CHANGELOG.md
Labels: approved, lgtm, size/L

#1310 libvirt: Pass correct InfraID prefix to destroy
  pkg/destroy/libvirt/libvirt.go
Labels: approved, lgtm, size/XS

#1299 updating docs to include deails about VPC gateway endpoints
  docs/user/aws/limits.md
Labels: approved, lgtm, size/XS

#1305 tls: switch to self-signed admin.kubeconfig
  docs/design/resource_dep.svg
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/kubeconfig/admin.go
  pkg/asset/targets/targets.go
  pkg/asset/tls/adminkubeconfig.go
Labels: approved, lgtm, size/XXL

#1308 data: route53 A records with SimplePolicy should not use health check
  data/data/aws/route53/base.tf
Labels: approved, lgtm, size/XS

#1274 bootkube.sh: do not hide problems with render
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/M

#1315 data/bootstrap/files/usr/local/bin/bootkube: etcdctl from release image
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, size/XS

#1251 pkg/types/validation: Drop v1beta1 backwards compat hack
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, size/XS

#1267 pkg/asset/tls: self-sign etcd-client-ca
  pkg/asset/tls/etcd.go
Labels: approved, lgtm, size/S

#1275 pkg/asset/tls: self-sign aggregator-ca
  pkg/asset/tls/aggregator.go
Labels: approved, lgtm, size/S

#1319 pkg/types/validation/installconfig: Drop nominal v1beta2 support
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, size/XS

#1306 Removing unused/deprecated security groups and ports. Updated AWS doc
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/sg-elb.tf
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
  docs/user/aws/limits.md
Labels: approved, lgtm, size/L

#1296 data/aws: Encrypt the AMI used by the bootstrap and master machines
  data/data/aws/main.tf
  data/data/aws/variables-aws.tf
  docs/user/aws/install.md
  pkg/destroy/aws/aws.go
  pkg/tfvars/aws/aws.go
Labels: approved, lgtm, size/M

#1316 CHANGELOG: Document changes since 8f08508
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1323 aws: use the standard logger for creds checking
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, size/XS

#1311 Kubelet bootstrap signer
  docs/design/resource_dep.svg
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/tls/apiserver.go
  pkg/asset/tls/kubelet.go
Labels: approved, lgtm, size/XXL

#1326 data/aws/bootstrap: Restore global SSH access
  data/data/aws/bootstrap/main.tf
Labels: approved, lgtm, size/S

#1327 data/aws/master: drop 2 unused outputs
  data/data/aws/master/outputs.tf
Labels: approved, lgtm, size/XS

#1328 add ec2:CopyImage as a required permission
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, size/XS

#794 openstack: Support setting network UUID via terraform variable.
  data/data/openstack/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/README.md
  pkg/types/openstack/platform.go
Labels: approved, lgtm, platform/openstack, size/M

#1263 Rename labels from sigs.k8s.io to machine.openshift.io
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/libvirt/machines.go
  pkg/asset/machines/libvirt/machinesets.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
Labels: approved, lgtm, size/M

#1340 add ec2:DeregisterImage permission to pre-flight checks
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, size/XS

#1329 docs/troubleshooting: add sections to cover all post-create phases
  docs/user/troubleshooting.md
Labels: approved, lgtm, size/L
