Repository openshift/installer, pull requests merged in 2019-07, with the labels that each got.

#1923 openstack: Fix rhcos version wrong info in doc
  docs/user/openstack/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1920 OpenStack: fix cluster destroy
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, size/XS

#1925 data/data/openstack: Open UDP 5353 (mdns) port
  data/data/openstack/topology/sg-master.tf
Labels: approved, lgtm, size/S

#1926 Decouple Destroyer interface and registry from destroy command
  pkg/destroy/aws/aws.go
  pkg/destroy/aws/register.go
  pkg/destroy/azure/azure.go
  pkg/destroy/azure/register.go
  pkg/destroy/destroyer.go
  pkg/destroy/libvirt/libvirt.go
  pkg/destroy/libvirt/register.go
  pkg/destroy/openstack/openstack.go
  pkg/destroy/openstack/register.go
  pkg/destroy/providers/registry.go
  pkg/destroy/providers/types.go
Labels: approved, lgtm, size/M

#1930 manifests/infrastructure: Setup the platform specific status fields.
  Gopkg.lock
  pkg/asset/manifests/infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#1934 manifests/infrastructure.go: drop double assignment for .status.platformType
  pkg/asset/manifests/infrastructure.go
Labels: approved, lgtm, size/XS

#1932 Fix the build issue
  pkg/destroy/libvirt/libvirt.go
  pkg/destroy/libvirt/register.go
Labels: approved, lgtm, ok-to-test, platform/libvirt, size/XS

#1935 Bug 1725524: types/aws/default: move ap-northeast-2 to m5 instance class
  pkg/types/aws/defaults/platform.go
  platformtests/aws/default_instance_class_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1929 google: create network infrastructure
  data/data/gcp/main.tf
  data/data/gcp/network/common.tf
  data/data/gcp/network/firewall-compute.tf
  data/data/gcp/network/firewall-control.tf
  data/data/gcp/network/network.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/network/variables.tf
  data/data/gcp/variables-google.tf
Labels: approved, lgtm, size/L

#1940 google: create virtual machines
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  data/data/gcp/master/outputs.tf
  data/data/gcp/master/variables.tf
  data/data/gcp/network/common.tf
  data/data/gcp/network/firewall-compute.tf
  data/data/gcp/network/firewall-control.tf
  data/data/gcp/network/network.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/network/variables.tf
  data/data/gcp/variables-google.tf
Labels: approved, lgtm, size/L

#1875 bootkube.sh: remove image refs for mco components
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#1945 Add cloud providers metadata ip address to no proxy
  pkg/asset/manifests/proxy.go
Labels: approved, lgtm, size/S

#1937 Add machine and machinesets for GCP
  Gopkg.lock
  Gopkg.toml
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/gcp/machinesets.go
  pkg/asset/machines/gcp/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/cluster-api-provider-gcp/LICENSE
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/addtoscheme_gcpprovider_v1beta1.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/apis.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#1563 aws: allow GENEVE (6081) and OVN database ports (6641 & 6642)
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
Labels: approved, lgtm, size/M

#1947 data/data/openstack: Generate master clustervars
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
Labels: approved, lgtm, platform/openstack, size/M

#1938 pkg: create tfvars for gcp
  data/data/gcp/main.tf
  data/data/gcp/variables-gcp.tf
  data/data/gcp/variables-google.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm, size/L

#1957 Make `terraform fmt` output diff
  hack/tf-fmt.sh
Labels: approved, lgtm, size/XS

#1941 data/data/rhcos.json: update the bootimage to 420.8.20190708.2 for CRI-O 1.14
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#1950 Uninstaller for GCP
  Gopkg.lock
  cmd/openshift-install/destroy.go
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/dns.go
  pkg/destroy/gcp/doc.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/iam.go
  pkg/destroy/gcp/network.go
  pkg/destroy/gcp/register.go
  pkg/destroy/gcp/storage.go
  pkg/types/clustermetadata.go
  pkg/types/gcp/metadata.go
  vendor/google.golang.org/api/iam/v1/iam-gen.go
  vendor/google.golang.org/api/storage/v1/storage-gen.go
Labels: approved, lgtm, size/XXL

#1958 baremetal: vendor terraform-provider-ironic and provide initial terraform configuration
  OWNERS_ALIASES
  data/data/baremetal/OWNERS
  data/data/baremetal/bootstrap/README.md
  data/data/baremetal/bootstrap/main.tf
  data/data/baremetal/bootstrap/variables.tf
  data/data/baremetal/bootstrap/versions.tf
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/masters/versions.tf
  data/data/baremetal/variables-baremetal.tf
  data/data/baremetal/versions.tf
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/ironic.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/noauth/doc.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/noauth/requests.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/allocations/requests.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/allocations/results.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/allocations/urls.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/doc.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/results.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/urls.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/ports/doc.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/ports/requests.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/ports/results.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/ports/urls.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/noauth/doc.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/noauth/requests.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/v1/introspection/doc.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/v1/introspection/requests.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/v1/introspection/results.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/v1/introspection/urls.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/utils/openstack/baremetal/v1/nodes/configdrive.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/utils/openstack/baremetal/v1/nodes/doc.go
  pkg/terraform/exec/plugins/vendor/github.com/gophercloud/utils/openstack/baremetal/v1/nodes/util.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/LICENSE
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/data_source_ironic_introspection.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/provider.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/resource_ironic_allocation_v1.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/resource_ironic_deployment.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/resource_ironic_node_v1.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/resource_ironic_port_v1.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/workflow.go
Labels: approved, lgtm, platform/baremetal, size/XXL

#1964 [gcp] pkg/asset/machines: fix gcp machine decoding
  pkg/asset/machines/gcp/machines.go
Labels: approved, lgtm, platform/google, size/XS

#1966 [gcp] pkg/asset/cluster - add gcp metadata
  pkg/asset/cluster/gcp/gcp.go
  pkg/asset/cluster/metadata.go
Labels: approved, lgtm, platform/google, size/S

#1961 Add terminal prompts for GCP: region, project id, & base domain.
  pkg/asset/installconfig/basedomain.go
  pkg/asset/installconfig/gcp/dns.go
  pkg/asset/installconfig/gcp/gcp.go
  pkg/asset/installconfig/gcp/session.go
  pkg/asset/installconfig/installconfig.go
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, platform/google, size/L

#1960 bootstrap: add platform-specific configuration for baremetal
  data/data/bootstrap/baremetal/README.md
  data/data/bootstrap/baremetal/files/etc/coredns/Corefile
  data/data/bootstrap/baremetal/files/etc/dhcp/dhclient.conf
  data/data/bootstrap/baremetal/files/etc/keepalived/keepalived.conf.tmpl
  data/data/bootstrap/baremetal/files/usr/local/bin/coredns.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/fletcher8
  data/data/bootstrap/baremetal/files/usr/local/bin/get_vip_subnet_cidr
  data/data/bootstrap/baremetal/files/usr/local/bin/keepalived.sh
  data/data/bootstrap/baremetal/systemd/units/coredns.service
  data/data/bootstrap/baremetal/systemd/units/keepalived.service
  docs/design/baremetal/networking-infrastructure.md
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, platform/baremetal, size/L

#1967 [gcp] data/data: fix machine var names
  data/data/gcp/main.tf
Labels: approved, lgtm, platform/google, size/XS

#1968 [gcp] pkg/destroy: call network destroy regardless of route delete errors
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, platform/google, size/XS

#1969 pkg/types/validation/installconfig: Fix platform value in error message
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/S

#1971 gcp: Create public and private load balancers
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/output.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  data/data/gcp/master/outputs.tf
  data/data/gcp/network/external-lb.tf
  data/data/gcp/network/firewall-control.tf
  data/data/gcp/network/internal-lb.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/network/variables.tf
Labels: approved, lgtm, platform/google, size/L

#1981 baremetal: Expand on networking documentation.
  data/data/bootstrap/baremetal/README.md
  data/data/bootstrap/baremetal/files/etc/coredns/Corefile
  data/data/bootstrap/baremetal/files/etc/dhcp/dhclient.conf
  data/data/bootstrap/baremetal/files/usr/local/bin/coredns.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/fletcher8
  data/data/bootstrap/baremetal/systemd/units/coredns.service
  docs/design/baremetal/networking-infrastructure.md
Labels: approved, lgtm, platform/baremetal, size/L

#1977 [gcp] add dns resources
  data/data/config.tf
  data/data/gcp/dns/base.tf
  data/data/gcp/dns/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/master/outputs.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/gcp/gcp.go
  pkg/tfvars/tfvars.go
Labels: approved, lgtm, platform/google, size/L

#1983 data/gcp/network: create nat-gateways per subnet for egress from private instances
  data/data/gcp/network/network.tf
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, size/M

#1970 [gcp] data/data: use gcs bucket for bootstrap ignition and expose bootstrap node
  data/data/gcp/bootstrap/main.tf
Labels: approved, lgtm, platform/google, size/M

#1975 [gcp] destroy region backend services
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, platform/google, size/XS

#1972 [gcp] pkg/destroy/gcp - use debug for error logging
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, platform/google, size/XS

#1990 [gcp] Add service accounts for masters and workers
  data/data/gcp/iam/main.tf
  data/data/gcp/iam/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  pkg/asset/machines/gcp/machines.go
Labels: approved, lgtm, platform/google, size/M

#1988 [gcp] destroy legacy HTTP health checks
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, platform/google, size/M

#1991 network: block ExternalIPs by default.
  pkg/asset/manifests/network.go
Labels: approved, lgtm, size/XS

#1993 gcp: workaround terraform dependencies with bootstrap destroy
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/output.tf
  data/data/gcp/bootstrap/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/network/external-lb.tf
  data/data/gcp/network/internal-lb.tf
  data/data/gcp/network/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm, platform/google, size/M

#1989 assets/manifests: include scheduler asset in the manifests asset.
  docs/design/resource_dep.svg
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, size/XXL

#1953 OpenStack: Add subnet pools destroy
  Gopkg.lock
  pkg/destroy/openstack/openstack.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/urls.go
Labels: approved, lgtm, size/XL

#1980 data/data/openstack: set correct hostnames for machines during bootstrap
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/masters/main.tf
Labels: approved, lgtm, size/XS

#1956 Manage and use own storage pool
  data/data/libvirt/bootstrap/main.tf
  data/data/libvirt/bootstrap/variables.tf
  data/data/libvirt/main.tf
  data/data/libvirt/volume/main.tf
  data/data/libvirt/volume/variables.tf
  docs/dev/libvirt/README.md
  pkg/asset/machines/libvirt/machines.go
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/pool.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/provider.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_pool.go
Labels: approved, lgtm, platform/libvirt, size/L

#1994 gcp: limit internal load balancer during bootstrap
  data/data/gcp/network/internal-lb.tf
Labels: approved, lgtm, platform/google, size/XS

#2000 data/gcp/dns: api.cluster_domain inside the VPC must point to internal LB for consistency
  data/data/gcp/dns/base.tf
Labels: approved, lgtm, platform/google, size/S

#1949 Add support for machineSets per az on azure
  Gopkg.lock
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/master/variables.tf
  data/data/azure/variables-azure.tf
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/azure/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/machinepool.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/containerservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleries.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimageversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/loganalytics.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/proximityplacementgroups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinesizes.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/azureclusterproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#2012 Update docs for release mirrors.
  docs/dev/alternative_release_image_sources.md
  pkg/asset/manifests/imagesourcepolicy.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/M

#2018 data/data/openstack: Add registry to coredns image
  data/data/openstack/service/main.tf
Labels: approved, lgtm, size/XS

#2011 gcp: Ensure terraform object names have max length 63
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/network/firewall-compute.tf
  data/data/gcp/network/firewall-control.tf
Labels: approved, lgtm, platform/google, size/M

#1997 Add Fedosin to OpenStack approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1995 libvirt: simplify how bootstrap_dns is passed to terraform
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm, size/S

#2002 pkg/types/aws: allow specifying AMI ID for machines
  pkg/asset/rhcos/image.go
  pkg/types/aws/platform.go
Labels: approved, lgtm, size/XS

#2015 vendor: update github.com/openshift/api
  Gopkg.lock
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
Labels: approved, lgtm, size/L

#2017 OpenStack: Check octavia support
  Gopkg.lock
  data/data/openstack/main.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/openstack/validation/realvalidvaluesfetcher.go
  pkg/types/openstack/validation/validvaluesfetcher.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/L

#2023 Add gather support for gcp
  cmd/openshift-install/gather.go
  pkg/terraform/gather/gcp/ip.go
Labels: approved, lgtm, platform/google, size/M

#2016 correct typo for Azure
  pkg/types/machinepools.go
Labels: approved, lgtm, size/XS

#2022 Baremetal: update networking documentation - API LB
  docs/design/baremetal/networking-infrastructure.md
Labels: approved, lgtm, platform/baremetal, size/XS

#1992 gcp: use the zones from machine objects in terraform
  data/data/gcp/main.tf
  data/data/gcp/network/common.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/variables-gcp.tf
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm, platform/google, size/M

#1999 baremetal: terraform updates for baremetal platform
  data/data/baremetal/main.tf
  data/data/baremetal/masters/variables.tf
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/ironic.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/LICENSE
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/data_source_ironic_introspection.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/provider.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_allocation_v1.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_node_v1.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_port_v1.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/main.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metalkube/terraform-provider-ironic/ironic/provider.go
Labels: approved, lgtm, platform/baremetal, size/L

#2027 docs/metal: worker host should have role 'worker'
  docs/user/metal/install_ipi.md
Labels: approved, lgtm, size/XS

#2039 Enable http /readyz for kube-apiserver bootstrap pods
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, platform/google, size/XS

#2029 gcp: move external health_check to http port 6080
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/gcp/network/external-lb.tf
  data/data/gcp/network/firewall-control.tf
Labels: approved, lgtm, platform/google, size/XS

#2047 baremetal: Note short-term requirement for ns1 DNS record.
  docs/user/metal/install_ipi.md
Labels: approved, lgtm, platform/baremetal, size/XS

#2050 GCP: simplify load balancing and relax bootstrap-complete
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/output.tf
  data/data/gcp/dns/base.tf
  data/data/gcp/dns/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  data/data/gcp/master/outputs.tf
  data/data/gcp/network/external-lb.tf
  data/data/gcp/network/firewall-control.tf
  data/data/gcp/network/internal-lb.tf
  data/data/gcp/network/lb.tf
  data/data/gcp/network/network.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/network/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/destroy/bootstrap/bootstrap.go
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, platform/google, size/L

#2019 Set resource group explicitly for machines
  pkg/asset/machines/azure/machines.go
Labels: approved, lgtm, size/XS

#2046 asset/cluster: don't record usernames
  pkg/asset/cluster/tfvars.go
Labels: approved, lgtm, size/S

#2052 OpenStack: Fix Octavia support detection
  pkg/types/openstack/validation/realvalidvaluesfetcher.go
Labels: approved, lgtm, platform/openstack, size/XS

#2045 [gcp] Add load balancer UID asset to manifests and metadata
  pkg/asset/manifests/gcp/clouduid.go
  pkg/asset/manifests/infrastructure.go
  pkg/types/gcp/clouduid.go
Labels: approved, lgtm, platform/google, size/M

#2042 Add static external ip address to GCP bootstrap node.
  data/data/gcp/bootstrap/main.tf
Labels: approved, lgtm, platform/google, size/XS

#2041 baremetal: Add VIPs to status.platformStatus.baremetal
  pkg/asset/manifests/infrastructure.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
Labels: approved, lgtm, size/S

#2044 baremetal: rename os_image to bootstrap_os_image
  data/data/baremetal/main.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, lgtm, size/S

#2062 baremetal: Add ingressVIP to sample install config.
  docs/user/metal/install_ipi.md
Labels: approved, lgtm, platform/baremetal, size/XS

#2013 [gcp] pkg/destroy: handle async call results, log delete info messages
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/dns.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/iam.go
  pkg/destroy/gcp/network.go
  pkg/destroy/gcp/storage.go
Labels: approved, lgtm, platform/google, size/L

#1161 Adds a customize doc for libvirt with tt0 bridge customization
  docs/dev/libvirt/README.md
  docs/dev/libvirt/customization.md
Labels: approved, lgtm, platform/libvirt, priority/backlog, size/S

#2054 [gcp] pkg/destroy: delete disks
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, platform/google, size/M

#1976 azure: create an image for booting machines for the cluster from vhd blob
  data/data/azure/bootstrap/main.tf
  data/data/azure/bootstrap/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/master/variables.tf
  data/data/azure/variables-azure.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/rhcos/image.go
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm, size/L

#2059 Sort GCP basedomains in installer prompts.
  pkg/asset/installconfig/gcp/dns.go
Labels: approved, lgtm, platform/google, size/XS

#2068 GCP client: pass scope when using default credentials.
  pkg/asset/installconfig/gcp/session.go
Labels: approved, lgtm, platform/google, size/XS

#2072 ISSUE_TEMPLATE.md: List baremetal and none as paltform types
  .github/ISSUE_TEMPLATE.md
Labels: approved, lgtm, size/XS

#2081 [gcp] pkg/asset/manifests: avoid creating an empty cloudconfig for gcp
  pkg/asset/manifests/cloudproviderconfig.go
Labels: approved, lgtm, platform/google, size/XS

#2088 gcp: reduce the length of the names of machines
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/master/main.tf
  pkg/asset/installconfig/clusterid.go
  pkg/asset/installconfig/clusterid_test.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/gcp/machinesets.go
Labels: approved, lgtm, platform/google, size/M

#2056 [gcp] pkg/destroy: handle deletion of lb related resources
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, size/L

#2055 Add AdditionalTrustBundle to InstallConfig
  Gopkg.lock
  data/data/bootstrap/files/etc/pki/ca-trust/source/anchors/ca.crt.template
  data/data/rhcos.json
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/machines/machineconfig/trustbundle.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/additionaltrustbundleconfig.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/proxy.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#2094 Add Azure and GCP Boot Images
  data/data/rhcos.json
  hack/update-rhcos-bootimage.py
  pkg/rhcos/builds.go
Labels: approved, lgtm, size/L

#2101 Fix string fmt bug in saving credentials message.
  pkg/asset/installconfig/gcp/session.go
Labels: approved, lgtm, size/XS

#2085 azure: generate loopback kubeconfig to access API locally
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/asset/kubeconfig/loopback.go
Labels: approved, lgtm, size/M

#2097 Make ImageContentSourcePolicy objects available to the machine-config-controller bootstrap container
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/XS

#2084 Set GCP to pull boot images from RHCOS pipeline.
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/variables.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  data/data/gcp/master/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/rhcos/image.go
  pkg/rhcos/gcp.go
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm, platform/google, size/M

#2099 pkg/asset/machines: drop trustbundle MC
  pkg/asset/machines/machineconfig/trustbundle.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, size/M

#2109 data/gcp/masters: add roles/compute.securityAdmin to masters
  data/data/gcp/master/main.tf
Labels: approved, lgtm, platform/google, size/XS

#2107 set the cloud-provider-config for GCP
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig_test.go
Labels: approved, lgtm, platform/google, size/M

#2100 data/data/baremetal: disable introspection on masters
  data/data/baremetal/masters/main.tf
Labels: approved, lgtm, platform/baremetal, size/XS

#2105 baremetal: Start coredns/keepalived after crio
  data/data/bootstrap/baremetal/systemd/units/coredns.service
  data/data/bootstrap/baremetal/systemd/units/keepalived.service
Labels: approved, lgtm, platform/baremetal, size/XS

#2075 Pass baremetal infra images to MCO bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, platform/baremetal, size/S

#2078 Bug 1734157: data/bootstrap: Remove the unwanted backslash newline escape char
  data/data/bootstrap/systemd/units/kubelet.service.template
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#2106 a few bootstrap spelling issues
  cmd/openshift-install/gather.go
  docs/user/metal/install_upi.md
  docs/user/vsphere/install_upi.md
  tests/run.sh
  upi/aws/cloudformation/04_cluster_bootstrap.yaml
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, size/S

#2115 azure: source Azure OS bootimage from RHCOS pipeline
  pkg/asset/rhcos/image.go
  pkg/rhcos/azure.go
Labels: approved, lgtm, size/S

#2083 openstack: Add a floating IP to bootstrap node for must-gather
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
Labels: approved, lgtm, platform/openstack, size/S

#2004 scheduler: Use schedulable masters if no compute hosts defined.
  pkg/asset/manifests/scheduler.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, size/M

#2113 OWNERS_ALIASES: update the installer-approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2082 libvirt: Delete volumes & storage pool directory
  pkg/destroy/libvirt/libvirt.go
Labels: approved, lgtm, platform/libvirt, size/M

#2121 data/gcp/dns: fix resource name for internal dns zone
  data/data/gcp/dns/base.tf
Labels: approved, lgtm, platform/google, size/XS

#2119 Deploy baremetal bootstrap services with MCO
  data/data/bootstrap/baremetal/files/etc/coredns/Corefile
  data/data/bootstrap/baremetal/files/etc/keepalived/keepalived.conf.tmpl
  data/data/bootstrap/baremetal/files/usr/local/bin/coredns.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/keepalived.sh
  data/data/bootstrap/baremetal/systemd/units/coredns.service
  data/data/bootstrap/baremetal/systemd/units/keepalived.service
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, platform/baremetal, size/L

#2061 Decouple bootstrap and cluster bootimages
  docs/design/resource_dep.svg
  pkg/asset/cluster/tfvars.go
  pkg/asset/rhcos/bootstrap_image.go
  pkg/asset/rhcos/image.go
  pkg/rhcos/builds.go
  pkg/rhcos/openstack.go
Labels: approved, lgtm, platform/baremetal, size/XXL

#2129 [gcp] pkg/destroy/gcp: Fix external and internal load balancer deletion
  pkg/destroy/gcp/compute.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, platform/google, size/M

#2130 bootkube: use long flags for consistency
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/S
