Repository openshift/installer, pull requests merged in 2019-09, with the labels that each got.

#2307 CONTRIBUTING: Drop CoreOS disclosure anchor
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#2313 upi/gcp: clarify that Service Account Key Admin role is required
  docs/user/gcp/install_upi.md
Labels: approved, lgtm, size/XS

#2169 Bug 1740933: pkg/destroy/aws: Terminate instances before other resources
  pkg/destroy/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2317 Bug 1749409: update vendor of cloud-cred-op and add CreateNetworkInterface perm
  Gopkg.lock
  pkg/asset/installconfig/aws/permissions.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/azure_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/gcp_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/aws/client.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/aws/utils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2227 Stop using deprecated options in documentation examples
  docs/user/aws/customization.md
  docs/user/azure/customization.md
Labels: approved, lgtm, size/S

#2321 docs/user: Bump vSphere and metal from v1beta4 to v1
  docs/user/metal/install_ipi.md
  docs/user/vsphere/install_upi.md
Labels: approved, lgtm, size/XS

#2312 docs/dev/libvirt: update links in customizing install note
  docs/dev/libvirt/README.md
Labels: approved, lgtm, size/XS

#2324 Bug 1749624: data/aws/vpc/master-elb: Bump load-balancer timeouts to 20m
  data/data/aws/vpc/master-elb.tf
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#2315 Adding a note about quota on GCP
  docs/user/gcp/README.md
  docs/user/gcp/limits.md
Labels: approved, lgtm, size/S

#2325 Bug 1746119: GCP Terraform ignore changes to min_cpu_platform
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/master/main.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2322 Bug 1746748: OpenStack: idempotent cluster deletion
  Gopkg.lock
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2305 OpenStack: troubleshooting: add broken machine deletion section
  docs/user/openstack/troubleshooting.md
Labels: approved, lgtm, size/S

#2333 Fix reference links in GCP quota limit docs.
  docs/user/gcp/limits.md
Labels: approved, lgtm, size/XS

#2162 docs/user: Standardize install-config property documentation
  docs/dev/proxy.md
  docs/user/aws/customization.md
  docs/user/azure/customization.md
  docs/user/customization.md
  docs/user/metal/install_upi.md
  docs/user/openstack/customization.md
  docs/user/vsphere/customization.md
  docs/user/vsphere/install_upi.md
  pkg/types/aws/machinepool.go
  pkg/types/aws/platform.go
  pkg/types/azure/platform.go
  pkg/types/installconfig.go
  pkg/types/machinepools.go
Labels: approved, lgtm, size/L

#2214 Bug 1747519: pkg/destroy/aws: Delete security groups and subnets by VPC
  pkg/destroy/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2304 data/openstack/topology: update security groups
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, lgtm, size/L

#2331 fix typo for clusterversion
  docs/user/openstack/README.md
Labels: approved, lgtm, size/XS

#2270 Bug 1749816: OpenStack: Validates cluster name length and document known issues
  docs/user/openstack/README.md
  docs/user/openstack/known-issues.md
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2228 openstack: Bump recommended memory in prompt doc
  pkg/asset/installconfig/openstack/openstack.go
Labels: approved, lgtm, platform/openstack, size/XS

#2337 Bug 1747474: OpenStack: Escape special characters in cloud provider password
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2340 Bump libvirt resource from 6GB to 7GB
  pkg/asset/machines/libvirt/machines.go
Labels: approved, lgtm, size/XS

#2329 Bug 1749276: OpenStack: remove volumes along with other resources
  Gopkg.lock
  pkg/destroy/openstack/openstack.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/util.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#2335 Bug 1748162: Open GENEVE wherever possible
  data/data/gcp/network/firewall-compute.tf
  data/data/gcp/network/firewall-control.tf
  upi/aws/cloudformation/03_cluster_security.yaml
  upi/gcp/03_security.py
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2341 OpenStack: Document Ceph RGW limitation with temp-url
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, size/XS

#2332 OpenStack: remove region from install-config
  Gopkg.lock
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/customization.md
  pkg/asset/cluster/openstack/openstack.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/metadata.go
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/openstack/validation/realvalidvaluesfetcher.go
  pkg/types/openstack/validation/validvaluesfetcher.go
  pkg/types/validation/installconfig_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/urls.go
Labels: approved, lgtm, size/XL

#2343 docs/user/metal: Fix link to SDN ports
  docs/user/metal/install_upi.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2342 Bug 1750636: OpenStack: delete floating ips
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2346 Bug 1747519: pkg/destroy/aws: Do not failFast for deleteEC2SecurityGroupsByVPC
  pkg/destroy/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2351 Add g+w /etc/passwd to be able to collect proxy access logs in teardown
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, size/XS

#2358 OpenStack: Install test dependencies into openstack-installer image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, size/XS

#2361 asset: Make warning message read for humans
  pkg/asset/releaseimage/pullspec.go
Labels: approved, lgtm, size/XS

#2355 Update GCP user docs
  README.md
  docs/user/azure/limits.md
  docs/user/gcp/dns.md
  docs/user/gcp/iam.md
  docs/user/gcp/images/gcp-quota.png
  docs/user/gcp/images/gcp-roles.png
  docs/user/gcp/images/install_console.png
  docs/user/gcp/install.md
  docs/user/gcp/limits.md
  docs/user/gcp/postinstall.md
Labels: approved, lgtm, size/L

#2365 pkg/destroy/gcp/network.go: fix missing nextPageToken
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, size/XS

#2362 OpenStack: bump image version for CI 4.1 -> 4.2
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, size/XS

#2371 docs/user/azure/customization: Add azure availability zones
  docs/user/azure/customization.md
Labels: approved, lgtm, size/XS

#2356 docs/user/customization: Add a section on imageContentSources
  docs/user/customization.md
Labels: approved, lgtm, size/M

#2367 Bug 1751375: Azure: bump disk size to 1TB for control plane
  docs/user/azure/limits.md
  pkg/asset/machines/master.go
  pkg/types/azure/defaults/machines.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2377 update openstack owner aliases
  OWNERS_ALIASES
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#2382 Bug 1753187: OpenStack: Permit choosing the volume type for instances
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/variables-openstack.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2386 Fix typo in GCP limits doc.
  docs/user/gcp/limits.md
Labels: approved, lgtm, size/XS

#2385 Document disk speed requirements
  docs/user/openstack/README.md
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, size/XS

#2397 Bug 1754644: vsphere upi: changes to resolve ci issues
  upi/vsphere/machine/ignition.tf
  upi/vsphere/machine/main.tf
  upi/vsphere/machine/variables.tf
  upi/vsphere/main.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2388 docs/user/azure: remove the out-of-place sp creation instructions
  docs/user/azure/credentials.md
  docs/user/azure/install.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#2383 [4.3] data/gcp: Drop unused defaults for control-plane/bootstrap volumes
  data/data/gcp/bootstrap/variables.tf
  data/data/gcp/master/variables.tf
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm, platform/google, size/XS

#2297 [4.3] vendor: update gopkg.in/AlecAivazis/survey to v1.8.7
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/AlecAivazis/survey.v1/multiselect.go
  vendor/gopkg.in/AlecAivazis/survey.v1/select.go
  vendor/gopkg.in/AlecAivazis/survey.v1/terminal/cursor.go
  vendor/gopkg.in/AlecAivazis/survey.v1/terminal/output.go
  vendor/gopkg.in/AlecAivazis/survey.v1/terminal/runereader_linux.go
  vendor/gopkg.in/AlecAivazis/survey.v1/terminal/runereader_ppc64le.go
Labels: approved, lgtm, ok-to-test, size/M

#2310 baremetal: Remove spurious Type from ironic.service
  data/data/bootstrap/baremetal/systemd/units/ironic.service
Labels: approved, lgtm, size/XS

#2387 pkg/destroy/gcp: delete http-health-checks for LB
  pkg/destroy/gcp/network.go
Labels: approved, lgtm, size/S

#2407 Fixes Bug 1753930: Adds GCP metadata hostnames to default noProxy
  pkg/asset/manifests/proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2398 upi/gcp: templates to use zone paramaters
  docs/user/gcp/install_upi.md
  upi/gcp/04_bootstrap.py
  upi/gcp/05_control_plane.py
Labels: approved, lgtm, size/M

#2182 baremetal: Remove unused assets
  data/data/bootstrap/baremetal/README.md
  data/data/bootstrap/baremetal/files/usr/local/bin/fletcher8
  data/data/bootstrap/baremetal/files/usr/local/bin/get_vip_subnet_cidr
Labels: approved, lgtm, platform/baremetal, size/M

#2405 Bug 1753930: Adds support for trailing dot in noProxy domain names
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2394 Bug 1754070: Allow setting root volume via installconfig
  Gopkg.lock
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  docs/user/openstack/known-issues.md
  pkg/asset/machines/master.go
  pkg/asset/machines/openstack/machines.go
  pkg/destroy/openstack/openstack.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/machinepool.go
  pkg/types/openstack/validation/machinepool.go
  pkg/types/openstack/validation/machinepool_test.go
  pkg/types/validation/installconfig_test.go
  vendor/github.com/gophercloud/gophercloud/internal/pkg.go
  vendor/github.com/gophercloud/gophercloud/internal/util.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2406 GCP: Add install-config and terraform support for BYO VPC
  data/data/gcp/dns/base.tf
  data/data/gcp/main.tf
  data/data/gcp/master/variables.tf
  data/data/gcp/network/common.tf
  data/data/gcp/network/firewall-compute.tf
  data/data/gcp/network/firewall-control.tf
  data/data/gcp/network/network.tf
  data/data/gcp/network/outputs.tf
  data/data/gcp/network/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig_test.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/platform.go
Labels: approved, lgtm, platform/google, size/L

#2418 docs/user/customization: Fix "utalize" -> "utilize" typo
  docs/user/customization.md
Labels: approved, lgtm, size/XS

#2419 gcp: collapse the firewall rules
  data/data/gcp/network/firewall-compute.tf
  data/data/gcp/network/firewall-control.tf
  data/data/gcp/network/firewall.tf
  docs/user/gcp/limits.md
  upi/gcp/03_security.py
Labels: approved, lgtm, size/XL

#2429 data/azure: remove the hard-coded ip for the ILB
  data/data/azure/main.tf
  data/data/azure/master/variables.tf
  data/data/azure/vnet/internal-lb.tf
Labels: approved, lgtm, size/XS

#2428 asset/releaseimage/default.go: bump to 4.3 release image
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, size/XS

#2415 Bug 1754115: Allow setting root volume via installconfig
  Gopkg.lock
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  docs/user/openstack/known-issues.md
  pkg/asset/machines/master.go
  pkg/asset/machines/openstack/machines.go
  pkg/destroy/openstack/openstack.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/machinepool.go
  pkg/types/openstack/validation/machinepool.go
  pkg/types/openstack/validation/machinepool_test.go
  pkg/types/validation/installconfig_test.go
  vendor/github.com/gophercloud/gophercloud/internal/pkg.go
  vendor/github.com/gophercloud/gophercloud/internal/util.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#2422 Fix openstack docs for swift temp url support
  docs/user/openstack/README.md
Labels: approved, lgtm, ok-to-test, platform/openstack, size/XS

#2416 openstack: add note about compressed image format
  docs/user/openstack/README.md
Labels: approved, lgtm, size/S

#2408 Destroy cluster fails for a missing FIP
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, platform/openstack, size/L

#2431 Fix AWS storage size validation error message
  pkg/types/aws/validation/machinepool.go
  pkg/types/aws/validation/machinepool_test.go
Labels: approved, lgtm, size/XS

#2430 gcp upi: allow nodePort between masters and workers
  upi/gcp/03_security.py
Labels: approved, lgtm, size/M

#2434 Bug 1750494: Use standard field validation in pkg/types/conversion/
  pkg/types/conversion/installconfig.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
