Repository openshift/installer, pull requests merged in 2019-12, with the labels that each got.

#2681 Allowed address pairs for bootstrap and workers
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, ok-to-test, size/XS

#2729 Bug 1777804: OpenStack: add Nova metadata service to the list of requirements
  docs/user/openstack/README.md
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2726 Bug 1776272: OpenStack: fix getting service catalog
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/validation/realvalidvaluesfetcher.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2701 Bug 1773909: OpenStack: Fix destroy module
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack, size/L

#2730 *: add support for cluster-etcd-operator
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/manifests/bootkube/etcd-host-service-endpoints.yaml.template
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/manifests/operators.go
Labels: approved, lgtm, platform/baremetal, size/L

#2728 Bug 1778894: baremetal: update terraform-provider-ironic and use newer API
  data/data/baremetal/main.tf
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
  pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/M, ¯\_(ツ)_/¯

#2591 openstack UPI: Automate Control Plane creation
  upi/openstack/04_control-plane.yaml
  upi/openstack/down-04_control-plane.yaml
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/M

#2694 Bug 1764812: pkg/destroy/gcp/bucket.go: join multipe dashes when looking for cluster bucket prefix
  pkg/asset/installconfig/clusterid.go
  pkg/asset/installconfig/clusterid_test.go
  pkg/destroy/gcp/bucket.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2749 Bug 1779740: vSphere UPI: set specific version of ignition provider
  upi/vsphere/machine/ignition.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2664 Log credentials loading for AWS, Azure, GCP, OpenStack
  Gopkg.lock
  pkg/asset/installconfig/aws/session.go
  pkg/asset/installconfig/azure/session.go
  pkg/asset/installconfig/gcp/session.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
  pkg/asset/installconfig/openstack/session.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/manifests/cloudproviderconfig.go
  vendor/github.com/gophercloud/utils/env/env.go
  vendor/github.com/gophercloud/utils/env/env_windows.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go
Labels: approved, lgtm, size/XL

#2602 openstack UPI: Automate Compute nodes creation
  upi/openstack/05_compute-nodes.yaml
  upi/openstack/down-05_compute-nodes.yaml
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/M

#2751 [release-4.3] Bug 1779791:vSphere UPI: set specific version of ignition provider
  upi/vsphere/machine/ignition.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2759 OpenStack UPI: Set Default Compute Nodes to 3
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/XS

#2761 bootkube.sh: CEO: add cluster-config-file to parse sdn cidr
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/S

#2750 OpenStack UPI: add a router to cluster network
  upi/openstack/01_network.yaml
  upi/openstack/down-01_network.yaml
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/S

#2770 Update github.com/gophercloud/utils
  Gopkg.lock
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go
Labels: approved, lgtm, size/L

#2772 Include NFS configuration and control plane schedulability.
  docs/user/zvm/install_upi.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#2767 bootkube.sh: CEO: properly handle etcd endpoints on retry
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, size/M

#2752 Bug 1779793: vSphere UPI: set specific version of ignition provider
  upi/vsphere/machine/ignition.tf
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS, ¯\_(ツ)_/¯

#2765 openstack: Remove dead code
  pkg/asset/manifests/openstack/cloudproviderconfig.go
Labels: approved, lgtm, platform/openstack, size/S

#2774 .yamllint: Exclude vendor/
  .yamllint
Labels: approved, lgtm, size/XS

#2766 baremetal: configure ironic interfaces for other boot mechanisms
  Gopkg.lock
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/tfvars/baremetal/baremetal.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/access.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/idrac.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ipmi.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go
Labels: approved, lgtm, platform/baremetal, size/L

#2786 terraform/plugins: update libvirt provider
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/coreos_ignition_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/volume.go
Labels: approved, lgtm, size/L

#2760 Bug 1777232: Add GCP-specific validation of cluster name.
  pkg/asset/installconfig/clustername.go
  pkg/types/gcp/validation/platform.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#2787 Bug 1778972: Default new file and directory permissions to not be world readable
  pkg/asset/asset.go
  pkg/asset/store/store.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2790 Bug 1782583: destroy/gcp/policybinding.go: identity deleted service accounts belonging to the cluster
  pkg/destroy/gcp/policybinding.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#2776 Bug 1775388: rhcos: Bump to latest RHCOS
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/L

#2795 [FCOS] bootstrap: replace CRIO's hooks dir on bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
Labels: approved, lgtm, size/XS

#2784 Bug 1780534: create bootstrap floating ip after the bootstrap machine
  data/data/openstack/bootstrap/main.tf
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#2743 [FCOS] install-masters-gather: gather logs for machine-config-daemon-pull
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, size/XS

#2660 [release-4.2] Bug 1771358: manually prepare cloud provider's config
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#2798 [release-4.2] Bug 1782588: destroy/gcp/policybinding.go: identity deleted service accounts belonging to the cluster
  pkg/destroy/gcp/iam.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#2783 Adding optional AMI encryption step to the AWS UPI docs
  docs/user/aws/install_upi.md
Labels: approved, lgtm, size/S

#2804 Bug 1782994: terraform/plugins: update libvirt provider
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/coreos_ignition_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_volume.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/volume.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/volume_def.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#2777 Bug 1782546: rhcos: Bump to 43.81.201912091858.0
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#2818 OWNERS_ALIASES: add jstuever to aws approvers
  OWNERS_ALIASES
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#2757 baremetal: Enable the baremetal platform to override the default rhcos images
  pkg/asset/rhcos/bootstrap_image.go
  pkg/asset/rhcos/image.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, lgtm, ok-to-test, platform/baremetal, size/L

#2814 destroy: clean up tagged vpc peering connections
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, size/S

#2807 rhcos: Bump to 44.81.201912121813.0
  data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#2821 Bug 1783973: Rename rhcos-downloader to machine-os-downloader
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  pkg/asset/machines/baremetal/machines.go
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/S

#2665 docs/baremetal: add additional troubleshooting information
  docs/user/metal/install_ipi.md
Labels: approved, size/M

#2768 aws: add new vCPU limit to docs
  docs/user/aws/limits.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#2851 openstack UPI: Do not rely on auto_ip to create bootstrap FIP
  upi/openstack/03_bootstrap.yaml
  upi/openstack/down-03_bootstrap.yaml
Labels: approved, lgtm, platform/openstack, size/XS

#2848 openstack UPI: Remove unneeded allowed IP
  upi/openstack/03_bootstrap.yaml
Labels: approved, lgtm, platform/openstack, size/XS

#2852 openstack UPI: Skip gathering facts
  upi/openstack/01_network.yaml
  upi/openstack/02_security-groups.yaml
  upi/openstack/03_bootstrap.yaml
  upi/openstack/04_control-plane.yaml
  upi/openstack/05_compute-nodes.yaml
  upi/openstack/down-01_network.yaml
  upi/openstack/down-02_security-groups.yaml
  upi/openstack/down-03_bootstrap.yaml
  upi/openstack/down-04_control-plane.yaml
  upi/openstack/down-05_compute-nodes.yaml
Labels: approved, lgtm, platform/openstack, size/S

#2738 [FCOS] bootstrap: disable zincati on bootstrap
  data/data/bootstrap/files/etc/zincati/config.d/90-disable-feature.toml
Labels: approved, lgtm, size/XS

#2823 [OpenStack][UPI]: tweaks
  upi/openstack/01_network.yaml
  upi/openstack/02_security-groups.yaml
  upi/openstack/03_bootstrap.yaml
  upi/openstack/04_control-plane.yaml
  upi/openstack/05_compute-nodes.yaml
  upi/openstack/down-01_network.yaml
  upi/openstack/down-02_security-groups.yaml
  upi/openstack/down-03_bootstrap.yaml
  upi/openstack/down-04_control-plane.yaml
  upi/openstack/down-05_compute-nodes.yaml
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/L

#2850 images/openstack: Make cli stage overrideable
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, size/XS

#2858 OpenStack UPI: Create API and Ingress ports
  upi/openstack/01_network.yaml
  upi/openstack/01_security-groups.yaml
  upi/openstack/02_network.yaml
  upi/openstack/down-01_security-groups.yaml
  upi/openstack/down-02_network.yaml
  upi/openstack/inventory.yaml
Labels: approved, lgtm, platform/openstack, size/L

#2867 OpenStack UPI: introduce common playbook
  upi/openstack/01_security-groups.yaml
  upi/openstack/02_network.yaml
  upi/openstack/03_bootstrap.yaml
  upi/openstack/04_control-plane.yaml
  upi/openstack/05_compute-nodes.yaml
  upi/openstack/common.yaml
  upi/openstack/down-01_security-groups.yaml
  upi/openstack/down-02_network.yaml
  upi/openstack/down-03_bootstrap.yaml
  upi/openstack/down-04_control-plane.yaml
  upi/openstack/down-05_compute-nodes.yaml
Labels: approved, lgtm, platform/openstack, size/L
