Repository openshift/installer, pull requests merged in 2020-08, with the labels that each got.

#3995 Remove unused bootstrap etcd cert generation mechanism
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#3888 Bug 1852112: Ignore hostPrefix validation for non-(sdn/ovn) plugins
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/customization.md
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3918 OpenStack Availibility Zones
  data/data/install.openshift.io_installconfigs.yaml
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/machinepool.go
Labels: approved, lgtm, platform/openstack

#3979 Bug 1840705: pkg/asset/installconfig/azure/validation.go: do not hide error from API
  pkg/asset/installconfig/azure/validation.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3990 Bug 1862065: aws: use default resolver for signing_region of global APIs
  pkg/asset/installconfig/aws/session.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3730 Have the MCO manage the ignition stub config
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#2753 Azure: make cluster destroy code more robust
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, size/S

#4004 Bug 1864280: set AZs default for machine pool in the right place
  pkg/asset/machines/worker.go
  pkg/types/openstack/machinepool.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, platform/openstack

#3831 Bug 1864677: bootkube.sh: update cluster-config-operator to generate bootstrap configmap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2834 docs/customization: Clarify "day 1" MachineConfigs are supported
  docs/user/customization.md
Labels: approved, lgtm, size/XS

#4000 Bug 1863917: give unique names for machinesets in different AZs
  pkg/asset/machines/openstack/machinesets.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#3971 replace error type assertions with errors.As() in the `destroy` module
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, platform/openstack

#3949 oVirt: remove tmp template VM on bootstrap destroy phase
  data/data/ovirt/template/main.tf
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm

#3983 Bug 1862111: bump RHCOS images for CVE-2020-10713
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4010 Bug 1866328: use correct cloud name for tfvars
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#3865 upi/metal: Add pxe_kernel_args, stop using pxe_os_image_url
  docs/user/metal/install_upi.md
  upi/metal/config.tf
  upi/metal/main.tf
  upi/metal/terraform.tfvars.example
Labels: approved, lgtm

#3826 Bug 1852722: Bump go-ovirt
  go.mod
  go.sum
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/github.com/ovirt/go-ovirt/reader.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4018 Bug 1866693: docs: steps to enable RHCOS extensions during cluster install
  docs/user/customization.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3984 Bug 1862112: bump RHCOS images for CVE-2020-10713
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3985 Bug 1862113: bump RHCOS images for CVE-2020-10713
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4009 Bug 1864120: Clean Up OpenStack IPI AZ patch
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/types/openstack/machinepool.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4008 Bug 1862209: types/aws: validate Name and kubernetes.io/clustername/* keys are not allowed
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4026 docs/user/openstack: Replace try.openshift.com with www.openshift.com/try
  docs/user/openstack/README.md
Labels: approved, lgtm

#3987 Bug 1862114: bump RHCOS images for CVE-2020-10713
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4036 Bug 1867747: bump RHCOS images to fix the booting issue from PXE
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3929 baremetal: make provisioning network optional
  data/data/baremetal/bootstrap/main.tf
  data/data/baremetal/bootstrap/variables.tf
  data/data/baremetal/main.tf
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  data/data/install.openshift.io_installconfigs.yaml
  data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
  docs/user/metal/install_ipi.md
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/ignition/bootstrap/baremetal/template_test.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/installconfig/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/types/baremetal/defaults/platform.go
  pkg/types/baremetal/defaults/platform_test.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/libvirt.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/conversion/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#4005 Bug 1865707: [baremetal] Add host roles to hosts in baremetal survey
  pkg/asset/installconfig/baremetal/baremetal.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/baremetal

#4016 OpenStack: Document the MachineSet resource
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack

#4039 upi/metal: remove deprecated coreos-installer kernel arguments
  upi/metal/main.tf
Labels: approved, lgtm

#4040 Bug 1867853: bump RHCOS images to fix the Ignition boot issue
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4031 Bug 1867530: mark deprecated parameters as optional
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/openstack/platform.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4029 Bug 1867519: make externalNetwork optional
  data/data/openstack/topology/private-network.tf
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
  pkg/types/openstack/platform.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4021 Bump rhcos images for ppc64le
  data/data/rhcos-ppc64le.json
Labels: approved, lgtm

#4042 Bug 1867972: destroy/aws: setup the resourcetagging api with correct region for gov cloud
  pkg/destroy/aws/aws.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4045 [FCOS] Rebase Aug 12
  data/data/rhcos-amd64.json
  data/data/rhcos.json
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/asset/machines/vsphere/machines.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  upi/azure/05_masters.json
Labels: approved, lgtm

#4032 Bug 1862044: deleting servers using metadata-based filtering
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/masters/main.tf
  pkg/asset/machines/openstack/machines.go
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4043 Bug 1866949: data/data/aws/route53: use CNAME for gov cloud partition
  data/data/aws/main.tf
  data/data/aws/route53/base.tf
  data/data/aws/route53/variables.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3955 OpenStack: baremetal worker documentation
  docs/user/openstack/deploy_baremetal_workers.md
Labels: approved, lgtm

#4054 [FCOS] Fix Terraform for Azure
  data/data/azure/bootstrap/main.tf
  data/data/azure/main.tf
Labels: approved, lgtm, ok-to-test

#4047 Bug 1868439: openstack upi: fix Ignition key error
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4057 OpenStack: Fixups to BM workers documentation
  docs/user/openstack/deploy_baremetal_workers.md
Labels: approved, lgtm, platform/openstack

#4050 Bump rhcos images for s390x
  data/data/rhcos-s390x.json
Labels: approved, lgtm

#4056 Bug 1869329: OpenStack: Place Bootstrap in one of the master AZs
  data/data/openstack/bootstrap/main.tf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4051 openstack: Known issue: no BMs on Kuryr
  docs/user/openstack/README.md
  docs/user/openstack/deploy_baremetal_workers.md
Labels: approved, lgtm, platform/openstack

#4058 Bug 1868439: openstack UPI: Fix Ignition v3
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4060 Bug 1862290: vendor/terraform-provider-vsphere: DiskPostCloneOperation patch carry
  go.mod
  go.sum
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4002 Bug 1864092: baremetal: copy the implementation of rootdevicehints from baremetal-operator
  pkg/tfvars/baremetal/baremetal.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/rootdevice.go
  pkg/types/baremetal/rootdevice_test.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/devicehints/devicehints.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4046 Bug 1868350: Backport new feature to bypass problems with AWS Accounts using SCP
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/platformpermscheck.go
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4030 Bug 1866693: docs: drop kernel-devel from supported extensions 
  docs/user/customization.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3982 Readme.md: Remove experimental tag for OpenStack UPI
  README.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3948 Bug 1859874: Add basic engine URL validation
  pkg/asset/installconfig/ovirt/credentials.go
  pkg/asset/installconfig/ovirt/validaton.go
  pkg/asset/installconfig/ovirt/validaton_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4074 Bug 1870592: openstack: Document MachineSet availabilityZone
  docs/user/openstack/README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4066 Bug 1862957: bump RHCOS images for FIPS fix
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4081 Bug 1862209: aws: fix validation for user tags
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4080 Bug 1868773: Libvirt: Bump bootstrap memory to 4G
  data/data/libvirt/variables-libvirt.tf
  pkg/tfvars/libvirt/libvirt.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4077 Bug 1871048: OpenStack: dynamically set end of DHCP allocation pool
  data/data/openstack/topology/private-network.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#4090 bug 1863026: docs/user/azure: remove newlines from base64 encoding in UPI install doc
  docs/user/azure/install_upi.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4062 Bug 1813012: Remove legacy code for unmanaged cluster-etcd-operator
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4070 Bug 1870082: Use index in MachineSet names for Openstack IPI
  pkg/asset/machines/openstack/machinesets.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4083 Bug 1856270: Update known issues with info about provisioning state node bug
  docs/user/openstack/known-issues.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4089 bug 1871030: data/data/gcp: be pedantic about setting the region
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/bootstrap/variables.tf
  data/data/gcp/main.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4068 Bug 1813012: Remove unused etcd host service and endpoints
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/manifests/bootkube/etcd-host-service-endpoints.yaml.template
  data/data/manifests/bootkube/etcd-host-service.yaml
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/etcd-host-service-endpoints.go
  pkg/asset/templates/content/bootkube/etcd-host-service.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4100 Bug 1873123: omit deprecated parameters during config generation
  pkg/types/openstack/platform.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4095 Bug 1871795: bump RHCOS images to fix SSH authentication
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4111 Bug 1873537: vendor/terraform-provider-vsphere: DiskPostCloneOperation patch carry
  go.mod
  go.sum
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4109 Bug 1873712: Add information about AZs limitations with Kuryr
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  docs/user/openstack/kuryr.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4098 Bug 1872861: Update cli container image for UPI
  images/installer/Dockerfile.upi.ci
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4118 Bug 1873448: Ensure proper tagging of compute nodes ports
  upi/openstack/compute-nodes.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4115 Bug 1842071: Add ppc64le and s390x documentation links
  README.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, retest-not-required-docs-only
