Repository openshift/installer, pull requests merged in 2020-05, with the labels that each got.

#3418 Bug 1821151: oVirt, add os_type to ovirt templates
  data/data/ovirt/template/main.tf
  go.mod
  go.sum
  pkg/asset/installconfig/ovirt/validators_test.go
  vendor/github.com/ovirt/go-ovirt/CHANGES.adoc
  vendor/github.com/ovirt/go-ovirt/LICENSE.txt
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/github.com/ovirt/go-ovirt/go.mod
  vendor/github.com/ovirt/go-ovirt/go.sum
  vendor/github.com/ovirt/go-ovirt/readers.go
  vendor/github.com/ovirt/go-ovirt/services.go
  vendor/github.com/ovirt/go-ovirt/types.go
  vendor/github.com/ovirt/go-ovirt/version.go
  vendor/github.com/ovirt/go-ovirt/writers.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_image_transfer.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#3538 metal: Fix matchbox link in docs
  docs/user/metal/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3531 Bug 1831366: upi/metal fix compact clusters after porting to terraform v0.12
  upi/metal/main.tf
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#3539 baremetal: Clarify install config needs to be hand-written in the docs
  docs/user/metal/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3510 [release-4.4] images/baremetal: save rhcos.json in container image
  images/baremetal/Dockerfile.ci
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3541 baremetal: Link directly to getting-started guide in the docs
  upi/metal/README.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3540 Bug 1830995: Add ModifyTargetGroupAttributes and Describe* to MasterIamRole
  data/data/aws/master/main.tf
  upi/aws/cloudformation/03_cluster_security.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3552 baremetal: Clarify it's the matchbox instance that needs to be public reachable
  upi/metal/README.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3498 Bug 1826100: vSphere allow users to specify existing folder
  data/data/vsphere/main.tf
  data/data/vsphere/variables-vsphere.tf
  docs/user/vsphere/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/vsphere/cloudproviderconfig.go
  pkg/asset/manifests/vsphere/cloudproviderconfig_test.go
  pkg/destroy/vsphere/vsphere.go
  pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
  pkg/tfvars/vsphere/vsphere.go
  pkg/types/validation/installconfig_test.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/platform.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3534 bug 1807111: terraform/exec: suppress the warnings from error to debug
  pkg/terraform/exec/exec.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3551 Bug 1831760: Fix bootstrap certificate generation
  pkg/asset/tls/tls.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3542 Bug 1814605: openstack: Require three workers
  docs/user/openstack/README.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#3406 Bug 1816714: ovirt - add vnic profile id to platform
  data/data/ovirt/main.tf
  data/data/ovirt/template/main.tf
  data/data/ovirt/template/variables.tf
  data/data/ovirt/variables-ovirt.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/ovirt/client.go
  pkg/asset/installconfig/ovirt/network.go
  pkg/asset/installconfig/ovirt/ovirt.go
  pkg/asset/installconfig/ovirt/validaton.go
  pkg/asset/installconfig/ovirt/validaton_test.go
  pkg/asset/installconfig/ovirt/validators.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/destroy/ovirt/destroyer.go
  pkg/tfvars/ovirt/ovirt.go
  pkg/types/defaults/installconfig.go
  pkg/types/ovirt/defaults/platform.go
  pkg/types/ovirt/defaults/platform_test.go
  pkg/types/ovirt/platform.go
  pkg/types/ovirt/validation/platform.go
  pkg/types/ovirt/validation/platform_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#3506 docs/user: add troubleshootingbootstrap to define the bootstrap log bundle
  docs/user/troubleshooting.md
  docs/user/troubleshootingbootstrap.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3562 baremetal: Fix a small typo in cp cmdline in docs
  docs/user/metal/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3560 baremetal: Fix broken link to example tfvars in docs
  docs/user/metal/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3518 Bug 1828947: cmd/openshift-install/create.go: return lastErr when waiting API fails
  cmd/openshift-install/create.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3511 Bug 1828238: OpenStack: Allow Booting bootstrap node from volume
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  docs/user/openstack/customization.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#3563 [FCOS] Azure fixes (correct FCOS version, decompress fcos image for Azure, page blob)
  data/data/azure/main.tf
  data/data/rhcos-amd64.json
  data/data/rhcos.json
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm, ok-to-test

#3561 Bug 1794839: data/azure: Use a single network security group for Azure clusters
  data/data/azure/main.tf
  data/data/azure/vnet/nsg.tf
  data/data/azure/vnet/outputs.tf
  pkg/asset/manifests/cloudproviderconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3455 Bug 1824172: enable ppc64le & s390x bootimage support
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  go.mod
  go.sum
  hack/update-rhcos-bootimage.py
  pkg/tfvars/libvirt/libvirt.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
  vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/coreos_ignition_def.go
  vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_network.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#3120 Bug 1732124: Azure: don't allow installing with the same cluster name as an existing install
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/platformprovisioncheck.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, size/L

#3499 docs/user/power/install_upi: 2 compute and copy-edits
  docs/user/power/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm

#3259 BUG 1782516: Disable client side rate limiting in Azure.
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#3572 [fcos] data/data/rhcos: update to FCOS 20200420.3.0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, lgtm

#3550 BUG 1831717: Ensure AWS PublicIP is omitted from MachineSet when empty
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/aws/aws.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/common_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/consts.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/utils/pointer/README.md
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/addtoscheme_openshiftawsprovider_v1beta1.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/awsproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/register.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3570 Bug 1833425: pkg/explain/cmd.go: fix help text
  hack/verify-codegen.sh
  pkg/explain/cmd.go
  pkg/rhcos/ami_regions_generate.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3588 Bug 1834748: os: Fix wait-for install-complete timeout in docs
  docs/user/openstack/README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#3583 bug 1834177: upi/azure: Use a single network security group for Azure clusters
  docs/user/azure/install_upi.md
  upi/azure/01_vnet.json
  upi/azure/04_bootstrap.json
  upi/azure/setup-manifests.py
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3537 load balancer health check for kube-apiserver
  data/data/aws/vpc/master-elb.tf
  data/data/gcp/network/lb-private.tf
  data/data/gcp/network/lb-public.tf
  docs/dev/kube-apiserver-health-check.md
  upi/gcp/02_lb_ext.py
  upi/gcp/02_lb_int.py
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3584 Bug 1828638: set vSphere node diskSize based on machine pool
  data/data/vsphere/master/main.tf
  pkg/types/validation/machinepools.go
  pkg/types/vsphere/validation/machinepool.go
  pkg/types/vsphere/validation/machinepool_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3589 Bug 1833483: Revert "baremetal: send full ignition to masters"
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#3587 [fcos] libvirt container entrypoint, resize image to 16GB
  data/data/libvirt/volume/main.tf
  images/libvirt/Dockerfile.ci
Labels: approved, lgtm

#3497 Bug 1824991: Update vSphere and Metal UPI for terraform 0.12
  images/installer/Dockerfile.upi.ci
  upi/metal/bootstrap/matchbox.tf
  upi/metal/bootstrap/outputs.tf
  upi/metal/bootstrap/packet.tf
  upi/metal/bootstrap/variables.tf
  upi/metal/config.tf
  upi/metal/main.tf
  upi/metal/outputs.tf
  upi/vsphere/cluster_domain/main.tf
  upi/vsphere/cluster_domain/outputs.tf
  upi/vsphere/cluster_domain/variables.tf
  upi/vsphere/folder/main.tf
  upi/vsphere/folder/output.tf
  upi/vsphere/folder/variables.tf
  upi/vsphere/host_a_record/main.tf
  upi/vsphere/host_a_record/outputs.tf
  upi/vsphere/host_a_record/variables.tf
  upi/vsphere/ipam/cidr_to_ip.sh
  upi/vsphere/ipam/main.tf
  upi/vsphere/ipam/outputs.tf
  upi/vsphere/ipam/variables.tf
  upi/vsphere/ipam/versions.tf
  upi/vsphere/lb/haproxy.service
  upi/vsphere/lb/haproxy.tmpl
  upi/vsphere/lb/main.tf
  upi/vsphere/lb/outputs.tf
  upi/vsphere/lb/variables.tf
  upi/vsphere/machine/ignition.tf
  upi/vsphere/machine/ip.tf
  upi/vsphere/machine/main.tf
  upi/vsphere/machine/output.tf
  upi/vsphere/machine/variables.tf
  upi/vsphere/main.tf
  upi/vsphere/resource_pool/main.tf
  upi/vsphere/resource_pool/output.tf
  upi/vsphere/resource_pool/variables.tf
  upi/vsphere/route53/main.tf
  upi/vsphere/route53/variables.tf
  upi/vsphere/variables.tf
  upi/vsphere/vm/ifcfg.tmpl
  upi/vsphere/vm/ignition.tf
  upi/vsphere/vm/main.tf
  upi/vsphere/vm/variables.tf
  upi/vsphere/vm/versions.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3399 Bug 1820300: Extend oVirt's MachinePool
  data/data/install.openshift.io_installconfigs.yaml
  data/data/ovirt/main.tf
  data/data/ovirt/masters/main.tf
  data/data/ovirt/masters/variables.tf
  data/data/ovirt/template/main.tf
  data/data/ovirt/template/variables.tf
  data/data/ovirt/variables-ovirt.tf
  docs/user/ovirt/customization.md
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/ovirt/validaton.go
  pkg/asset/machines/master.go
  pkg/asset/machines/ovirt/machines.go
  pkg/asset/machines/ovirt/machinesets.go
  pkg/asset/machines/worker.go
  pkg/tfvars/ovirt/ovirt.go
  pkg/types/ovirt/machinepool.go
  pkg/types/ovirt/validation/machinepool.go
  pkg/types/ovirt/validation/machinepool_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/types.go
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#3569 Bug 1820575: Cherry-pick oVirt PR 3406 vNIC profiles
  data/data/ovirt/main.tf
  data/data/ovirt/template/main.tf
  data/data/ovirt/template/variables.tf
  data/data/ovirt/variables-ovirt.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/ovirt/client.go
  pkg/asset/installconfig/ovirt/network.go
  pkg/asset/installconfig/ovirt/ovirt.go
  pkg/asset/installconfig/ovirt/validaton.go
  pkg/asset/installconfig/ovirt/validaton_test.go
  pkg/asset/installconfig/ovirt/validators.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/destroy/ovirt/destroyer.go
  pkg/tfvars/ovirt/ovirt.go
  pkg/types/defaults/installconfig.go
  pkg/types/ovirt/defaults/platform.go
  pkg/types/ovirt/defaults/platform_test.go
  pkg/types/ovirt/platform.go
  pkg/types/ovirt/validation/platform.go
  pkg/types/ovirt/validation/platform_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3597 Bug 1835438: move vSphere folder validation to provisioning
  pkg/asset/installconfig/vsphere/validation.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#3571 Bug 1828948: cmd/openshift-install/create.go: return lastErr when waiting API fails
  cmd/openshift-install/create.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3600 Bug 1828382: data/azure/vnet: switch to HTTPS probes for lbs
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/public-lb.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3408 Bug 1820591: Add retries to DeleteSwiftContainer
  pkg/destroy/openstack/swift.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3601 Bug 1815071: check for api dns record before creating cluster
  hack/go-genmock.sh
  pkg/asset/installconfig/gcp/.mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/dns.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/installconfig/platformprovisioncheck.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3591 Baremetal: Bug 1801238: Pull data from ironic inspector and annotate BareMetalHost
  data/data/baremetal/masters/main.tf
  data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
  data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/baremetal

#3609 Bug 1836368: ovirt: return slice and not nil in instanceTypeID validation
  pkg/asset/installconfig/ovirt/validaton.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#3610 ovirt: Add ovirt to supported platforms
  README.md
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, retest-not-required-docs-only

#3599 Bug 1835867: data/data/aws/vpc: create subnet sizes based on az count
  data/data/aws/vpc/vpc-private.tf
  data/data/aws/vpc/vpc-public.tf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3611 [fcos] Inject etcd and ingress tweaks when a single master is used
  pkg/asset/machines/master.go
  pkg/asset/machines/singlemaster.go
Labels: approved, lgtm

#3595 Bug 1836339: GCP: Enable disk type and size customization
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/gcp/customization.md
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/worker.go
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/gcp/validation/machinepool_test.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  pkg/types/validation/machinepools.go
  pkg/types/validation/machinepools_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3520 Bug 1836337: Azure: Add functionality to change Azure Machine Disk Types
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/azure/customization.md
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
  pkg/types/azure/validation/platform.go
  pkg/types/validation/machinepools.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3619 Bug 1834966: update vSphere UPI docs to remove machinesets
  docs/user/vsphere/install_upi.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3183 Bug 1804230: Documentation Incorrect for OCP 4.4 RHV IPI Install
  docs/user/ovirt/install_ipi.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, retest-not-required-docs-only, size/L

#3535 Bug 1837564: pkg/terraform: add diagnostics errors for terraform apply operations
  pkg/diagnostics/error.go
  pkg/terraform/diagnose.go
  pkg/terraform/diagnose_test.go
  pkg/terraform/terraform.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3632 Bug 1838032: Don't create router to external network when BYO subnet is set
  data/data/openstack/topology/private-network.tf
  docs/user/openstack/customization.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#3428 Bug 1820222: libvirt: Bump bootstrap memory to 5G for ppc64le
  data/data/libvirt/bootstrap/main.tf
  data/data/libvirt/bootstrap/variables.tf
  data/data/libvirt/main.tf
  data/data/libvirt/variables-libvirt.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/libvirt/libvirt.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3612 Bug 1836042: set folder absolute path in vSphere cloud provider
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/vsphere/cloudproviderconfig.go
  pkg/asset/manifests/vsphere/cloudproviderconfig_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3613 Bug 1837039: rhcos: Bump to 45.81.202005181029-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3457 Bug 1824180: Backport adding groundwork for multi-arch images
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  hack/update-rhcos-bootimage.py
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/coreos_ignition_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  pkg/tfvars/libvirt/libvirt.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3544 Bug 1837642: installconfig: relax GCP cluster id restriction
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/master/main.tf
  pkg/asset/installconfig/clusterid.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/gcp/machinesets.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3628 Bug 1835795: downport disk extension support for masters/workers
  Gopkg.lock
  Gopkg.toml
  data/data/ovirt/main.tf
  data/data/ovirt/masters/main.tf
  data/data/ovirt/masters/variables.tf
  data/data/ovirt/template/main.tf
  data/data/ovirt/template/variables.tf
  data/data/ovirt/variables-ovirt.tf
  docs/user/ovirt/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/ovirt/validaton.go
  pkg/asset/machines/master.go
  pkg/asset/machines/ovirt/machines.go
  pkg/asset/machines/ovirt/machinesets.go
  pkg/asset/machines/worker.go
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/go-ovirt/connection.go
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/go-ovirt/readers.go
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/go-ovirt/services.go
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/go-ovirt/types.go
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/go-ovirt/version.go
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/go-ovirt/writers.go
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_image_transfer.go
  pkg/terraform/exec/plugins/vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go
  pkg/tfvars/ovirt/ovirt.go
  pkg/types/ovirt/machinepool.go
  pkg/types/ovirt/validation/machinepool.go
  pkg/types/ovirt/validation/machinepool_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/apis.go
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/types.go
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/ovirt/cluster-api-provider-ovirt/LICENSE
  vendor/github.com/ovirt/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/doc.go
  vendor/github.com/ovirt/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/register.go
  vendor/github.com/ovirt/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/types.go
  vendor/github.com/ovirt/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/github.com/ovirt/go-ovirt/readers.go
  vendor/github.com/ovirt/go-ovirt/services.go
  vendor/github.com/ovirt/go-ovirt/types.go
  vendor/github.com/ovirt/go-ovirt/version.go
  vendor/github.com/ovirt/go-ovirt/writers.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3646 Bug 1839268: pkg/destroy/gcp: ensure cluster service accounts and policy bindings are removed
  pkg/destroy/gcp/policybinding.go
  pkg/destroy/gcp/serviceaccount.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3618 Add oVirt OWNERS
  OWNERS_ALIASES
  data/data/bootstrap/ovirt/OWNERS
  data/data/ovirt/OWNERS
  docs/user/ovirt/OWNERS
  pkg/asset/cluster/ovirt/OWNERS
  pkg/asset/installconfig/ovirt/OWNERS
  pkg/asset/machines/ovirt/OWNERS
  pkg/destroy/ovirt/OWNERS
  pkg/tfvars/ovirt/OWNERS
  pkg/types/ovirt/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test

#3654 Bug 1821151: oVirt, fix rhcos os_type name
  data/data/ovirt/template/main.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3640 OWNER_ALIASES: ensure there are atleast 2 reviewers for each platform
  OWNERS_ALIASES
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3645 Adding a few people to the ARO team to our list of reviewers
  OWNERS_ALIASES
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3617 Bug 1798498: gather: enable bootstrap log gathering for baremetal
  cmd/openshift-install/gather.go
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  go.mod
  go.sum
  pkg/terraform/gather/baremetal/OWNERS
  pkg/terraform/gather/baremetal/ip.go
  vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/provider.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/baremetal

#3639 Bug 1838631: Set validations for GCP disk sizes.
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/gcp/customization.md
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/gcp/validation/machinepool_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3668 Update libvirt approver and reviewer
  OWNERS_ALIASES
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3667 Add openstack reviewers
  OWNERS_ALIASES
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3415 Bug 1821638: oVirt, add os_type to ovirt templates
  data/data/ovirt/template/main.tf
  pkg/asset/installconfig/ovirt/validaton_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3304 Bug 1840496: [baremetal] Remove DNS VIP
  docs/user/metal/install_ipi.md
  pkg/asset/manifests/infrastructure.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/baremetal

#3666 Bug 1840710: libvirt: Bump machine memory from 7G to 8G
  pkg/asset/machines/libvirt/machines.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3672 vSphere docs: add IPI documentation
  docs/user/vsphere/OWNERS
  docs/user/vsphere/README.md
  docs/user/vsphere/images/assign-role.png
  docs/user/vsphere/images/certs.png
  docs/user/vsphere/images/install_console.png
  docs/user/vsphere/images/remove-permission.png
  docs/user/vsphere/images/select-privileges.png
  docs/user/vsphere/images/view-privileges.png
  docs/user/vsphere/install.md
  docs/user/vsphere/privileges.md
  docs/user/vsphere/requirements.md
  docs/user/vsphere/vips-dns.md
Labels: approved, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3633 Update initial FCOS to 31.20200505.3.0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, lgtm

#3652 [fcos] Prevent crio from pulling the pause image. The crio-configure.service should test if crio already is installed before patching its config.
  data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
  data/data/bootstrap/systemd/units/bootkube.service
Labels: approved, lgtm, ok-to-test

#3662 [release-4.4] Bug 1838885: installconfig: relax GCP cluster id restriction
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/master/main.tf
  pkg/asset/installconfig/clusterid.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/gcp/machinesets.go
  pkg/destroy/gcp/policybinding.go
  pkg/destroy/gcp/serviceaccount.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3655 Bug 1823487: openstack: Pass the master server group by name
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/variables-openstack.tf
  go.mod
  go.sum
  pkg/asset/machines/openstack/machines.go
  pkg/tfvars/openstack/openstack.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/common/plugins.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/common_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/doc.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/register.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/common_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/consts.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#3679 Bug 1841118: add error handling to vSphere survey
  pkg/asset/installconfig/vsphere/vsphere.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3685 Bug 1841913: images: libvirt: add yq to libvirt CI image
  images/libvirt/Dockerfile.ci
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3682 Bug 1841072: [UPI] Rely on security group ID when deleting it
  upi/openstack/down-security-groups.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack
