Repository openshift/installer, pull requests merged in 2020-06, with the labels that each got.

#3638 Warn about security risks of the recommended libvirt install configuration
  docs/dev/libvirt/README.md
Labels: approved, lgtm, ok-to-test

#3669 openstack: Add numbers to disk requirements
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack

#3594 Add information about ovn-octavia
  docs/user/openstack/kuryr.md
Labels: approved, lgtm, platform/openstack

#3690 Add links from customization.md to ovirt/customization.md topic
  docs/user/customization.md
Labels: approved, lgtm, ok-to-test

#3701 Bug 1842607: update README with vSphere IPI docs
  README.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, retest-not-required-docs-only

#3615 cmd/openshift-install/gather: Recognize "connection refused"
  cmd/openshift-install/gather.go
  pkg/gather/ssh/agent.go
  pkg/gather/ssh/ssh.go
Labels: approved, lgtm, version/4.6

#2854 aws: update the bootstrap ignition fetching to use custom region endpoints
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  data/data/aws/variables-aws.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/aws/presign.go
  pkg/tfvars/aws/aws.go
Labels: approved, lgtm, size/M, version/4.6

#3708 Add reviewers to the OpenStack directories
  data/data/bootstrap/openstack/OWNERS
  data/data/openstack/OWNERS
  images/openstack/OWNERS
  pkg/asset/cluster/openstack/OWNERS
  pkg/asset/installconfig/openstack/OWNERS
  pkg/asset/machines/openstack/OWNERS
  pkg/asset/manifests/openstack/OWNERS
  pkg/destroy/openstack/OWNERS
  pkg/tfvars/openstack/OWNERS
  pkg/types/openstack/OWNERS
  upi/openstack/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only

#3683 bootstrap: Make crio-configure.service RequiredBy=crio.service
  data/data/bootstrap/systemd/units/crio-configure.service.template
Labels: approved, lgtm

#3532 cmd/openshift-install: Drop unused 'directory' arguments
  cmd/openshift-install/create.go
  cmd/openshift-install/waitfor.go
Labels: approved, lgtm, version/4.6

#3133 bootstrap: restore 30 minute bootstrap timeout
  cmd/openshift-install/create.go
Labels: approved, lgtm, size/XS, version/4.6

#3691 baremetal: allow bootstrap vm to use libvirt nat networks
  pkg/types/baremetal/validation/libvirt.go
Labels: approved, lgtm

#3709 Bug 1836018: upi/aws/cloudformation: Define healthcheck probes for LBs
  upi/aws/cloudformation/02_cluster_infra.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2898 upi: update upi/vsphere/README.md
  upi/vsphere/README.md
Labels: approved, lgtm, ok-to-test, retest-not-required-docs-only, size/XS, version/4.6

#3172 Give a proper error when misusing OPENSHIFT_INSTALL_AZURE_EMULATE_SINGLESTACK_IPV6
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, size/XS, version/4.6

#3430 Add nested support for GCP
  data/data/gcp/main.tf
  data/data/gcp/variables-gcp.tf
  docs/user/gcp/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, ok-to-test, version/4.6

#3665 [release-4.3] Bug 1840230: data/azure/vnet: switch to HTTPS probes for lbs
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/public-lb.tf
  pkg/asset/tls/tls.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3681 Fix re-generation of install config on wait-for install-complete command
  cmd/openshift-install/create.go
  pkg/asset/store.go
  pkg/asset/store/store.go
  pkg/asset/store/store_test.go
Labels: approved, lgtm

#3492 Bug 1841066: OpenStack: Remove DNS VIP
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/manifests/infrastructure.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/defaults/platform.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#3494 upi: Post TF 0.12.x migration fixups
  docs/user/vsphere/install_upi.md
  upi/vsphere/README.md
  upi/vsphere/lb/main.tf
  upi/vsphere/terraform.tfvars.example
Labels: approved, lgtm

#3722 validation/installconfig: fix the test to work with go 1.14
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#3647 Bug 1838032: Better docs for using custom subnets
  docs/user/openstack/customization.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#3718 Bug 1844103: allow OpaqueNetwork type in vSphere wizard
  pkg/asset/installconfig/vsphere/vsphere.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3696 [UPI on OSP] make remove network and port more faster
  upi/openstack/down-network.yaml
Labels: approved, lgtm, platform/openstack

#3634 support for other Azure cloud environments
  cmd/openshift-install/migrate/azure/eligible.go
  cmd/openshift-install/migrate/azure/migrate.go
  data/data/azure/main.tf
  data/data/azure/variables-azure.tf
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/cluster/azure/azure.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/azure/azure.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/installconfig/azure/session.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/basedomain.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/machines/azure/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/openshift.go
  pkg/destroy/azure/azure.go
  pkg/explain/printer_test.go
  pkg/migrate/azure/privatedns.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/defaults/platform.go
  pkg/types/azure/defaults/platform_test.go
  pkg/types/azure/metadata.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#3712 Bug 1823967: Add the --pod-infra-container-image flag to the kubelet service
  data/data/bootstrap/files/usr/local/bin/kubelet-pause-image.sh.template
  data/data/bootstrap/systemd/units/kubelet.service.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3324 azure: add OutboundType for controlling egress
  data/data/azure/bootstrap/main.tf
  data/data/azure/bootstrap/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/master.tf
  data/data/azure/master/variables.tf
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/public-lb.tf
  data/data/azure/vnet/variables.tf
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/azure/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/manifests/openshift.go
  pkg/explain/printer_test.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/defaults/platform.go
  pkg/types/azure/defaults/platform_test.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
Labels: approved, lgtm

#3720 Bug 1836016: use https for lb probes in Azure UPI
  upi/azure/03_infra.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3721 Bug 1843314: baremetal: bump ironic timeout to 3600 seconds
  data/data/baremetal/main.tf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/baremetal

#3734 Bug 1734460: OpenStack: Wait for router interface to create FIP
  data/data/openstack/topology/private-network.tf
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3744 ISSUE_TEMPLATE.md: Specify the platform for UPI
  .github/ISSUE_TEMPLATE.md
Labels: approved, lgtm, retest-not-required-docs-only

#3737 [fcos] add vrutkovs and LorbusChris to owners
  OWNERS
Labels: approved, lgtm

#3742 Bug 1846366: ovirt: use pointer instead of struct for user/pass
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3702 GCP: Fix uninstaller to not use hardcoded base path.
  pkg/destroy/gcp/cloudcontroller.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/instance.go
  pkg/destroy/gcp/instancegroup.go
Labels: approved, lgtm

#3713 GCP UPI: relax cluster name
  docs/user/gcp/install_upi.md
  upi/gcp/05_control_plane.py
Labels: approved, lgtm

#3738 vSphere docs: update UPI docs for folder name
  docs/user/vsphere/install_upi.md
Labels: approved, lgtm, retest-not-required-docs-only

#3757 Bug 1836018: Use /healthz for mco
  upi/aws/cloudformation/02_cluster_infra.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3677 docs/dev/libvirt: update libvirt/firewalld setup instructions
  docs/dev/libvirt/README.md
Labels: approved, lgtm, ok-to-test

#3760 Bug 1846386: typo in filenames
  pkg/asset/installconfig/ovirt/validation.go
  pkg/asset/installconfig/ovirt/validation_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3741 Bug 1846296: openstack UPI: prune containers
  docs/user/openstack/install_upi.md
  upi/openstack/common.yaml
  upi/openstack/down-containers.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#3769 Bug 1848080: README.md: dummy change to test new automation feature
  README.md
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#3770 gcp: Fix uninstaller for internal clusters on GCP.
  pkg/destroy/gcp/cloudcontroller.go
  pkg/destroy/gcp/instancegroup.go
Labels: approved, lgtm

#3735 [FCOS] go.mod: update MCO to latest commit in `fcos` branch
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#3765 destroy: provide way to stop aws uninstall using context
  pkg/destroy/aws/aws.go
Labels: approved, lgtm

#3767 pkg/asset/installconfig/azure: create reusable session
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/azure/azure.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/installconfig/azure/metadata.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/basedomain.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/machines/azure/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/openshift.go
Labels: approved, lgtm

#3776 Bug 1848988: os UPI: Make down-containers idempotent
  upi/openstack/down-containers.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#3775 Bug 1848106: data/azure: use outbound_rule instead of dummy inbound lb_rule
  data/data/azure/vnet/public-lb.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#3763 Bug 1847705: rhcos: Bump to 46.82.202006162207-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#3779 Bug 1849150: rhcos/amd64: Bump to 45.82.202006191325-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, group-lead-approved, lgtm

#3759 [FCOS] Use Ignition spec 3 in openstack terraform
  data/data/openstack/masters/main.tf
  upi/vsphere/lb/main.tf
  upi/vsphere/vm/ignition.tf
Labels: approved, lgtm

#3774 [FCOS] Update to bootimage to 32.20200601.3.0
  data/data/fcos-amd64.json
  data/data/fcos.json
  hack/update-fcos-bootimage.py
Labels: approved, lgtm

#3778 [FCOS] data/data/bootstrap/vsphere: prepend DNS VIP via NM script instead of…
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/vsphere/files/etc/dhcp/dhclient.conf.template
Labels: approved, lgtm

#3782 [FCOS] data/data/bootstrap: use NM-based prepender in openstack and ovirt
  data/data/bootstrap/openstack/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/openstack/files/etc/dhcp/dhclient.conf
  data/data/bootstrap/ovirt/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/ovirt/files/etc/dhcp/dhclient.conf
Labels: approved, lgtm

#3789 OpenStack: Use prepender script for bootstrap resolver
  data/data/bootstrap/openstack/files/etc/NetworkManager/conf.d/dhcp-client.conf
  data/data/bootstrap/openstack/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/openstack/files/etc/dhcp/dhclient.conf
Labels: approved, lgtm, platform/openstack

#3792 Bug 1850235: empty commit: dummy change to test new automation feature
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3791 rhcos/amd64: Bump to 45.82.202006230709-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3787 [FCOS] Periodic rebase on release-4.5 branch
  data/data/azure/vnet/public-lb.tf
  data/data/baremetal/main.tf
  data/data/bootstrap/files/usr/local/bin/kubelet-pause-image.sh.template
  data/data/bootstrap/systemd/units/kubelet.service.template
  data/data/openstack/topology/private-network.tf
  data/data/rhcos-amd64.json
  data/data/rhcos.json
  docs/user/vsphere/install_upi.md
  pkg/asset/installconfig/vsphere/vsphere.go
Labels: approved, lgtm

#3793 Libvirt: Make master disk size configurable
  data/data/libvirt/main.tf
  data/data/libvirt/variables-libvirt.tf
  pkg/tfvars/libvirt/libvirt.go
Labels: approved, lgtm

#3804 Bug 1850940: OpenStack: Wait for router to create FIP
  data/data/openstack/topology/private-network.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#3806 baremetal: Start coreos-downloader before ipa-downloader
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm

#3803 Docs: DNS VIP no longer exists
  docs/design/openstack/networking-infrastructure.md
Labels: approved, lgtm, platform/openstack

#3749 destroy/gcp: bubble up errors after 5 minutes
  pkg/destroy/gcp/address.go
  pkg/destroy/gcp/backendservice.go
  pkg/destroy/gcp/bucket.go
  pkg/destroy/gcp/disk.go
  pkg/destroy/gcp/errortracker.go
  pkg/destroy/gcp/firewall.go
  pkg/destroy/gcp/forwardingrule.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/healthcheck.go
  pkg/destroy/gcp/httphealthcheck.go
  pkg/destroy/gcp/image.go
  pkg/destroy/gcp/instance.go
  pkg/destroy/gcp/instancegroup.go
  pkg/destroy/gcp/network.go
  pkg/destroy/gcp/policybinding.go
  pkg/destroy/gcp/route.go
  pkg/destroy/gcp/router.go
  pkg/destroy/gcp/serviceaccount.go
  pkg/destroy/gcp/subnetwork.go
  pkg/destroy/gcp/targetpool.go
Labels: approved, lgtm

#3802 Bug 1851067: rhcos/ppc64le,s390x: Bump to 46.82.202006241544-0 and 46.82.202006241639-0
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3786 Bug 1850714: adjust Azure UPI disk size to the same used in IPI
  upi/azure/05_masters.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3797 Bug 1851069: rhcos/ppc64le, s390x: Bump to 45.82.202006240558-0 and 45.82.202006240257-0
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3703 create cmd: Display command asset directories.
  cmd/openshift-install/create.go
  pkg/asset/logging/filelogging.go
  pkg/asset/logging/filelogging_test.go
Labels: approved, lgtm

#3823 Bug 1838559: Bump go-ovirt
  go.mod
  go.sum
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/github.com/ovirt/go-ovirt/reader.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
