Repository openshift/installer, pull requests merged in 2020-04, with the labels that each got.

#3390 Bug 1819320: os UPI Idempotent server group create
  upi/openstack/04_control-plane.yaml
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3362 Enhancements to Kuryr documentation
  docs/user/openstack/kuryr.md
Labels: approved, lgtm, platform/openstack

#3378 openstack UPI: Small documentation fixes
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, platform/openstack

#3380 Use "default-ingress-cert", not "router-ca"
  cmd/openshift-install/create.go
  docs/user/troubleshooting.md
Labels: approved, lgtm

#3374 [FCOS] pkg/asset/releaseimage/default: use OKD 4.4 as default release
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm

#3394 OpenStack: Temporary disable image import
  pkg/tfvars/openstack/rhcos_image.go
Labels: approved, lgtm

#3381 pass the manifests-dir param to CCO render
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#3352 Bug 1816155: OpenStack: Add retries to DeleteGlanceImage
  pkg/destroy/openstack/glance.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3372 vSphere: Add IPI-specific validation.
  docs/design/resource_dep.svg
  pkg/asset/cluster/cluster.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/installconfig/vsphere/validation_test.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm

#3369 Bug 1814172: [ovirt] Cannot run openshift-install as a non-root user
  pkg/asset/installconfig/ovirt/config.go
Labels: approved, bugzilla/valid-bug, lgtm

#3351 Bug 1817717: Backport Azure UPI to 4.3
  docs/user/azure/install_upi.md
  upi/azure/01_vnet.json
  upi/azure/02_storage.json
  upi/azure/03_infra.json
  upi/azure/04_bootstrap.json
  upi/azure/05_masters.json
  upi/azure/06_workers.json
  upi/azure/setup-manifests.py
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2921 gcp: Flag RHCOS with SECURE_BOOT and UEFI_COMPATIBLE
  data/data/gcp/main.tf
Labels: approved, lgtm, size/XS

#3402 Fix indentation on a UPI Playbook task
  upi/openstack/down-06_load-balancers.yaml
Labels: approved, lgtm, platform/openstack

#3400 OWNERS: include component for image tracking by ART
  OWNERS
Labels: approved, lgtm

#3373 Bug 1810840 : Quote user and password values for good UX and avoid co…
  cmd/openshift-install/create.go
Labels: approved, lgtm, ok-to-test

#3393 bug 1815518: pkg/destroy/aws: delete versioned objects from s3 buckets
  pkg/destroy/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm

#3395 Bug 1820153: OpenStack: Allow destroying cluster without trunk ports
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3376 Bug 1818608: os UPI fix step order
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#3404 OpenStack: Link to GH issue for glance image import
  pkg/tfvars/openstack/rhcos_image.go
Labels: approved, lgtm

#3411 Fix playbooks names
  docs/user/openstack/install_upi.md
  upi/openstack/README.md
  upi/openstack/bootstrap.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/down-bootstrap.yaml
  upi/openstack/down-compute-nodes.yaml
  upi/openstack/down-control-plane.yaml
  upi/openstack/down-load-balancers.yaml
  upi/openstack/down-network.yaml
  upi/openstack/down-security-groups.yaml
  upi/openstack/network.yaml
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, platform/openstack

#3392 baremetal: validate hosts number
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#3396 Bug 1821788:libvirt: Bump bootstrap memory to 5G for ppc64le
  data/data/libvirt/bootstrap/main.tf
  data/data/libvirt/bootstrap/variables.tf
  data/data/libvirt/main.tf
  data/data/libvirt/variables-libvirt.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/libvirt/libvirt.go
Labels: approved, bugzilla/valid-bug, lgtm

#3423 docs(README): README build steps don't require clone to GOPATH
  README.md
Labels: approved, lgtm, needs-ok-to-test

#3401 pkg/types/validation: Drop internal ClusterDomain
  pkg/asset/installconfig/clustername.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm

#3388 Bug 1819136: Convert ansible module to openstackcli
  docs/user/openstack/install_upi.md
  upi/openstack/01_security-groups.yaml
  upi/openstack/02_network.yaml
  upi/openstack/03_bootstrap.yaml
  upi/openstack/04_control-plane.yaml
  upi/openstack/05_compute-nodes.yaml
  upi/openstack/down-01_security-groups.yaml
  upi/openstack/down-02_network.yaml
  upi/openstack/down-04_control-plane.yaml
  upi/openstack/down-05_compute-nodes.yaml
  upi/openstack/down-06_load-balancers.yaml
  upi/openstack/inventory.yaml
  upi/openstack/library/os_create_subnet_pool.py
  upi/openstack/library/os_create_svc_subnet.py
  upi/openstack/library/os_delete_lb_resources.py
  upi/openstack/library/os_delete_network_resources.py
  upi/openstack/library/os_delete_ports_on_router.py
  upi/openstack/library/os_tag.py
  upi/openstack/library/os_trunk.py
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#3419 Bug 1821653: Fix LB deletion for lbs with same or status pending
  docs/user/openstack/install_upi.md
  upi/openstack/down-load-balancers.yaml
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3263 Print time for each step of installation
  cmd/openshift-install/create.go
  cmd/openshift-install/destroy.go
  cmd/openshift-install/waitfor.go
  go.sum
  pkg/asset/cluster/cluster.go
  pkg/metrics/timer/timer.go
  pkg/metrics/timer/timer_test.go
Labels: approved, lgtm, size/M

#3366 OpenStack: Custom API and Ingress vip addresses
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/topology/private-network.tf
  docs/user/openstack/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/machine/node.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/tls/mcscertkey.go
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/openstack/defaults/platform.go
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
Labels: approved, lgtm, platform/openstack

#3291 OpenStack: allow to specify additional networks and security groups for masters and workers
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/customization.md
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/openstack/machines.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/machinepool.go
  pkg/types/openstack/validation/machinepool.go
  pkg/types/openstack/validation/machinepool_test.go
  pkg/types/validation/installconfig_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, lgtm

#3421 Bug 1819461: validate Azure regions
  pkg/asset/installconfig/azure/azure.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/subscriptions/models.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#3432 [fcos] GCP-routes: switch to using conntrack instead of route tables
  data/data/bootstrap/gcp/files/usr/local/bin/gcp-routes.sh
Labels: approved, lgtm

#3438 pkg/types/config: Remove unused directory
  pkg/types/config/openstack/OWNERS
Labels: approved, lgtm

#3439 OpenStack: Docs: Fix a typo in the property name
  docs/user/openstack/customization.md
Labels: approved, lgtm

#3443 Bug 1822858: vsphere ipi: tag virtual machine created when importing ova
  data/data/vsphere/main.tf
  pkg/terraform/exec/plugins/vsphereprivate/config.go
  pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, bugzilla/valid-bug, lgtm

#3427 handle the posibility that CCO will have no pod definition
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#3445 pkg/destroy/ovirt: Cleanup VM logging
  pkg/destroy/ovirt/destroyer.go
Labels: approved, lgtm

#3444 update permissions list to cover new installer functionality
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm

#3442 [fcos] Update base image to 31.20200323.3.2
  data/data/rhcos-amd64.json
  data/data/rhcos.json
  hack/update-rhcos-bootimage.py
Labels: approved, lgtm

#3446 Bug 1823659: os: Mention the bootstrap FIP
  docs/user/openstack/README.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3425 Updates to fix DNS error for compact cluster worker nodes
  upi/metal/main.tf
Labels: approved, lgtm

#3448 [fcos] Cherrypick few 4.4 fixes
  docs/user/openstack/install_upi.md
  docs/user/openstack/known-issues.md
  go.mod
  go.sum
  pkg/asset/installconfig/ovirt/config.go
  pkg/destroy/openstack/glance.go
  vendor/modules.txt
Labels: approved, lgtm

#3416 uninstall: allow for azure uninstall to succeed for missing rg
  pkg/destroy/azure/azure.go
Labels: approved, lgtm

#2972 hack/update-rhcos-bootimage: Drop the f-string
  hack/update-rhcos-bootimage.py
Labels: approved, lgtm, size/XS

#3343 cmd/openshift-install/migrate: sub command for migrating azure legacy private zones
  cmd/openshift-install/main.go
  cmd/openshift-install/migrate.go
  cmd/openshift-install/migrate/azure/eligible.go
  cmd/openshift-install/migrate/azure/migrate.go
  docs/user/azure/images/azure-migrate-dns-1.png
  docs/user/azure/images/azure-migrate-dns-2.png
  docs/user/azure/images/azure-migrate-dns-3.png
  docs/user/azure/images/azure-migrate-dns-4.png
  docs/user/azure/images/azure-migrate-dns-5.png
  docs/user/azure/images/azure-migrate-dns-6.png
  docs/user/azure/images/azure-migrate-dns-7.png
  docs/user/azure/migrate.md
  go.sum
  pkg/migrate/azure/privatedns.go
Labels: approved, lgtm

#3424 Bug 1802526: AWS Terraform: use machine_cidr instead of VPC main cidr …
  data/data/aws/main.tf
  data/data/aws/vpc/outputs.tf
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
  data/data/aws/vpc/variables.tf
  data/data/aws/vpc/vpc.tf
  data/data/azure/main.tf
  data/data/azure/variables-azure.tf
  data/data/config.tf
  data/data/gcp/main.tf
  data/data/libvirt/main.tf
  data/data/openstack/main.tf
  docs/user/aws/customization.md
  docs/user/gcp/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/azure/azure.go
  pkg/tfvars/tfvars.go
Labels: approved, bugzilla/valid-bug, lgtm

#3437 always atleast use the default SSH key for gathering
  cmd/openshift-install/gather.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/tls/bootstrapsshkeypair.go
  pkg/asset/tls/utils.go
  pkg/gather/ssh/agent.go
Labels: approved, lgtm

#3451 RFE-592: Tightening IAM roles for master/worker nodes to match cloud-provider-aws requirements
  data/data/aws/iam/main.tf
  data/data/aws/master/main.tf
  docs/dev/aws/iam_permissions.md
  upi/aws/cloudformation/03_cluster_security.yaml
Labels: approved, lgtm

#3452 Bug 1823918: Validate Azure regions
  Gopkg.lock
  pkg/asset/installconfig/azure/azure.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/subscriptions/models.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3459 OpenStack: Correcting the instructions to refresh a CA cert
  docs/user/openstack/README.md
Labels: approved, lgtm

#3463 bug 1821667: baremetal IPI: Document Virtual Router IDs
  docs/user/metal/install_ipi.md
Labels: approved, bugzilla/valid-bug, lgtm

#3464 Bug 1819746: Add a note on slow installations
  docs/user/openstack/known-issues.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3276 Baremetal: Support to send full ignition to masters
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/variables-baremetal.tf
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
  vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
  vendor/golang.org/x/lint/go.mod
  vendor/golang.org/x/lint/go.sum
  vendor/golang.org/x/lint/lint.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, platform/baremetal, size/M

#3467 pkg/asset/installconfig: add vSphere TUI wizard
  pkg/asset/installconfig/gcp/gcp.go
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/types/installconfig.go
Labels: approved, lgtm

#3461 Bug 1824287: OpenStack: Replace remote_group_id with remote_ip_prefix
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm, platform/openstack

#3471 baremetal: add documentation for configuration validations
  docs/user/metal/install_ipi.md
Labels: approved, lgtm

#3398 OpenStack: Custom subnets
  data/data/openstack/main.tf
  data/data/openstack/topology/outputs.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/mock/filefetcher_generated.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/openstack/validation/validvaluesfetcher.go
Labels: approved, lgtm, platform/openstack

#3472 Bug 1825286: OpenStack UPI: Replace remote_group_id with remote_ip_prefix
  upi/openstack/security-groups.yaml
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm, platform/openstack

#3474 Bug 1825415: ovirt: clean up prompts and logging
  pkg/asset/installconfig/ovirt/cluster.go
  pkg/asset/installconfig/ovirt/credentials.go
  pkg/asset/installconfig/ovirt/network.go
  pkg/asset/installconfig/ovirt/ovirt.go
  pkg/asset/installconfig/ovirt/storage.go
  pkg/destroy/ovirt/destroyer.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#3435 Bug 1822701: OpenStack: Set vrrp protocol number instead of name
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3447 openstack: Mention Server group requirement
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack

#3473 update cloud provider to use folder from platform
  pkg/asset/manifests/vsphere/cloudproviderconfig.go
Labels: approved, lgtm

#3358 Bug 1813422: baremetal: validate no overlap between provisioning and machine nets
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#3470 vsphere ipi: align with baremetal and remove DNSVIP
  pkg/asset/installconfig/vsphere/validation_test.go
  pkg/asset/manifests/infrastructure.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm

#3434 Bug 1820434: OpenStack: Allow Booting bootstrap node from volume
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  docs/user/openstack/customization.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3479 installconfig/ovirt: fix CA prompt and add warning
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, lgtm

#3480 Bug 1825418: ovirt: clean up prompts and logging
  pkg/asset/installconfig/ovirt/cluster.go
  pkg/asset/installconfig/ovirt/credentials.go
  pkg/asset/installconfig/ovirt/network.go
  pkg/asset/installconfig/ovirt/ovirt.go
  pkg/asset/installconfig/ovirt/storage.go
  pkg/destroy/ovirt/destroyer.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3477 [release-4.4] Bug 1825460: OpenStack: Replace remote_group_id with remote_ip_prefix
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#3454 Add instructions for UPI install on Power
  docs/user/power/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm

#3462 Dockerfile.upi.ci: Add GCP UPI required binaries.
  images/installer/Dockerfile.upi.ci
Labels: approved, bugzilla/valid-bug, lgtm

#3487 [fcos] add a new upstream community operator source
  data/data/manifests/openshift/community-operators.yaml
  data/data/manifests/openshift/upstream-community-operators.yaml
  pkg/asset/templates/content/openshift/community-operators.go
Labels: approved, lgtm

#3429 Bug 1819492: vsphere upi and metal: terraform 0.12.x update, general updates and reorg
  images/installer/Dockerfile.upi.ci
  upi/metal/bootstrap/matchbox.tf
  upi/metal/bootstrap/outputs.tf
  upi/metal/bootstrap/packet.tf
  upi/metal/bootstrap/variables.tf
  upi/metal/config.tf
  upi/metal/main.tf
  upi/metal/outputs.tf
  upi/vsphere/cluster_domain/main.tf
  upi/vsphere/cluster_domain/outputs.tf
  upi/vsphere/cluster_domain/variables.tf
  upi/vsphere/folder/main.tf
  upi/vsphere/folder/output.tf
  upi/vsphere/folder/variables.tf
  upi/vsphere/host_a_record/main.tf
  upi/vsphere/host_a_record/outputs.tf
  upi/vsphere/host_a_record/variables.tf
  upi/vsphere/ipam/cidr_to_ip.sh
  upi/vsphere/ipam/main.tf
  upi/vsphere/ipam/outputs.tf
  upi/vsphere/ipam/variables.tf
  upi/vsphere/ipam/versions.tf
  upi/vsphere/lb/haproxy.service
  upi/vsphere/lb/haproxy.tmpl
  upi/vsphere/lb/main.tf
  upi/vsphere/lb/outputs.tf
  upi/vsphere/lb/variables.tf
  upi/vsphere/machine/ignition.tf
  upi/vsphere/machine/ip.tf
  upi/vsphere/machine/main.tf
  upi/vsphere/machine/output.tf
  upi/vsphere/machine/variables.tf
  upi/vsphere/main.tf
  upi/vsphere/resource_pool/main.tf
  upi/vsphere/resource_pool/output.tf
  upi/vsphere/resource_pool/variables.tf
  upi/vsphere/route53/main.tf
  upi/vsphere/route53/variables.tf
  upi/vsphere/variables.tf
  upi/vsphere/vm/ifcfg.tmpl
  upi/vsphere/vm/ignition.tf
  upi/vsphere/vm/main.tf
  upi/vsphere/vm/variables.tf
  upi/vsphere/vm/versions.tf
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#3495 Bug 1826739: openstack UPI: Fix step name
  upi/openstack/down-load-balancers.yaml
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm, platform/openstack

#3489 bug 1821932: cmd/openshift-install/gather: clarify location of log bundle
  cmd/openshift-install/gather.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#3501 Bug 1827070: openstack: Explain why awscli in the CI image
  images/openstack/Dockerfile.ci
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm, platform/openstack

#3483 Bug 1824426: tag primary OpenStack networks
  data/data/openstack/topology/private-network.tf
  pkg/destroy/openstack/openstack.go
  pkg/tfvars/openstack/openstack.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#3496 Bug 1823359: baremetal: update provisioning CR to quote strings
  data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#3481 [release-4.3] Bug 1825973: OpenStack: Replace remote_group_id with remote_ip_prefix
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#3500 Bug 1827067: openstack UPI: Server group name to match IPI
  upi/openstack/common.yaml
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm, platform/openstack

#3508 Bug 1826896: rhcos: bump RHCOS boot image to 44.81.202004250133-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3509 Bug 1826895: rhcos: bump RHCOS boot image to 44.81.202004250133-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3519 [FCOS] data/data/rhcos: Update to stable FCOS 20200407.3.0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, lgtm

#3440 Bug 1794839: Azure masters should correctly support service load balancers
  data/data/azure/main.tf
  data/data/azure/master/outputs.tf
  data/data/azure/master/variables.tf
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/public-lb.tf
Labels: approved, bugzilla/valid-bug, lgtm

#3503 Bug 1827667: openstack: Add jq to the CI image
  images/openstack/Dockerfile.ci
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3522 Bug 1826317: openstack docs: Add tagging as a requirement
  docs/user/openstack/README.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#3505 Bug 1827795: OpenStack: Replace remote_group_id with remote_ip_prefix
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack
