Repository openshift/installer, pull requests merged in 2020-10, with the labels that each got.

#4230 Bug 1882752: openstack BM: Remove MachineSet on separate subnet
  docs/user/openstack/deploy_baremetal_workers.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4228 Bug 1881703: Revert "Have the MCO manage the ignition stub config"
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4236 Bug 1876844: openstack UPI: Ignition token needs Glance access
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4235 [FCOS] Periodic rebase on master - Oct 02
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos.json
  docs/user/openstack/deploy_baremetal_workers.md
  docs/user/openstack/install_upi.md
  docs/user/ovirt/install_upi.md
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
  pkg/asset/installconfig/openstack/validvaluesfetcher.go
  pkg/asset/tls/mcscertkey.go
  pkg/destroy/openstack/openstack.go
  pkg/types/conversion/installconfig.go
  pkg/types/conversion/installconfig_test.go
  pkg/types/defaults/installconfig.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  upi/openstack/bootstrap.yaml
  upi/openstack/common.yaml
  upi/openstack/network.yaml
  upi/ovirt/create-templates-and-vms.yml
Labels: approved, lgtm

#4219 Bug 1878758: openstack UPI: Allow for no FIP or router
  docs/user/openstack/install_upi.md
  upi/openstack/bootstrap.yaml
  upi/openstack/down-bootstrap.yaml
  upi/openstack/inventory.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4227 Bug 1884558: do not use local cacert path in generated clouds.yaml
  pkg/asset/manifests/openshift.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4231 Bug 1876815: OpenStack: unset OS_CLOUD
  pkg/asset/installconfig/openstack/session.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4208 Docs: OpenStack: Remove mention of cluster failing to destroy
  docs/user/openstack/troubleshooting.md
Labels: approved, lgtm, platform/openstack

#4160 installer/pkg/quota/gcp/limits.go: fix minor typo in comment
  pkg/quota/gcp/limits.go
Labels: approved, lgtm

#4166 Fix json tag for GCP auth service account
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm, ok-to-test

#4241 Bump RHCOS images for Ignition entropy fix
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, lgtm

#4223 Bug 1777224: pkg/asset: metadata to depend on ignition
  pkg/asset/cluster/metadata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4237 Bug 1884435: vsphere - add delay if resolv.conf is not available; wait for dhcp
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4234 Bug 1882515: bump RHCOS images for Ignition entropy fix
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#4248 Bug 1882191: Add GODEBUG=x509ignoreCN=0 to systemd DefaultEnvironment
  data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env-godebug.conf.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4244 OpenStack: Rename lbFloatingIP to apiFloatingIP
  data/data/install.openshift.io_installconfigs.yaml
  data/data/openstack/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/conversion/installconfig.go
  pkg/types/conversion/installconfig_test.go
  pkg/types/openstack/platform.go
Labels: approved, lgtm, platform/openstack

#4214 openstack privileges documented
  docs/user/openstack/README.md
  docs/user/openstack/privileges.md
Labels: approved, lgtm

#4251 Updating ose-installer-artifacts builder & base images to be consistent with ART
  images/installer-artifacts/Dockerfile.rhel
Labels: approved, lgtm

#4252 Remove dead code
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/testutils_test.go
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/installconfig/installconfig_test.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/manifests/infrastructure.go
  pkg/destroy/aws/aws.go
  pkg/destroy/gcp/gcp.go
  pkg/terraform/exec/plugins/azureprivatedns/provider.go
  pkg/terraform/exec/plugins/azureprivatedns/tags.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate_test.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/containerservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/dedicatedhostgroups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/dedicatedhosts.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/diskencryptionsets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/galleries.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/galleryapplications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/galleryapplicationversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/galleryimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/galleryimageversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/loganalytics.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/proximityplacementgroups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachinescalesetvmextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachinesizes.go
  vendor/modules.txt
Labels: approved, lgtm

#4250 Updating ose-installer builder & base images to be consistent with ART
  images/installer/Dockerfile.ci
Labels: approved, lgtm

#4238 Bug 1884691: types: allow manual cred mode for gcp and azure
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4254 Bug 1874248: types/vsphere/validation: ensure vcenter is all lower case
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4247 [FCOS] Update FCOS to 32.20200923.3.0
  data/data/fcos-amd64.json
  data/data/fcos.json
Labels: approved, lgtm

#4261 openstack: Bump Ansible to 2.9 in UPI
  docs/user/openstack/install_upi.md
  images/openstack/Dockerfile.ci
Labels: approved, lgtm

#4262 Bug 1887525: baremetal: Wait for master-bmh-update script to succeed
  data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3964 OpenStack: add clusterOSImage validations
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
  vendor/github.com/gophercloud/utils/openstack/imageservice/v2/images/utils.go
  vendor/modules.txt
Labels: approved, lgtm, platform/openstack

#4259 install-complete: provide troubleshooting info when operators fail
  cmd/openshift-install/create.go
  cmd/openshift-install/waitfor.go
Labels: approved, lgtm

#4270 destroy: return aws resources that could not be deleted
  pkg/destroy/aws/aws.go
Labels: approved, lgtm

#4271 Bug 1888671: openstack: Document Cinder's ignore-volume-az
  docs/user/openstack/README.md
  docs/user/openstack/known-issues.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4092 OpenStack UPI: Custom API and Ingress vip addresses
  upi/openstack/bootstrap.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
Labels: approved, lgtm, ok-to-test, platform/openstack

#4269 Bug 1878900: openstack: Fix error messages in flavor validation
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4277 OpenStack: remove legacy image validation
  pkg/tfvars/openstack/openstack.go
Labels: approved, lgtm, platform/openstack

#4278 Update README.md - Broken Link - Spelling
  upi/ovirt/README.md
Labels: approved, lgtm, ok-to-test

#4274 vSphere: Update dockerfile removing certificate
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm

#4279 Bug 1882649: Determine Glance disk format based on file extension
  pkg/tfvars/openstack/rhcos_image.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4290 openstack: Add a new team member
  OWNERS_ALIASES
Labels: approved, lgtm, retest-not-required-docs-only

#4282 cmd: split newlines in logrus stderr output to new entry
  cmd/openshift-install/create.go
  cmd/openshift-install/log.go
  cmd/openshift-install/main.go
Labels: approved, lgtm

#4273 Bug 1886553: GCP - Increase worker NAT min ports
  data/data/gcp/network/network.tf
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4281 Bug 1877116: aws: use file for bootstrap ign when uploading to s3
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  data/data/config.tf
  pkg/tfvars/tfvars.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4288 Bug 1889852: add new AWS regions
  data/data/rhcos-amd64.json
  data/data/rhcos.json
  pkg/rhcos/ami_regions.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4287 bug 1870728: pkg/asset/ignition/bootstrap: Display warning if certificates are expired
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4012 Bug 1836017: Configure haproxy to check /readyz
  upi/vsphere/lb/haproxy.tmpl
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4294 go.mod Update
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#4293 [FCOS] update base FCOS to 32.20201004.3.0
  data/data/fcos-amd64.json
  data/data/fcos.json
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm

#4258 pkg/asset/installconfig/aws: Validate install-config instance type
  pkg/asset/installconfig/aws/instancetypes.go
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
Labels: approved, lgtm

#4291 openstack: Update CI base image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm

#4196 Bug 1880443: allow providing client options when generating OpenStack MachineSets
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/asset/machines/worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4297 install-approvers: add staebler
  OWNERS_ALIASES
Labels: approved, lgtm, retest-not-required-docs-only

#4285 Bug 1889267: oVirt, increase terraform template and release image timeout to 20m
  data/data/ovirt/template/main.tf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4272 Code cleanup and optimizations
  cmd/openshift-install/migrate/azure/migrate.go
  pkg/asset/ignition/node.go
  pkg/asset/installconfig/aws/subnet.go
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/session.go
  pkg/asset/installconfig/ovirt/credentials.go
  pkg/asset/kubeconfig/kubeconfig.go
  pkg/destroy/aws/aws.go
  pkg/destroy/azure/azure.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/instancegroup.go
  pkg/destroy/openstack/openstack.go
  pkg/gather/ssh/ssh.go
  pkg/metrics/timer/timer_test.go
  pkg/migrate/azure/privatedns.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/baremetal/rootdevice.go
  pkg/types/conversion/installconfig.go
Labels: approved, lgtm

#4311 oVirt: change owners
  OWNERS_ALIASES
Labels: approved, lgtm

#4320 Bug 1888378: [Azure][Destroy] Check if resource group exists
  pkg/destroy/azure/azure.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, do-not-merge/hold, lgtm

#4317 bug 1891702: pkg/asset/ignition/bootstrap: exit loop if pem.Decode() fails
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4315 aws: ensure users set ami id for c2s regions
  pkg/types/aws/validation/machinepool.go
Labels: approved, lgtm

#4316 aws: block cluster destroy in c2s region
  pkg/destroy/aws/aws.go
Labels: approved, lgtm

#4318 [CORS-1577] Add Encryption Key reference to GCP MachinePool API
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/machinepools.go
Labels: approved, lgtm

#4322 Revert "[Azure][Destroy] Check if resource group exists"
  pkg/destroy/azure/azure.go
Labels: approved, lgtm

#4150 Bug 1877374: Remove unused bootstrap etcd cert generation mechanism
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4328 openstack: fixup markdown
  docs/user/openstack/README.md
  docs/user/openstack/deploy_baremetal_workers.md
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, platform/openstack

#4331 Bug 1866925: display Azure destroy auth error
  pkg/destroy/azure/azure.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4327 Bug 1878374: Adding more nitro and the AMD instance types (AWS, UPI)
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
