Repository openshift/installer, pull requests merged in 2020-03, with the labels that each got.

#3160 Support xz-encoded images
  go.mod
  go.sum
  pkg/tfvars/internal/cache/cache.go
  vendor/github.com/h2non/filetype/LICENSE
  vendor/github.com/h2non/filetype/matchers/application.go
  vendor/github.com/h2non/filetype/matchers/archive.go
  vendor/github.com/h2non/filetype/matchers/audio.go
  vendor/github.com/h2non/filetype/matchers/document.go
  vendor/github.com/h2non/filetype/matchers/font.go
  vendor/github.com/h2non/filetype/matchers/image.go
  vendor/github.com/h2non/filetype/matchers/isobmff/isobmff.go
  vendor/github.com/h2non/filetype/matchers/matchers.go
  vendor/github.com/h2non/filetype/matchers/video.go
  vendor/github.com/h2non/filetype/types/defaults.go
  vendor/github.com/h2non/filetype/types/mime.go
  vendor/github.com/h2non/filetype/types/split.go
  vendor/github.com/h2non/filetype/types/type.go
  vendor/github.com/h2non/filetype/types/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3203 OpenStack: UPI: Glance for storing ignition configs
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, size/M

#3206 Bug 1786363: filter out unsupported regions in Azure
  pkg/asset/installconfig/azure/azure.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/deploymentoperations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/deployments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/groups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/providers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/resources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/tags.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources/version.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#3209 [fcos] bootstrap: check files for duplicates before appending
  pkg/asset/ignition/bootstrap/bootstrap.go
Labels: approved, lgtm, size/XS

#3214 Bug 1809187: OpenStack: return an error if load balancer deletion fails
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#3219 Fix invocation of log.Errorf
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, size/L

#3196 Bug 1713336: aws destroy: show warnings when things fail to delete after 5 minutes.
  pkg/destroy/aws/aws.go
  pkg/destroy/aws/errortracker.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#3227 aws: update the IAM role policy to remove hard coded partition ID
  data/data/aws/bootstrap/main.tf
  data/data/aws/iam/main.tf
  data/data/aws/master/main.tf
Labels: approved, lgtm, size/S

#3226 Bug 1809780: OpenStack: pass all CA from cert bundle to bootstrap ign…
  pkg/tfvars/openstack/bootstrap_ignition.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/S

#3223 Bug 1809691: baremetal: block 547/udp for DHCPv6 as well
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, bugzilla/valid-bug, lgtm, platform/baremetal, size/XS

#3234 Bug 1810196: Use RPM for UPI dependencies
  docs/user/openstack/install_upi.md
  upi/openstack/requirements.txt
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/M

#3207 [release-4.3] Bug 1808482: OpenStack: allow to overwrite default os image in the install config
  docs/user/openstack/customization.md
  pkg/asset/rhcos/image.go
  pkg/types/openstack/platform.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack, size/M

#3237 baremetal: update docs to indicate stable IP's are required
  docs/user/metal/install_ipi.md
Labels: approved, lgtm, platform/baremetal, size/XS

#3255 Replace --config with --kubeconfig for `oc` command
  docs/user/customization.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#3096 Bug 1801446: Move permissions check to cluster asset
  pkg/asset/cluster/cluster.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/platformpermscheck.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#3213 [release-4.3] Bug 1808095: Bump survey vendor for panic
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/AlecAivazis/survey.v1/multiselect.go
  vendor/gopkg.in/AlecAivazis/survey.v1/select.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#3239 Bug 1809820: gcp/platform: Allow periods in the cluster name.
  pkg/asset/installconfig/clustername.go
  pkg/types/azure/validation/platform.go
  pkg/types/gcp/validation/platform.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#3240 OpenStack: Fail early when boostrap ignition shim is to big
  pkg/tfvars/openstack/bootstrap_ignition.go
Labels: approved, lgtm, platform/openstack, size/XS

#3249 gather: ensure gather data is all in one directory
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, lgtm, size/XS

#3257 data/data/rhcos.json: Update bootimage to 44.81.202003062006-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, lgtm, size/L

#3262 terraform-provider-vsphere: Switch to v1.16.2 from fork
  go.mod
  go.sum
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/config.go
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/host_port_group_structure.go
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/helper/envbrowse/environment_browser_helper.go
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/helper/provider/provider_helper.go
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/helper/spbm/spbm_helper.go
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/resource_vsphere_host_port_group.go
  vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/virtual_machine_guest_structure.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3261 Bug 1794313: Some cluster operators fail to come up because RHV CA is not trusted by a pod
  data/data/manifests/openshift/cloud-creds-secret.yaml.template
  pkg/asset/installconfig/ovirt/config.go
  pkg/asset/installconfig/ovirt/credentials.go
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/template.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#3264 [Release 4.3] Bug 1811154: validation: Allow periods in gcp and azure cluster names.
  pkg/asset/installconfig/clustername.go
  pkg/types/gcp/validation/platform.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#3254 Bug 1810489: Ignore 401 error when deleting containers
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/S

#3210 Installs upi support on openstack-installer image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, platform/openstack, size/XS

#3253 Bug 1810916: openstack UPI: Adapt the script to older Ansible
  upi/openstack/04_control-plane.yaml
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack, size/M

#3272 Add adduarte to openstack approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3265 etcd: remove etcd DNS entries because etcd no longer uses DNS
  data/data/aws/main.tf
  data/data/aws/route53/base.tf
  data/data/aws/route53/variables.tf
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/main.tf
  data/data/bootstrap/baremetal/README.md
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/gcp/dns/base.tf
  data/data/gcp/dns/variables.tf
  data/data/gcp/main.tf
  data/data/libvirt/main.tf
Labels: approved, lgtm, platform/baremetal, size/L

#3271 Bug 1803926: bump RHCOS boot image to 44.81.202003110027-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#3279 baremetal: Add nss mock, ssh to Dockerfile
  images/baremetal/Dockerfile.ci
Labels: approved, lgtm, size/XS

#3287 data/manifests/bootkube/cvo-overrides: Bump default to stable-4.5
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, size/XS

#3285 OpenStack: reuse the existing function to get glance public URL
  pkg/tfvars/openstack/openstack.go
Labels: approved, lgtm, platform/openstack, size/S

#3274 Bug 1812599: bump RHCOS boot images to 43.81.202003111353.0
  data/data/rhcos.json
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#2574 gcp upi: split templates to simplify shared vpc workflow.
  docs/user/gcp/install_upi.md
  upi/gcp/02_dns.py
  upi/gcp/02_lb_ext.py
  upi/gcp/03_firewall.py
  upi/gcp/03_iam.py
  upi/gcp/04_bootstrap.py
Labels: approved, lgtm, size/L

#3290 Bug 1809921: Openstack UPI: Document use with Self-signed cert
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3289 images/baremetal: remove nss package as it's no longer needed
  images/baremetal/Dockerfile.ci
Labels: approved, lgtm, platform/baremetal, size/XS

#3301 images/baremetal: make /etc/passwd writeable
  images/baremetal/Dockerfile.ci
Labels: approved, lgtm

#3295 permissions.go: configure crendential check with installer session
  go.mod
  go.sum
  pkg/asset/installconfig/aws/permissions.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/aws/client.go
  vendor/modules.txt
Labels: approved, lgtm

#3247 bug 1805251: Master azure terraform address prefixes
  go.mod
  go.sum
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/resource_arm_loadbalancer.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/resource_arm_virtual_network.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#3270 gcp upi: enable internal load balancers
  docs/user/gcp/install_upi.md
  upi/gcp/01_vpc.py
  upi/gcp/02_lb_ext.py
  upi/gcp/02_lb_int.py
  upi/gcp/03_firewall.py
Labels: approved, lgtm, size/XL

#3298 Bug 1810916: openstack UPI: servers in group
  upi/openstack/04_control-plane.yaml
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3293 AWS: replace aws copy for encryption with encrypted EBS volumes
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/master/variables.tf
  data/data/aws/variables-aws.tf
  docs/user/aws/customization.md
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/aws/machines.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/machinepool.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#3296 Bug 1813822: Openstack UPI: Document use with Self-signed cert
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#3311 Docs: stop using deprecated parameters
  docs/user/customization.md
Labels: approved, lgtm

#3282 [release 4.4] Bug 1813004: etcd: remove etcd DNS entries because etcd no longer uses DNS
  data/data/aws/main.tf
  data/data/aws/route53/base.tf
  data/data/aws/route53/variables.tf
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/main.tf
  data/data/bootstrap/baremetal/README.md
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/gcp/dns/base.tf
  data/data/gcp/dns/variables.tf
  data/data/gcp/main.tf
  data/data/libvirt/main.tf
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/baremetal, size/L

#3268 VSphere: populate bootstrap dhclient.conf if user provides VIPs.
  data/data/bootstrap/vsphere/OWNERS
  data/data/bootstrap/vsphere/files/etc/dhcp/dhclient.conf.template
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/vsphere/OWNERS
  pkg/asset/ignition/bootstrap/vsphere/template.go
Labels: approved, lgtm, size/M

#3308 aws: allow users to provide AMI for each machine pool
  docs/user/aws/customization.md
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/aws/machinepool.go
Labels: approved, lgtm

#3313 [release-4.4] Bug 1808969: azure - vendor update to support multiple prefixes
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  pkg/terraform/exec/plugins/vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_loadbalancer.go
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_network.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3309 gcp upi: add bootstrap to instance group
  docs/user/gcp/install_upi.md
  upi/gcp/04_bootstrap.py
Labels: approved, lgtm

#3269 Bug 1808464: filter out unsupported regions in Azure
  Gopkg.lock
  pkg/asset/installconfig/azure/azure.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/deploymentoperations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/deployments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/groups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/providers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/resources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/tags.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-03-01/resources/version.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#3321 Add documentation for virtualmedia
  docs/user/metal/install_ipi.md
Labels: approved, lgtm

#3322 [FCOS] ovirt: Ask for the CA pem content ovirt API
  data/data/manifests/openshift/cloud-creds-secret.yaml.template
  pkg/asset/installconfig/ovirt/config.go
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/template.go
Labels: approved, lgtm

#3250 data: Tune all cloud load balancers to have consistent intervals
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/public-lb.tf
  data/data/gcp/network/lb-private.tf
  data/data/gcp/network/lb-public.tf
Labels: approved, lgtm, size/S

#3326 OpenStack: remove 'region' from the examples
  docs/user/openstack/customization.md
Labels: approved, lgtm

#3232 baremetal: platform host validations
  go.mod
  go.sum
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  vendor/github.com/go-playground/locales/.gitignore
  vendor/github.com/go-playground/locales/.travis.yml
  vendor/github.com/go-playground/locales/LICENSE
  vendor/github.com/go-playground/locales/README.md
  vendor/github.com/go-playground/locales/currency/currency.go
  vendor/github.com/go-playground/locales/go.mod
  vendor/github.com/go-playground/locales/go.sum
  vendor/github.com/go-playground/locales/logo.png
  vendor/github.com/go-playground/locales/rules.go
  vendor/github.com/go-playground/universal-translator/.gitignore
  vendor/github.com/go-playground/universal-translator/.travis.yml
  vendor/github.com/go-playground/universal-translator/LICENSE
  vendor/github.com/go-playground/universal-translator/README.md
  vendor/github.com/go-playground/universal-translator/errors.go
  vendor/github.com/go-playground/universal-translator/go.mod
  vendor/github.com/go-playground/universal-translator/go.sum
  vendor/github.com/go-playground/universal-translator/import_export.go
  vendor/github.com/go-playground/universal-translator/logo.png
  vendor/github.com/go-playground/universal-translator/translator.go
  vendor/github.com/go-playground/universal-translator/universal_translator.go
  vendor/github.com/go-playground/validator/v10/.gitignore
  vendor/github.com/go-playground/validator/v10/.travis.yml
  vendor/github.com/go-playground/validator/v10/LICENSE
  vendor/github.com/go-playground/validator/v10/Makefile
  vendor/github.com/go-playground/validator/v10/README.md
  vendor/github.com/go-playground/validator/v10/baked_in.go
  vendor/github.com/go-playground/validator/v10/cache.go
  vendor/github.com/go-playground/validator/v10/doc.go
  vendor/github.com/go-playground/validator/v10/errors.go
  vendor/github.com/go-playground/validator/v10/field_level.go
  vendor/github.com/go-playground/validator/v10/go.mod
  vendor/github.com/go-playground/validator/v10/go.sum
  vendor/github.com/go-playground/validator/v10/logo.png
  vendor/github.com/go-playground/validator/v10/regexes.go
  vendor/github.com/go-playground/validator/v10/struct_level.go
  vendor/github.com/go-playground/validator/v10/translations.go
  vendor/github.com/go-playground/validator/v10/util.go
  vendor/github.com/go-playground/validator/v10/validator.go
  vendor/github.com/go-playground/validator/v10/validator_instance.go
  vendor/github.com/leodido/go-urn/.gitignore
  vendor/github.com/leodido/go-urn/.travis.yml
  vendor/github.com/leodido/go-urn/LICENSE
  vendor/github.com/leodido/go-urn/README.md
  vendor/github.com/leodido/go-urn/go.mod
  vendor/github.com/leodido/go-urn/go.sum
  vendor/github.com/leodido/go-urn/machine.go
  vendor/github.com/leodido/go-urn/machine.go.rl
  vendor/github.com/leodido/go-urn/makefile
  vendor/github.com/leodido/go-urn/urn.go
  vendor/modules.txt
Labels: approved, lgtm, platform/baremetal, size/XXL

#3330 images/baremetal: save rhcos.json in container image
  images/baremetal/Dockerfile.ci
Labels: approved, lgtm

#3327 Add vCenter CA to UPI CI image.
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm

#3319 Bug 1814593: OpenStack: Allow destroying cluster without trunk ports
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3303 openstack: soft-anti-affinity policy for CP
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/README.md
  go.mod
  go.sum
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/destroy/openstack/openstack.go
  pkg/destroy/openstack/register.go
  pkg/tfvars/openstack/openstack.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, lgtm, platform/openstack

#3328 Bug 1815133: osp UPI machineset OS image name
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3292 Add AWS CLI to UPI image.
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm

#3344 [fcos] ignition.Config Spec v3 to runtime.RawExtension conversion
  data/data/bootstrap/gcp/files/usr/local/bin/gcp-routes.sh
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/machine/node.go
  pkg/asset/ignition/machine/worker.go
  pkg/asset/ignition/node.go
  pkg/asset/machines/machineconfig/authorizedkeys.go
  pkg/asset/machines/machineconfig/fips.go
  pkg/asset/machines/machineconfig/hyperthreading.go
  pkg/asset/machines/machineconfig/manifest.go
  pkg/asset/machines/master.go
  pkg/asset/machines/master_test.go
  pkg/asset/machines/worker.go
  pkg/asset/machines/worker_test.go
  pkg/tfvars/openstack/bootstrap_ignition.go
  vendor/github.com/clarketm/json/LICENSE
  vendor/github.com/clarketm/json/README.md
  vendor/github.com/clarketm/json/decode.go
  vendor/github.com/clarketm/json/encode.go
  vendor/github.com/clarketm/json/fold.go
  vendor/github.com/clarketm/json/fuzz.go
  vendor/github.com/clarketm/json/indent.go
  vendor/github.com/clarketm/json/scanner.go
  vendor/github.com/clarketm/json/stream.go
  vendor/github.com/clarketm/json/tables.go
  vendor/github.com/clarketm/json/tags.go
  vendor/github.com/coreos/ignition/v2/config/merge/merge.go
  vendor/github.com/coreos/ignition/v2/config/v3_0/config.go
  vendor/github.com/coreos/vcontext/path/path.go
  vendor/github.com/coreos/vcontext/validate/validate.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/machineconfig.deepcopy.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/register.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/types.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#3325 Bug 1815551: images/baremetal: make /etc/passwd writeable and add SSH client
  images/baremetal/Dockerfile.ci
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3329 Bug 1812950: generate metadata before tfvars
  pkg/asset/targets/targets.go
Labels: approved, bugzilla/valid-bug, lgtm

#3355 Bug 1816995: OpenStack: create server group only once
  pkg/asset/machines/openstack/machines.go
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3356 openstack: Detail the clouds.yaml cacert option
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack

#3273 OpenStack: support "file" scheme for custom os image urls
  docs/dev/openstack/customization.md
  docs/user/openstack/customization.md
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/platform.go
Labels: approved, lgtm, size/M

#3349 [FCOS] Update initial FCOS images to 31.20200310.3.0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, lgtm

#3364 Update Kuryr known limitations
  docs/user/openstack/kuryr.md
Labels: approved, lgtm

#3233 Bug 1818140: Backport adding groundwork for multi-arch images
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  docs/user/customization.md
  hack/update-rhcos-bootimage.py
  pkg/asset/installconfig/installconfig_test.go
  pkg/asset/manifests/operators_test.go
  pkg/asset/rhcos/bootstrap_image.go
  pkg/asset/rhcos/image.go
  pkg/rhcos/ami.go
  pkg/rhcos/azure.go
  pkg/rhcos/builds.go
  pkg/rhcos/gcp.go
  pkg/rhcos/openstack.go
  pkg/rhcos/qemu.go
  pkg/terraform/exec/plugins/Gopkg.lock
  pkg/terraform/exec/plugins/Gopkg.toml
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/coreos_ignition_def.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
  pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
  pkg/types/defaults/machinepools.go
  pkg/types/defaults/machinepools_test.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
  pkg/types/validation/machinepools_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#3367 [FCOS] cvo-overrides.yaml: point OKD releases to release-controller
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm

#3370 Bug 1818590: openstack UPI fix order of steps
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3368 [fcos] vSphere UPI: use IPs as node names
  upi/vsphere/machine/ignition.tf
Labels: approved, lgtm

#3377 Bug 1814651: os UPI known issues: stale resources
  docs/user/openstack/install_upi.md
  docs/user/openstack/known-issues.md
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3278 GCP UPI: document how to install into a Shared VPC
  docs/user/gcp/install_upi.md
Labels: approved, lgtm, size/XL

#3342 vsphere ipi: set vm name to extra config - guestinfo.hostname
  data/data/vsphere/bootstrap/main.tf
  data/data/vsphere/master/ignition.tf
  data/data/vsphere/master/main.tf
Labels: approved, lgtm

#3315 gcp upi: document how to tag the masters and workers
  docs/user/gcp/install_upi.md
Labels: approved, lgtm

#3384 OpenStack: Docs: Fix a typo in the property name
  docs/user/openstack/customization.md
Labels: approved, lgtm, platform/openstack

#3318 Bug 1819132: Convert ansible module to openstackcli
  docs/user/openstack/install_upi.md
  upi/openstack/01_security-groups.yaml
  upi/openstack/02_network.yaml
  upi/openstack/03_bootstrap.yaml
  upi/openstack/04_control-plane.yaml
  upi/openstack/05_compute-nodes.yaml
  upi/openstack/down-01_security-groups.yaml
  upi/openstack/down-02_network.yaml
  upi/openstack/down-04_control-plane.yaml
  upi/openstack/down-05_compute-nodes.yaml
  upi/openstack/down-06_load-balancers.yaml
  upi/openstack/inventory.yaml
  upi/openstack/library/os_create_subnet_pool.py
  upi/openstack/library/os_create_svc_subnet.py
  upi/openstack/library/os_delete_lb_resources.py
  upi/openstack/library/os_delete_network_resources.py
  upi/openstack/library/os_delete_ports_on_router.py
  upi/openstack/library/os_tag.py
  upi/openstack/library/os_trunk.py
Labels: approved, bugzilla/valid-bug, lgtm, platform/openstack

#3359 Bug 1817201: Fix intermittent deprovision loop on NoSuchHostedZone error
  pkg/destroy/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm

#3363 baremetal: Validate os images exist
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, lgtm
