Repository openshift/installer, pull requests merged in 2020-07, with the labels that each got.

#3717 libvirt: support using the file:// URI scheme for OS image overrides
  pkg/tfvars/libvirt/libvirt.go
Labels: approved, lgtm

#3829 [fcos] Bump go-ovirt
  go.mod
  go.sum
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/github.com/ovirt/go-ovirt/reader.go
  vendor/modules.txt
Labels: approved, lgtm

#3821 upi/vsphere: Make cidr_to_ip.sh more verbose
  upi/vsphere/ipam/cidr_to_ip.sh
Labels: approved, lgtm

#3832 [FCOS] cvo-overrides.yaml: update default channel
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm

#3827 [FCOS] update to 32.20200615.3.0
  data/data/fcos-amd64.json
  data/data/fcos.json
Labels: approved, lgtm

#3773 gcp: verify project services are enabled before install
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/installconfig/platformpermscheck.go
Labels: approved, lgtm

#3795 baremetal: Allow rootDeviceHints to override Host profiles
  docs/user/metal/install_ipi.md
  pkg/tfvars/baremetal/baremetal.go
  pkg/types/baremetal/platform.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/devicehints/devicehints.go
  vendor/modules.txt
Labels: approved, lgtm, platform/baremetal

#3839 [fcos] cvo-overrides.yaml: update upstream URL
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm

#3723 bump the minimum version for building installer to go 1.14
  data/data/install.openshift.io_installconfigs.yaml
  docs/dev/dependencies.md
  go.mod
  hack/build.sh
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-sec.sh
  hack/go-test.sh
  hack/go-vet.sh
  hack/verify-codegen.sh
  hack/verify-vendor.sh
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.ci.rhel7
  images/installer/Dockerfile.upi.ci
  images/libvirt/Dockerfile.ci
  images/mock/Dockerfile
  images/openstack/Dockerfile.ci
  vendor/modules.txt
Labels: approved, lgtm

#3848 Bug 1850417: data/manifests/bootkube/cvo-overrides: Bump default to stable-4.6
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3849 Bug 1854222: rhcos/amd64: Bump to 45.82.202007062333-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3845 ovirt: populate again ovirt ca bundle in yaml
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, lgtm

#3844 rhcos: Bump to 46.82.202007051540-0
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, lgtm

#3856 platformtests: Drop no-longer-used directory
  platformtests/README.md
Labels: approved, lgtm

#3853 Bug 1710981: Default AWS instance type to 'm5'
  docs/user/aws/limits.md
  pkg/asset/machines/master_test.go
  pkg/asset/machines/worker_test.go
  pkg/types/aws/defaults/platform.go
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3790 [FCOS] data/data/bootstrap/gcp: install openshift-gcp-routes on bootstrap node
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
  data/data/bootstrap/gcp/files/opt/libexec/openshift-gcp-routes.sh
  data/data/bootstrap/systemd/units/openshift-gcp-routes.service
Labels: approved, lgtm

#3866 Remove metal todo for install gather support
  docs/user/metal/install_ipi.md
Labels: approved, lgtm, platform/baremetal

#3850 vendor: update baremetal-operator for virtual media support
  go.mod
  go.sum
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/access.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ibmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/idrac.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ipmi.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go
  vendor/modules.txt
Labels: approved, lgtm, platform/baremetal

#3870 Pass down release-image to the MCO on bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#3840 Bug 1813354: OpenStack: Fix the cacert trustbundle parser
  pkg/tfvars/openstack/bootstrap_ignition.go
  pkg/tfvars/openstack/bootstrap_ignition_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3862 Bug 1853859: Add validations for IP inputs
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3768 Bug 1841135: baremetal: increase default provisioning dhcp range
  docs/user/metal/customization_ipi.md
  pkg/types/baremetal/defaults/platform.go
  pkg/types/baremetal/defaults/platform_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/baremetal

#3286 OpenStack: Deprecate TrunkSupport and OctaviaSupport in the config
  data/data/install.openshift.io_installconfigs.yaml
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  docs/user/openstack/customization.md
  docs/user/openstack/kuryr.md
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/openstack/validation/validvaluesfetcher.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/L

#3851 Baremetal: Re-arrange validations for provisioning network at cluster creation time
  pkg/asset/installconfig/baremetal/OWNERS
  pkg/asset/installconfig/baremetal/validation.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/types/baremetal/validation/libvirt.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, lgtm, platform/baremetal

#3842 [fcos] rebase july 11
  data/data/fcos-amd64.json
  data/data/fcos.json
  data/data/libvirt/main.tf
  data/data/libvirt/variables-libvirt.tf
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos.json
  pkg/tfvars/libvirt/libvirt.go
Labels: approved, lgtm

#3843 baremetal: Add example of rootDeviceHints usage
  docs/user/metal/install_ipi.md
Labels: approved, lgtm

#3877 [OpenStack] Set default values for octavia and trunk support tf vars
  data/data/openstack/variables-openstack.tf
Labels: approved, lgtm

#3816 OpenStack: stop using custom cloud loaders for realValidValuesFetcher
  pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
Labels: approved, lgtm

#3835 clean up the validations to improve readability and high level flow
  pkg/types/openstack/validation/platform.go
Labels: approved, lgtm, platform/openstack

#3883 ovirt: update documentation
  docs/user/ovirt/install_ipi.md
Labels: approved, lgtm

#3889 Bug 1856820: update boot images for RHCOS Secure Boot issue
  data/data/rhcos-amd64.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#3884 ovirt: update approvers list
  OWNERS_ALIASES
Labels: approved, lgtm

#3880 Bug 1848987: Add hint to switch username
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3868 ovirt: tag and remove tmp/bootstrap machines
  data/data/ovirt/bootstrap/main.tf
  data/data/ovirt/bootstrap/variables.tf
  data/data/ovirt/main.tf
  data/data/ovirt/template/outputs.tf
  data/data/ovirt/template/variables.tf
  data/data/ovirt/variables-ovirt.tf
  pkg/destroy/ovirt/destroyer.go
Labels: approved, lgtm

#3891 [FCOS] Download Azure image in the installer
  data/data/azure/main.tf
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm

#3872 ovirt: remove template from the deploy
  pkg/destroy/ovirt/destroyer.go
Labels: approved, lgtm

#3892 Bug 1857169: ovirt: Use NetworkManager instead of dhclient in bootstrap
  data/data/bootstrap/ovirt/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/ovirt/files/etc/dhcp/dhclient.conf
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#3893 Bug 1857188: OpenStack: skip container deletion if it was removed
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3847 docs/user/gcp/install_upi: Drop unused 'region' from compute
  docs/user/gcp/install_upi.md
Labels: approved, lgtm

#3863 Bug 1852545: Add ResourcePoolPath to machines in vsphere
  pkg/asset/machines/vsphere/machines.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3885 Bug 1854115: vendor: bump to fix tf panic on mac OS
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform/helper/wrappedstreams/streams.go
  vendor/github.com/hashicorp/terraform/helper/wrappedstreams/streams_other.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#3818 OpenStack: Deleting servers using tag-based filtering
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/masters/main.tf
  pkg/asset/machines/openstack/machines.go
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm

#3819 gcp: check quotas for GCP before creating cluster
  go.mod
  pkg/asset/cluster/cluster.go
  pkg/asset/quota/gcp/OWNERS
  pkg/asset/quota/gcp/gcp.go
  pkg/asset/quota/gcp/gcp_test.go
  pkg/asset/quota/quota.go
  pkg/quota/doc.go
  pkg/quota/gcp/gcp.go
  pkg/quota/gcp/gcp_test.go
  pkg/quota/gcp/limits.go
  pkg/quota/gcp/usage.go
  pkg/quota/quota.go
  pkg/quota/quota_test.go
  vendor/cloud.google.com/go/monitoring/apiv3/alert_policy_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/doc.go
  vendor/cloud.google.com/go/monitoring/apiv3/group_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/metric_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/notification_channel_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/path_funcs.go
  vendor/cloud.google.com/go/monitoring/apiv3/service_monitoring_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/uptime_check_client.go
  vendor/github.com/golang/protobuf/ptypes/struct/struct.pb.go
  vendor/github.com/golang/protobuf/ptypes/struct/struct.proto
  vendor/google.golang.org/api/serviceusage/v1beta1/serviceusage-api.json
  vendor/google.golang.org/api/serviceusage/v1beta1/serviceusage-gen.go
  vendor/google.golang.org/genproto/googleapis/api/distribution/distribution.pb.go
  vendor/google.golang.org/genproto/googleapis/api/label/label.pb.go
  vendor/google.golang.org/genproto/googleapis/api/launch_stage.pb.go
  vendor/google.golang.org/genproto/googleapis/api/metric/metric.pb.go
  vendor/google.golang.org/genproto/googleapis/api/monitoredres/monitored_resource.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/alert.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/alert_service.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/common.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/dropped_labels.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/group.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/group_service.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/metric.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/metric_service.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/mutation_record.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/notification.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/notification_service.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/service.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/service_service.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/span_context.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/uptime.pb.go
  vendor/google.golang.org/genproto/googleapis/monitoring/v3/uptime_service.pb.go
  vendor/google.golang.org/genproto/googleapis/type/calendarperiod/calendar_period.pb.go
  vendor/modules.txt
Labels: approved, lgtm

#3895 Bug 1847549: gcp - add new regions in us-west, asia-northeast, and asia-southeast
  pkg/types/gcp/validation/platform.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3860 Bug 1843587: baremetal: verify that provisioning IP's are not in DHCP range
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/baremetal

#3897 Bug 1857651: oVirt, add condition for non existing tmp-vm
  data/data/ovirt/template/outputs.tf
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#3807 baremetal: Remove any references to the DHCP chain
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm, platform/baremetal

#3820 aws: check quotas for services before creating cluster
  pkg/asset/quota/aws/OWNERS
  pkg/asset/quota/aws/aws.go
  pkg/asset/quota/aws/aws_test.go
  pkg/asset/quota/aws/instancetypes.go
  pkg/asset/quota/quota.go
  pkg/quota/aws/aws.go
  pkg/quota/aws/limits.go
Labels: approved, lgtm

#3864 OpenStack: get rid of ValidValuesFetcher
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/validation.go
  pkg/asset/installconfig/openstack/validvaluesfetcher.go
  pkg/types/openstack/validation/machinepool_test.go
  pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/openstack/validation/validvaluesfetcher.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
Labels: approved, lgtm

#3894 Bug 1857650: oVirt, fix incorrect template removal condition
  pkg/asset/cluster/ovirt/ovirt.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3903 Need to reset PasswordQuestionTemplate
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, lgtm

#3874 Bug 1848885: check if 404 returned before ask users questions
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3907 baremetal: populate TypeMeta for baremetal provider config
  pkg/asset/machines/baremetal/machines.go
Labels: approved, lgtm, platform/baremetal

#3122 validation: OVN requires a HostPrefix of 64 for IPv6 networks
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, size/S

#3916 asset/quota: warn and skip when all quota errors are type unknown
  pkg/asset/quota/quota.go
Labels: approved, lgtm

#3828 [fcos] images: use 4.5 as a base
  images/baremetal/Dockerfile.ci
  images/installer/Dockerfile.ci
  images/openstack/Dockerfile.ci
Labels: approved, lgtm

#3915 OpenStack: fix runtime error with machine pool validation
  pkg/asset/installconfig/openstack/validation/validation.go
Labels: approved, lgtm

#3911 Bug 1838682: ovirt: document ovirt-config.yaml
  docs/user/ovirt/install_ipi.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3855 Option to pass floating IP to ingress port
  data/data/install.openshift.io_installconfigs.yaml
  data/data/openstack/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/openstack/platform.go
Labels: approved, lgtm

#3908 Bug 1857924: ovirt: remove defer ovirtConfig.Save()
  pkg/asset/installconfig/ovirt/ovirt.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3928 Bug 1858705: assets/machines/worker.go: add vsphere provider scheme to load machinsets
  pkg/asset/machines/worker.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3925 Initial docs for ovirt/RHV UPI
  docs/user/ovirt/install_upi.md
Labels: approved, lgtm

#3822 OpenStack: Make externalnetwork and lbfloating ip optional
  data/data/install.openshift.io_installconfigs.yaml
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/topology/private-network.tf
  docs/user/openstack/customization.md
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/terraform/gather/openstack/ip.go
  pkg/types/openstack/platform.go
Labels: approved, lgtm, platform/openstack

#3777 data/data/bootstrap: prepend DNS VIP via NM script instead of dhclient
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/vsphere/files/etc/dhcp/dhclient.conf.template
Labels: approved, lgtm

#3909 Bug 1857945: ovirt: if TLS verify is disable raise a question to users
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3771 oVirt UPI: initial setup
  upi/ovirt/OWNERS
  upi/ovirt/README.md
Labels: approved, lgtm

#3890 OpenStack: Create SG rules in parallel
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
Labels: approved, lgtm, platform/openstack

#3933 [FCOS] bootstrap: reboot manually after pivot
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
Labels: approved, lgtm

#3930 ovirt: doc: Add TOC and oVirt logo to documentation
  docs/user/ovirt/images/oVirt-logo.png
  docs/user/ovirt/install_ipi.md
Labels: approved, lgtm

#3938 baremetal: Only set BMC secret reference in Hosts when BMC details are specified
  pkg/asset/machines/baremetal/hosts.go
Labels: approved, lgtm

#3942 Masters-gather: Include the full logs of failed units
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm

#3924 Ovirt upi basic installation
  upi/ovirt/README.md
  upi/ovirt/bootstrap.yml
  upi/ovirt/common-auth.yml
  upi/ovirt/create-templates-and-vms.yml
  upi/ovirt/inventory.yml
  upi/ovirt/masters.yml
  upi/ovirt/retire-bootstrap.yml
  upi/ovirt/retire-masters.yml
  upi/ovirt/retire-workers.yml
  upi/ovirt/workers.yml
Labels: approved, lgtm

#3919 types: add field to InstallConfig to force credentials mode
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/platformpermscheck.go
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#3809 baremetal: Prevent race condition when adding HardwareDetails
  data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
  pkg/asset/machines/baremetal/hosts.go
Labels: approved, lgtm, platform/baremetal

#3935 baremetal: create machines and machineset linked to cluster
  pkg/asset/machines/baremetal/machines.go
  pkg/asset/machines/baremetal/machinesets.go
Labels: approved, lgtm

#3946 use correct base URI for other azure cloud environments
  data/data/azure/main.tf
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/installconfig/azure/session.go
  pkg/asset/machines/azure/zones.go
  pkg/destroy/azure/azure.go
  pkg/migrate/azure/privatedns.go
Labels: approved, lgtm

#3947 Bug 1856467: upi/aws: add m5 instances to allowed list for upi templates
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3808 gcp: use GCP Image published by RHCOS instead of creating per cluster
  data/data/gcp/main.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/rhcos/builds.go
  pkg/rhcos/gcp.go
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm

#3940 Bug 1855345: ovirt: show more info about PEM file loaded
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3934 Bug 1857158: OpenStack: validate there is no . in the cluster name
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3959 vSphere UPI docs: clarify folder naming
  docs/user/vsphere/install_upi.md
Labels: approved, lgtm

#3879 Baremetal: Add default storage pool at /var/lib/libvirt/openshift-images
  data/data/baremetal/bootstrap/main.tf
  data/data/baremetal/bootstrap/variables.tf
  docs/user/metal/install_ipi.md
  pkg/destroy/baremetal/baremetal.go
Labels: approved, lgtm, platform/baremetal

#3936 destroy: means to obtain gcp blocked resources
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm

#3956 ovirt: docs - minimum permissions for installation
  docs/user/ovirt/install_ipi.md
Labels: approved, lgtm

#3958 pkg/asset/installconfig/openstack: Cleaner and Tested Validation Code
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/validate.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
Labels: approved, lgtm, platform/openstack

#3920 Azure: Allow use to provide an empty resource group for cluster
  data/data/azure/main.tf
  data/data/azure/variables-azure.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/azure/azure.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/openshift.go
  pkg/destroy/azure/azure.go
  pkg/explain/printer_test.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/metadata.go
  pkg/types/azure/platform.go
Labels: approved, lgtm

#3965 Bug 1861088: aws: skip quota checking for not supported regions
  pkg/asset/quota/quota.go
  pkg/quota/aws/limits.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#3762 Metrics: Add push client to push metrics to endpoint
  go.mod
  pkg/metrics/pushclient/pushclient.go
  pkg/metrics/pushclient/pushclient_test.go
  vendor/github.com/prometheus/client_golang/prometheus/push/push.go
  vendor/modules.txt
Labels: approved, lgtm

#3957 README: add oVirt UPI link
  README.md
Labels: approved, lgtm

#3910 Baremetal: Enable installer survey for baremetal platform
  pkg/asset/installconfig/baremetal/baremetal.go
  pkg/asset/installconfig/baremetal/host.go
  pkg/asset/installconfig/platform.go
  pkg/types/installconfig_baremetal.go
Labels: approved, lgtm, platform/baremetal

#3967 improve cloud info generation
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
Labels: approved, lgtm, platform/openstack

#3972 Ovirt Upi docs fix
  docs/user/ovirt/install_upi.md
Labels: approved, lgtm

#3941 Bug 1846125: deleting vsphere cluster tag after deleting the attached resources
  pkg/destroy/vsphere/vsphere.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3961 ovirt: fix typo in tfvars ovirt
  pkg/tfvars/ovirt/ovirt.go
Labels: approved, lgtm

#3953 Flavor validations
  pkg/asset/installconfig/openstack/validate.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
Labels: approved, lgtm, platform/openstack

#3973 Ovirt UPI: Start vms with async
  upi/ovirt/masters.yml
  upi/ovirt/workers.yml
Labels: approved, lgtm

#3952 baremetal: set the boot mode for hosts based on the input
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/metal/install_ipi.md
  go.mod
  go.sum
  pkg/asset/machines/baremetal/hosts.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go
  vendor/modules.txt
Labels: approved, lgtm, platform/baremetal

#3977 aws: add additionalTrustBundle to bootstrap ignition stub config
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/main.tf
  data/data/aws/variables-aws.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/aws/aws.go
  pkg/tfvars/aws/bootstrap_ignition.go
  pkg/tfvars/aws/bootstrap_ignition_test.go
Labels: approved, lgtm

#3950 Baremetal: Add diagnostic error message for ironic terraform errors
  go.mod
  go.sum
  pkg/terraform/diagnose.go
  pkg/terraform/diagnose_test.go
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/httpbasic/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/httpbasic/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/httpbasic/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/httpbasic/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/oauth1/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/provider.go
  vendor/modules.txt
Labels: approved, lgtm, platform/baremetal

#3969 baremetal: Make master-bmh-update script more robust
  data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
  data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service
Labels: approved, lgtm, platform/baremetal

#3970 OpenStack Validations and Doc Updates for Floating IPs
  docs/user/openstack/customization.md
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
Labels: approved, lgtm, platform/openstack

#3968 types: capitalize CredentialsMode values
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#3980 Bug 1858342: types: allow docker bridge network range except on libvirt
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#3992 ovirt: docs - add info about ovirt-credentials
  docs/user/ovirt/install_ipi.md
Labels: approved, lgtm

#3996 baremetal: ensure boot mode is set before introspection begins
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, lgtm
