Repository openshift/installer, pull requests merged in 2021-06, with the labels that each got.

#4964 Bump default bootstrap memory.
  data/data/libvirt/variables-libvirt.tf
Labels: approved, lgtm, ok-to-test

#4969 Bug 1965921: [oVirt] High performance VMs shouldn't be created with Existing policy
  go.mod
  go.sum
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4900 Bug 1949859: baremetal: stop provisioning services once control plane is deployed
  data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  data/data/bootstrap/baremetal/systemd/units/ironic.service
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4973 Bug 1966862: pattern removed from sed to prevent expansion
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#4965 Bug 1965182: update baremetal-operator to fix miss IPMI credentials
  go.mod
  go.sum
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, ok-to-test

#4952 Bug 1820238: delete manila shares and snapshots along with the cluster
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4976 Bug 1967623: oVirt: Fix password input
  pkg/asset/installconfig/ovirt/credentials.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4928 Bug 1963205: rhcos: Use ART redirector
  data/data/rhcos-aarch64.json
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4867 Bug 1952604: [baremetal] Fix port in external loadbalancer example config
  docs/user/metal/external_loadbalancer_ipi.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4980 /pkg/tfvars/vsphere: add OWNERS
  pkg/tfvars/vsphere/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#4982 Bug 1969578: manifests: don't use deprecated api in role-cloud-creds-secret-reader
  data/data/manifests/openshift/role-cloud-creds-secret-reader.yaml.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4984 Bug 1969601: manifests: link networking CRD from API
  data/data/manifests/openshift/cluster-networkconfig-crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4958 Bug 1970415: Document SR-IOV use case: using network with port security disabled
  docs/user/openstack/deploy_sriov_workers.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4938 bug 1925343: upi/metal: add more configuration options for bare metal
  upi/metal/bootstrap/packet.tf
  upi/metal/bootstrap/variables.tf
  upi/metal/config.tf
  upi/metal/main.tf
  upi/metal/terraform.tfvars.example
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4978 Bug 1955697: Revert "tfvars/vsphere: use explicit path for datacenter."
  pkg/tfvars/vsphere/vsphere.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4961 Bug 1956483: Bump boot images for RHCOS fixes
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4989 Bug 1946079: baremetal: pass IP_OPTIONS to os downloader
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4990 bug 1971068: Updating AWS instance types
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4833 doc/openstack: add a note about image registry in AZ
  docs/user/openstack/README.md
Labels: approved, lgtm, platform/openstack

#4899 fixing a link
  docs/dev/pinned-coreos.md
Labels: approved, lgtm, ok-to-test

#4934 docs/user/aws/install: Update cloud install links
  docs/user/aws/install.md
  docs/user/azure/install.md
  docs/user/gcp/install.md
  docs/user/vsphere/install.md
Labels: approved, lgtm

#4997 OWNERS: add more core team members as approvers
  OWNERS_ALIASES
Labels: approved

#4977 Bug 1962850: Bump RHCOS bootimages for various fixes
  data/data/rhcos-aarch64.json
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
  docs/dev/pinned-coreos.md
  hack/update-rhcos-bootimage.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, group-lead-approved, lgtm

#4946 Openstack IPI: Validate API and Ingress VIPs are not the same
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
Labels: approved, lgtm

#4807 Bug 1945467: aws: allow use of unknown regions in known partitions
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#4803 Bug 1929136: OpenStack: document Manila share mounting
  docs/user/openstack/connect_nodes_to_manila_network.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#5000 Bug 1971518: Try deleting associated trunk after port delete failure
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#4891 Add linux-amd64 binary to installer-artifacts
  images/installer-artifacts/Dockerfile.rhel
Labels: approved, lgtm

#4856 pkg/asset/installconfig/kubevirt: fix dropped error
  pkg/asset/installconfig/kubevirt/client.go
Labels: approved, lgtm, ok-to-test

#4748 azure: divide machine CIDR into 2 networks for subnets
  data/data/azure/vnet/common.tf
Labels: approved, lgtm

#4843 azure: don't use managed identity on ARO
  data/data/manifests/openshift/99_azure-cloud-provider-secret-getter-role.yaml
  data/data/manifests/openshift/99_azure-cloud-provider-secret-getter-rolebinding.yaml
  data/data/manifests/openshift/99_azure-cloud-provider-secret.yaml.template
  pkg/asset/machines/azure/machines.go
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/openshift.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/openshift/azure-cloud-provider-secret.go
  pkg/types/azure/platform.go
  pkg/types/azure/platform_aro.go
Labels: approved, lgtm

#4870 Add arm64 support
  hack/build.sh
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.ci.rhel7
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
  images/libvirt/Dockerfile.ci
  images/openstack/Dockerfile.ci
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/aws/platform.go
  pkg/asset/installconfig/aws/regions.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
  pkg/asset/machines/aws/instance_types.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/rhcos/image.go
  pkg/destroy/libvirt/libvirt.go
  pkg/rhcos/ami_regions_aarch64.go
  pkg/rhcos/ami_regions_generate.go
  pkg/rhcos/ami_regions_x86_64.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/defaults/platform.go
  pkg/types/aws/validation/machinepool.go
  pkg/types/defaults/machinepools.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig_test.go
  pkg/types/validation/machinepools.go
  pkg/version/version.go
Labels: approved, lgtm

#4937 OpenStack: Add Unit Tests for validation of platform.openstack.machineSubnet
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
Labels: approved, lgtm

#5004 Bug 1974598: OpenStack: Optimize cluster deletion
  pkg/destroy/openstack/openstack.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#5020 ibmcloud: fix struct field json
  pkg/types/clustermetadata.go
Labels: approved, lgtm

#5001 [SPLAT-211] vSphere: Switch from sockets to cores by default
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#4880 azure: removes dummy outbound service
  data/data/manifests/openshift/private-cluster-outbound-service.yaml
  pkg/asset/manifests/openshift.go
  pkg/asset/templates/content/openshift/private-cluster-outbound-service.go
Labels: approved, lgtm

#4849 doc/gcp: remove no-longer-needed etcd records
  docs/user/gcp/install_upi.md
Labels: approved, lgtm

#5030 .yamllint: ignore cluster-networkconfig-crd.yaml
  .yamllint
Labels: approved, lgtm

#5028 Bug 1975475: aws: block creation of bootstrap instance until ignition config is uploaded
  data/data/aws/bootstrap/main.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4879 azure: don't require BaseDomainResourceGroupName on ARO
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
Labels: approved, lgtm

#4953 kubevirt: removes dependency on a deprecated package
  go.mod
  go.sum
  pkg/asset/machines/kubevirt/machinesets.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#4789 azure: changes the way we get credentials
  pkg/asset/installconfig/azure/metadata.go
  pkg/asset/installconfig/azure/session.go
Labels: approved, lgtm

#5038 OWNERS: update vSphere-approvers
  OWNERS_ALIASES
Labels: approved, lgtm
