Repository openshift/installer, pull requests merged in 2021-01, with the labels that each got.

#4519 Bug 1911819: Fix docs/user/kubevirt/install-config.yaml to pass ./hack/yaml-lint.sh
  docs/user/kubevirt/install-config.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4486 Bug 1786314: bump gophercloud/utils
  go.mod
  go.sum
  vendor/github.com/gophercloud/utils/internal/util.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4511 Bug 1910070: Set termination_grace_period_seconds to 10 minutes
  data/data/kubevirt/masters/main.tf
  go.mod
  go.sum
  vendor/github.com/kubevirt/terraform-provider-kubevirt/kubevirt/schema/virtualmachineinstance/spec.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4521 Bug 1913151: KubeVirt user docs: change role example - add "update" verb to VM
  docs/user/kubevirt/role.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4498 Bug 1910127: ovirt: UPI doc improvements
  docs/user/ovirt/install_upi.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4522 Bug 1909587: openstack: Create Control plane nodes sequentially
  data/data/openstack/masters/main.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#4529 Bug 1914439: OpenStack Port Create Typo in SRIOV Docs
  docs/user/openstack/install_upi.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4520 [FCOS] Update FCOS to 33.20201214.3.1
  data/data/fcos-amd64.json
  data/data/fcos.json
Labels: approved, lgtm

#4528 Bug 1908583: Set same additional networks on Bootstrap as Control Plane
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4530 Bug 1908468: azure/validation: some memory values are float and not int
  pkg/asset/installconfig/azure/validation.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4554 Bug 1916505: AWS IPI: Add IPsec master-to-worker flows
  data/data/aws/vpc/sg-worker.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4426 Bug 1813949: ignore local env variables when we create a service client
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/session.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validvaluesfetcher.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/asset/machines/worker.go
  pkg/destroy/openstack/glance.go
  pkg/destroy/openstack/openstack.go
  pkg/tfvars/openstack/bootstrap_ignition.go
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/openstack/rhcos_image.go
  pkg/types/openstack/defaults/clientopts.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4557 [FCOS] pkg/asset/machines: include authentication setting for single master
  pkg/asset/machines/master.go
  pkg/asset/machines/singlemaster.go
Labels: approved, lgtm

#4508 Bug 1899161: openstack: consider volumes for storage requirements checks
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, platform/openstack

#4548 Bug 1916271: openstack known issues: ControlPlane anti-affinity
  docs/user/openstack/known-issues.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4551 Bug 1915998: Set Additional Control Plane Security Groups on Bootstrap Node
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  docs/user/openstack/customization.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4567 [fcos] Update FCOS to 33.20210104.3.0
  data/data/fcos-amd64.json
  data/data/fcos.json
Labels: approved, lgtm

#4518 Bug 1909502: pkg/asset/manifests: remove etcd records from proxy config
  pkg/asset/manifests/proxy.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4540 Bug 1915617: update boot images for various fixes
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4537 Bug 1915460: ovirt: validate cluster name during install
  pkg/asset/installconfig/clustername.go
  pkg/types/validation/installconfig.go
  pkg/validate/validate.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4552 Bug 1916373: upi: allow IPsec ports
  upi/aws/cloudformation/03_cluster_security.yaml
  upi/gcp/03_firewall.py
  upi/openstack/security-groups.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4562 Bug 1912828: Rebase on the latest terraform provider/go-ovirt
  go.mod
  go.sum
  pkg/asset/installconfig/ovirt/validation_test.go
  vendor/github.com/ovirt/go-ovirt/CHANGES.adoc
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/github.com/ovirt/go-ovirt/readers.go
  vendor/github.com/ovirt/go-ovirt/services.go
  vendor/github.com/ovirt/go-ovirt/types.go
  vendor/github.com/ovirt/go-ovirt/writers.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/data_source_ovirt_template.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/provider.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_affinity_group.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_cluster.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_disk.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_image_transfer.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go
  vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm_template.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4578 Fix Authentication manifest for SNO
  pkg/asset/machines/singlemaster.go
Labels: approved, kind/bug, lgtm, priority/critical-urgent

#4483 Bug 1907822: Don't panic on bad data in quota validations
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/quota/openstack/openstack.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4575 Bug 1916938: tolerate equal APIFloatingIP and LbFloatingIP
  pkg/types/conversion/installconfig.go
  pkg/types/conversion/installconfig_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4584 [FCOS] vsphere bootstrap: support systemd-resolved in NM prepender
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
Labels: approved, lgtm

#4583 Bug 1919072: AWS cloudformation change protocol from ESP to 50
  upi/aws/cloudformation/03_cluster_security.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#4566 Bug 1893117: terraform/vsphereprivate: ignore hosts in maintenance mode
  pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4577 Bug 1917101: UPI ovirt - remove RHCOS image from Network req
  docs/user/ovirt/install_upi.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4588 [FCOS] Rebase on release-4.6
  data/data/openstack/main.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/variables.tf
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
Labels: approved, lgtm

#4590 Bug 1920243: disable anonymous auth on bootstrap nodes
  data/data/bootstrap/systemd/units/kubelet.service.template
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4524 Bug 1810438: oVirt: Add missing piece for gathering bootstrap IP info
  cmd/openshift-install/gather.go
  pkg/terraform/gather/ovirt/ip.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#3620 maintenance: remove pools and volumes
  scripts/maintenance/virsh-cleanup.sh
Labels: approved, bugzilla/valid-bug, lgtm

#4589 Bug 1896218: remove GCP role bindings before service accounts
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/policybinding.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4599 Bug 1921655: OpenStack: fix error handling for cloudinfo
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4600 Bug 1921911: Revert "Merge pull request #4589 from patrickdillon/bz-1896218-gcp-se…
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/policybinding.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4602 Bug 1896218: remove GCP role bindings before service accounts
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/policybinding.go
  pkg/destroy/gcp/serviceaccount.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
