Repository openshift/installer, pull requests merged in 2021-03, with the labels that each got.

#4646 doc: openstack/IPI - Provider Networks
  docs/user/openstack/README.md
  docs/user/openstack/provider-network.png
  docs/user/openstack/provider_networks.md
Labels: approved, lgtm, platform/openstack

#4636 Bug 1880758: Replace description to a more meaningful one
  data/data/aws/bootstrap/main.tf
  data/data/aws/main.tf
  data/data/aws/master/main.tf
  data/data/aws/vpc/common.tf
  data/data/aws/vpc/sg-master.tf
  data/data/aws/vpc/sg-worker.tf
  data/data/azure/bootstrap/main.tf
  data/data/azure/main.tf
  data/data/azure/vnet/common.tf
  data/data/azure/vnet/nsg.tf
  data/data/gcp/bootstrap/common.tf
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/dns/base.tf
  data/data/gcp/iam/main.tf
  data/data/gcp/main.tf
  data/data/gcp/master/main.tf
  data/data/gcp/network/common.tf
  data/data/gcp/network/firewall.tf
  data/data/gcp/network/lb-private.tf
  data/data/gcp/network/lb-public.tf
  data/data/gcp/network/network.tf
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/topology/common.tf
  data/data/openstack/topology/private-network.tf
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/sg-worker.tf
  data/data/vsphere/bootstrap/main.tf
  data/data/vsphere/main.tf
  data/data/vsphere/master/main.tf
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4692 Bug 1932799: baremetal: always use API VIP for installer communication
  data/data/baremetal/main.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4687 Bug 1894774: openstack: Document setting affinity for workers
  docs/user/openstack/README.md
  docs/user/openstack/affinity.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, platform/openstack

#4606 Bug 1923038: OpenStack: cache cloud info
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4716 Bug 1924474: upgrade gogo/protobuf to v1.3.2 and k8s.io/api to v0.20.1
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/go/analysis/analysis.go
  vendor/golang.org/x/tools/go/analysis/diagnostic.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/analysis/validate.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/golang.org/x/tools/go/buildutil/fakecontext.go
  vendor/golang.org/x/tools/go/buildutil/tags.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4712 Adjust master-update.fcc to the new ceo render secret structure
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc
Labels: approved, lgtm

#4715 Bug 1926364: baremetal: update terraform diagnosis for API timeout
  pkg/terraform/diagnose.go
  pkg/terraform/diagnose_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4708 vsphere: Validate vcenter user input to match RFC standards
  pkg/asset/installconfig/vsphere/validation_test.go
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm

#4723 [ovirt]: Removed '0' from machineset name
  pkg/asset/machines/ovirt/machinesets.go
Labels: approved, lgtm, ok-to-test

#4681 cmd/openshift-install: fix dropped error
  cmd/openshift-install/gather.go
Labels: approved, lgtm, ok-to-test

#4481 openstack: add networking quota checks
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/quota/openstack/openstack.go
  pkg/asset/quota/quota.go
Labels: approved, lgtm, platform/openstack

#4702 Bug 1930240: baremetal: Set missing IP in clouds.yaml
  data/data/bootstrap/baremetal/files/opt/metal3/auth/clouds.yaml.template
  pkg/asset/ignition/bootstrap/baremetal/template.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/baremetal

#4691 Transition responsibility for CEO asset creation and placement
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/manifests/bootkube/etcd-ca-bundle-configmap.yaml.template
  data/data/manifests/bootkube/etcd-client-secret.yaml.template
  data/data/manifests/bootkube/etcd-metric-client-secret.yaml.template
  data/data/manifests/bootkube/etcd-metric-serving-ca-configmap.yaml.template
  data/data/manifests/bootkube/etcd-metric-signer-secret.yaml.template
  data/data/manifests/bootkube/etcd-namespace.yaml
  data/data/manifests/bootkube/etcd-service.yaml
  data/data/manifests/bootkube/etcd-serving-ca-configmap.yaml.template
  data/data/manifests/bootkube/etcd-signer-secret.yaml.template
  docs/user/customization.md
  docs/user/openstack/install_upi.md
  docs/user/ovirt/install_upi.md
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/manifests/operators.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/etcd-ca-bundle-configmap.go
  pkg/asset/templates/content/bootkube/etcd-client-secret.go
  pkg/asset/templates/content/bootkube/etcd-metric-client-secret.go
  pkg/asset/templates/content/bootkube/etcd-metric-serving-ca-configmap.go
  pkg/asset/templates/content/bootkube/etcd-metric-signer-secret.go
  pkg/asset/templates/content/bootkube/etcd-namespace.go
  pkg/asset/templates/content/bootkube/etcd-service.go
  pkg/asset/templates/content/bootkube/etcd-serving-ca-configmap.go
  pkg/asset/templates/content/bootkube/etcd-signer-secret.go
  pkg/asset/tls/etcd.go
  pkg/asset/tls/etcdmetrics.go
Labels: approved, lgtm

#4720 kubevirt platfrom validate permissions
  docs/user/kubevirt/role.yaml
  pkg/asset/installconfig/kubevirt/client.go
  pkg/asset/installconfig/kubevirt/mock/client_generated.go
  pkg/asset/installconfig/kubevirt/validation.go
  pkg/asset/installconfig/kubevirt/validation_test.go
  pkg/asset/installconfig/platformpermscheck.go
Labels: approved, lgtm

#4722 Bug 1936443: Revert "baremetal: send full ignition to masters"
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/baremetal

#4649 Add docs about issues on UPI with Kuryr
  docs/user/openstack/known-issues.md
Labels: approved, lgtm

#4695 Bug 1903055: Set default values to machine pools before validation
  pkg/asset/installconfig/openstack/validate.go
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
  pkg/asset/installconfig/openstack/validation/platform.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, platform/openstack

#4727 pkg/asset/cluster/aws: fix dropped error
  pkg/asset/cluster/aws/aws.go
Labels: approved, lgtm, ok-to-test

#4741 Bug 1937460: Update gophercloud module from master
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/quotas/results.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4594 [gcp] Change bootstrap ignition storage bucket access
  data/data/gcp/bootstrap/main.tf
Labels: approved, lgtm, tide/merge-method-squash

#4699 installconfig/aws: validate connectivity to service endpoints.
  pkg/asset/installconfig/aws/validation.go
Labels: approved, lgtm

#4740 Bug 1934123: generate glance url considering the region
  pkg/tfvars/openstack/openstack.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4745 Bug 1934557: bump RHCOS image for LUKS fix
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4734 Bug 1933414: openstack: Consistent port names
  data/data/openstack/topology/private-network.tf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, platform/openstack

#4762 docs/user/aws/customization: Fix KMS-key link format
  docs/user/aws/customization.md
Labels: approved, lgtm

#4764 Bug 1804230: fix broken ETCD link in user docs
  docs/user/ovirt/install_ipi.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4765 IPI-BAREMETAL: document how to use external LB for api/ingress traffic
  docs/user/metal/customization_ipi.md
  docs/user/metal/external_loadbalancer_ipi.md
Labels: approved, lgtm, platform/baremetal

#4757 Support configurable libvirt disk size
  pkg/tfvars/libvirt/libvirt.go
Labels: approved, lgtm

#4749 gcp: divide machine CIDR into 2 networks for subnets
  data/data/gcp/main.tf
  docs/user/gcp/install_upi.md
Labels: approved, lgtm

#4742 bootstrap: record progress of services
  data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/bootstrap-in-place.sh
  data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/install-to-disk.sh.template
  data/data/bootstrap/files/usr/local/bin/approve-csr.sh
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/bootstrap-service-record.sh
  data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/kubelet-pause-image.sh.template
  data/data/bootstrap/files/usr/local/bin/kubelet.sh
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
  data/data/bootstrap/files/usr/local/bin/report-progress.sh
  data/data/bootstrap/systemd/units/chown-gatewayd-key.service
  data/data/bootstrap/systemd/units/kubelet.service.template
  docs/dev/bootstrap_services.md
Labels: approved, lgtm

#4752 gcp: add kubernetes owned label to master machines
  data/data/gcp/main.tf
Labels: approved, lgtm

#4747 README: change install to create
  README.md
Labels: approved, lgtm, ok-to-test

#4709 Baremetal: Explicitly set watchAllNamespaces
  data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
Labels: approved, lgtm, platform/baremetal

#4769 asset/tls: fixes certkey unit test for Go >= 1.15
  pkg/asset/tls/certkey_test.go
Labels: approved, lgtm

#4774 Update owners with new Installer Team members
  OWNERS_ALIASES
Labels: approved, lgtm

#4754 Bug 1918469: Check if VIP IPs overlap with machine CIDR provided during vsphere installation
  pkg/asset/installconfig/vsphere/validation.go
  pkg/types/validation/installconfig.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4759 Bug 1939513: KubeVirt platform: Add the immediate request annotation to the source PVC
  data/data/kubevirt/datavolume/main.tf
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#4771 Enable forward compatibility with kcmo rendering of signing keypair
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#4717 Add resource filter that matches Label or ClusterID
  pkg/destroy/gcp/disk.go
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm

#4784 Dockerfile.upi.ci: Drop pip+pyopenssl installs
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm

#4779 Revert "Check if VIP IPs overlap with machine CIDR provided during vsphere installation"
  pkg/asset/installconfig/vsphere/validation.go
  pkg/types/validation/installconfig.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm

#4693 gather-bootstrap: Gather logs before bootstrap shuts down
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/bootstrap-cluster-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, lgtm

#4785 images: Add Dockerfile.upi.ci.rhel8
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm

#4778 Bug 1934557: RHCOS boot image bump for LUKS fixes
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos.json
  pkg/rhcos/ami_regions.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#4650 Validate HotplugVolumes feature gate in Kubevirt
  pkg/asset/installconfig/kubevirt/client.go
  pkg/asset/installconfig/kubevirt/mock/client_generated.go
  pkg/asset/installconfig/kubevirt/validation.go
  pkg/asset/installconfig/kubevirt/validation_test.go
  pkg/asset/installconfig/platformprovisioncheck.go
Labels: approved, lgtm

#4726 Bug 1931115: Azure: Check Azure disk Instance Type for PremiumIO Capabilities
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/worker.go
  pkg/types/azure/machinepool.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#4582 Add and use stream metadata for RHCOS, add openshift-install coreos print-stream-json
  cmd/openshift-install/coreos.go
  cmd/openshift-install/main.go
  data/data/rhcos-stream.json
  docs/dev/pinned-coreos.md
  docs/user/aws/install_upi.md
  docs/user/metal/customization_ipi.md
  docs/user/openstack/customization.md
  docs/user/overview.md
  go.mod
  go.sum
  hack/update-rhcos-bootimage.py
  pkg/asset/cluster/tfvars.go
  pkg/asset/rhcos/bootstrap_image.go
  pkg/asset/rhcos/image.go
  pkg/coreoscli/cmd.go
  pkg/rhcos/ami.go
  pkg/rhcos/azure.go
  pkg/rhcos/builds.go
  pkg/rhcos/gcp.go
  pkg/rhcos/openstack.go
  pkg/rhcos/qemu.go
  pkg/rhcos/vmware.go
  vendor/github.com/coreos/stream-metadata-go/LICENSE
  vendor/github.com/coreos/stream-metadata-go/arch/arch.go
  vendor/github.com/coreos/stream-metadata-go/stream/rhcos/rhcos.go
  vendor/github.com/coreos/stream-metadata-go/stream/stream.go
  vendor/github.com/coreos/stream-metadata-go/stream/stream_utils.go
  vendor/modules.txt
Labels: approved, lgtm

#4770 pkg/asset/cluster: fix dropped error
  pkg/asset/cluster/tfvars.go
Labels: approved, lgtm, ok-to-test

#4760 Inject CoreOS stream metadata as configmap via CVO manifest
  hack/build-coreos-manifest.go
  images/installer/Dockerfile.ci
Labels: approved, lgtm

#4786 Bug 1925216: Bump gophercloud utils
  go.mod
  go.sum
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/modules.txt
Labels: approved, lgtm, platform/openstack

#4793 installer/pkg/asset/installconfig/azure: fix dropped error
  pkg/asset/installconfig/azure/session.go
Labels: approved, lgtm, ok-to-test

#4592 data/bootstrap: Check if release image architecture matches host architecture
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
Labels: approved, lgtm

#4800 installer-create: Provide user friendly error messages during failures
  cmd/openshift-install/create.go
  cmd/openshift-install/waitfor.go
Labels: approved, lgtm

#4766 Fix ipv6/dual-stack validation with Azure
  data/data/azure/bootstrap/variables.tf
  data/data/azure/dns/dns.tf
  data/data/azure/dns/variables.tf
  data/data/azure/main.tf
  data/data/azure/master/variables.tf
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/outputs.tf
  data/data/azure/vnet/variables.tf
  pkg/tfvars/azure/azure.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm

#4801 Bug 1944268: aws: allow use of unknown regions in known partitions
  pkg/asset/installconfig/aws/validation.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
