Repository openshift/installer, pull requests merged in 2021-08, with the labels that each got.

#5121 Bug 1978213: openstack - relax value for minNetworkConstraint
  pkg/asset/quota/openstack/openstack.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#5097 Bug 1963132: Fix us-east4 Ashburn description
  pkg/types/gcp/validation/platform.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#5106 Bug 1977129: Remove runlevel label from openshift-kubevirt-infra
  data/data/manifests/bootkube/openshift-kubevirt-infra-namespace.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#5129 Bug 1989604: ibmcloud: GetVSIProfiles error handling
  pkg/asset/installconfig/ibmcloud/client.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#5133 Bug 1987845: openstack: relax quotas with Kuryr
  pkg/asset/quota/openstack/openstack.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#5117 Bug 1990617: Update fedora-coreos stream to 34.20210725.2.0
  data/data/fcos-stream.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5140 Bug 1989917: openstack: relax Security Group quotas
  pkg/asset/quota/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5139 Bug 1990206: Fix invalid UPI AWS instance type
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5145 Bug 1987845: openstack: relax port constrain by one
  pkg/asset/quota/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5051 Bug 1969651: bump RHCOS 4.8 boot images
  data/data/rhcos-aarch64.json
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#5127 Bug 1992876: gather: Add OKD specific journal logs
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5069 Bug 1992463: libvirt: bump default memory and cpus
  data/data/libvirt/variables-libvirt.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5144 Bug 1989973: Fix Azure typo
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/azure/customization.md
  pkg/explain/printer_test.go
  pkg/types/azure/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5116 Bug 1994103: ibmcloud: Support Terraform stages
  data/data/ibmcloud/bootstrap/common.tf
  data/data/ibmcloud/bootstrap/ignition.tf
  data/data/ibmcloud/bootstrap/main.tf
  data/data/ibmcloud/bootstrap/outputs.tf
  data/data/ibmcloud/bootstrap/variables.tf
  data/data/ibmcloud/cis/main.tf
  data/data/ibmcloud/main.tf
  data/data/ibmcloud/master/common.tf
  data/data/ibmcloud/master/main.tf
  data/data/ibmcloud/master/outputs.tf
  data/data/ibmcloud/master/variables.tf
  data/data/ibmcloud/network/cis/main.tf
  data/data/ibmcloud/network/cis/variables.tf
  data/data/ibmcloud/network/common.tf
  data/data/ibmcloud/network/image/main.tf
  data/data/ibmcloud/network/image/outputs.tf
  data/data/ibmcloud/network/image/variables.tf
  data/data/ibmcloud/network/main.tf
  data/data/ibmcloud/network/outputs.tf
  data/data/ibmcloud/network/vpc/lb-private.tf
  data/data/ibmcloud/network/vpc/lb-public.tf
  data/data/ibmcloud/network/vpc/outputs.tf
  data/data/ibmcloud/network/vpc/security-groups.tf
  data/data/ibmcloud/network/vpc/variables.tf
  data/data/ibmcloud/network/vpc/vpc.tf
  pkg/asset/installconfig/ibmcloud/dns.go
  pkg/terraform/stages/ibmcloud/stages.go
  pkg/terraform/stages/platform/stages.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5153 Bug 1978213: openstack/quota: relax min ports
  pkg/asset/quota/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5154 Bug 1958154: Restrict number of AWS user tags
  pkg/types/aws/validation/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5159 Bug 1995655: bump default channel to stable-4.9
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5155 Bug 1974640: Write user credentials to specified env location
  pkg/asset/installconfig/aws/session.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5157 Bug 1976016: Display proper error message on failure to delete
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5107 Bug 1996124: version: display release architecture
  cmd/openshift-install/version.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5156 Bug 1969371: Stop searching other China regions for resources
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5110 Bug 1972524: baremetal: Ensure ipv6 bootstrap VM client-id is predictable
  data/data/bootstrap/baremetal/files/etc/NetworkManager/conf.d/99-baremetal.conf
  docs/user/metal/customization_ipi.md
Labels: approved, lgtm, bugzilla/valid-bug, platform/baremetal, bugzilla/severity-medium

#5177 Bug 1993207: fix(ibmcloud): Set account ID for resource group look up
  pkg/asset/installconfig/ibmcloud/client.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#5120 Bug 1999119: bump to golang-1.16
  .ci-operator.yaml
  docs/dev/dependencies.md
  go.mod
  go.sum
  hack/build.sh
  hack/go-fmt.sh
  hack/go-genmock.sh
  hack/go-lint.sh
  hack/go-sec.sh
  hack/go-test.sh
  hack/go-vet.sh
  hack/verify-codegen.sh
  hack/verify-vendor.sh
  images/installer/Dockerfile.ci.rhel7
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
  images/libvirt/Dockerfile.ci
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5181 Bug 1993207: fix(ibmcloud): Set account ID for rg on destroy
  pkg/destroy/ibmcloud/ibmcloud.go
  pkg/destroy/ibmcloud/resourcegroup.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
