Repository openshift/installer, pull requests merged in 2021-12, with the labels that each got.

#5433 Add Kiran and Caleb into Installer reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#5407 Bug 1968364: azure: fix upi bug preventing using ed25519 keys
  upi/azure/04_bootstrap.json
  upi/azure/05_masters.json
  upi/azure/06_workers.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5429 OpenStack: Parallelize port deletion
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm

#5422 Alibaba: fix: remove the master node records
  data/data/alibabacloud/cluster/dns/privatezone.tf
  data/data/alibabacloud/cluster/dns/variables.tf
  data/data/alibabacloud/cluster/main.tf
  data/data/alibabacloud/cluster/master/outputs.tf
  data/data/alibabacloud/cluster/outputs.tf
Labels: approved, lgtm, ok-to-test

#5436 Bug 2027387: fix(ibmcloud): Do not compute image file checksum
  data/data/ibmcloud/network/image/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5431 Alibaba: fix: remove unused ResourceGroupID
  pkg/asset/cluster/alibabacloud/alibabacloud.go
  pkg/types/alibabacloud/metadata.go
Labels: approved, lgtm, ok-to-test

#5417 vendor: update terraform-provider-google for rate limit fix
  go.mod
  go.sum
  vendor/github.com/terraform-providers/terraform-provider-google/google/common_operation.go
  vendor/github.com/terraform-providers/terraform-provider-google/google/error_retry_predicates.go
  vendor/modules.txt
Labels: approved, lgtm

#4930 libvirt: add doc on a default load balancer configuration for libvirt
  docs/dev/libvirt/load_balancer.md
Labels: approved, lgtm, ok-to-test

#5410 Alibaba: fix: remove the default value
  data/data/alibabacloud/cluster/dns/variables.tf
  data/data/alibabacloud/cluster/master/variables.tf
  data/data/alibabacloud/cluster/ram/variables.tf
  data/data/alibabacloud/cluster/vpc/variables.tf
  data/data/alibabacloud/variables-alibabacloud.tf
  pkg/tfvars/alibabacloud/alibabacloud.go
Labels: approved, lgtm, ok-to-test

#5394 Bug 1964380: azure upi: do not create etcd DNS records
  upi/azure/05_masters.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5445 Bug 2028611: vendor: update terraform-provider-google for rate limit fix
  go.mod
  go.sum
  vendor/github.com/terraform-providers/terraform-provider-google/google/common_operation.go
  vendor/github.com/terraform-providers/terraform-provider-google/google/error_retry_predicates.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5314 Bug 1999668: Azure: Ensure destroy doesn't panic when invalid credent…
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, platform/azure, bugzilla/valid-bug, bugzilla/severity-low

#5406 Alibaba: fix kubebuilder validation
  pkg/types/alibabacloud/machinepool.go
Labels: approved, lgtm

#5418 installer-artifacts: add darwin/arm64 binary
  images/installer-artifacts/Dockerfile.rhel
Labels: approved, lgtm

#5382 azurestack: Fix gather bootstrap for azurestack
  data/data/azurestack/cluster/master/outputs.tf
Labels: approved, lgtm

#5137 Update URL from cloud.redhat.com to console.redhat.com
  docs/user/aws/install.md
  docs/user/azure/install.md
  docs/user/gcp/install.md
  docs/user/ovirt/install_upi.md
  docs/user/vsphere/install.md
  pkg/asset/installconfig/pullsecret.go
Labels: approved, lgtm, ok-to-test

#5169 machines: Extract root disk sizes to constants
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#5456 Bug 1968364: azure: Update upi docs to remove mentions of sshKeyData
  docs/user/azure/install_upi.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5450 Bug 2029409: Update defaultReleaseImageOriginal to 4.9
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#5455 Condense IBM Cloud SG names
  data/data/ibmcloud/network/vpc/security-groups.tf
Labels: approved, lgtm

#5434 Bug 1928761: Validation of platform.openstack.machineSubnet
  pkg/asset/installconfig/openstack/validation/platform.go
Labels: approved, lgtm, platform/openstack, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#5454 Migrate `ibmcloud` from hidden to an installer recognized/supported platform
  pkg/types/installconfig.go
  pkg/types/installconfig_ibmcloud.go
Labels: approved, lgtm, tide/merge-method-squash

#5392 Bug 1997059: aws: Filter out local zones when generating a default list of zones
  pkg/asset/installconfig/aws/availabilityzones.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5451 Revert "open cluster-policy-controller ports for metrics"
  data/data/aws/cluster/vpc/sg-master.tf
  data/data/gcp/cluster/network/firewall.tf
  data/data/ibmcloud/network/vpc/security-groups.tf
  data/data/openstack/topology/sg-master.tf
  upi/aws/cloudformation/03_cluster_security.yaml
  upi/gcp/03_firewall.py
  upi/openstack/security-groups.yaml
Labels: approved, lgtm

#5444 pkg/types: Correct docs for deprecated options
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/installconfig.go
Labels: approved, lgtm

#5457 Bug 2020216: replace public-access with sas token in bootstrap deployment
  docs/user/azure/install_upi.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5453 docs/dev/pinned-coreos.md: update rhcos-stream.json example
  docs/dev/pinned-coreos.md
Labels: approved, lgtm

#5460 Alibaba: fix: rename the bootstrap output variable
  data/data/alibabacloud/bootstrap/outputs.tf
Labels: approved, lgtm

#5464 bootstrap: remove support for certs lacking SAN
  data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env-godebug.conf.template
Labels: approved, lgtm

#5452 Bug 2027501: bump RHCOS 4.10 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5459 Bug 1964380: remove privateDNSZoneName
  docs/user/azure/install_upi.md
Labels: approved, lgtm

#5448 azure: Fix terraform cluster IP output
  data/data/azure/cluster/master/outputs.tf
Labels: approved, lgtm

#5447 close a verify-codegen ci failure loophole
  hack/verify-codegen.sh
Labels: approved, lgtm

#5416 Bug 2025093: Remove The Default Value For The Disk Provisioning Type of Vsphere
  data/data/install.openshift.io_installconfigs.yaml
  data/data/vsphere/variables-vsphere.tf
  docs/user/vsphere/customization.md
  pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
  pkg/types/vsphere/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5461 Alibaba: fix: replace the ic.ClusterName in the validateClusterName
  pkg/asset/installconfig/alibabacloud/validation.go
Labels: approved, lgtm

#5466 rhcos: ami regions from rhcos stream at runtime
  hack/verify-codegen.sh
  pkg/asset/installconfig/aws/regions.go
  pkg/asset/installconfig/aws/validation.go
  pkg/rhcos/ami_regions.go
  pkg/rhcos/ami_regions_aarch64.go
  pkg/rhcos/ami_regions_generate.go
  pkg/rhcos/ami_regions_x86_64.go
  pkg/types/aws/validation/machinepool.go
Labels: approved, lgtm

#5469 azure upi: get VHD_URL with openshift-install coreos print-stream-json
  docs/user/azure/install_upi.md
Labels: approved, lgtm

#5421 Alibaba: fix: destroy the records of the current cluster
  pkg/destroy/alibabacloud/alibabacloud.go
Labels: approved, lgtm, ok-to-test

#5442 Azure Stack availability set
  data/data/azurestack/vnet/main.tf
  data/data/azurestack/vnet/outputs.tf
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/azure/azure.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/LICENSE
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/addtoscheme_azureprovider_v1beta1.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/apis.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#5471 openstack: Document credential rotation
  docs/user/openstack/README.md
Labels: approved, lgtm

#5465 Bug 2025464: aws: get ips for all control plane instances for bootstrap gather
  data/data/aws/cluster/master/outputs.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5443 Azure Stack Bootstrap Destroy Bug
  pkg/asset/cluster/cluster.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/terraform/stages/azure/stages.go
  pkg/terraform/stages/platform/stages.go
  pkg/types/azure/doc.go
Labels: approved, lgtm

#5472 Cleanup machine references to ibmcloud SG
  pkg/asset/machines/ibmcloud/machines.go
Labels: approved, lgtm

#5435 Alibaba: format the log of the destroyer
  pkg/destroy/alibabacloud/alibabacloud.go
Labels: approved, lgtm

#5426 Alibaba: refactor validation of machine pool
  go.mod
  go.sum
  pkg/asset/installconfig/alibabacloud/client.go
  pkg/asset/installconfig/alibabacloud/validation.go
  pkg/asset/machines/alibabacloud/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/alibabacloud/machinepool.go
  vendor/github.com/wxnacy/wgo/LICENSE
  vendor/github.com/wxnacy/wgo/arrays/arrays.go
  vendor/github.com/wxnacy/wgo/arrays/contains.go
  vendor/github.com/wxnacy/wgo/arrays/set.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#5475 openstack: Document Control plane node migration
  docs/user/openstack/README.md
Labels: approved, lgtm

#5034 ovirt: split terraform into stages
  data/data/ovirt/bootstrap/main.tf
  data/data/ovirt/bootstrap/outputs.tf
  data/data/ovirt/bootstrap/variables.tf
  data/data/ovirt/cluster/affinity_group/main.tf
  data/data/ovirt/cluster/affinity_group/outputs.tf
  data/data/ovirt/cluster/affinity_group/variables.tf
  data/data/ovirt/cluster/affinity_group/versions.tf
  data/data/ovirt/cluster/main.tf
  data/data/ovirt/cluster/masters/main.tf
  data/data/ovirt/cluster/masters/outputs.tf
  data/data/ovirt/cluster/masters/variables.tf
  data/data/ovirt/cluster/masters/versions.tf
  data/data/ovirt/cluster/outputs.tf
  data/data/ovirt/cluster/template/main.tf
  data/data/ovirt/cluster/template/outputs.tf
  data/data/ovirt/cluster/template/variables.tf
  data/data/ovirt/cluster/template/versions.tf
  data/data/ovirt/cluster/variables.tf
  data/data/ovirt/cluster/versions.tf
  data/data/ovirt/image/main.tf
  data/data/ovirt/image/outputs.tf
  data/data/ovirt/image/versions.tf
  data/data/ovirt/template/main.tf
  data/data/ovirt/template/outputs.tf
  data/data/ovirt/template/variables.tf
  data/data/ovirt/variables-ovirt.tf
  pkg/terraform/stages/compat/stage.go
  pkg/terraform/stages/ovirt/stages.go
  pkg/terraform/stages/platform/stages.go
  pkg/terraform/stages/split.go
  pkg/terraform/stages/vsphere/stages.go
  pkg/tfvars/ovirt/ovirt.go
  pkg/tfvars/ovirt/ovirt_test.go
Labels: approved, lgtm

#5064 Baremetal: Split terraform into stages
  data/data/baremetal/bootstrap/main.tf
  data/data/baremetal/bootstrap/variables.tf
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/outputs.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/versions.tf
  pkg/terraform/stages/baremetal/OWNERS
  pkg/terraform/stages/baremetal/stages.go
  pkg/terraform/stages/compat/stage.go
  pkg/terraform/stages/platform/stages.go
Labels: approved, lgtm, platform/baremetal

#5480 Alibaba: fix the validation of instance type
  pkg/asset/installconfig/alibabacloud/validation.go
Labels: approved, lgtm

#5078 Openstack: Split terraform into stages
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/bootstrap/outputs.tf
  data/data/openstack/bootstrap/variables.tf
  data/data/openstack/main.tf
  data/data/openstack/masters/common.tf
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/outputs.tf
  data/data/openstack/masters/private-network.tf
  data/data/openstack/masters/sg-master.tf
  data/data/openstack/masters/sg-worker.tf
  data/data/openstack/masters/variables.tf
  data/data/openstack/topology/outputs.tf
  data/data/openstack/topology/variables.tf
  data/data/openstack/workers/main.tf
  data/data/openstack/workers/variables.tf
  pkg/terraform/gather/openstack/ip.go
  pkg/terraform/stages/compat/stage.go
  pkg/terraform/stages/openstack/stages.go
  pkg/terraform/stages/platform/stages.go
Labels: approved, lgtm

#5362 azurestack: Fix cluster tag check for A record destroy
  pkg/asset/cluster/azure/azure.go
  pkg/destroy/azure/azure.go
  pkg/types/azure/metadata.go
Labels: approved, lgtm

#4828 Bug 1921627: Shorten instance group suffix to ig
  docs/user/gcp/install_upi.md
  upi/gcp/02_lb_int.py
  upi/gcp/04_bootstrap.py
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5390 OpenStack: Instruction on how to deploy on ovs-dpk
  docs/user/openstack/ovs-dpdk.md
Labels: approved, lgtm

#5483 aws: Update our local zone filtering code
  pkg/asset/installconfig/aws/availabilityzones.go
Labels: approved, lgtm

#5486 images/libvirt: provide specific version of google cloud sdk
  images/libvirt/Dockerfile.ci
Labels: approved, lgtm

#5379 Alibaba: support existing VPC, VSwitchs and PrivateZone
  data/data/alibabacloud/cluster/dns/outputs.tf
  data/data/alibabacloud/cluster/dns/privatezone.tf
  data/data/alibabacloud/cluster/dns/variables.tf
  data/data/alibabacloud/cluster/main.tf
  data/data/alibabacloud/cluster/master/main.tf
  data/data/alibabacloud/cluster/master/variables.tf
  data/data/alibabacloud/cluster/vpc/nat_gateway.tf
  data/data/alibabacloud/cluster/vpc/outputs.tf
  data/data/alibabacloud/cluster/vpc/sg-master.tf
  data/data/alibabacloud/cluster/vpc/sg-worker.tf
  data/data/alibabacloud/cluster/vpc/slb.tf
  data/data/alibabacloud/cluster/vpc/variables.tf
  data/data/alibabacloud/cluster/vpc/vpc.tf
  data/data/alibabacloud/variables-alibabacloud.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/alibabacloud/client.go
  pkg/asset/installconfig/alibabacloud/metadata.go
  pkg/asset/installconfig/alibabacloud/validation.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/machines/alibabacloud/machines.go
  pkg/asset/machines/alibabacloud/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/alibabacloud/alibabacloud.go
  pkg/types/alibabacloud/platform.go
  pkg/types/alibabacloud/validation/platform.go
  pkg/types/alibabacloud/validation/platform_test.go
Labels: approved, lgtm, ok-to-test

#5484 tf/stages: add resolution to stages for openstack and ovirt
  pkg/terraform/stages/platform/stages.go
Labels: approved, lgtm

#5485 owners: refresh baremetal-approvers/reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#5189 pkg/asset/installconfig/aws: public DNS validation
  data/data/aws/cluster/route53/base.tf
  pkg/asset/installconfig/aws/validation.go
Labels: approved, lgtm

#5430 Azure Stack: add CA support in bootstrap ign stub
  data/data/azure/variables-azure.tf
  data/data/azurestack/bootstrap/main.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm

#5477 asset/tfvars: use generic name for platform tfvars file
  pkg/asset/cluster/tfvars.go
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm

#5439 [MCO-8] machineconfig: Use KernelArguments field instead of kernel-args file
  pkg/asset/machines/machineconfig/hyperthreading.go
  pkg/asset/machines/master_test.go
  pkg/asset/machines/worker_test.go
Labels: approved, lgtm

#5488 Bug 2032521: vendor: address eventually consistency creating aws dhcp options associations
  go.mod
  go.sum
  vendor/github.com/hashicorp/aws-sdk-go-base/CHANGELOG.md
  vendor/github.com/hashicorp/aws-sdk-go-base/README.md
  vendor/github.com/hashicorp/aws-sdk-go-base/awsauth.go
  vendor/github.com/hashicorp/aws-sdk-go-base/awserr.go
  vendor/github.com/hashicorp/aws-sdk-go-base/mock.go
  vendor/github.com/hashicorp/aws-sdk-go-base/session.go
  vendor/github.com/hashicorp/aws-sdk-go-base/tfawserr/awserr.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/data_source_aws_vpc.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags/s3_tags.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/errors.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/finder/finder.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/waiter/status.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/waiter/waiter.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/internal/tfresource/errors.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_eip_association.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_vpc.go
  vendor/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_vpc_dhcp_options_association.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5437 Remove GCP cluster api provider
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/gcp/machines_test.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/quota/gcp/gcp.go
  pkg/tfvars/gcp/gcp.go
  vendor/github.com/openshift/cluster-api-provider-gcp/LICENSE
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/addtoscheme_gcpprovider_v1beta1.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/apis.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#5462 ibmcloud: remove resource group question from survey
  pkg/asset/installconfig/ibmcloud/ibmcloud.go
Labels: approved, lgtm

#5470 azurestack upi : get VHD_URL with openshift-install coreos print-stream-json
  docs/user/azure/install_upi_azurestack.md
Labels: approved, lgtm

#5489 tf/alibaba: fix name of alibaba tf provider
  data/data/alibabacloud/bootstrap/versions.tf
  data/data/alibabacloud/cluster/dns/versions.tf
  data/data/alibabacloud/cluster/master/versions.tf
  data/data/alibabacloud/cluster/ram/versions.tf
  data/data/alibabacloud/cluster/resourcegroup/versions.tf
  data/data/alibabacloud/cluster/versions.tf
  data/data/alibabacloud/cluster/vpc/versions.tf
Labels: approved, lgtm

#5438 Alibaba: fix: add the availability zone of worker
  data/data/alibabacloud/cluster/main.tf
  data/data/alibabacloud/cluster/vpc/variables.tf
  data/data/alibabacloud/variables-alibabacloud.tf
  pkg/tfvars/alibabacloud/alibabacloud.go
Labels: approved, lgtm, ok-to-test

#5492 Azure Stack: fix versions for Terraform Upgrade
  data/data/azurestack/vnet/versions.tf
Labels: approved, lgtm

#5493 Terraform: Unset TRACE-level debugging
  pkg/terraform/terraform.go
Labels: approved, lgtm

#5476 tf/stages: delete unused code around compat and gather, and improve comments
  pkg/terraform/gather/azure/ip.go
  pkg/terraform/gather/baremetal/ip.go
  pkg/terraform/gather/libvirt/ip.go
  pkg/terraform/gather/ovirt/ip.go
  pkg/terraform/gather/vsphere/ip.go
  pkg/terraform/stages/alibabacloud/stages.go
  pkg/terraform/stages/aws/OWNERS
  pkg/terraform/stages/aws/stages.go
  pkg/terraform/stages/azure/OWNERS
  pkg/terraform/stages/azure/stages.go
  pkg/terraform/stages/baremetal/stages.go
  pkg/terraform/stages/compat/stage.go
  pkg/terraform/stages/gcp/OWNERS
  pkg/terraform/stages/gcp/stages.go
  pkg/terraform/stages/ibmcloud/OWNERS
  pkg/terraform/stages/ibmcloud/stages.go
  pkg/terraform/stages/libvirt/OWNERS
  pkg/terraform/stages/libvirt/stages.go
  pkg/terraform/stages/openstack/OWNERS
  pkg/terraform/stages/openstack/stages.go
  pkg/terraform/stages/ovirt/OWNERS
  pkg/terraform/stages/ovirt/stages.go
  pkg/terraform/stages/platform/stages.go
  pkg/terraform/stages/split.go
  pkg/terraform/stages/vsphere/OWNERS
  pkg/terraform/stages/vsphere/stages.go
  pkg/terraform/state.go
  pkg/tfvars/ibmcloud/OWNERS
Labels: approved, lgtm

#5468 azurestack: Add a custom rhcos image field for ASH
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/rhcos/image.go
  pkg/explain/printer_test.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
Labels: approved, lgtm

#5473 Baremetal: Deploy using CoreOS ISO from the release payload
  data/data/baremetal/masters/main.tf
  data/data/baremetal/variables-baremetal.tf
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  go.mod
  go.sum
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/ignition/bootstrap/baremetal/template_test.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/machines/baremetal/machines.go
  pkg/asset/machines/baremetal/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/rhcos/image.go
  pkg/tfvars/baremetal/baremetal.go
  vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
  vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_node_v1.go
  vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go
  vendor/github.com/openshift/cluster-api-provider-baremetal/LICENSE
  vendor/github.com/openshift/cluster-api-provider-baremetal/pkg/apis/addtoscheme_baremetal_v1alpha1.go
  vendor/github.com/openshift/cluster-api-provider-baremetal/pkg/apis/apis.go
  vendor/github.com/openshift/cluster-api-provider-baremetal/pkg/apis/baremetal/v1alpha1/baremetalmachineproviderspec_types.go
  vendor/github.com/openshift/cluster-api-provider-baremetal/pkg/apis/baremetal/v1alpha1/baremetalmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-baremetal/pkg/apis/baremetal/v1alpha1/doc.go
  vendor/github.com/openshift/cluster-api-provider-baremetal/pkg/apis/baremetal/v1alpha1/register.go
  vendor/github.com/openshift/cluster-api-provider-baremetal/pkg/apis/baremetal/v1alpha1/zz_generated.deepcopy.go
  vendor/golang.org/x/lint/README.md
  vendor/modules.txt
Labels: approved, lgtm, platform/baremetal

#5497 Bug 2033749: Azure Stack: Terraform Local Provider
  data/data/azurestack/bootstrap/versions.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5501 Bug 2034245: terraform: use the correct os for terraform providers
  pkg/terraform/terraform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5506 Bug 2028695: Delete bootstrap profiles during cluster destroy
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5432 Bug 2019977: Validate region provided in install config
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
