Repository openshift/installer, pull requests merged in 2021-11, with the labels that each got.

#5296 Bug 2004313: azure: Skip making azure bootstrap ignition temp file
  data/data/azure/bootstrap/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5351 azurestack: Fix destroyer to delete A records
  pkg/destroy/azure/azure.go
Labels: approved, lgtm

#5349 openstack: Fix install config for openstack manifests
  scripts/openstack/manifest-tests/additional-security-group/install-config.yaml
  scripts/openstack/manifest-tests/cinder-availability-zones/install-config.yaml
  scripts/openstack/manifest-tests/nova-availability-zones/install-config.yaml
  scripts/openstack/manifest-tests/server-groups/install-config.yaml
Labels: approved, lgtm

#5355 Implement WithCustomExtractHostAddresses to gather bootstrap in stages
  data/data/vsphere/bootstrap/outputs.tf
  data/data/vsphere/master/outputs.tf
  data/data/vsphere/pre-bootstrap/main.tf
  data/data/vsphere/pre-bootstrap/outputs.tf
  pkg/terraform/gather/vsphere/ip.go
  pkg/terraform/stages/split.go
  pkg/terraform/stages/vsphere/stages.go
Labels: approved, lgtm

#5307 validation: Enforce strict unmarshalling of config
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/installconfig_test.go
Labels: approved, lgtm

#5340 Bug 1956776: Fix network validation for UPI
  pkg/asset/installconfig/vsphere/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5232 Bug 2021364: aws: remove invalid s3 permission
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-low

#5363 OWNERS_ALIASES: Removing Etienne
  OWNERS_ALIASES
Labels: approved, lgtm

#4664 vSphere IPI: Enable thin provisioning via the OVA import
  data/data/install.openshift.io_installconfigs.yaml
  data/data/vsphere/pre-bootstrap/main.tf
  data/data/vsphere/variables-vsphere.tf
  docs/user/vsphere/customization.md
  pkg/asset/cluster/tfvars.go
  pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
  pkg/tfvars/vsphere/vsphere.go
  pkg/types/vsphere/platform.go
Labels: approved, lgtm

#5354 openstack: Add stephenfin to owners
  OWNERS_ALIASES
Labels: approved, lgtm

#5205 Bug 2003113: Improve host role management during assets creation
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
  pkg/types/baremetal/defaults/platform.go
  pkg/types/baremetal/defaults/platform_test.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, platform/baremetal, bugzilla/severity-medium

#5165 docs: correct spelling in docs
  docs/design/openstack/networking-infrastructure.md
  docs/dev/libvirt/README.md
  docs/user/aws/limits.md
  docs/user/azure/install_upi.md
  docs/user/azure/limits.md
  docs/user/customization.md
  docs/user/gcp/limits.md
  docs/user/metal/README.md
  docs/user/metal/customization_ipi.md
  docs/user/openstack/README.md
  docs/user/openstack/install_upi.md
  docs/user/openstack/privileges.md
  docs/user/ovirt/install_upi.md
  docs/user/troubleshootingbootstrap.md
  docs/user/vsphere/install_upi.md
  docs/user/vsphere/vips-dns.md
Labels: approved, lgtm, ok-to-test

#5343 Bug 1965969: aws: Output public zone id correctly when deleting hosted dns records
  pkg/destroy/aws/shared.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5014 update Packet UPI for Equinix Metal rename
  docs/user/metal/install_upi.md
  upi/metal/README.md
Labels: needs-ok-to-test, approved, lgtm

#5367 Bug 2021607: Relax vcenter hostname check
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5237 Update registry.ci.openshift.org/origin image to 4.9
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm

#5360 Alibaba: add metadata server IP validation
  pkg/types/alibabacloud/validation/platform.go
  pkg/types/alibabacloud/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, ok-to-test

#5377 Bug 2016008: aws: add newly supported regions for arm64
  data/data/coreos/rhcos.json
  pkg/rhcos/ami_regions_aarch64.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5288 Add timestamps to Waiting messages when creating clusters
  cmd/openshift-install/create.go
Labels: approved, lgtm, tide/merge-method-squash

#5136 IPI for vSphere w/ existing resource pool
  data/data/install.openshift.io_installconfigs.yaml
  data/data/vsphere/pre-bootstrap/main.tf
  data/data/vsphere/pre-bootstrap/outputs.tf
  data/data/vsphere/variables-vsphere.tf
  docs/user/vsphere/customization.md
  docs/user/vsphere/privileges.md
  pkg/asset/installconfig/vsphere/client.go
  pkg/asset/installconfig/vsphere/mock/vsphereclient_mock.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/manifests/vsphere/cloudproviderconfig.go
  pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
  pkg/tfvars/vsphere/vsphere.go
  pkg/types/validation/installconfig_test.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/platform.go
Labels: approved, lgtm, ok-to-test

#5346 bug 1960378: Relax the imageContentSource validation
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5358 update registry.ci.openshift.org/ocp and origin images to 4.10
  images/installer/Dockerfile.ci.rhel7
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
  images/libvirt/Dockerfile.ci
  images/openstack/Dockerfile.ci
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm

#5397 Update code and Dockerfiles for golang 1.17
  .ci-operator.yaml
  data/assets.go
  data/assets_generate.go
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
  images/libvirt/Dockerfile.ci
  images/openstack/Dockerfile.ci
  pkg/destroy/baremetal/baremetal.go
  pkg/destroy/baremetal/register.go
  pkg/destroy/libvirt/libvirt.go
  pkg/destroy/libvirt/register.go
  pkg/rhcos/ami_regions_generate.go
  pkg/rhcos/stream.go
  pkg/rhcos/stream_okd.go
  pkg/terraform/exec/config_unix.go
  pkg/terraform/exec/config_windows.go
  pkg/terraform/exec/plugin.go
  pkg/terraform/exec/plugin_release.go
  pkg/terraform/exec/plugins/ironic.go
  pkg/terraform/exec/plugins/libvirt.go
  pkg/terraform/exec/signal_unix.go
  pkg/terraform/exec/signal_windows.go
  pkg/types/azure/platform_aro.go
  pkg/types/baremetal/validation/libvirt.go
  pkg/types/installconfig_baremetal.go
  pkg/types/installconfig_ibmcloud.go
  pkg/types/installconfig_libvirt.go
  pkg/types/installconfig_okd.go
  tools.go
Labels: approved, lgtm

#5395 vSphere: Set default disktype to thick not eager
  data/data/vsphere/variables-vsphere.tf
  pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, lgtm

#5396 Alibaba Cloud Provider: remove the ingress record.
  data/data/alibabacloud/cluster/dns/privatezone.tf
Labels: approved, lgtm

#5400 upi/aws/cloudformation: make bootstrap instance type configurable
  upi/aws/cloudformation/04_cluster_bootstrap.yaml
Labels: approved, lgtm

#5348 alibaba: implement cluster destroy
  cmd/openshift-install/destroy.go
  pkg/destroy/alibabacloud/alibabacloud.go
  pkg/destroy/alibabacloud/doc.go
  pkg/destroy/alibabacloud/register.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/list_tag_keys.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/list_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/list_tag_values.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_failed_resource.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_failed_resources_in_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_failed_resources_in_untag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_keys.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_result.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_tag.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_tag_resource.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_tags.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/struct_values.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/tag/untag_resources.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#5386 [release-4.8] Bug 2023363: Add ingress rules to master SG for compact clusters
  data/data/config.tf
  data/data/openstack/main.tf
  data/data/openstack/topology/sg-master.tf
  data/data/openstack/topology/variables.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/manifests/scheduler.go
  pkg/tfvars/tfvars.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#5393 Vendor: Bump API for Azure Marketplace Images
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/register.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#5398 Bug 2015837: openstack: unset OS_CLOUD for running Terraform
  pkg/terraform/exec/plugins/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5350 Use openshift/api instead of machine-api-operator
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/master.go
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/machines/worker.go
  pkg/tfvars/vsphere/vsphere.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/addtoscheme_vsphereprovider_v1beta1.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/apis.go
  vendor/modules.txt
Labels: approved, lgtm

#5378 Alibaba: support to create a resource group
  data/data/alibabacloud/bootstrap/main.tf
  data/data/alibabacloud/bootstrap/variables.tf
  data/data/alibabacloud/cluster/main.tf
  data/data/alibabacloud/cluster/outputs.tf
  data/data/alibabacloud/cluster/resourcegroup/main.tf
  data/data/alibabacloud/cluster/resourcegroup/outputs.tf
  data/data/alibabacloud/cluster/resourcegroup/variables.tf
  data/data/alibabacloud/cluster/vpc/sg-master.tf
  data/data/alibabacloud/cluster/vpc/sg-worker.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/alibabacloud/alibabacloud.go
  pkg/asset/installconfig/alibabacloud/validation.go
  pkg/types/alibabacloud/metadata.go
  pkg/types/alibabacloud/platform.go
Labels: approved, lgtm, ok-to-test

#5295 feat(ibmcloud): Support VPC dedicated hosts
  data/data/ibmcloud/bootstrap/main.tf
  data/data/ibmcloud/bootstrap/variables.tf
  data/data/ibmcloud/master/main.tf
  data/data/ibmcloud/master/variables.tf
  data/data/ibmcloud/network/dhost/main.tf
  data/data/ibmcloud/network/dhost/outputs.tf
  data/data/ibmcloud/network/dhost/variables.tf
  data/data/ibmcloud/network/image/main.tf
  data/data/ibmcloud/network/main.tf
  data/data/ibmcloud/network/outputs.tf
  data/data/ibmcloud/network/vpc/variables.tf
  data/data/ibmcloud/network/vpc/vpc.tf
  data/data/ibmcloud/variables-ibmcloud.tf
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/asset/installconfig/ibmcloud/validation.go
  pkg/asset/machines/ibmcloud/machines.go
  pkg/destroy/ibmcloud/dedicatedhost.go
  pkg/destroy/ibmcloud/ibmcloud.go
  pkg/tfvars/ibmcloud/ibmcloud.go
  pkg/types/ibmcloud/machinepool.go
  pkg/types/ibmcloud/validation/machinepool.go
  pkg/types/ibmcloud/validation/machinepool_test.go
  pkg/types/ibmcloud/validation/platform.go
  pkg/types/validation/machinepools.go
  vendor/github.com/openshift/cluster-api-provider-ibmcloud/pkg/apis/ibmcloudprovider/v1beta1/ibmcloudproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-ibmcloud/pkg/apis/ibmcloudprovider/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#5383 remove MCO manifests
  data/data/manifests/bootkube/04-openshift-machine-config-operator.yaml
  pkg/asset/manifests/operators.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/04-openshift-machine-config-operator.go
Labels: approved, lgtm

#5414 Alibaba: fix: use the max function
  data/data/alibabacloud/cluster/vpc/vpc.tf
Labels: needs-ok-to-test, approved, lgtm

#5385 Alibaba: update tags for cloud resources
  data/data/alibabacloud/bootstrap/main.tf
  data/data/alibabacloud/cluster/main.tf
  pkg/asset/machines/alibabacloud/machines.go
Labels: approved, lgtm, ok-to-test

#5427 fix/alibaba-slb: remove unused listeners, and set kube-apiserver to HTTP/6080
  data/data/alibabacloud/cluster/vpc/slb.tf
Labels: approved, lgtm

#5415 Alibaba: fix: update comment on ResourceGroupID
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/alibabacloud/platform.go
Labels: needs-ok-to-test, approved, lgtm

#5424 Bug 2027329: Handle unset default machine pool
  pkg/types/openstack/validation/machinepool.go
  pkg/types/openstack/validation/machinepool_test.go
Labels: approved, lgtm, platform/openstack, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#5207 baremetal: add NetworkConfig field
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/metal/install_ipi.md
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, lgtm, platform/baremetal

#5411 Alibaba: fix: use EXACT search mode
  pkg/asset/installconfig/alibabacloud/client.go
Labels: approved, lgtm, ok-to-test
