Repository openshift/installer, pull requests merged in 2022-01, with the labels that each got.

#5505 Bug 2025788: Check vCPUsAvailable for given instance type
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5503 Bug 2034537: openstack: Update OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5490 Bug 2033239: Alibaba: fix the wrong default region
  pkg/asset/installconfig/alibabacloud/alibabacloud.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5495 Bug 2020480: [vsphere] installation failure sometimes with error: the object 'vim.Folder:group-v******' has already been deleted or has not been completely created
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5519 Bug 2038384: Azure: Update Default Instance Types
  pkg/types/azure/defaults/machines.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5494 Bug 1965969: aws: Fix dns destroy logs
  pkg/destroy/aws/shared.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5529 Bug 2039689: Alibaba: fix payment method for NAT gateway
  data/data/alibabacloud/cluster/vpc/nat_gateway.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5521 Bug 2034527: Pass different IP options to installed CoreOS image and IPA
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, platform/baremetal, bugzilla/severity-high

#5531 Bug 2039408: Add northamerica-northeast-2 region to GCP validation
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5530 Bug 2035454: [alibaba] fix deletion of the OSS bucket
  pkg/destroy/alibabacloud/alibabacloud.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#5525 Bug 2039241: [baremetal] use podman secret for image-customization server
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/ignition/bootstrap/baremetal/template_test.go
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, bugzilla/valid-bug, platform/baremetal, bugzilla/severity-high

#5516 Bug 2035705: Azure: Only attempt to destroy resourcegroups if present
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5533 Bug 2033524: [Alibaba] support for list existing domains
  pkg/asset/installconfig/alibabacloud/basedomain.go
  pkg/asset/installconfig/alibabacloud/client.go
  pkg/asset/installconfig/basedomain.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5540 Bug 2041361: [Alibaba] fix load balance listener strategy
  data/data/alibabacloud/cluster/vpc/slb.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5544 Bug 2038166: openstack: Document legacy HTTPS cert validation
  docs/user/openstack/invalid-https-certificates.md
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5510 Bug 2017874: Check quota for G and VT instances
  pkg/asset/quota/aws/aws.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5543 Bug 2041598: Azure Stack remove CA bundle from CPC
  pkg/asset/manifests/cloudproviderconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5536 Bug 2033271: [Alibaba] fix deletion of resource group
  pkg/destroy/alibabacloud/alibabacloud.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5546 Bug 2042438: openstack/Dockerfile: add make and gettext
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5535 Bug 2035757: cluster-bootstrap/alibaba: set tear-down-delay to wait kube-apiserver rolls out on AlibabaCloud
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, bugzilla/severity-urgent

#5532 Bug 2026321: Remove allowed values for nodeVMsize
  upi/azure/04_bootstrap.json
  upi/azure/05_masters.json
  upi/azure/06_workers.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5547 Bug 2040160: [Alibaba] fix EIP metering method
  data/data/alibabacloud/cluster/vpc/eip.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5548 Bug 2042315: Fallback to External IP_OPTIONS when ProvisioningNetwork is Disabled
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  pkg/asset/ignition/bootstrap/baremetal/template.go
Labels: approved, lgtm, bugzilla/valid-bug, platform/baremetal, bugzilla/severity-urgent

#5545 Bug 2037813: [baremetal] networkConfig field now accepts yaml instead of string value
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/metal/install_ipi.md
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
  pkg/asset/machines/master_test.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, lgtm, bugzilla/valid-bug, platform/baremetal, bugzilla/severity-medium

#5538 Bug 2043731: Add IP outputs for IBM terraform instances
  data/data/ibmcloud/bootstrap/outputs.tf
  data/data/ibmcloud/master/outputs.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5562 Bug 2037209: update alibaba for provider spec api changes
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/alibabacloud/machines.go
  pkg/asset/machines/alibabacloud/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/alibabacloud/alibabacloud.go
  pkg/types/alibabacloud/platform.go
  tmp/simple_log.log
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/machine/v1/common.go
  vendor/github.com/openshift/api/machine/v1/doc.go
  vendor/github.com/openshift/api/machine/v1/register.go
  vendor/github.com/openshift/api/machine/v1/types_alibabaprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/cluster-api-provider-alibaba/LICENSE
  vendor/github.com/openshift/cluster-api-provider-alibaba/pkg/apis/addtoscheme_alibabacloudprovider_v1beta1.go
  vendor/github.com/openshift/cluster-api-provider-alibaba/pkg/apis/alibabacloudprovider/v1beta1/alibabacloudmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-alibaba/pkg/apis/alibabacloudprovider/v1beta1/alibabacloudmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-alibaba/pkg/apis/alibabacloudprovider/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api-provider-alibaba/pkg/apis/alibabacloudprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-alibaba/pkg/apis/apis.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5576 Bug 2038166: openstack: Fix invalid-https-certificate detection
  docs/user/openstack/invalid-https-certificates.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5565 Bug 2041926: [Alibaba] fix creating public record being skipped
  data/data/alibabacloud/cluster/dns/privatezone.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5566 Bug 2041319: [Alibaba] fix VSwitch subnets overlap
  data/data/alibabacloud/cluster/vpc/vpc.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5550 Bug 2042655: revert delay of bootstrap control plane teardown for alibaba
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5564 Bug 2041694: [Alibaba] fix system disk category of bootstrap
  data/data/alibabacloud/bootstrap/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5569 Bug 2045927: Add proxy for ironic-agent.service
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#5585 Bug 2047258: Read GovCloud from RHCOS stream
  pkg/types/aws/validation/machinepool.go
  pkg/types/aws/validation/machinepool_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5541 Bug 2041765: Adjust the startup order of httpd container
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, platform/baremetal, bugzilla/severity-high

#5568 Bug 2042036: remove options for existing resources which are currently not supported
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/ibmcloud/ibmcloud.go
  pkg/asset/installconfig/ibmcloud/validation.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
  pkg/asset/machines/ibmcloud/machines.go
  pkg/types/ibmcloud/platform.go
  pkg/types/ibmcloud/validation/platform.go
  pkg/types/ibmcloud/validation/platform_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5509 Bug 2025868: Check HyperVGenerations for instance type
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5534 Bug 2035720: [Alibaba] support internal publish strategy
  data/data/alibabacloud/bootstrap/main.tf
  data/data/alibabacloud/bootstrap/outputs.tf
  data/data/alibabacloud/cluster/dns/privatezone.tf
  data/data/alibabacloud/cluster/dns/variables.tf
  data/data/alibabacloud/cluster/main.tf
  data/data/alibabacloud/cluster/master/main.tf
  data/data/alibabacloud/cluster/master/variables.tf
  data/data/alibabacloud/cluster/vpc/outputs.tf
  data/data/alibabacloud/cluster/vpc/slb.tf
  data/data/alibabacloud/cluster/vpc/variables.tf
  data/data/alibabacloud/cluster/vpc/vpc.tf
  data/data/alibabacloud/variables-alibabacloud.tf
  pkg/tfvars/alibabacloud/alibabacloud.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5574 Bug 2042770: [Alibaba] fix resource creation for existing network
  data/data/alibabacloud/cluster/vpc/eip.tf
  data/data/alibabacloud/cluster/vpc/nat_gateway.tf
  data/data/alibabacloud/cluster/vpc/outputs.tf
  data/data/alibabacloud/cluster/vpc/vpc.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5575 Bug 2042370: [Alibaba] fix installer index panic
  pkg/asset/installconfig/alibabacloud/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5577 Bug 2043297: bump RHCOS 4.10 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5578 Bug 2045916: IBMCloud: Stop defaulting to dedicated storage profile
  data/data/ibmcloud/variables-ibmcloud.tf
  pkg/asset/machines/worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#5580 Bug 2043003: [Alibaba] fix destroy not exist security group
  pkg/destroy/alibabacloud/alibabacloud.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5583 Bug 2046025: [Alibaba] fix destory exist private zone
  pkg/asset/cluster/alibabacloud/alibabacloud.go
  pkg/destroy/alibabacloud/alibabacloud.go
  pkg/types/alibabacloud/metadata.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5584 Bug 2047255: [Alibaba] fix validation of resource group ID
  pkg/asset/installconfig/alibabacloud/client.go
  pkg/asset/installconfig/alibabacloud/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5587 Bug 2047455: Update custom image os type
  data/data/ibmcloud/network/image/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5528 [OCPCLOUD-1385] Ensure removal of placement-groups during cluster destroy on AWS
  pkg/destroy/aws/aws.go
Labels: approved, lgtm

#5593 Remove Caleb Boylan from core installer reviewers
  OWNERS_ALIASES
Labels: approved, lgtm
