Repository openshift/installer, pull requests merged in 2022-08, with the labels that each got.

#6174 CORS-2167: Remove UPI Metal TF references
  docs/user/metal/install_upi.md
  upi/metal/.gitignore
  upi/metal/README.md
  upi/metal/bootstrap/main.tf
  upi/metal/bootstrap/matchbox.tf
  upi/metal/bootstrap/outputs.tf
  upi/metal/bootstrap/packet.tf
  upi/metal/bootstrap/variables.tf
  upi/metal/config.tf
  upi/metal/main.tf
  upi/metal/outputs.tf
  upi/metal/terraform.tfvars.example
Labels: approved, lgtm

#6099 AGENT-246: Do not fail on nmstateconfig validation if agent-config is provided
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm

#6159 Bug 2095320: bump RHCOS 4.9 bootimage metadata
  data/data/rhcos-aarch64.json
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
  hack/update-rhcos-bootimage.py
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#6058 Revert "GCP: Revert Instance Type from N2 to N1"
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#6195 tls: only report error if one happened
  pkg/asset/tls/utils.go
Labels: approved, lgtm

#6196 Bug 2112906: Add a delay when checking Node0 IP address
  data/data/agent/files/usr/local/bin/set-node-zero.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#6193 AGENT-161: install-config validations for agent installer
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
Labels: approved, lgtm

#6115 AGENT-173: Add agent wait-for install-complete
  cmd/openshift-install/agent/waitfor.go
  pkg/agent/cluster.go
  pkg/agent/ocp.go
  pkg/agent/waitfor.go
Labels: approved, lgtm

#6167 AGENT-273 Installer command to create agent-config.yaml file
  cmd/openshift-install/agent.go
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
  pkg/asset/agent/agentconfig/util_test.go
Labels: approved, lgtm

#6201 Bug 2114977: Populate staticNetworkConfig in NMStateConfig.Generate
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#6137 Bug 2108581: [release-4.8] RHCOS: move to rhcos.mirror.openshift.com
  data/data/rhcos-aarch64.json
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
  docs/dev/pinned-coreos.md
  hack/update-rhcos-bootimage.py
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#6197 Bug 2114754: gather: properly delete serial log dir
  pkg/gather/gcp/gcp.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#6108 Bug 2105933: data/data/coreos: update FCOS to 36.20220716.3.1
  data/data/coreos/fcos.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4866 Fix ineffassign
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, ok-to-test

#6180 CORS-2009: Update default release image
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm

#6185 GCP: Added user specified tags on compute instances in installconfig
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/machines/gcp/machines.go
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/validation/machinepool.go
Labels: approved, lgtm

#6181 OWNERS_ALIASES: Add Adam Piasecki (c4rt0)
  OWNERS_ALIASES
Labels: approved, lgtm

#6209 Power VS: Add Montreal as a supported region
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm

#6192 Bug 2098252: bump RHCOS 4.8 bootimage metadata
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#6178 Alibaba: Use a static region list
  pkg/asset/installconfig/alibabacloud/alibabacloud.go
Labels: approved, lgtm

#6202 Add SPLAT members to platform reviewer/approver aliases
  OWNERS_ALIASES
Labels: approved, lgtm

#5834 Remove LoadBalancer settings from cloud provider config
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Labels: approved, lgtm

#6008 Download `yq` in upi installer containers
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm

#6211 powervs: default to tier1 storage
  data/data/powervs/variables-powervs.tf
Labels: approved, lgtm

#6166 GCP: Add networkProjectID parameter to install-config.
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/types/gcp/platform.go
Labels: approved, lgtm

#6163 Update installer images to use golang 1.18
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
  images/libvirt/Dockerfile.ci
Labels: approved, lgtm

#6077 Revendor with golang 1.18
  docs/dev/dependencies.md
  go.mod
  go.sum
  hack/build.sh
  hack/go-fmt.sh
  hack/go-genmock.sh
  hack/go-lint.sh
  hack/go-sec.sh
  hack/go-test.sh
  hack/go-vet.sh
  hack/verify-codegen.sh
  hack/verify-vendor.sh
Labels: approved, lgtm

#6212 Bug 2115790: bump RHCOS 4.12 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#5657 Azure Stack UPI Docs: Remove Feature Gate CRs
  docs/user/azure/install_upi_azurestack.md
Labels: approved, lgtm

#6194 Remove assisted-ui service from list of agentEnabledServices
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm

#6199 GCP: Added user specified tags on control plane instances
  data/data/gcp/cluster/main.tf
  data/data/gcp/cluster/master/main.tf
  data/data/gcp/cluster/master/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm

#5409 Bug 2025901: Improve host role management during assets creation
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
  pkg/types/baremetal/defaults/platform.go
  pkg/types/baremetal/defaults/platform_test.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, platform/baremetal, bugzilla/severity-medium, backport-risk-assessed

#6147 IBMCLOUD Power VS: Updated Max and Min machinepool resource limits
  pkg/types/powervs/validation/machinepool.go
  pkg/types/powervs/validation/machinepool_test.go
Labels: approved, lgtm

#6225 Bug 2118514: [4.11] Download yq in upi installer containers
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#6223 Bug 2117687: compute.replicas must be 0 for SNO
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6183 IBMCloud: BYON Enablement
  pkg/asset/cluster/ibmcloud/ibmcloud.go
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/subnet.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/machines/ibmcloud/machines.go
  pkg/asset/machines/ibmcloud/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/ibmcloud/cloudproviderconfig.go
  pkg/asset/manifests/ibmcloud/cloudproviderconfig_test.go
Labels: approved, lgtm

#6239 AGENT-246: Temporarily require at least one NMStateConfig to be specified
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm

#6208 Bug 2109800: IBMCloud: Allow metrics traffic
  data/data/ibmcloud/network/vpc/security-groups.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#6236 Bug 2115770: Check for RendezvousIP in Agent config if NMStateConfig is not provided
  pkg/agent/rest.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#6222 Bug 2098252: locations fix
  data/data/rhcos-stream.json
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#6237 Collapse AgentConfig spec and add versioning
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/util_test.go
  pkg/types/agent/OWNERS
  pkg/types/agent/agent_config_type.go
  pkg/types/agent/conversion/agentconfig.go
  pkg/types/agent/conversion/agentconfig_test.go
Labels: approved, lgtm

#6234 Extract the image-references file from the release, pass it to `machine-config-operator`
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#6047 OCPBUGS-262: UPI image download govc rate limit failure
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6241 IBMCloud: Use unique mutex for Client retrieval
  pkg/asset/installconfig/ibmcloud/metadata.go
Labels: approved, lgtm

#6226 Bug 2117279: bump RHCOS 4.11 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#6152 Bug 2061947: IBMCloud: Handle missing RG
  pkg/destroy/ibmcloud/ibmcloud.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#6233 Bug 2098072: vsphere: fix default disk type when not speficied
  terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#6207 gcp: Add validation for Network Project Data
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm

#6253 [release-4.8] OCPBUGS-448: Allow setting bootstrap kubelet ip
  data/data/bootstrap/files/usr/local/bin/kubelet.sh.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#6215 OCPBUGS-268: vSphere - enable steal time accounting
  data/data/vsphere/master/main.tf
  upi/vsphere/vm/main.tf
Labels: approved, lgtm, qe-approved, jira/valid-bug

#6056 IBMCloud: Pull in latest openshift/api changes
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image_digest_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_image_tag_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/register.go
  vendor/github.com/openshift/api/machine/v1/types_aws.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_powervsprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_insights-operator_00-insightsoperator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_insights.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch
  vendor/github.com/openshift/api/route/v1/test-route-validation.sh
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#5336 cmd/openshift-install/create: One shot console access
  cmd/openshift-install/create.go
Labels: approved, lgtm

#6242 manifests: Pass the NetworkProjectID to manifests
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig_test.go
Labels: approved, lgtm

#6259 GCP: Add missing regions
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm

#6219 GCP: Remove firewall rules when providing network project id
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/cluster/main.tf
  data/data/gcp/cluster/network/firewall.tf
  data/data/gcp/cluster/network/variables.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm

#6157 Add support for private DNS server to PowerVS
  data/data/powervs/bootstrap/vm/outputs.tf
  data/data/powervs/cluster/bootstrap/lb/ouputs.tf
  data/data/powervs/cluster/bootstrap/outputs.tf
  data/data/powervs/cluster/dns/dns.tf
  data/data/powervs/cluster/dns/variables.tf
  data/data/powervs/cluster/main.tf
  data/data/powervs/cluster/master/lb/variables.tf
  data/data/powervs/variables-powervs.tf
  pkg/asset/cluster/tfvars.go
  pkg/destroy/powervs/cloud-instance.go
  pkg/destroy/powervs/cloud-sshkey.go
  pkg/destroy/powervs/cloudconnection.go
  pkg/destroy/powervs/power-instance.go
  pkg/destroy/powervs/power-sshkey.go
  pkg/destroy/powervs/powervs.go
  pkg/destroy/powervs/publicgateway.go
  pkg/tfvars/powervs/powervs.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm

#5741 [vsphere] validate vSphere privileges
  pkg/asset/installconfig/vsphere/mock/authmanager_generated.go
  pkg/asset/installconfig/vsphere/mock/vsphereclient_mock.go
  pkg/asset/installconfig/vsphere/permission_test.go
  pkg/asset/installconfig/vsphere/permissions.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/installconfig/vsphere/validation_test.go
Labels: approved, lgtm

#6268 Bug OCPBUGS-164: OpenStack: Set minimum disk of a flavor to 100 GB
  docs/user/openstack/README.md
  docs/user/openstack/deploy_sriov_workers.md
  pkg/asset/installconfig/openstack/validation/machinepool.go
  pkg/asset/installconfig/openstack/validation/machinepool_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6255 CORS-2271: IBMCloud: Add DNS Service support - installconfig
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/dns.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/asset/installconfig/ibmcloud/validation.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/infrastructure.go
  pkg/types/validation/installconfig.go
  vendor/github.com/IBM/networking-go-sdk/dnszonesv1/dns_zones_v1.go
  vendor/modules.txt
Labels: approved, lgtm

#6286 Bug OCPBUGS-164: OpenStack: Update Kuryr storage requirements
  docs/user/openstack/kuryr.md
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6275 AGENT-326: Fix releaseImage mirror handling with unit test
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm

#6230 Bug 2117439: Azure masters should publish on an internal load balancer
  pkg/asset/machines/azure/machines.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved
