Repository openshift/installer, pull requests merged in 2022-05, with the labels that each got.

#5831 Bug 2077662: Fix AWS Platform Provisioning Check
  pkg/asset/installconfig/aws/validation.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#5836 Bug 2064170: Fixed duplicate strings in explain
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer.go
  pkg/explain/printer_test.go
  pkg/types/azure/machinepool.go
  pkg/types/gcp/machinepools.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#5859 Update the comment explaining vCPUs on Nutanix
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/nutanix/machinepool.go
Labels: approved, lgtm

#5860 [ibmcloud] Update os name to correct value
  data/data/ibmcloud/network/image/main.tf
Labels: approved, lgtm

#5820 Bug 2076613: [release-4.10] data/data/coreos/fcos.json: update initial FCOS to 35.20220327.3.0
  data/data/coreos/fcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5811 Bug 2074210:Add new Regions to the GCP Installer configuration list
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#5857 Change the default machine pool config for Nutanix
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#5384 Use neutral pronoun in doc.
  docs/dev/openstack/customization.md
Labels: approved, lgtm, ok-to-test

#5863 Power VS: fix terraform vars
  data/data/powervs/cluster/bootstrap/variables.tf
  data/data/powervs/cluster/master/lb/variables.tf
Labels: approved, lgtm

#5868 Pull the OS Image for Nutanix via URL
  data/data/nutanix/cluster/main.tf
  data/data/nutanix/variables-nutanix.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/nutanix/nutanix.go
Labels: approved, lgtm

#5794 Bug 2080054: Add 'ARG TAGS=""' line for each build step
  images/installer-artifacts/Dockerfile.rhel
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#5712 Update SR-IOV & DPDK doc for OpenStack
  docs/user/openstack/deploy_sriov_workers.md
  docs/user/openstack/ovs-dpdk.md
Labels: approved, lgtm

#5795 Add -n argument to copy network config from install environment to install-to-disk.sh.template
  data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/install-to-disk.sh.template
Labels: approved, lgtm, ok-to-test

#5875 Update template for CloudProviderConfig
  pkg/asset/manifests/powervs/cloudproviderconfig.go
Labels: approved, lgtm

#5866 openstack: Add the Kuryr squad as approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#5869 Bug 2082604: Revert "image: set os name to red-coreos-stable-amd64"
  data/data/ibmcloud/network/image/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#5838 Bug 2078875: Delete all the ports from tagged Neutron networks.
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5881 OpenStack: fix SR-IOV documentation TOC
  docs/user/openstack/deploy_sriov_workers.md
Labels: approved, lgtm

#5878 AGENT-56: Move create cluster and infraenv to assisted-service repo
  data/data/agent/files/usr/local/bin/create-cluster-and-infra-env.sh.template
  data/data/agent/files/usr/local/bin/wait-for-assisted-service.sh
  data/data/agent/systemd/units/create-cluster-and-infra-env.service
  data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
  go.mod
  pkg/agent/imagebuilder/content.go
  pkg/agent/imagebuilder/embed_ignition.go
  pkg/agent/manifests/clusterdeployment.go
  pkg/agent/manifests/infraenv.go
  pkg/agent/manifests/manifests.go
  pkg/agent/manifests/nmstateconfig.go
  vendor/github.com/thoas/go-funk/.gitignore
  vendor/github.com/thoas/go-funk/.travis.yml
  vendor/github.com/thoas/go-funk/CHANGELOG.md
  vendor/github.com/thoas/go-funk/LICENSE
  vendor/github.com/thoas/go-funk/Makefile
  vendor/github.com/thoas/go-funk/README.rst
  vendor/github.com/thoas/go-funk/assign.go
  vendor/github.com/thoas/go-funk/builder.go
  vendor/github.com/thoas/go-funk/chain_builder.go
  vendor/github.com/thoas/go-funk/compact.go
  vendor/github.com/thoas/go-funk/fill.go
  vendor/github.com/thoas/go-funk/helpers.go
  vendor/github.com/thoas/go-funk/intersection.go
  vendor/github.com/thoas/go-funk/join.go
  vendor/github.com/thoas/go-funk/join_primitives.go
  vendor/github.com/thoas/go-funk/lazy_builder.go
  vendor/github.com/thoas/go-funk/map.go
  vendor/github.com/thoas/go-funk/max.go
  vendor/github.com/thoas/go-funk/min.go
  vendor/github.com/thoas/go-funk/operation.go
  vendor/github.com/thoas/go-funk/options.go
  vendor/github.com/thoas/go-funk/permutation.go
  vendor/github.com/thoas/go-funk/predicate.go
  vendor/github.com/thoas/go-funk/presence.go
  vendor/github.com/thoas/go-funk/reduce.go
  vendor/github.com/thoas/go-funk/retrieve.go
  vendor/github.com/thoas/go-funk/scan.go
  vendor/github.com/thoas/go-funk/short_if.go
  vendor/github.com/thoas/go-funk/subset.go
  vendor/github.com/thoas/go-funk/subtraction.go
  vendor/github.com/thoas/go-funk/transform.go
  vendor/github.com/thoas/go-funk/typesafe.go
  vendor/github.com/thoas/go-funk/utils.go
  vendor/github.com/thoas/go-funk/without.go
  vendor/github.com/thoas/go-funk/zip.go
  vendor/modules.txt
Labels: approved, lgtm

#5871 AGENT-159: Assets generation for create manifests command
  cmd/openshift-install/agent.go
  cmd/openshift-install/agent/create.go
  go.mod
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentpullsecret.go
  pkg/asset/agent/manifests/agentpullsecret_test.go
  pkg/asset/agent/manifests/clusterdeployment.go
  pkg/asset/agent/manifests/infraenv.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm

#5846 Azure Provider: fix vmNetworkType defaults by checking vm capabilities
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/capabilities.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#5841 machines: Set defaults for machine instance types
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#5880 update azure arm templates to support customer provided vnet
  upi/azure/03_infra.json
  upi/azure/04_bootstrap.json
  upi/azure/05_masters.json
  upi/azure/06_workers.json
Labels: approved, lgtm

#5893 azure: validation: dedup getting the capabilities
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
Labels: approved, lgtm

#5844 azure: move zones functionality to the client API
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/containerservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleries.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimageversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/loganalytics.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/proximityplacementgroups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinesizes.go
  vendor/modules.txt
Labels: approved, lgtm

#5874 Bug 2083327: [release-4.10] Add 'ARG TAGS=""' line for each build step
  images/installer-artifacts/Dockerfile.rhel
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5894 AGENT-194: Fixes to start cluster installation script and service
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
  data/data/agent/systemd/units/start-cluster-installation.service
Labels: approved, lgtm, px-approved

#5855 Bug 2080219: OpenStack+Kuryr: Fix `cluster destroy` with BYON
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5898 GCP: Revert Instance Type from N2 to N1
  pkg/asset/machines/worker.go
Labels: approved, lgtm

#5892 Bug 2084547: update azure arm templates to support customer provided vnet
  upi/azure/03_infra.json
  upi/azure/04_bootstrap.json
  upi/azure/05_masters.json
  upi/azure/06_workers.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5807 Aws console logs
  cmd/openshift-install/gather.go
  pkg/gather/aws/aws.go
  pkg/gather/aws/register.go
  pkg/gather/doc.go
  pkg/gather/gather.go
  pkg/gather/providers/registry.go
  pkg/gather/providers/types.go
Labels: approved, lgtm

#5901 Power VS: Separating bootstrap resources to own stage for clean destroy
  data/data/powervs/bootstrap-routing/main.tf
  data/data/powervs/bootstrap-routing/variables.tf
  data/data/powervs/bootstrap/lb/main.tf
  data/data/powervs/bootstrap/lb/variables.tf
  data/data/powervs/bootstrap/main.tf
  data/data/powervs/bootstrap/outputs.tf
  data/data/powervs/bootstrap/variables.tf
  data/data/powervs/bootstrap/vm/main.tf
  data/data/powervs/bootstrap/vm/outputs.tf
  data/data/powervs/bootstrap/vm/templates/bootstrap.ign
  data/data/powervs/bootstrap/vm/variables.tf
  data/data/powervs/cluster/bootstrap/main.tf
  data/data/powervs/cluster/main.tf
  data/data/powervs/cluster/master/lb/main.tf
  data/data/powervs/cluster/master/lb/variables.tf
  data/data/powervs/cluster/master/main.tf
  data/data/powervs/cluster/master/variables.tf
  data/data/powervs/cluster/outputs.tf
  data/data/powervs/post-install/main.tf
  data/data/powervs/variables-powervs.tf
  pkg/terraform/stages/powervs/stages.go
Labels: approved, lgtm

#5872 AGENT-40: allow reading cert keys
  pkg/asset/tls/adminkubeconfig.go
  pkg/asset/tls/apiserver.go
  pkg/asset/tls/certkey.go
Labels: approved, lgtm

#5734 Added changes for validating the IBM Account Type for Provisioning Power VS resources
  go.mod
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/platform.go
  pkg/asset/installconfig/powervs/session.go
  vendor/github.com/IBM-Cloud/bluemix-go/.gitignore
  vendor/github.com/IBM-Cloud/bluemix-go/.legal.yaml
  vendor/github.com/IBM-Cloud/bluemix-go/.travis.yml
  vendor/github.com/IBM-Cloud/bluemix-go/Makefile
  vendor/github.com/IBM-Cloud/bluemix-go/README.md
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/accounts.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/api_service.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/paginate.go
  vendor/github.com/IBM-Cloud/bluemix-go/authentication/auth.go
  vendor/github.com/IBM-Cloud/bluemix-go/authentication/iam.go
  vendor/github.com/IBM-Cloud/bluemix-go/authentication/uaa.go
  vendor/github.com/IBM-Cloud/bluemix-go/bmxerror/cert.go
  vendor/github.com/IBM-Cloud/bluemix-go/bmxerror/error.go
  vendor/github.com/IBM-Cloud/bluemix-go/bmxerror/network.go
  vendor/github.com/IBM-Cloud/bluemix-go/bmxerror/token.go
  vendor/github.com/IBM-Cloud/bluemix-go/bmxerror/types.go
  vendor/github.com/IBM-Cloud/bluemix-go/client/client.go
  vendor/github.com/IBM-Cloud/bluemix-go/config.go
  vendor/github.com/IBM-Cloud/bluemix-go/endpoints/endpoints.go
  vendor/github.com/IBM-Cloud/bluemix-go/errors.go
  vendor/github.com/IBM-Cloud/bluemix-go/helpers/conversion.go
  vendor/github.com/IBM-Cloud/bluemix-go/helpers/env.go
  vendor/github.com/IBM-Cloud/bluemix-go/helpers/file.go
  vendor/github.com/IBM-Cloud/bluemix-go/helpers/template.go
  vendor/github.com/IBM-Cloud/bluemix-go/helpers/utils.go
  vendor/github.com/IBM-Cloud/bluemix-go/helpers/zip.go
  vendor/github.com/IBM-Cloud/bluemix-go/http/http.go
  vendor/github.com/IBM-Cloud/bluemix-go/http/transport.go
  vendor/github.com/IBM-Cloud/bluemix-go/rest/client.go
  vendor/github.com/IBM-Cloud/bluemix-go/rest/request.go
  vendor/github.com/IBM-Cloud/bluemix-go/session/session.go
  vendor/github.com/IBM-Cloud/bluemix-go/trace/trace.go
  vendor/github.com/IBM-Cloud/bluemix-go/version.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, lgtm

#5791 Increase Unit Testing Coverage of AWS Install Config to Include ValidateForProvisioning
  pkg/asset/installconfig/aws/mock/awsroute53_generated.go
  pkg/asset/installconfig/aws/route53.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
  pkg/asset/installconfig/platformprovisioncheck.go
Labels: approved, lgtm

#5910 Typo: Fixed redundant `
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
Labels: approved, lgtm

#5909 Bug 2085721: Fix name for customization controller image
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5887 Bug 2065893: bump RHCOS 4.11 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5886 Bug 2086056: openstack: add doc for OVS HW offload
  docs/user/openstack/README.md
  docs/user/openstack/deploy_sriov_workers.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5916 Rename "fleeting" to "agent-installer"
  data/data/agent/files/etc/issue
  pkg/agent/imagebuilder/embed_ignition.go
Labels: approved, lgtm

#5914 Bug 2086936: vSphere: change socket back to cores
  pkg/asset/machines/worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5919 AGENT-194: Fix service name in dependencies
  data/data/agent/systemd/units/start-cluster-installation.service
Labels: approved, lgtm

#5906 AGENT-131: Ignition and iso assets for agent installer
  cmd/openshift-install/agent.go
  pkg/agent/build_image.go
  pkg/agent/imagebuilder/content.go
  pkg/agent/imagebuilder/embed_ignition.go
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm

#5876 [release-4.10] Bug 2083335: Set rc-manager=unmanaged for on-prem bootstrap
  data/data/bootstrap/baremetal/files/etc/NetworkManager/conf.d/99-baremetal.conf
  data/data/bootstrap/baremetal/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/openstack/files/etc/NetworkManager/conf.d/99-openstack.conf
  data/data/bootstrap/openstack/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/ovirt/files/etc/NetworkManager/conf.d/99-ovirt.conf
  data/data/bootstrap/ovirt/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/vsphere/files/etc/NetworkManager/conf.d/99-vsphere.conf.template
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#5891 AGENT-193: Do not set api_vip for SNO cluster
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
Labels: approved, lgtm

#5920 Agent-196: Add asset for nmstateconfig
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm

#5864 Bug 2078431: Set TF_DATA_DIR to the Terraform Dir.
  pkg/terraform/init.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5889 Agent-160: Add baseIso asset
  pkg/agent/isosource/download.go
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/baseiso_test.go
  pkg/asset/agent/image/cache.go
Labels: approved, lgtm

#5924 Bug 2084441: azure: proper premiumIO validation message
  pkg/asset/installconfig/azure/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#5922 Bug 1969794: Correct typo
  docs/user/openstack/image_registry_with_custom_pvc_backends.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5408 Bug 2025862: Improve host role management during assets creation
  data/data/baremetal/main.tf
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/variables.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
  pkg/types/baremetal/defaults/platform.go
  pkg/types/baremetal/defaults/platform_test.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, platform/baremetal, bugzilla/severity-medium, backport-risk-assessed

#5923 Bug 1965468: Revert "Bug 1909136: OpenStack: delete volume snapshots"
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5890 AGENT-169: AgentClusterInstall asset
  go.mod
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm

#5935 Bug 2088660: Fix for absence folder for bootstrap ignition iso
  pkg/types/nutanix/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5933 AGENT-165: Install release specified in ClusterImageSet
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/files/usr/local/share/assisted-service/images.env.template
  pkg/agent/imagebuilder/content.go
  pkg/agent/imagebuilder/releaseimage.go
  pkg/agent/imagebuilder/releaseimage_test.go
  pkg/agent/manifests/manifests.go
Labels: approved, lgtm

#5934 Fix unnecessary delays in start-cluster-installation
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
Labels: approved, lgtm

#5942 AGENT-203: Add ClusterImageSet asset
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/clusterimageset.go
  pkg/asset/agent/manifests/clusterimageset_test.go
Labels: approved, lgtm
