Repository openshift/installer, pull requests merged in 2022-11, with the labels that each got.

#6541 OCPBUGS-3018: Use result from List function after checking error
  pkg/agent/rest.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6492 OCPBUGS-1033: support multiple documents in the same extra manifest file
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6514 Add linux/arm64 binary to installer-artifacts
  images/installer-artifacts/Dockerfile.rhel
Labels: approved, lgtm

#6521 OCPBUGS-1791: add bootstrap configmap during the SNO reboot
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6533 OCPBUGS-2966: Add GCP CreateFirewallRules to tech preview
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/platform.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6529 OCPBUGS-2795: Bump gophercloud
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/requests.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#6547 OCPBUGS-2758: Provide datastore as full path
  pkg/asset/manifests/vsphere/infrastructure.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#6522 OCPBUGS-2847: GCP XPN Featuregates
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-low, jira/valid-bug

#6527 OCPBUGS-3110: azure: Fix client certs authentication
  pkg/asset/installconfig/platformcredscheck.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6552 OCPBUGS-2911: Use project after creation
  pkg/asset/installconfig/gcp/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug

#6548 OCPBUGS-3096: Static linking the terraform and providers binaries
  hack/build.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6530 OCPBUGS-3287: agent ased installation fix for dual stack vips
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/common.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6516 OCPBUGS-1704: gcp: fail during validation if service usage is not enabled
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug

#6412 OCPBUGS-1627: [vsphere-zones] Fix user folders
  data/data/install.openshift.io_installconfigs.yaml
  data/data/vspherezoning/bootstrap/main.tf
  data/data/vspherezoning/master/main.tf
  pkg/tfvars/vsphere/vsphere.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate

#6545 OCPBUGS-2513: Set PublicContainerRegistries for entries in mirror
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6557 OCPBUGS-3214: Always add router CAs to kubeconfig, even if console is not available
  cmd/openshift-install/create.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#6546 OCPBUGS-2841: (AGENT) only support amd64 archs
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#6563 OCPBUGS-3304: Always use first matching mirror in assisted-service
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6567 OCPBUGS-3280: Automatically retry install
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
  pkg/agent/cluster.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6507 Bug 2099604: Remove optional services from permissions check
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#6571 OCPBUGS-3382: Fix cluster wide proxy
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6576 OCPBUGS-3123: Pass FeatureSet to cluster config render
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6553 OCPBUGS-3186: IBMCloud: Confirm Zones and BYON Subnets
  pkg/asset/installconfig/ibmcloud/validation.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6593 docs: fix broken link to default kubelet.service taint
  docs/user/customization.md
Labels: approved, lgtm

#5671 OCPBUGS-2384: [Alibaba] fix the creation of public record
  data/data/alibabacloud/cluster/dns/privatezone.tf
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-important

#6597 OCPBUGS-3743: build: change ppc64le linking mode
  hack/build.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#6600 add ibmcloud cli to image
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm

#6615 OCPBUGS-3933: OpenStack: Force JSON content-type in Swift
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#6577 OCPBUGS-3277: Restart create-cluster-and-infraenv.service if it fails
  data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6573 OCPBUGS-3278: (Agent) Do not require host data in platform baremetal section in installconfig
  pkg/asset/agent/installconfig.go
  pkg/types/baremetal/validation/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#6624 mv ibmcloud to /bin folder
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm

#6579 OCPBUGS-3985: Pass featureset to kas
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6540 OCPBUGS-2931: Azure Stack: use managed images for compute nodes
  pkg/asset/machines/azure/machines.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-critical

#6531 Adding aarch64 instance types for azure
  docs/user/azure/tested_instance_types_aarch64.md
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm

#6574 OCPBUGS-3405: Redact pull secret from agent-gather
  data/data/agent/files/usr/local/bin/agent-gather
  data/data/agent/systemd/units/agent.service.template
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/agentpullsecret.go
  pkg/asset/agent/manifests/agentpullsecret_test.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6583 OCPBUGS-3524: data: azurerm: restore RHCOS SA access configuration
  data/data/azure/vnet/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate
