Repository openshift/installer, pull requests merged in 2022-04, with the labels that each got.

#5692 Validate disk encryption sets
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/compute/mgmt/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/dedicatedhostgroups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/dedicatedhosts.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/diskaccesses.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/diskencryptionsets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/diskrestorepoint.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/galleries.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/galleryapplications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/galleryapplicationversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/galleryimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/galleryimageversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/loganalytics.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/proximityplacementgroups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/sshpublickeys.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachineimagesedgezone.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachinescalesetvmextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachinescalesetvmruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/virtualmachinesizes.go
  vendor/modules.txt
Labels: approved, lgtm

#5765 Bug 2070666: Update the default channel for new 4.6 installs to eus-4.6
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5766 OWNERS_ALIASES: Update current installer team
  OWNERS_ALIASES
Labels: approved, lgtm

#5759 Azure: validate UltraSSD instance types
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
Labels: approved, lgtm

#5757 Refactor UltraSSD tfvars
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm

#5770 collect machine state in bootstrap gather
  data/data/bootstrap/files/usr/local/bin/bootstrap-cluster-gather.sh
Labels: approved, lgtm

#5774 Update default releaseimage to 4.11
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm

#5633 Add nutanix-specific customizations to installconfig
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/nutanix/OWNERS
  pkg/asset/installconfig/nutanix/nutanix.go
  pkg/asset/installconfig/nutanix/validation.go
  pkg/asset/installconfig/platform.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/types/nutanix/client.go
Labels: approved, lgtm

#5764 Removing no-longer-needed DNS etcd stuff
  upi/aws/cloudformation/05_cluster_master_nodes.yaml
Labels: approved, lgtm

#5753 Bug 2069166: stop considering Mint mode as supported on Azure (#5699)
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#5771 gather: collect sssd journal logs
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm

#5594 Bug 2056460: Preallocated disks for OCP nodes on oVirt
  data/data/install.openshift.io_installconfigs.yaml
  data/data/ovirt/cluster/main.tf
  data/data/ovirt/cluster/masters/main.tf
  data/data/ovirt/cluster/masters/variables.tf
  data/data/ovirt/cluster/template/main.tf
  data/data/ovirt/variables-ovirt.tf
  go.mod
  go.sum
  pkg/asset/machines/ovirt/machines.go
  pkg/tfvars/ovirt/ovirt.go
  pkg/tfvars/ovirt/ovirt_test.go
  pkg/types/ovirt/machinepool.go
  pkg/types/ovirt/validation/machinepool.go
  pkg/types/ovirt/validation/platform.go
  terraform/providers/ovirt/go.mod
  terraform/providers/ovirt/go.sum
  terraform/providers/ovirt/vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/provider.go
  terraform/providers/ovirt/vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_image_transfer.go
  terraform/providers/ovirt/vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go
  terraform/providers/ovirt/vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm_template.go
  terraform/providers/ovirt/vendor/github.com/ovirt/terraform-provider-ovirt/tr-ocp-installer.spec
  terraform/providers/ovirt/vendor/modules.txt
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/types.go
  vendor/github.com/openshift/cluster-api-provider-ovirt/pkg/apis/ovirtprovider/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5636 Update declarative assets for Nutanix
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/nutanix/OWNERS
  data/data/nutanix/bootstrap/main.tf
  data/data/nutanix/bootstrap/outputs.tf
  data/data/nutanix/bootstrap/variables.tf
  data/data/nutanix/cluster/main.tf
  data/data/nutanix/cluster/outputs.tf
  data/data/nutanix/variables-nutanix.tf
  pkg/terraform/stages/nutanix/OWNERS
  pkg/terraform/stages/nutanix/stages.go
  pkg/terraform/stages/platform/stages.go
Labels: approved, lgtm

#5539 Bug 2038774: [IBM] add IPsec IKE UDP ports 500, 4500 to security group
  data/data/ibmcloud/network/vpc/security-groups.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5662 Re-update BMO vendor to use ipxe for iRMC
  go.mod
  go.sum
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_validation.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/firmwareschema_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardware/profile.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ilo5.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#5781 Update installconfig validation for Nutanix
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#5784 Remove defaultStorageContainer from nutanix platform installconfig
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/nutanix/nutanix.go
  pkg/types/nutanix/platform.go
  pkg/types/nutanix/validation/platform.go
  pkg/types/nutanix/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#5786 Bootstrap-in-place ignition creation should also create a `worker.ign` file
  pkg/asset/targets/targets.go
Labels: approved, lgtm

#5702 Add exit code for infra, bootstrip and install failures
  cmd/openshift-install/create.go
  cmd/openshift-install/waitfor.go
  pkg/asset/asset.go
  pkg/asset/cluster/cluster.go
  pkg/asset/installconfig/installconfig.go
Labels: approved, lgtm

#5783 pkg/asset/manifests/operators: Set kubernetes.io/description for cluster-config-v1
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/utils.go
Labels: approved, lgtm

#5615 Add IBM Power VS: tfvars
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/rhcos/image.go
  pkg/terraform/stages/platform/stages.go
  pkg/terraform/stages/powervs/stages.go
  pkg/tfvars/powervs/powervs.go
  vendor/github.com/coreos/stream-metadata-go/stream/artifact_utils.go
  vendor/github.com/coreos/stream-metadata-go/stream/stream.go
  vendor/github.com/google/renameio/.golangci.yml
  vendor/github.com/google/renameio/CONTRIBUTING.md
  vendor/github.com/google/renameio/LICENSE
  vendor/github.com/google/renameio/README.md
  vendor/github.com/google/renameio/doc.go
  vendor/github.com/google/renameio/tempfile.go
  vendor/github.com/google/renameio/writefile.go
  vendor/modules.txt
Labels: approved, lgtm

#5708 Added platform validation testcases for IBM PowerVS platform
  pkg/types/powervs/powervs_regions.go
  pkg/types/powervs/validation/platform.go
  pkg/types/powervs/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#5748 Power VS quota asset
  pkg/asset/quota/quota.go
Labels: approved, lgtm

#5742 Add VolumeID testscases for Power VS machinepool
  pkg/types/powervs/validation/machinepool.go
  pkg/types/powervs/validation/machinepool_test.go
Labels: approved, lgtm

#5778 Bug 2033482: vsphere: ensure terraform variables are defined
  data/data/vsphere/bootstrap/variables.tf
  data/data/vsphere/master/variables.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#5762 images: Update terraform version in UPI image
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm

#5747 Lower severity of ListAWSDefaultServiceQuotas warning msg
  pkg/asset/quota/quota.go
Labels: approved, lgtm

#5785 remove platform.azure.osDisk
  docs/user/azure/customization.md
Labels: approved, lgtm

#5727 terraform: fix module name of terraform providers
  docs/dev/terraform.md
  terraform/providers/alicloud/go.mod
  terraform/providers/aws/go.mod
  terraform/providers/azureprivatedns/go.mod
  terraform/providers/azurerm/go.mod
  terraform/providers/azurestack/go.mod
  terraform/providers/google/go.mod
  terraform/providers/ibm/go.mod
  terraform/providers/ignition/go.mod
  terraform/providers/ironic/go.mod
  terraform/providers/libvirt/go.mod
  terraform/providers/local/go.mod
  terraform/providers/openstack/go.mod
  terraform/providers/ovirt/go.mod
  terraform/providers/random/go.mod
  terraform/providers/vsphere/go.mod
  terraform/providers/vsphereprivate/go.mod
Labels: approved, lgtm

#5775 pkg/destroy/aws: Log unfiltered pagination
  pkg/destroy/aws/aws.go
Labels: approved, lgtm

#5721 azure: Enable HyperVGeneration setting for Azure disks
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/main.tf
  data/data/azure/vnet/outputs.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm

#5715 cluster: unpack terraform binaries into install directory
  cmd/openshift-install/create.go
  pkg/asset/cluster/cluster.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/terraform/init.go
  pkg/terraform/stage.go
  pkg/terraform/stages/alibabacloud/stages.go
  pkg/terraform/stages/gcp/stages.go
  pkg/terraform/stages/split.go
  pkg/terraform/state.go
  pkg/terraform/terraform.go
Labels: approved, lgtm

#5614 Add IBM Power VS: tf data
  data/data/powervs/cluster/bootstrap/main.tf
  data/data/powervs/cluster/bootstrap/outputs.tf
  data/data/powervs/cluster/bootstrap/templates/bootstrap.ign
  data/data/powervs/cluster/bootstrap/variables.tf
  data/data/powervs/cluster/bootstrap/versions.tf
  data/data/powervs/cluster/dns/dns.tf
  data/data/powervs/cluster/dns/variables.tf
  data/data/powervs/cluster/dns/versions.tf
  data/data/powervs/cluster/loadbalancer/alb.tf
  data/data/powervs/cluster/loadbalancer/outputs.tf
  data/data/powervs/cluster/loadbalancer/sg.tf
  data/data/powervs/cluster/loadbalancer/variables.tf
  data/data/powervs/cluster/loadbalancer/versions.tf
  data/data/powervs/cluster/main.tf
  data/data/powervs/cluster/master/main.tf
  data/data/powervs/cluster/master/outputs.tf
  data/data/powervs/cluster/master/variables.tf
  data/data/powervs/cluster/master/versions.tf
  data/data/powervs/cluster/outputs.tf
  data/data/powervs/cluster/versions.tf
  data/data/powervs/iaas/power-iaas.tf
  data/data/powervs/iaas/variables.tf
  data/data/powervs/post-install/main.tf
  data/data/powervs/post-install/versions.tf
  data/data/powervs/variables-powervs.tf
Labels: approved, lgtm

#5797 Repin libvirt-version
  images/baremetal/Dockerfile.ci
Labels: approved, lgtm

#5802 Bug 2064170: Fixed Azure punctuation installconfig.controlPlane.platf…
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/azure/disk.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#5810 Revert "cluster: unpack terraform binaries into install directory"
  cmd/openshift-install/create.go
  pkg/asset/cluster/cluster.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/terraform/init.go
  pkg/terraform/stage.go
  pkg/terraform/stages/alibabacloud/stages.go
  pkg/terraform/stages/gcp/stages.go
  pkg/terraform/stages/split.go
  pkg/terraform/state.go
  pkg/terraform/terraform.go
Labels: approved, lgtm

#5749 Adding public&private zones to DNS config on PowerVS
  pkg/asset/manifests/dns.go
Labels: approved, lgtm

#5779 Power VS: Add basic install-config validation
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
Labels: approved, lgtm

#5796 vSphere session cleanup
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/vsphere/client.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/destroy/vsphere/vsphere.go
  pkg/terraform/stages/vsphere/stages.go
Labels: approved, lgtm

#5732 Add in-repo documentation for user-selectable capabilities
  docs/user/customization.md
Labels: approved, lgtm

#5745 Check for CVO failing condition before exiting as success
  cmd/openshift-install/create.go
Labels: approved, lgtm

#5809 Add Power VS-specific fields to cloud-provider config
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/powervs/cloudproviderconfig.go
Labels: approved, lgtm

#5813 Ensure ignition host is set to API VIP for Nutanix platform
  pkg/asset/ignition/machine/node.go
Labels: approved, lgtm

#5707 Changing the machine-config service name
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, ok-to-test

#5817 Bug 2075873: data/data/coreos/fcos.json: update initial FCOS to 35.20220327.3.0
  data/data/coreos/fcos.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5467 libvirt: use el8 repo for Google Cloud SDK
  images/libvirt/google-cloud-sdk.repo
Labels: approved, lgtm

#5803 data/bootstrap/files/usr/local/bin/bootkube: --rm all Podman containers
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#5704 update the vm types OCPQE-8674
  docs/user/azure/tested_instance_types.md
Labels: approved, lgtm

#5743 Bug 2048451: Fix proxy dial to pick all proxies
  go.mod
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5821 Ensure Nutanix API VIP is populated in the SAN for the MCS Cert
  pkg/asset/tls/mcscertkey.go
Labels: approved, lgtm

#5788 Bug 2076880: for vsphere ipi add cluster domain to the uploaded vm configs so that 30-local-dns-prepender can use it
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
  data/data/vsphere/bootstrap/main.tf
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#5818 Bug 2076393: vsphere: no longer logout of platform client before finished
  pkg/asset/installconfig/vsphere/vsphere.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5808 vsphere: upi, use community ignition provider
  upi/vsphere/lb/main.tf
  upi/vsphere/main.tf
Labels: approved, lgtm

#5801 Bug 2074659:Fix empty string usage in ValidateForProvisioning
  pkg/asset/installconfig/aws/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5829 Ensure that the /bin/terraform-provider-matchbox binary is present
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm

#5309 Provider Azure: Enable accelerated networking on control plane nodes
  data/data/azure/cluster/main.tf
  data/data/azure/cluster/master/master.tf
  data/data/azure/cluster/master/variables.tf
  data/data/azure/variables-azure.tf
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/azure/customization.md
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/machines.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/machinepool.go
Labels: approved, lgtm, qe-approved

#5828 Add bootstrap directory for Nutanix platform
  data/data/bootstrap/nutanix/OWNERS
  data/data/bootstrap/nutanix/README.md
  data/data/bootstrap/nutanix/files/etc/NetworkManager/conf.d/99-nutanix.conf
  data/data/bootstrap/nutanix/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
Labels: approved, lgtm

#5698 Determine Nic name in Bootstrap VM for ARM and x86
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/types/baremetal/defaults/platform.go
  pkg/types/baremetal/defaults/platform_test.go
Labels: approved, lgtm, platform/baremetal

#5598 baremetal: remove redundant proxy setting
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm

#5825 Unpack to install dir
  cmd/openshift-install/create.go
  pkg/asset/cluster/cluster.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/terraform/init.go
  pkg/terraform/stage.go
  pkg/terraform/stages/alibabacloud/stages.go
  pkg/terraform/stages/gcp/stages.go
  pkg/terraform/stages/split.go
  pkg/terraform/state.go
  pkg/terraform/terraform.go
Labels: approved, lgtm

#5482 Bug 2029438: Set rc-manager=unmanaged on baremetal bootstrap
  data/data/bootstrap/baremetal/files/etc/NetworkManager/conf.d/99-baremetal.conf
  data/data/bootstrap/baremetal/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/openstack/files/etc/NetworkManager/conf.d/99-openstack.conf
  data/data/bootstrap/openstack/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/ovirt/files/etc/NetworkManager/conf.d/99-ovirt.conf
  data/data/bootstrap/ovirt/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/vsphere/files/etc/NetworkManager/conf.d/99-vsphere.conf
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5824 vsphere: remove unused namer interface
  pkg/asset/installconfig/vsphere/vsphere.go
Labels: approved, lgtm

#5839 Fixup Azure marketplace pr 5799
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/machines.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
  pkg/types/azure/validation/platform.go
  pkg/types/validation/machinepools.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/latest/marketplaceordering/mgmt/marketplaceordering/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceagreements.go
  vendor/github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/version.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash

#5842 vsphere upi: missing etc resolv
  data/data/bootstrap/vsphere/files/etc/NetworkManager/conf.d/99-vsphere.conf
  data/data/bootstrap/vsphere/files/etc/NetworkManager/conf.d/99-vsphere.conf.template
Labels: lgtm

#5847 Bug 2078895: ovirt: fixing incorrect 'format' value validation
  pkg/types/ovirt/validation/machinepool.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5848 vSphere: ignore bootstrap eagerly scrub changes
  data/data/vsphere/bootstrap/main.tf
Labels: approved, lgtm

#5850 vsphere: upi ignition leak
  upi/vsphere/vm/variables.tf
Labels: approved, lgtm

#5823 agent: create skeleton commands and folders structure for agent-based installer
  OWNERS_ALIASES
  cmd/openshift-install/agent.go
  cmd/openshift-install/agent/OWNERS
  cmd/openshift-install/agent/create.go
  cmd/openshift-install/agent/waitfor.go
  cmd/openshift-install/main.go
  data/data/agent/OWNERS
  pkg/agent/OWNERS
  pkg/agent/build_image.go
  pkg/agent/create_manifests.go
  pkg/agent/wait_for.go
  pkg/asset/agent/OWNERS
Labels: approved, lgtm

#5812 Handle the mapi-provider-nutanix types moving to openshift/api
  data/data/install.openshift.io_installconfigs.yaml
  data/data/manifests/openshift/cloud-creds-secret.yaml.template
  go.mod
  go.sum
  pkg/asset/cluster/nutanix/nutanix.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/nutanix/nutanix.go
  pkg/asset/installconfig/nutanix/validation.go
  pkg/asset/machines/master.go
  pkg/asset/machines/nutanix/machines.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/template.go
  pkg/tfvars/nutanix/nutanix.go
  pkg/types/defaults/installconfig.go
  pkg/types/nutanix/platform.go
  pkg/types/nutanix/validation/platform.go
  pkg/types/nutanix/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/register.go
  vendor/github.com/openshift/api/machine/v1/types_alibabaprovider.go
  vendor/github.com/openshift/api/machine/v1/types_aws.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/machine-api-provider-nutanix/LICENSE
  vendor/github.com/openshift/machine-api-provider-nutanix/pkg/apis/addtoscheme_openshiftnutanixprovider_v1beta1.go
  vendor/github.com/openshift/machine-api-provider-nutanix/pkg/apis/apis.go
  vendor/github.com/openshift/machine-api-provider-nutanix/pkg/apis/nutanixprovider/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-provider-nutanix/pkg/apis/nutanixprovider/v1beta1/nutanixproviderconfig_types.go
  vendor/github.com/openshift/machine-api-provider-nutanix/pkg/apis/nutanixprovider/v1beta1/nutanixproviderstatus_types.go
  vendor/github.com/openshift/machine-api-provider-nutanix/pkg/apis/nutanixprovider/v1beta1/register.go
  vendor/github.com/openshift/machine-api-provider-nutanix/pkg/apis/nutanixprovider/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm
