Repository openshift/installer, pull requests merged in 2022-06, with the labels that each got.

#5927 Bug 2090487: SNO network type update
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/customization.md
  pkg/types/defaults/installconfig.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5954 Hard-code agent release image to fix CI
  pkg/agent/imagebuilder/content.go
  pkg/agent/imagebuilder/releaseimage.go
  pkg/agent/imagebuilder/releaseimage_test.go
Labels: approved, lgtm

#5944 AGENT-133: Export addStorageFiles and addSystemdUnits as functions
  pkg/asset/ignition/bootstrap/bootstrap_in_place.go
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm

#5943 AGENT-180: use nmstateconfig asset and improved validations/tests
  pkg/agent/imagebuilder/content.go
  pkg/agent/manifests/manifests.go
  pkg/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/agent_test.go
  pkg/asset/agent/manifests/agentpullsecret.go
  pkg/asset/agent/manifests/agentpullsecret_test.go
  pkg/asset/agent/manifests/infraenv.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm

#5931 Bug 2084580: Add check to validate cluster name for dots
  pkg/asset/installconfig/clustername.go
  pkg/types/validation/installconfig.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#5918 Bug 2085380: azure: validate VM image and instance HyperV gen match
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/azure/capabilities.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/capabilities.go
  pkg/asset/machines/azure/machines.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#5915 Bug 2084280: Remove optional services from permissions check
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#5925 BUG 2075459: IOPS was not being set even when manually configured
  data/data/aws/cluster/master/main.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/aws/machinepool.go
  pkg/types/aws/validation/machinepool.go
  pkg/types/aws/validation/machinepool_test.go
  pkg/types/aws/validation/platform_test.go
  pkg/types/validation/machinepools_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5941 Bug 2057582: For metal upi update source and versions of terraform providers
  upi/metal/bootstrap/main.tf
  upi/metal/bootstrap/packet.tf
  upi/metal/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5949 agent: default openshift version when pullspec it's a digest
  pkg/agent/imagebuilder/content.go
  pkg/agent/imagebuilder/releaseimage.go
  pkg/agent/imagebuilder/releaseimage_test.go
Labels: approved, lgtm

#5969 Bug 2057582: Remove all occurances of packet_device from upi/metal
  upi/metal/bootstrap/outputs.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5964 Bug 2093368: OpenStack: Fix LoadBalancer FIP deletion on destroy
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5945 AGENT-133: Move Ignition generation from fleeting code to asset
  data/data/agent/files/root/.docker/config.json.template
  pkg/agent/create_manifests.go
  pkg/agent/imagebuilder/content.go
  pkg/agent/manifests/manifests.go
  pkg/agent/manifests/nmstateconfig.go
  pkg/agent/manifests/nmstateconfig_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/image/releaseimage.go
  pkg/asset/agent/image/releaseimage_test.go
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/agent_test.go
  pkg/asset/agent/manifests/clusterdeployment.go
  pkg/asset/agent/manifests/network-scripts.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm

#5959 AGENT-40: Generate kubeconfig alongside ISO
  cmd/openshift-install/agent.go
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/systemd/units/assisted-service.service
  pkg/asset/agent/image/ignition.go
  pkg/asset/kubeconfig/agent.go
Labels: approved, lgtm

#5873 [release-4.11.0] Bug 2089563: Use Power VS machine provider spec from openshift/api
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/master.go
  pkg/asset/machines/powervs/machines.go
  pkg/asset/machines/worker.go
  pkg/tfvars/powervs/powervs.go
  pkg/types/powervs/machinepools.go
  pkg/types/powervs/validation/machinepool.go
  pkg/types/powervs/validation/machinepool_test.go
  vendor/github.com/openshift/api/config/v1/0000_03_marketplace-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_awsplacementgroup.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/register.go
  vendor/github.com/openshift/api/machine/v1/types.go
  vendor/github.com/openshift/api/machine/v1/types_alibabaprovider.go
  vendor/github.com/openshift/api/machine/v1/types_aws.go
  vendor/github.com/openshift/api/machine/v1/types_awsplacementgroup.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/types_powervsprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/machine-api-provider-powervs/LICENSE
  vendor/github.com/openshift/machine-api-provider-powervs/pkg/apis/addtoscheme_openshiftpowervsprovider_v1alpha1.go
  vendor/github.com/openshift/machine-api-provider-powervs/pkg/apis/apis.go
  vendor/github.com/openshift/machine-api-provider-powervs/pkg/apis/powervsprovider/v1alpha1/groupversion_info.go
  vendor/github.com/openshift/machine-api-provider-powervs/pkg/apis/powervsprovider/v1alpha1/powervsmachineproviderconfig_types.go
  vendor/github.com/openshift/machine-api-provider-powervs/pkg/apis/powervsprovider/v1alpha1/powervsmachineproviderstatus_types.go
  vendor/github.com/openshift/machine-api-provider-powervs/pkg/apis/powervsprovider/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5975 Improve user interface of agent installer
  cmd/openshift-install/create.go
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/cache.go
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/agentpullsecret_test.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm

#5957 AGENT-207: Assets for disconnected installs
  pkg/asset/agent/mirror/cabundle.go
  pkg/asset/agent/mirror/cabundle_test.go
  pkg/asset/agent/mirror/mirror.go
  pkg/asset/agent/mirror/registriesconf.go
  pkg/asset/agent/mirror/registriesconf_test.go
Labels: approved, lgtm

#5913 Bug 2085336: based on 4.11 CORS-1916 add the vm family
  docs/user/azure/tested_instance_types.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5905 Bug 2094902: Simplify cross-compiling
  hack/build.sh
  images/installer-artifacts/Dockerfile.rhel
  terraform/Makefile
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5963 Bug 2043298: bump RHCOS 4.9 boot images
  data/data/rhcos-aarch64.json
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5977 AGENT-133: Remove double embedding of agent data
  data/data/agent/embed.go
Labels: approved, lgtm

#5965 Bug 2090049: GCP Destroy resources that are owned by cluster
  pkg/destroy/gcp/cloudcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#5974 Bug 2068180: update doc for DNS and disconnected clusters
  docs/user/aws/install_upi.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5787 baremetal: static IP for bootstrap node
  data/data/bootstrap/baremetal/files/etc/NetworkManager/system-connections/nmconnection.template
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/installconfig/baremetal/validation.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/types/baremetal/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, platform/baremetal, px-approved, docs-approved, qe-approved

#5986 Bug 2094896: ensure all the required agent manifests are available
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/agentpullsecret.go
  pkg/asset/agent/manifests/agentpullsecret_test.go
  pkg/asset/agent/manifests/clusterdeployment.go
  pkg/asset/agent/manifests/clusterdeployment_test.go
  pkg/asset/agent/manifests/clusterimageset.go
  pkg/asset/agent/manifests/clusterimageset_test.go
  pkg/asset/agent/manifests/infraenv.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm, bugzilla/severity-high

#5981 Bug 2090816: baremetal: wait longer for bootstrap to complete
  cmd/openshift-install/create.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5988 Bug 2096352: Collect whole journal and netstat data
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#5989 OWNERS_ALIASES: update coreos aliases
  OWNERS_ALIASES
Labels: approved, lgtm

#5982 Bug 1859153: IAM instance profile race condition
  data/data/aws/bootstrap/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5998 Bug 2095917: Nutanix set osDisk with diskSizeGB rather than diskSizeMiB
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/machines/nutanix/machines.go
  pkg/asset/machines/worker.go
  pkg/types/nutanix/machinepool.go
  pkg/types/nutanix/validation/machinepool.go
  pkg/types/nutanix/validation/machinepool_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6010 Bug 2090816: Increase bootstrap timeout, not k8s API timeout
  cmd/openshift-install/create.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#5929 [release-4.11.0] Bug 2097239: Changed Lower limits of CPU for PowerVS Cloud
  pkg/types/powervs/validation/machinepool.go
  pkg/types/powervs/validation/machinepool_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5940 [release-4.11.0] Bug 2092296: Changed DefaultMachineCIDR of PowerVS to 192.168.0.0/16
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/types/defaults/installconfig.go
  pkg/types/installconfig.go
  pkg/types/powervs/defaults/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6007 Bug 2097260: Fixes openshift-install create manifest failure of Power VS Platform
  pkg/asset/installconfig/powervs/session.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6016 Bug 2049108: Fix network interface not found error
  data/data/aws/cluster/master/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#5987 Bug 2006965: bump RHCOS 4.8 boot images
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos-stream.json
  data/data/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#6012 Bug 2007087: bump RHCOS 4.7 boot images
  data/data/rhcos-amd64.json
  data/data/rhcos-ppc64le.json
  data/data/rhcos-s390x.json
  data/data/rhcos.json
  pkg/rhcos/ami_regions.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#5958 Bug 2098243: Adding error handling to powervs platform
  pkg/asset/installconfig/platform.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#5991 Bug 2094694: Nutanix cluster name validation
  pkg/asset/installconfig/clustername.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6020 Bug 2097940: PowerVS: Handle optional VPCRegion
  pkg/destroy/powervs/powervs.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#5899 [release-4.11.0] Bug 2095226: Added changes to verify cloud connection and dhcp serviceinstance details of a powervs instance
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/quota/quota.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6029 AGENT-230: Enable multipathd in agent ISO
  data/data/agent/files/etc/multipath.conf
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm

#5962 Bug 2047732: [IBM]Volume is not deleted after destroy cluster
  go.mod
  go.sum
  pkg/destroy/ibmcloud/disk.go
  pkg/destroy/ibmcloud/ibmcloud.go
  vendor/github.com/IBM/go-sdk-core/v5/core/base_service.go
  vendor/github.com/IBM/go-sdk-core/v5/core/constants.go
  vendor/github.com/IBM/go-sdk-core/v5/core/container_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/iam_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/version.go
  vendor/github.com/IBM/go-sdk-core/v5/core/vpc_instance_authenticator.go
  vendor/github.com/IBM/vpc-go-sdk/common/version.go
  vendor/github.com/IBM/vpc-go-sdk/vpcv1/vpc_v1.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#5947 Bug 2064693: Restore ability to use local clouds.yaml
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#6022 AGENT-187: AgentConfig asset
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
  pkg/asset/agent/image/ignition.go
  pkg/types/agent/agent_config_type.go
Labels: approved, lgtm

#6044 Bug 2100496: oVirt VM creation fails on empty affinity group description
  terraform/providers/ovirt/OWNERS
  terraform/providers/ovirt/go.mod
  terraform/providers/ovirt/go.sum
  terraform/providers/ovirt/vendor/github.com/ovirt/go-ovirt-client/affinitygroup.go
  terraform/providers/ovirt/vendor/github.com/ovirt/go-ovirt-client/retry.go
  terraform/providers/ovirt/vendor/github.com/ovirt/go-ovirt-client/template.go
  terraform/providers/ovirt/vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#6026 [release-4.8] Bug 2098162: Bootstrap timeout
  cmd/openshift-install/create.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#6033 Bug 1997704: [OpenStack] Document in-tree limitation for external LBs
  docs/user/openstack/known-issues.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#5992 AGENT-214: Mount mirror registries.conf for assisted-service
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/systemd/units/assisted-service.service.template
  data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
  go.mod
  go.sum
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/mirror/cabundle.go
  pkg/asset/agent/mirror/cabundle_test.go
  pkg/asset/agent/mirror/mirror.go
  pkg/asset/agent/mirror/registriesconf.go
  pkg/asset/agent/mirror/registriesconf_test.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: approved, lgtm

#6046 Bug 2099401: IBMCloud: Set regional URL for ibmcloud client
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
  pkg/asset/installconfig/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#6054 AGENT-227: Use root device hints from agent-config.yaml
  data/data/agent/systemd/units/apply-host-config.service.template
  data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
  data/data/agent/systemd/units/start-cluster-installation.service
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm

#6045 AGENT-144: Pre-generate InfraEnv ID
  data/data/agent/files/usr/local/bin/start-agent.sh.template
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/systemd/units/agent.service.template
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm

#6060 Bug 2093126: bump RHCOS 4.11 boot image metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, staff-eng-approved
