Repository openshift/installer, pull requests merged in 2022-12, with the labels that each got.

#6627 [ibmcloud] ibmcloud plugin "permission denied"
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm

#6602 Replace deprecated io/ioutil package
  cmd/openshift-install/create.go
  cmd/openshift-install/gather.go
  cmd/openshift-install/main.go
  data/unpack_test.go
  hack/build-coreos-manifest.go
  pkg/agent/cluster.go
  pkg/agent/validations_test.go
  pkg/asset/asset.go
  pkg/asset/asset_test.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/metadata.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/installconfig/azure/session.go
  pkg/asset/installconfig/gcp/session.go
  pkg/asset/installconfig/ovirt/config.go
  pkg/asset/installconfig/ovirt/credentials.go
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/installconfig/ssh.go
  pkg/asset/installconfig/vsphere/mock/vsphere_sim.go
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/state.go
  pkg/asset/store/assetcreate_test.go
  pkg/asset/store/filefetcher.go
  pkg/asset/store/filefetcher_test.go
  pkg/asset/store/store.go
  pkg/asset/templates/content/helper.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/destroy/quota/quota.go
  pkg/explain/cmd.go
  pkg/explain/data_test.go
  pkg/gather/ssh/ssh.go
  pkg/rhcos/builds.go
  pkg/terraform/stages/baremetal/stages.go
  pkg/terraform/stages/split.go
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/tfvars.go
Labels: approved, lgtm

#6610 GCP: remove private zone manipulation
  data/data/gcp/cluster/dns/base.tf
  data/data/gcp/cluster/dns/variables.tf
  data/data/gcp/cluster/main.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/manifests/dns.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#6612 [SPLAT-877] vSphere Zonal: validate dns and external load balancer
  pkg/asset/installconfig/vsphere/validation.go
Labels: approved, lgtm

#6641 OCPBUGS-4328: images: updating images to be consistent with ART
  .ci-operator.yaml
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6646 OCPBUGS-4355: Fix return value from execute()
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6488 OCPBUGS-3164: hold bootkube service until bootstrap has pivoted
  data/data/bootstrap/systemd/units/release-image-pivot.service.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6465 openstack: Refactor TFVars generation
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/openstack/rhcos_image.go
Labels: approved, lgtm

#6647 [release-4.11] OCPBUGS-4325: gcp: fail during validation if service usage is not enabled
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug

#6649 OCPBUGS-4125: Enable CVO unmanage overrides in bootstrap-in-place installations
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#6535 Alibaba: add the tags of the machine nodes
  data/data/alibabacloud/bootstrap/main.tf
  data/data/alibabacloud/cluster/main.tf
  pkg/asset/machines/alibabacloud/machines.go
  pkg/destroy/alibabacloud/alibabacloud.go
Labels: approved, lgtm

#6595 platformprovisioncheck: fix shadowing of `err` variable
  pkg/asset/installconfig/platformprovisioncheck.go
Labels: approved, lgtm

#6651 Wait longer for VM to obtain IP from DHCP in PowerVS
  data/data/powervs/bootstrap/vm/main.tf
  data/data/powervs/cluster/master/vm/main.tf
Labels: approved, lgtm

#6658 image: Updating installer images to be consistent with ART
  .ci-operator.yaml
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  pkg/asset/agent/manifests/network-scripts.go
  pkg/destroy/aws/aws.go
  pkg/destroy/aws/ec2helpers.go
  pkg/destroy/aws/iamhelpers.go
  pkg/lineprinter/lineprinter.go
  pkg/migrate/azure/privatedns.go
  pkg/types/openstack/validation/networkextensions/networkextensions.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#6519 OCPBUGS-2130: import ova resource cluster path fix
  terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6626 OCPBUGS-3196: Set ip=dhcp,dhcp6 for master nodes on dualstack
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6532 CORS-2291: terraform: save logs to a file
  go.mod
  go.sum
  pkg/terraform/terraform.go
  vendor/github.com/hashicorp/go-version/CHANGELOG.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/terraform-exec/internal/version/version.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/cmd.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/cmd_default.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/cmd_linux.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/exit_errors.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/force_unlock.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/init.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/state_pull.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/state_push.go
  vendor/github.com/hashicorp/terraform-exec/tfexec/terraform.go
  vendor/github.com/zclconf/go-cty/cty/capsule_ops.go
  vendor/github.com/zclconf/go-cty/cty/element_iterator.go
  vendor/github.com/zclconf/go-cty/cty/gob.go
  vendor/github.com/zclconf/go-cty/cty/map_type.go
  vendor/github.com/zclconf/go-cty/cty/path_set.go
  vendor/github.com/zclconf/go-cty/cty/primitive_type.go
  vendor/github.com/zclconf/go-cty/cty/set/gob.go
  vendor/github.com/zclconf/go-cty/cty/set/iterator.go
  vendor/github.com/zclconf/go-cty/cty/set/ops.go
  vendor/github.com/zclconf/go-cty/cty/set/rules.go
  vendor/github.com/zclconf/go-cty/cty/set/set.go
  vendor/github.com/zclconf/go-cty/cty/set_helper.go
  vendor/github.com/zclconf/go-cty/cty/set_internals.go
  vendor/github.com/zclconf/go-cty/cty/types_to_register.go
  vendor/github.com/zclconf/go-cty/cty/value_init.go
  vendor/github.com/zclconf/go-cty/cty/value_ops.go
  vendor/modules.txt
Labels: approved, lgtm

#6498 OCPBUGS-1560: vsphere zonal, terraform depends on ova import
  data/data/vspherezoning/pre-bootstrap/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate

#6596 OCPBUGS-3668: fully qualified username must be provided
  pkg/asset/installconfig/vsphere/permission_test.go
  pkg/asset/installconfig/vsphere/permissions.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/installconfig/vsphere/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6591 Use backoff functions in PowerVS destroy logic
  pkg/destroy/powervs/cloud-instance.go
  pkg/destroy/powervs/cloud-sshkey.go
  pkg/destroy/powervs/cloudconnection.go
  pkg/destroy/powervs/cloudobjectstorage.go
  pkg/destroy/powervs/dhcp.go
  pkg/destroy/powervs/dns-dns.go
  pkg/destroy/powervs/dns-resource.go
  pkg/destroy/powervs/dns.go
  pkg/destroy/powervs/image.go
  pkg/destroy/powervs/job.go
  pkg/destroy/powervs/loadbalancer.go
  pkg/destroy/powervs/power-instance.go
  pkg/destroy/powervs/power-sshkey.go
  pkg/destroy/powervs/powervs.go
  pkg/destroy/powervs/publicgateway.go
  pkg/destroy/powervs/securitygroup.go
  pkg/destroy/powervs/subnet.go
  pkg/destroy/powervs/vpc.go
Labels: approved, lgtm

#6662 OCPBUGS-4367: Fix missing debug messages when getting baseISO
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/oc.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6505 CORS-2147: Add documentation for the client certs authentication
  docs/dev/azure/azure_client_certs_auth.md
Labels: approved, lgtm

#6674 OCPBUGS-3987: Check nmstateconfig content in agent-config.yaml
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6668 [release-4.11] OCPBUGS-4530: Enable CVO unmanage overrides in bootstrap-in-place installations
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc
  pkg/asset/ignition/bootstrap/bootstrap.go
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#6683 Save rendezvous IP in a file 'rendezvousIP' alongside the ISO
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm

#6696 OWNERS_ALIASES: Remove lucab
  OWNERS_ALIASES
Labels: approved, lgtm

#6686 Consolidate loadsdk debug statements
  pkg/destroy/powervs/powervs.go
Labels: approved, lgtm

#6528 OCPBUGS-2891: aws: destroy: delete ELB listeners
  pkg/destroy/aws/elbhelpers.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6692 Switch back to gp2 ebs volume type for bootstrap instance
  data/data/aws/bootstrap/main.tf
Labels: approved, lgtm, ok-to-test

#6688 OCPBUGS-3706: Wait longer for baremetal
  pkg/agent/waitfor.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6601 CORS-2340: hack: replace deprecated go-lint
  .golangci.yaml
  go.mod
  go.sum
  hack/go-lint.sh
  tools.go
  vendor/golang.org/x/lint/.travis.yml
  vendor/golang.org/x/lint/CONTRIBUTING.md
  vendor/golang.org/x/lint/LICENSE
  vendor/golang.org/x/lint/README.md
  vendor/golang.org/x/lint/lint.go
  vendor/modules.txt
Labels: approved, lgtm

#6694 OCPBUGS-4809: Azure: toggle image in machinesets
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/master.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, jira/valid-bug

#6703 OCPBUGS-2996: bump RHCOS 4.13 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6712 linter: fix issues since revision 75173a17cf
  .golangci.yaml
  cmd/openshift-install/agent_internal_integration_test.go
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/oc.go
  pkg/asset/agent/manifests/agentpullsecret.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
  pkg/asset/agent/manifests/util_test.go
  pkg/asset/asset.go
  pkg/asset/installconfig/vsphere/permissions.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/state.go
  pkg/asset/store/assetcreate_test.go
  pkg/asset/store/filefetcher_test.go
  pkg/asset/store/store.go
  pkg/destroy/alibabacloud/alibabacloud.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/destroy/openstack/openstack.go
  pkg/destroy/powervs/cloudobjectstorage.go
  pkg/destroy/powervs/dns-dns.go
  pkg/destroy/powervs/dns-resource.go
  pkg/destroy/powervs/powervs.go
  pkg/destroy/quota/quota.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#6700 PowerVS: Defer cancel when calling contextWithTimeout
  pkg/destroy/powervs/cloud-instance.go
  pkg/destroy/powervs/cloud-sshkey.go
  pkg/destroy/powervs/cloudconnection.go
  pkg/destroy/powervs/cloudobjectstorage.go
  pkg/destroy/powervs/dhcp.go
  pkg/destroy/powervs/dns-dns.go
  pkg/destroy/powervs/dns-resource.go
  pkg/destroy/powervs/image.go
  pkg/destroy/powervs/job.go
  pkg/destroy/powervs/loadbalancer.go
  pkg/destroy/powervs/power-instance.go
  pkg/destroy/powervs/power-sshkey.go
  pkg/destroy/powervs/powervs.go
  pkg/destroy/powervs/publicgateway.go
  pkg/destroy/powervs/securitygroup.go
  pkg/destroy/powervs/subnet.go
  pkg/destroy/powervs/vpc.go
Labels: approved, lgtm

#6707 OCPBUGS-4941: OpenStack: Force JSON content-type in Swift object listing
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#6679 GCP: Tfvars will determine the user has create firewall permissions
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/vsphere/mock/authmanager_generated.go
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#6681 [release-4.11] OCPBUGS-4405: UPI: Azure: create HyperV2 rhcos image
  upi/azure/02_storage.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#6594 cmd: update import of deprecated terminal package
  cmd/openshift-install/main.go
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/sys/cpu/cpu_other_ppc64x.go
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/unix/asm_bsd_ppc64.s
  vendor/golang.org/x/sys/unix/dirent.go
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_illumos.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd_libc.go
  vendor/golang.org/x/sys/unix/syscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/syscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix_gc.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_illumos_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysctl_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsysctl_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_illumos_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_solaris_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, lgtm

#6656 openstack: Rely on Go's stdlib for errors
  pkg/asset/cluster/openstack/openstack.go
  pkg/asset/installconfig/openstack/openstack.go
  pkg/asset/installconfig/openstack/session.go
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validvaluesfetcher.go
  pkg/destroy/openstack/glance.go
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm

#6699 AGENT-438: Create PXE files
  cmd/openshift-install/agent.go
  cmd/openshift-install/create.go
  cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
  pkg/asset/agent/image/agentpxefiles.go
Labels: approved, lgtm, tide/merge-method-squash

#6710 OSASINFRA-3057: openstack: Document Image Registry migration to Swift
  docs/user/openstack/README.md
  docs/user/openstack/image-registry-storage-swift.md
Labels: approved, lgtm

#6720 OCPBUGS-3362: bump RHCOS 4.11 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#6697 OCPBUGS-3032: Report status on the console immediately
  data/data/agent/files/usr/local/bin/install-status.sh
  data/data/agent/files/usr/local/bin/issue_status.sh
  data/data/agent/files/usr/local/bin/set-node-zero.sh.template
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
  data/data/agent/systemd/units/install-status.service
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6729 OCPBUGS-5151: baremetal: Extra time for provisioning interface
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important
