Repository openshift/installer, pull requests merged in 2023-05, with the labels that each got.

#7141 [release-4.12] OCPBUGS-7400: Check for AWS STS installation before trying to get all IAM Roles
  pkg/destroy/aws/iamhelpers.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7135 OCPBUGS-11792: update RHCOS 4.14 bootimage metadata to 414.92.202304252144-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7156 OCPBUGS-11799: update RHCOS 4.13 bootimage metadata to 413.92.202305021736-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7149 OCPBUGS-12964: Bootstrap on aws should have same metadata service type as on other nodes
  data/data/aws/bootstrap/main.tf
  data/data/aws/bootstrap/variables.tf
  data/data/aws/variables-aws.tf
  pkg/tfvars/aws/aws.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7131 OCPBUGS-12749: [Alibaba] update the bandwidth value of EIP
  data/data/alibabacloud/cluster/vpc/eip.tf
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7117 OCPBUGS-11921: GCP XPN: Pass instance service acct in manual mode
  pkg/asset/machines/gcp/machines.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7165 OCPBUGS-13107: openstack destroy: Limit Swift workers to 3
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#7164 OCPBUGS-13052: bump RHCOS 4.12 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7152 pass payload version and manifests to kas and kcm
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, bugzilla/valid-bug

#7176 OCPBUGS-13253: update RHCOS 4.14 bootimage metadata to 414.92.202305090606-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7158 remove special cases for featureset in rendering
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, bugzilla/valid-bug

#6585 OCPBUGS-3542: Add bootstrapExternalStaticDNS
  data/data/bootstrap/baremetal/files/etc/NetworkManager/system-connections/nmconnection.template
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/installconfig/baremetal/validation.go
  pkg/types/baremetal/platform.go
Labels: lifecycle/stale, approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#7172 OCPBUGS-13300: masters on a single compute server group
  docs/user/openstack/README.md
  pkg/asset/machines/openstack/machines.go
  scripts/openstack/manifest-tests/server-groups/install-config.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7183 OCPBUGS-13628: Revert "remove special cases for featureset in rendering"
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6902 OCPBUGS-7978: FCOS: bump to latest stable version
  data/data/coreos/fcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7189 OCPBUGS-13547: remove special cases for featureset in rendering
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7160 OCPBUGS-13547: Ensure --payload-version is set for MCO on bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7154 OCPBUGS-9378: vSphere set bootstrap/master efi
  data/data/vsphere/bootstrap/main.tf
  data/data/vsphere/master/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7194 OCPBUGS-13718: ic: azure: validate diskTypes in AzureStack
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7171 OCPBUGS-13552: vSphere Add ova sha query; additional debugging
  pkg/asset/rhcos/image.go
  pkg/tfvars/internal/cache/cache.go
  terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7101 OCPBUGS-7410: Reject active VPC connections before service destroy
  pkg/destroy/aws/ec2helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7116 OCPBUGS-12202: Relax vsphere, nutanix VIP validation
  pkg/asset/agent/installconfig_test.go
  pkg/asset/installconfig/nutanix/nutanix.go
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6996 OCPBUGS-14076: PowerVS: Remove ClusterOSImage
  pkg/asset/machines/powervs/machinesets.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7145 OCPBUGS-14077: MULTIARCH-3492: Avoid conflicting subnets
  pkg/types/defaults/installconfig.go
  pkg/types/powervs/defaults/platform.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7180 OCPBUGS-1769: Ignore IAM Roles that the Installer is not authorized to access
  pkg/destroy/aws/iamhelpers.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7192 OCPBUGS-13764: Support /dev/disk/by-path root device hints
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
  pkg/types/baremetal/rootdevice.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7061 AGENT-555: Move Rendezvous Host config to separate file
  data/data/agent/files/etc/assisted/agent-installer.env.template
  data/data/agent/files/usr/local/bin/common.sh
  data/data/agent/files/usr/local/bin/set-node-zero.sh
  data/data/agent/files/usr/local/bin/start-agent.sh
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
  data/data/agent/files/usr/local/bin/wait-for-assisted-service.sh
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/files/usr/local/share/assisted-service/images.env.template
  data/data/agent/systemd/units/agent-interactive-console.service
  data/data/agent/systemd/units/agent.service.template
  data/data/agent/systemd/units/apply-host-config.service
  data/data/agent/systemd/units/assisted-service.service.template
  data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
  data/data/agent/systemd/units/start-cluster-installation.service
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7102 AGENT-567: Re-enable 'create pxe-files' command
  cmd/openshift-install/agent.go
  cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7132 OCPBUGS-12750: [Alibaba] update the bandwidth value of EIP
  data/data/alibabacloud/cluster/vpc/eip.tf
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7127 OSASINFRA-3153: move `loadBalancer` API to GA for OpenStack
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/techpreview.go
  pkg/types/openstack/validation/techpreview_test.go
  pkg/types/validation/installconfig_test.go
  scripts/openstack/manifest-tests/lb-default-techpreview/install-config.yaml
  scripts/openstack/manifest-tests/lb-default-techpreview/test_cluster-infra.py
  scripts/openstack/manifest-tests/lb-managed/install-config.yaml
  scripts/openstack/manifest-tests/lb-unmanaged/install-config.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
