Repository openshift/installer, pull requests merged in 2023-01, with the labels that each got.

#6665 Better logic to derive vpcRegion/Zone from vpcName/Subnets
  data/data/powervs/cluster/main.tf
  data/data/powervs/variables-powervs.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/metadata.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/tfvars/powervs/powervs.go
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm

#6730 OCPBUGS-3706: Improve error reporting from agent wait-for install-complete
  cmd/openshift-install/agent/waitfor.go
  pkg/agent/waitfor.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6617 Bug OCPBUGS-3921: OpenStack: fix bootstrap destroy cmd
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/openstack/openstack.go
  pkg/destroy/bootstrap/bootstrap.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6534 OCPBUGS-2881: Destroy the service and host project dns records
  pkg/destroy/gcp/dns.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6695 CORS-2449: Create CPMS manifest
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/master.go
Labels: approved, lgtm

#6739 OCPBUGS-4874: Remove order dependency for agent CLI string
  pkg/types/baremetal/validation/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6738 SPLAT-900: provision VMs in to failure domains
  upi/vsphere/main.tf
  upi/vsphere/terraform.tfvars.example
  upi/vsphere/variables.tf
  upi/vsphere/vm/main.tf
  upi/vsphere/vm/variables.tf
Labels: approved, lgtm

#6716 OCPBUGS-2088: Validate that the rendevousIP is assigned to a master
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6737 Expose Azure useImageGallery parameter in the MachineSets() call
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, backport-risk-assessed

#6754 GCP XPN: remove tech preview feature gate
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/platform.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#6518 OCPBUGS-2743: skip sts credentials check in terraform
  data/data/aws/bootstrap/main.tf
  data/data/aws/cluster/main.tf
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#6666 OCPBUGS-1769: Check for AWS STS installation before trying to get all IAM Roles
  pkg/destroy/aws/iamhelpers.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6750 SPLAT-901: set default for variables that are deprecated by failure_domains
  upi/vsphere/variables.tf
Labels: approved, lgtm

#6469 OCPBUGS-881: fail to create install-config.yaml as apiVIP and ingress VIP are not in machine networks
  pkg/asset/installconfig/nutanix/nutanix.go
  pkg/asset/installconfig/ovirt/network.go
  pkg/asset/installconfig/vsphere/vsphere.go
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#6741 OCPBUGS-5324: CVE-2021-4235 go-yaml: Denial of Service in go-yaml
  go.mod
  go.sum
  pkg/asset/manifests/vsphere/cloudproviderconfig.go
  terraform/terraform/go.mod
  terraform/terraform/go.sum
  terraform/terraform/vendor/gopkg.in/yaml.v2/.travis.yml
  terraform/terraform/vendor/gopkg.in/yaml.v2/apic.go
  terraform/terraform/vendor/gopkg.in/yaml.v2/yaml.go
  terraform/terraform/vendor/modules.txt
  vendor/github.com/go-yaml/yaml/.travis.yml
  vendor/github.com/go-yaml/yaml/LICENSE
  vendor/github.com/go-yaml/yaml/LICENSE.libyaml
  vendor/github.com/go-yaml/yaml/NOTICE
  vendor/github.com/go-yaml/yaml/README.md
  vendor/github.com/go-yaml/yaml/apic.go
  vendor/github.com/go-yaml/yaml/decode.go
  vendor/github.com/go-yaml/yaml/emitterc.go
  vendor/github.com/go-yaml/yaml/encode.go
  vendor/github.com/go-yaml/yaml/parserc.go
  vendor/github.com/go-yaml/yaml/readerc.go
  vendor/github.com/go-yaml/yaml/resolve.go
  vendor/github.com/go-yaml/yaml/scannerc.go
  vendor/github.com/go-yaml/yaml/sorter.go
  vendor/github.com/go-yaml/yaml/writerc.go
  vendor/github.com/go-yaml/yaml/yaml.go
  vendor/github.com/go-yaml/yaml/yamlh.go
  vendor/github.com/go-yaml/yaml/yamlprivateh.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6747 AGENT-501: Make it easier to change node zero IP and SERVICE_BASE_URL
  data/data/agent/files/etc/assisted/agent-installer.env.template
  data/data/agent/files/usr/local/bin/common.sh
  data/data/agent/files/usr/local/bin/common.sh.template
  data/data/agent/files/usr/local/bin/extract-agent.sh
  data/data/agent/files/usr/local/bin/set-node-zero.sh
  data/data/agent/files/usr/local/bin/set-node-zero.sh.template
  data/data/agent/files/usr/local/bin/start-agent.sh
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
  data/data/agent/systemd/units/apply-host-config.service
  data/data/agent/systemd/units/assisted-service-pod.service
  data/data/agent/systemd/units/assisted-service.service.template
  data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
  data/data/agent/systemd/units/install-status.service
  data/data/agent/systemd/units/start-cluster-installation.service
Labels: approved, lgtm

#6755 BUG 2110982: GCP skip public loadbalancer ip addresses
  data/data/gcp/cluster/network/firewall.tf
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6763 OCPBUGS-5770: CVE-2021-4238: goutils: update for randomness fix
  go.mod
  go.sum
  terraform/providers/alicloud/go.mod
  terraform/providers/alicloud/go.sum
  terraform/providers/alicloud/vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  terraform/providers/alicloud/vendor/github.com/Masterminds/goutils/randomstringutils.go
  terraform/providers/alicloud/vendor/github.com/Masterminds/goutils/stringutils.go
  terraform/providers/alicloud/vendor/modules.txt
  terraform/providers/google/go.mod
  terraform/providers/google/go.sum
  terraform/providers/google/vendor/modules.txt
  terraform/providers/nutanix/go.mod
  terraform/providers/nutanix/go.sum
  terraform/providers/nutanix/vendor/modules.txt
  terraform/providers/openstack/go.mod
  terraform/providers/openstack/go.sum
  terraform/providers/openstack/vendor/modules.txt
  terraform/providers/time/go.mod
  terraform/providers/time/go.sum
  terraform/providers/time/vendor/modules.txt
  terraform/providers/vsphere/go.mod
  terraform/providers/vsphere/go.sum
  terraform/providers/vsphere/vendor/modules.txt
  terraform/providers/vsphereprivate/go.mod
  terraform/providers/vsphereprivate/go.sum
  terraform/providers/vsphereprivate/vendor/modules.txt
  terraform/terraform/go.mod
  terraform/terraform/go.sum
  terraform/terraform/vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  terraform/terraform/vendor/github.com/Masterminds/goutils/randomstringutils.go
  terraform/terraform/vendor/github.com/Masterminds/goutils/stringutils.go
  terraform/terraform/vendor/modules.txt
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6685 [release-4.11] OCPBUGS-4685: out-of-bounds read in golang.org/x/text/language leads to DoS
  go.mod
  go.sum
  terraform/providers/alicloud/go.mod
  terraform/providers/alicloud/go.sum
  terraform/providers/alicloud/vendor/modules.txt
  terraform/providers/aws/go.mod
  terraform/providers/aws/go.sum
  terraform/providers/aws/vendor/modules.txt
  terraform/providers/azurerm/go.mod
  terraform/providers/azurerm/go.sum
  terraform/providers/azurerm/vendor/modules.txt
  terraform/providers/azurestack/go.mod
  terraform/providers/azurestack/go.sum
  terraform/providers/azurestack/vendor/modules.txt
  terraform/providers/google/go.mod
  terraform/providers/google/go.sum
  terraform/providers/google/vendor/modules.txt
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/modules.txt
  terraform/providers/ignition/go.mod
  terraform/providers/ignition/go.sum
  terraform/providers/ignition/vendor/modules.txt
  terraform/providers/ironic/go.mod
  terraform/providers/ironic/go.sum
  terraform/providers/ironic/vendor/modules.txt
  terraform/providers/libvirt/go.mod
  terraform/providers/libvirt/go.sum
  terraform/providers/libvirt/vendor/modules.txt
  terraform/providers/local/go.mod
  terraform/providers/local/go.sum
  terraform/providers/local/vendor/modules.txt
  terraform/providers/nutanix/go.mod
  terraform/providers/nutanix/go.sum
  terraform/providers/nutanix/vendor/modules.txt
  terraform/providers/openstack/go.mod
  terraform/providers/openstack/go.sum
  terraform/providers/openstack/vendor/modules.txt
  terraform/providers/ovirt/go.mod
  terraform/providers/ovirt/go.sum
  terraform/providers/ovirt/vendor/modules.txt
  terraform/providers/time/go.mod
  terraform/providers/time/go.sum
  terraform/providers/time/vendor/modules.txt
  terraform/providers/vsphere/go.mod
  terraform/providers/vsphere/go.sum
  terraform/providers/vsphere/vendor/modules.txt
  terraform/providers/vsphereprivate/go.mod
  terraform/providers/vsphereprivate/go.sum
  terraform/providers/vsphereprivate/vendor/modules.txt
  terraform/terraform/go.mod
  terraform/terraform/go.sum
  terraform/terraform/vendor/golang.org/x/text/internal/language/language.go
  terraform/terraform/vendor/golang.org/x/text/internal/language/parse.go
  terraform/terraform/vendor/golang.org/x/text/language/parse.go
  terraform/terraform/vendor/modules.txt
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#6487 OCPBUGS-1695: Update FCOS to latest 37.20221127.3.0 stable
  data/data/coreos/fcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6761 OCPBUGS-5734: make VIP 168.63.129.16 noProxy in all clouds except Public
  pkg/asset/manifests/proxy.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug

#6632 CORS-2405: Create ControlPlaneMachineSet CRDs
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/master.go
Labels: approved, lgtm

#6269 Generate the cloudproviderconfig manifests for integration of nutanix-ccm to OCP
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/nutanix/cloudproviderconfig.go
Labels: approved, lgtm

#6409 OCPBUGS-1612: vsphere: set default resource pool when missing failure domain topology
  pkg/types/vsphere/defaults/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6752 CORS-2449: gcp: Set pre-created CPMS to Active state
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/gcp/machines_test.go
  pkg/asset/machines/master.go
Labels: approved, lgtm

#6734 OCPBUGS-5184: azure: validate Windows-only VM types
  pkg/asset/installconfig/azure/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug

#6684 OCPBUGS-4654: azure: upi: use Image Gallery in ARM templates
  docs/user/azure/install_upi.md
  upi/azure/02_storage.json
  upi/azure/04_bootstrap.json
  upi/azure/05_masters.json
  upi/azure/06_workers.json
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug

#6740 OCPBUGS-3253: Warn if agent assets detected when using non-agent waitfor
  cmd/openshift-install/create.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6776 OCPBUGS-5461: Allow NO_PROXY to contain IPs
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#6733 OCPBUGS-5182: validate additional confidential VM types
  pkg/asset/installconfig/azure/validation.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate

#6777 AGENT-504: Agent extract binary
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/cache.go
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm

#6515 Bug 2070744: Fix infinite loop error
  pkg/destroy/aws/shared.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#6727 CORS-2469: upi: Document removal of CPMS for UPI installation
  docs/user/azure/install_upi.md
  docs/user/azure/install_upi_azurestack.md
  docs/user/gcp/install_upi.md
Labels: approved, lgtm

#6787 OCPBUGS-6086: OpenStack: Force JSON content-type in Swift
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug

#6790 OCPBUGS-5959: bump RHCOS 4.13 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6756 AGENT-453: Create interactive console service for agent installer
  data/data/agent/files/usr/local/bin/agent-interactive-console.sh
  data/data/agent/systemd/units/agent-interactive-console.service
  data/data/agent/systemd/units/agent-tui.path
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm

#6771 GCP: Remove the BYOH code
  data/data/gcp/cluster/dns/base.tf
  data/data/gcp/cluster/dns/variables.tf
  data/data/gcp/cluster/main.tf
  data/data/gcp/variables-gcp.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/manifests/dns.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#6789 CORS-2479: bootstrap: set 0644 mode for registries.conf
  data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
Labels: approved, lgtm

#6292 CFE-583 : Update install-config CRD to support azure userTags.
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
Labels: approved, lgtm, tide/merge-method-squash

#6611 Bug 2072202: Check for reachability of API and API-Int URLs later in bootkube
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6772 PowerVS: Remove region requirement
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/powervs/session.go
  pkg/destroy/powervs/powervs.go
  pkg/types/powervs/platform.go
  pkg/types/powervs/powervs_regions.go
  pkg/types/powervs/validation/platform.go
  pkg/types/powervs/validation/platform_test.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#6786 AGENT-505: Embed agent-tui binary in the agent ISO
  cmd/openshift-install/agent_internal_integration_test.go
  cmd/openshift-install/testdata/agent/image/assets/default_assets.txt
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/cpio.go
Labels: approved, lgtm, jira/valid-reference

#6769 OCPBUGS-5782: CVE-2021-4235: Denial of Service in go-yaml
  go.mod
  go.sum
  pkg/asset/manifests/vsphere/cloudproviderconfig.go
  terraform/terraform/go.mod
  terraform/terraform/go.sum
  terraform/terraform/vendor/gopkg.in/yaml.v2/.travis.yml
  terraform/terraform/vendor/gopkg.in/yaml.v2/apic.go
  terraform/terraform/vendor/gopkg.in/yaml.v2/yaml.go
  terraform/terraform/vendor/modules.txt
  vendor/github.com/go-yaml/yaml/.travis.yml
  vendor/github.com/go-yaml/yaml/LICENSE
  vendor/github.com/go-yaml/yaml/LICENSE.libyaml
  vendor/github.com/go-yaml/yaml/NOTICE
  vendor/github.com/go-yaml/yaml/README.md
  vendor/github.com/go-yaml/yaml/apic.go
  vendor/github.com/go-yaml/yaml/decode.go
  vendor/github.com/go-yaml/yaml/emitterc.go
  vendor/github.com/go-yaml/yaml/encode.go
  vendor/github.com/go-yaml/yaml/parserc.go
  vendor/github.com/go-yaml/yaml/readerc.go
  vendor/github.com/go-yaml/yaml/resolve.go
  vendor/github.com/go-yaml/yaml/scannerc.go
  vendor/github.com/go-yaml/yaml/sorter.go
  vendor/github.com/go-yaml/yaml/writerc.go
  vendor/github.com/go-yaml/yaml/yaml.go
  vendor/github.com/go-yaml/yaml/yamlh.go
  vendor/github.com/go-yaml/yaml/yamlprivateh.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#6717 OCPBUGS-4549: destroy: azure: handle `nil` responses from msgraph sdk
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#6809 OCPBUGS-6663: Check platform baremetal settings against default values
  pkg/asset/agent/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
