Repository openshift/installer, pull requests merged in 2023-09, with the labels that each got.

#7461 OCPBUGS-18457: Fix PXE integration tests
  cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
  cmd/openshift-install/testdata/agent/pxe/configurations/sno_arm.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7454 OCPBUGS-18320: CORS-2445: GCP: Add osImage to the install config
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/machines/gcp/machines.go
  pkg/types/gcp/machinepools.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7462 integration tests: Swap order of diff arguments
  cmd/openshift-install/agent_internal_integration_test.go
Labels: approved, lgtm, acknowledge-critical-fixes-only

#7458 OCPBUGS-18365: Fix defaulting of userManagedNetworking value
  pkg/asset/agent/manifests/agentclusterinstall.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7460 OCPBUGS-18450: AWS permission missing for security group viewing.
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7381 OSDOCS-6999: tested machine series 'C3', 'C2D'
  docs/user/gcp/tested_instance_types.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7467 OCPBUGS-18428: Add ip=dhcp,dhcp6 kernel param for vSphere dual-stack
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#7445 Implement workaround to allow SNO installations for OKD/FCOS
  data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
  data/data/bootstrap/systemd/units/release-image-pivot.service.template
Labels: approved, lgtm, acknowledge-critical-fixes-only

#7451 OCPBUGS-18304: for vsphere ipi add cluster domain to the uploaded vm configs so that…
  data/data/vsphere/bootstrap/main.tf
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7448 OCPBUGS-18113: Do not set FailureDomains on CPMS when in a single zone Azure region
  pkg/asset/machines/azure/machines.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7432 OCPBUGS-11093: Azure: don't set default subscriptionID for disk encryption sets
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/azure/validation/disk.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7487 OCPBUGS-19017: Add Net capabilities to dnsmasq container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-dnsmasq.container
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#7490 OCPBUGS-19037: Handle agent tui failure gracefully
  data/data/agent/systemd/units/agent-interactive-console.service
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7208 OSASINFRA-3236: deps: Bump gophercloud to v1.6.0
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/README.md
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/urls.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/hashicorp/go-uuid/.travis.yml
  vendor/github.com/hashicorp/go-uuid/LICENSE
  vendor/github.com/hashicorp/go-uuid/README.md
  vendor/github.com/hashicorp/go-uuid/uuid.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7417 OCPBUGS-17218: Warn when firewall rull missing.
  pkg/asset/cluster/tfvars.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7323 AGENT: publish services diagrams
  docs/user/agent/agent-services.md
  docs/user/agent/agent_installer_services-automated_flow.png
  docs/user/agent/agent_installer_services-unconfigured_ignition_and_config_image_flow.png
Labels: approved, lgtm

#7429 OCPBUGS-17724: Graceful fail for AWS getUser on destroy
  pkg/destroy/aws/iamhelpers.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7411 OpenStack: Set external network for cloud-provider
  pkg/asset/installconfig/openstack/session.go
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Labels: approved, lgtm

#7457 SPLAT-1170: enable cloud controller manager type to be defined
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/manifests/external/infrastructure.go
  pkg/asset/manifests/infrastructure.go
  pkg/types/external/defaults/platform.go
  pkg/types/external/platform.go
Labels: approved, lgtm, jira/valid-reference

#7502 LICENSE: Update
  LICENSE
Labels: approved, lgtm

#7499 OCPBUGS-18945: update RHCOS 4.15 bootimage metadata to 415.92.202309161058-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7482 OpenStack: fix IPv6 docs
  docs/user/openstack/deploy_dual_stack_cluster.md
Labels: approved, lgtm

#7513 OCPBUGS-18876: Pass CPUPartitioning via install-config overrides if set
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7508 AGENT-710: Use invoker for bootstrap template generation
  data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
  data/data/bootstrap/systemd/units/release-image-pivot.service.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-reference

#7514 OCPBUGS-12707: always write AWS cloud.conf
  pkg/asset/manifests/cloudproviderconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7491 OCPBUGS-18830: AWS terraform bootstrap destroy will not refresh state
  pkg/terraform/stages/aws/stages.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7518 OCPBUGS-18187: Increase bootstrap timeout for vSphere platform by 30 mins
  cmd/openshift-install/create.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7527 OCPBUGS-19699: Remove warning about CPUPartitioning
  pkg/asset/agent/installconfig.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7419 pkg/asset/installconfig/powervs: fix dropped error
  pkg/asset/installconfig/powervs/metadata.go
Labels: approved, lgtm, ok-to-test

#7366 MULTIARCH-3701: Enable ppc64le for agent installer
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/infraenv.go
Labels: approved, lgtm, jira/valid-reference

#7519 OCPBUGS-19376: GCP default value for service account
  data/data/gcp/variables-gcp.tf
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#7510 OCPBUGS-18986: Tag aws instance profiles.
  data/data/aws/bootstrap/main.tf
  data/data/aws/cluster/iam/main.tf
  data/data/aws/cluster/master/main.tf
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7437 Tweaks to validateRendezvousIPNotWorker
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
Labels: approved, lgtm

#7464 add jbtrystram to coreOS approvers and reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#6745 CORS-2479: agent: Ensure registries.conf is world readable
  pkg/asset/agent/image/ignition.go
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-reference

#7524 OCPBUGS-19670: [release-4.13] Allow different service account for xpn installs in gcp
  data/data/gcp/cluster/dns/base.tf
  data/data/gcp/cluster/dns/variables.tf
  data/data/gcp/cluster/iam/main.tf
  data/data/gcp/cluster/main.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/machines/gcp/machines.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/validation/machinepools.go
  pkg/types/validation/machinepools_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#7500 OCPBUGS-18690: ic: azure: validate NVMe-only family types
  pkg/asset/installconfig/azure/validation.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7452 OCPBUGS-5728: Log "agent wait-for" commands to .openshift_install.log
  cmd/openshift-install/agent/waitfor.go
  cmd/openshift-install/analyze.go
  cmd/openshift-install/command/log.go
  cmd/openshift-install/create.go
  cmd/openshift-install/destroy.go
  cmd/openshift-install/gather.go
  cmd/openshift-install/main.go
  cmd/openshift-install/waitfor.go
  pkg/agent/cluster.go
  pkg/agent/kube.go
  pkg/agent/rest.go
  pkg/agent/waitfor.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference
