Repository openshift/installer, pull requests merged in 2023-02, with the labels that each got.

#6764 OCPBUGS-5667: CVE-2021-4238: goutils: update for randomness fix
  go.mod
  go.sum
  terraform/providers/alicloud/go.mod
  terraform/providers/alicloud/go.sum
  terraform/providers/alicloud/vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  terraform/providers/alicloud/vendor/github.com/Masterminds/goutils/randomstringutils.go
  terraform/providers/alicloud/vendor/github.com/Masterminds/goutils/stringutils.go
  terraform/providers/alicloud/vendor/modules.txt
  terraform/providers/google/go.mod
  terraform/providers/google/go.sum
  terraform/providers/google/vendor/modules.txt
  terraform/providers/nutanix/go.mod
  terraform/providers/nutanix/go.sum
  terraform/providers/nutanix/vendor/modules.txt
  terraform/providers/openstack/go.mod
  terraform/providers/openstack/go.sum
  terraform/providers/openstack/vendor/modules.txt
  terraform/providers/time/go.mod
  terraform/providers/time/go.sum
  terraform/providers/time/vendor/modules.txt
  terraform/providers/vsphere/go.mod
  terraform/providers/vsphere/go.sum
  terraform/providers/vsphere/vendor/modules.txt
  terraform/providers/vsphereprivate/go.mod
  terraform/providers/vsphereprivate/go.sum
  terraform/providers/vsphereprivate/vendor/modules.txt
  terraform/terraform/go.mod
  terraform/terraform/go.sum
  terraform/terraform/vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  terraform/terraform/vendor/github.com/Masterminds/goutils/randomstringutils.go
  terraform/terraform/vendor/github.com/Masterminds/goutils/stringutils.go
  terraform/terraform/vendor/modules.txt
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#6811 OCPBUGS-6722: bootimage: move secure execution artifact to separate artifact
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6781 [release-4.12] OCPBUGS-5996: vsphere: set default resource pool when missing failure domain topology
  pkg/types/vsphere/defaults/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6793 OCPBUGS-6270: Don't require vSphere details for agent installer
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_compact.txt
  pkg/asset/agent/installconfig.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/validate/method.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6791 OCPBUGS-5960: bump RHCOS 4.12 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6551 azure: Add error message when authorizer fails.
  pkg/asset/installconfig/azure/session.go
Labels: approved, lgtm

#6822 OCPBUGS-6919: vsphere: fix validation of CPUS and CoresPerSocket
  pkg/types/vsphere/validation/machinepool.go
  pkg/types/vsphere/validation/machinepool_test.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6827 OCPBUGS-4997: Set the configured proxy settings for agent installer
  data/data/agent/files/etc/systemd/system.conf.d/10-default-env.conf.template
  data/data/agent/systemd/units/agent.service.template
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#6691 CNF-6362: feat: add support for nto rendering during bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#6735 OCPBUGS-5234: azurestack: upi: fix compute scale up
  upi/azurestack/02_storage.json
  upi/azurestack/03_infra.json
  upi/azurestack/04_bootstrap.json
  upi/azurestack/05_masters.json
  upi/azurestack/06_workers.json
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug

#6824 Add Adam
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#6604 destroy: vsphere: move API calls to client abstraction and add unit tests
  hack/go-genmock.sh
  pkg/destroy/vsphere/client.go
  pkg/destroy/vsphere/mock/vsphereclient_generated.go
  pkg/destroy/vsphere/virtualmachines.go
  pkg/destroy/vsphere/vsphere.go
  pkg/destroy/vsphere/vsphere_test.go
Labels: approved, lgtm

#6782 SPLAT-820: multi-zone is no longer tech preview
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/validation/installconfig.go
  pkg/types/vsphere/platform.go
Labels: approved, lgtm, jira/valid-reference

#6430 CNF-6357: feat: add CPU Partitioning flag into the install config
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/infrastructure_test.go
  pkg/asset/manifests/topologies.go
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#6834 OpenStack: Fix distribution of zones on 32-bit systems
  pkg/asset/machines/openstack/machines.go
Labels: approved, lgtm

#6839 openstack-manifests: Add a debug option
  hack/openstack/test-manifests.sh
Labels: approved, lgtm

#6844 OCPBUGS-4549: azure: fix MS Graph calls on Gov cloud
  pkg/asset/installconfig/azure/session.go
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6765 OCPBUGS-5665: CVE-2021-4238: goutils: update for randomness fix
  go.mod
  go.sum
  terraform/providers/aws/go.mod
  terraform/providers/aws/go.sum
  terraform/providers/aws/vendor/modules.txt
  terraform/providers/azureprivatedns/go.mod
  terraform/providers/azureprivatedns/go.sum
  terraform/providers/azureprivatedns/vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  terraform/providers/azureprivatedns/vendor/github.com/Masterminds/goutils/randomstringutils.go
  terraform/providers/azureprivatedns/vendor/github.com/Masterminds/goutils/stringutils.go
  terraform/providers/azureprivatedns/vendor/modules.txt
  terraform/providers/azurerm/go.mod
  terraform/providers/azurerm/go.sum
  terraform/providers/azurerm/vendor/modules.txt
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/modules.txt
  terraform/providers/ironic/go.mod
  terraform/providers/ironic/go.sum
  terraform/providers/ironic/vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  terraform/providers/ironic/vendor/github.com/Masterminds/goutils/randomstringutils.go
  terraform/providers/ironic/vendor/github.com/Masterminds/goutils/stringutils.go
  terraform/providers/ironic/vendor/modules.txt
  terraform/providers/nutanix/go.mod
  terraform/providers/nutanix/go.sum
  terraform/providers/nutanix/vendor/modules.txt
  terraform/providers/openstack/go.mod
  terraform/providers/openstack/go.sum
  terraform/providers/openstack/vendor/modules.txt
  terraform/providers/ovirt/go.mod
  terraform/providers/ovirt/go.sum
  terraform/providers/ovirt/vendor/modules.txt
  terraform/providers/time/go.mod
  terraform/providers/time/go.sum
  terraform/providers/time/vendor/modules.txt
  terraform/providers/vsphere/go.mod
  terraform/providers/vsphere/go.sum
  terraform/providers/vsphere/vendor/modules.txt
  terraform/providers/vsphereprivate/go.mod
  terraform/providers/vsphereprivate/go.sum
  terraform/providers/vsphereprivate/vendor/modules.txt
  terraform/terraform/go.mod
  terraform/terraform/go.sum
  terraform/terraform/vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  terraform/terraform/vendor/github.com/Masterminds/goutils/randomstringutils.go
  terraform/terraform/vendor/github.com/Masterminds/goutils/stringutils.go
  terraform/terraform/vendor/modules.txt
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6840 OCPBUGS-7261: Update AgentConfig template
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6835 installer dev build settings to enable delve
  hack/build.sh
  terraform/Makefile
Labels: approved, lgtm

#6842 AGENT-505: Embed agent files in initrd
  cmd/openshift-install/testdata/agent/image/assets/default_assets.txt
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/cpio.go
Labels: approved, lgtm, jira/valid-reference

#6821 OCPBUGS-6777: Fix file check for loading openshift manifests
  pkg/asset/machines/master.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6689 OCPBUGS-7356: data/manifests/bootkube/cvo-overrides: Default to stable-4.13
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6808 OCPBUGS-6697: destroy/gcp: Use min length for destroying disks
  pkg/destroy/gcp/disk.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6354 CFE-586 : Apply user defined tags on created azure resources
  data/data/azure/bootstrap/main.tf
  data/data/azure/cluster/dns/dns.tf
  data/data/azure/cluster/dns/variables.tf
  data/data/azure/cluster/main.tf
  data/data/azure/cluster/master/master.tf
  data/data/azure/cluster/master/variables.tf
  data/data/azure/vnet/internal-lb.tf
  data/data/azure/vnet/main.tf
  data/data/azure/vnet/nsg.tf
  data/data/azure/vnet/public-lb.tf
  data/data/azure/vnet/vnet.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm

#6327 OCPBUGS-1048: if tag categories don't exist, the installation will fail to bootstrap
  pkg/asset/installconfig/vsphere/mock/vsphere_sim.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/installconfig/vsphere/validation_test.go
  pkg/asset/manifests/vsphere/cloudproviderconfig.go
  pkg/types/vsphere/platform.go
  vendor/github.com/vmware/govmomi/vapi/library/library.go
  vendor/github.com/vmware/govmomi/vapi/library/library_file.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item_downloadsession_file.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item_updatesession.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item_updatesession_file.go
  vendor/github.com/vmware/govmomi/vapi/simulator/simulator.go
  vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_ovf.go
  vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_vmtx.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#6348 IBMCloud: Add tests for installconfig metadata
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/metadata_test.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/asset/installconfig/ibmcloud/responses/responses.go
  pkg/asset/installconfig/ibmcloud/subnet.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
  pkg/asset/manifests/openshift.go
Labels: approved, lgtm

#6613 CORS-2386: IBMCloud: Add networkResourceGroupName
  data/data/ibmcloud/network/main.tf
  data/data/ibmcloud/network/vpc/variables.tf
  data/data/ibmcloud/network/vpc/vpc.tf
  data/data/ibmcloud/variables-ibmcloud.tf
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/ibmcloud/validation.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
  pkg/asset/machines/ibmcloud/machines.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/tfvars/ibmcloud/ibmcloud.go
  pkg/types/ibmcloud/platform.go
  vendor/github.com/openshift/machine-api-provider-ibmcloud/LICENSE
  vendor/github.com/openshift/machine-api-provider-ibmcloud/pkg/apis/addtoschema_ibmcloudprovider_v1.go
  vendor/github.com/openshift/machine-api-provider-ibmcloud/pkg/apis/apis.go
  vendor/github.com/openshift/machine-api-provider-ibmcloud/pkg/apis/ibmcloudprovider/v1/doc.go
  vendor/github.com/openshift/machine-api-provider-ibmcloud/pkg/apis/ibmcloudprovider/v1/ibmcloudproviderconfig_types.go
  vendor/github.com/openshift/machine-api-provider-ibmcloud/pkg/apis/ibmcloudprovider/v1/ibmcloudproviderstatus_types.go
  vendor/github.com/openshift/machine-api-provider-ibmcloud/pkg/apis/ibmcloudprovider/v1/register.go
  vendor/github.com/openshift/machine-api-provider-ibmcloud/pkg/apis/ibmcloudprovider/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#6820 CFE-757 : Fix issues reported by QE
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm

#6845 OCPBUGS-4954: IBMCloud: Handle COS reclamations
  pkg/destroy/ibmcloud/cloudobjectstorage.go
  pkg/destroy/ibmcloud/ibmcloud.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#6766 OCPBUGS-5663: CVE-2021-4238: goutils: update for randomness fix
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6859 linter: bump version to sync with CI
  .golangci.yaml
  hack/go-lint.sh
Labels: approved, lgtm

#6795 integration: Don't pass host data in the install-config
  cmd/openshift-install/testdata/agent/image/configurations/compact.txt
  cmd/openshift-install/testdata/agent/image/validations/compact_not_enough_hosts.txt
Labels: approved, lgtm

#6846 AGENT-456: Remove connectivity checks from bash script
  data/data/agent/files/etc/assisted/agent-installer.env.template
  data/data/agent/files/usr/local/bin/agent-interactive-console.sh
  data/data/agent/systemd/units/agent-interactive-console.service
Labels: approved, lgtm, jira/valid-reference

#6310 CFE-582 : Generate Infrastructure CR with the azure user defined tags
  go.mod
  go.sum
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/infrastructure_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#6855 OCPBUGS-7495: Convert platform type for AgentClusterInstall
  cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
  pkg/asset/agent/common.go
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6865 Removes m1kola from azure-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#6861 OCPBUGS-7180: update RHCOS 4.13 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6852 openstack: Fix missing docs link
  docs/user/openstack/README.md
Labels: approved, lgtm

#6857 OCPBUGS-7521: Update AgentConfig template
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6872 Bug 1904573: baremetal container modify /etc/passwd group writable
  images/baremetal/Dockerfile.ci
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#6812 OSASINFRA-3090: External LB support for on-prem platforms
  data/data/install.openshift.io_installconfigs.yaml
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/masters/private-network.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/installconfig/ovirt/validation.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/manifests/infrastructure.go
  pkg/tfvars/openstack/openstack.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/nutanix/platform.go
  pkg/types/nutanix/validation/platform.go
  pkg/types/nutanix/validation/platform_test.go
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/ovirt/platform.go
  pkg/types/ovirt/validation/platform.go
  pkg/types/ovirt/validation/platform_test.go
  pkg/types/validation/installconfig.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  scripts/openstack/manifest-tests/default-stable-lb/install-config.yaml
  scripts/openstack/manifest-tests/default-stable-lb/test_cluster-infra.py
  scripts/openstack/manifest-tests/default-techpreview-lb/install-config.yaml
  scripts/openstack/manifest-tests/default-techpreview-lb/test_cluster-infra.py
  scripts/openstack/manifest-tests/openshift-managed-lb/install-config.yaml
  scripts/openstack/manifest-tests/openshift-managed-lb/test_cluster-infra.py
  scripts/openstack/manifest-tests/user-managed-lb/install-config.yaml
  scripts/openstack/manifest-tests/user-managed-lb/test_cluster-infra.py
Labels: approved, lgtm, jira/valid-reference

#6873 OCPBUGS-7529: bump RHCOS 4.12 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6875 OCPBUGS-7530: bump RHCOS 4.11 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6814 CORS-2496: Default `2xlarge` instead of `xlarge` in AWS when the control-plane is single-node
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, jira/valid-reference

#6884 Update alias for Metal Platform
  OWNERS_ALIASES
Labels: approved, lgtm

#6871 OCPBUGS-7579: azure: fix certificate-based auth with passpharse
  pkg/asset/installconfig/azure/session.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6870 CFE-757 : Fix issues reported by QE
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/explain/printer_test.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
Labels: approved, lgtm

#6880 linter: enable reporting about exported names lacking comments
  .golangci.yaml
  pkg/asset/agent/common.go
  pkg/asset/agent/image/cpio.go
  pkg/asset/manifests/nutanix/cloudproviderconfig.go
  pkg/destroy/aws/iamhelpers.go
  pkg/types/vsphere/conversion/installconfig.go
  pkg/validate/method.go
Labels: approved, lgtm

#6887 OCPBUGS-7622: Ignore CPMS file if not exist
  pkg/asset/machines/master.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#6906 OCPBUGS-7993: hack/build-coreos-manifest: support OKD
  hack/build-coreos-manifest.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6796 AGENT-526: Refactor Agent InstallConfig embedding
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/util_test.go
  pkg/asset/agent/mirror/cabundle_test.go
  pkg/asset/agent/mirror/registriesconf_test.go
  pkg/asset/ignition/machine/master_ignition_customizations_test.go
  pkg/asset/ignition/machine/master_test.go
  pkg/asset/ignition/machine/worker_ignition_customizations_test.go
  pkg/asset/ignition/machine/worker_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/installconfigbase.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/logging/filelogging_test.go
  pkg/asset/machines/master_test.go
  pkg/asset/machines/worker_test.go
  pkg/asset/manifests/infrastructure_test.go
  pkg/asset/manifests/ingress_test.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  pkg/validate/method.go
Labels: approved, lgtm, jira/valid-reference

#6908 openstack-manifests: Option to run selected test cases
  hack/openstack/test-manifests.sh
Labels: approved, lgtm

#6841 Support the new fields in NutanixMachineProviderConfig
  data/data/install.openshift.io_installconfigs.yaml
  data/data/nutanix/cluster/main.tf
  data/data/nutanix/variables-nutanix.tf
  pkg/asset/machines/master.go
  pkg/asset/machines/nutanix/machines.go
  pkg/asset/machines/worker.go
  pkg/tfvars/nutanix/nutanix.go
  pkg/types/nutanix/client.go
  pkg/types/nutanix/machinepool.go
Labels: approved, lgtm
