Repository openshift/installer, pull requests merged in 2023-12, with the labels that each got.

#7715 CORS-2978: enable AWS SDK Installation through feature gates
  cmd/openshift-install/gather.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/metadata.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
  pkg/types/clustermetadata.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7768 OCPBUGS-23947: set client options when interacting with azure api
  pkg/asset/cluster/azure/azure.go
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7718 OCPBUGS-24008: Remove sno_arm.txt integration test
  cmd/openshift-install/testdata/agent/pxe/configurations/sno_arm.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7547 CORS-2854: azure: Allow users to set visibility to components
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/ingress.go
  pkg/explain/printer_test.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/validation/platform.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-reference

#7771 CORS-2852: Generate Cluster API Machine Manifests
  pkg/asset/machines/aws/awsmachines.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/manifests/capiutils/manifest.go
  pkg/asset/manifests/clusterapi/cluster.go
Labels: approved, lgtm, jira/valid-reference

#7773 MULTIARCH-3793: Power VS: Add mad and wdc assupported region
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, jira/valid-reference

#7782 CORS-2785: images: decouple installer and installer-artifacts
  images/installer-artifacts/Dockerfile.rhel
Labels: approved, lgtm, jira/valid-reference

#7778 CORS-2775: ic: azure: remove deprecated `errors` package
  pkg/asset/installconfig/azure/azure.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/dns.go
  pkg/asset/installconfig/azure/metadata.go
  pkg/asset/installconfig/azure/session.go
  pkg/asset/installconfig/azure/validation.go
Labels: approved, lgtm, jira/valid-reference

#7595 MIXEDARCH-310: Enable the use of the multi payload for agent installer
  pkg/asset/agent/image/agentartifacts.go
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm, jira/valid-reference

#7753 OCPBUGS-23539: Keep Machine manifests out of OpenShift Manifests asset
  pkg/asset/machines/master.go
  pkg/asset/machines/master_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7792 no-jira: pkg/asset: safety nets to keep installer from crashing
  pkg/asset/asset.go
  pkg/asset/cluster/cluster.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, jira/valid-reference

#7795 PowerVS: MULTIARCH-4030: Reintroduce serviceInstanceGUID install option
  data/data/install.openshift.io_installconfigs.yaml
  data/data/powervs/bootstrap/iaas/iaas.tf
  data/data/powervs/bootstrap/iaas/variables.tf
  data/data/powervs/bootstrap/main.tf
  data/data/powervs/cluster/iaas/iaas.tf
  data/data/powervs/cluster/iaas/outputs.tf
  data/data/powervs/cluster/iaas/variables.tf
  data/data/powervs/cluster/main.tf
  data/data/powervs/variables-powervs.tf
  pkg/asset/cluster/powervs/powervs.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/machines/powervs/machines.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/powervs/cloudproviderconfig.go
  pkg/destroy/powervs/powervs.go
  pkg/tfvars/powervs/powervs.go
  pkg/types/powervs/metadata.go
  pkg/types/powervs/platform.go
  pkg/types/powervs/validation/platform.go
  pkg/types/powervs/validation/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#7798 NO-ISSUE: Remove dead code from 'networking' asset
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/installconfig_test.go
  pkg/asset/installconfig/networking.go
Labels: approved, lgtm, jira/valid-reference

#7106 OCPBUGS-9066: Retry image download on failure
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/cache.go
  pkg/asset/agent/image/oc.go
  pkg/asset/rhcos/image.go
  pkg/rhcos/cache/cache.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
  pkg/tfvars/ibmcloud/ibmcloud.go
  pkg/tfvars/libvirt/libvirt.go
  pkg/tfvars/openstack/rhcos_image.go
  pkg/tfvars/ovirt/ovirt.go
  pkg/tfvars/vsphere/vsphere.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7693 CORS-2852: cmd/create: ensure proper cleanup on exit
  cmd/openshift-install/create.go
Labels: approved, lgtm, jira/valid-reference

#7466 OCPVE-648: gomod: bump api version with CloudCredential cap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/types/validation/installconfig_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/custom.authentication.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/custom.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.authentication.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/custom.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/techpreview.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7574 AGENT-337: Set VIPs directly in api, instead of install-config override
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_no-credentials.txt
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/valid-reference

#7642 CORS-2525: Azure: remove storage account with bootstrap destroy
  data/data/azure/bootstrap/main.tf
  data/data/azure/bootstrap/outputs.tf
  data/data/azure/bootstrap/storage.tf
  data/data/azure/bootstrap/variables.tf
  data/data/azure/cluster/main.tf
  data/data/azure/cluster/master/master.tf
  data/data/azure/cluster/master/variables.tf
  data/data/azure/cluster/variables.tf
  data/data/azure/vnet/main.tf
  data/data/azure/vnet/outputs.tf
Labels: approved, lgtm, jira/valid-reference

#7652 SPLAT-1218: AWS BYO VPC support for Wavelength Zones
  docs/user/aws/install_edge-zones.md
  pkg/asset/installconfig/aws/availabilityzones.go
  pkg/asset/installconfig/aws/subnet.go
  pkg/asset/installconfig/aws/validation.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/availabilityzones.go
Labels: approved, lgtm, jira/valid-reference

#7712 MULTIARCH-2678: Patch for Agent Based Installer to support s390x as supported architecture.
  pkg/asset/agent/image/agentpxefiles.go
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/infraenv.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#7727 OSASINFRA-3261: OpenStack: support dualstack in UPI
  docs/user/openstack/install_upi.md
  upi/openstack/bootstrap.yaml
  upi/openstack/common.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
  upi/openstack/security-groups.yaml
  upi/openstack/update-network-resources.yaml
Labels: approved, lgtm, jira/valid-reference

#7791 OCPBUGS-23458: force destroy bootstrap ign
  data/data/aws/bootstrap/main.tf
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7799 no-jira: hack: drop hardcoded -j8 in make invocations.
  hack/build.sh
Labels: approved, lgtm, jira/valid-reference

#7800 no-jira: image: infra-providers: use base image instead of builder
  images/infrastructure-providers/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#7364 AGENT-615: Split create-cluster-and-infraenv.service
  data/data/agent/files/usr/local/bin/install-status.sh
  data/data/agent/files/usr/local/bin/set-node-zero.sh
  data/data/agent/systemd/units/agent-register-cluster.service.template
  data/data/agent/systemd/units/agent-register-infraenv.service.template
  data/data/agent/systemd/units/apply-host-config.service
  data/data/agent/systemd/units/install-status.service
  docs/user/agent/agent-services.md
  docs/user/agent/agent_installer_services-automated_flow.png
  docs/user/agent/agent_installer_services-unconfigured_ignition_and_config_image_flow.png
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm, jira/valid-reference

#7770 OCPBUGS-23473: update RHCOS 4.15 bootimage metadata to 415.92.202311241643-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7592 MULTIARCH-4042: Reuse existing Transit Gateway in target Workspace, or create anew
  data/data/powervs/cluster/main.tf
  data/data/powervs/cluster/transit_gateway/transit_gateway.tf
  data/data/powervs/cluster/transit_gateway/variables.tf
  data/data/powervs/variables-powervs.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/tfvars/powervs/powervs.go
Labels: approved, lgtm, jira/valid-reference

#7585 AGENT-729: Support generic platform name for external platform
  cmd/openshift-install/testdata/agent/image/configurations/external_compact.txt
  cmd/openshift-install/testdata/agent/image/validations/external_invalid_platform_name.txt
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#7645 AGENT-739: Support for install-config baremetal host BMC fields
  cmd/openshift-install/testdata/agent/image/configurations/baremetal_host_bmc_config.txt
  pkg/asset/agent/agentconfig/agenthosts.go
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
  pkg/types/agent/agent_config_type.go
  pkg/types/baremetal/validation/platform.go
Labels: approved, lgtm, jira/valid-reference

#7803 OCPBUGS-23140, OCPBUGS-23305: Soften VIP validations for external load-balancer
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7662 CORS-2813: Pass LB ConfigMap manifest as a parameter to MCO instance during bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-reference

#7769 [release-4.12] OCPBUGS-22116: Add KMS encryption keys if provided
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/platformpermscheck.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7809 METAL-803: Update vendoring for baremetal-operator
  go.mod
  go.sum
  pkg/tfvars/baremetal/baremetal.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_validation.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_webhook.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/profile/profile.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/access.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ibmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ilo4.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ilo5.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ipmi.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish_virtualmedia.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7806 SPLAT-1272: Modify the terraform variables to support Nutanix Failure Domains
  data/data/nutanix/bootstrap/main.tf
  data/data/nutanix/cluster/main.tf
  data/data/nutanix/variables-nutanix.tf
  pkg/tfvars/nutanix/nutanix.go
Labels: approved, lgtm, jira/valid-reference

#7811 CORS-3003: [ibmcloud] add key-protect plugin in ibmcloud cli
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, jira/valid-reference

#7823 CORS-2840: images/altinfra: enable CAPI builds
  images/installer-altinfra/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference

#7822 OCPBUGS-24995: Revert "Merge pull request #7642 from AnnaZivkovic/azure_duplicate_im…
  data/data/azure/bootstrap/main.tf
  data/data/azure/bootstrap/outputs.tf
  data/data/azure/bootstrap/storage.tf
  data/data/azure/bootstrap/variables.tf
  data/data/azure/cluster/main.tf
  data/data/azure/cluster/master/master.tf
  data/data/azure/cluster/master/variables.tf
  data/data/azure/cluster/variables.tf
  data/data/azure/vnet/main.tf
  data/data/azure/vnet/outputs.tf
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7826 OCPBUGS-25191: ic: azure: fix retrieving marketplace image
  pkg/asset/installconfig/azure/client.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7484 OCPBUGS-19303: Changed OKD/FCOS workaround to also support Agent-based Installer
  data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
  data/data/bootstrap/systemd/common/units/kubelet.service.template
  data/data/bootstrap/systemd/common/units/release-image-pivot.service.template
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7828 no-jira: Revert "Merge pull request #7823 from patrickdillon/build-capi-altinfra"
  images/installer-altinfra/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference

#7739 OCPBUGS-23379: images: update govc image in upi-installer
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7651 Revert "OCPBUGS-4038: bootstrap: Skip gatewayd units only on OKD agent-installer"
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7821 OCPBUGS-24241: Pin openstack.cloud version.
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7805 OCPBUGS-24473: IBMCloud: Set IBM TF visibility based on URLs
  data/data/ibmcloud/bootstrap/common.tf
  data/data/ibmcloud/master/common.tf
  data/data/ibmcloud/network/common.tf
  data/data/ibmcloud/variables-ibmcloud.tf
  pkg/asset/cluster/tfvars.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/tfvars/ibmcloud/ibmcloud.go
  pkg/types/ibmcloud/platform.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7688 CORS-2870: build: only rebuild terraform providers if needed
  hack/build.sh
  images/baremetal/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.upi.ci
  images/libvirt/Dockerfile.ci
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference

#7847 no-jira: build: drop vsphereprivate build workaround
  hack/build.sh
Labels: approved, lgtm, jira/valid-reference

#7846 CORS-2315: GCP: Skip populating Private/Public Zones within DNS manifest
  pkg/asset/manifests/dns.go
Labels: approved, lgtm, jira/valid-reference

#7825 OCPBUGS-19054: Warn that FeatureSet is not supported
  pkg/asset/agent/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
