Repository openshift/installer, pull requests merged in 2023-08, with the labels that each got.

#7291 CORS-2719: Remove service account user permission
  data/data/gcp/cluster/master/main.tf
Labels: approved, lgtm, jira/valid-reference

#7373 OCPBUGS-16959: openstack/upi: add missing modules namespaces + doc
  docs/user/openstack/install_upi.md
  images/openstack/Dockerfile.ci
  upi/openstack/bootstrap.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/down-bootstrap.yaml
  upi/openstack/down-compute-nodes.yaml
  upi/openstack/down-containers.yaml
  upi/openstack/down-control-plane.yaml
  upi/openstack/down-load-balancers.yaml
  upi/openstack/down-network.yaml
  upi/openstack/down-security-groups.yaml
  upi/openstack/network.yaml
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7100 OCPBUGS-6759: Fix discrepancy with disk size master
  data/data/azurestack/cluster/master/master.tf
  pkg/asset/machines/master.go
  pkg/types/azure/defaults/platform.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7347 OCPBUGS-16292: GCP XPN: clarify service account support
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/machinepools.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7361 [release-4.13] OCPBUGS-15290: GCP: ic: improve project validation
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6903 PowerVS: Check whether Machine pool CIDR is /24
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
Labels: approved, lgtm

#7367 Bug OCPBUGS-16249: Add ip=dhcp,dhcp6 option to Kernel args
  pkg/asset/machines/machineconfig/ipv6.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  scripts/openstack/manifest-tests/dual-stack/install-config.yaml
  scripts/openstack/manifest-tests/dual-stack/test_machine-config.py
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7384 OCPBUGS-16912: Ensure DHCPv6 client sends Solicit with mac address
  data/data/agent/files/etc/NetworkManager/conf.d/clientid.conf
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/image/unconfigured_ignition.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7311 data/data/coreos: bump FCOS to F38 stable
  data/data/coreos/fcos.json
Labels: approved, lgtm

#7378 OpenStack: Remove SGS created by CPO on destroy
  pkg/destroy/openstack/openstack.go
Labels: approved, lgtm

#7338 OCPBUGS-15994: Update core password after loading config-image
  data/data/agent/files/usr/local/bin/load-config-iso.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7396 SPLAT-1123: Revert Alibaba deprecation warning
  pkg/asset/installconfig/alibabacloud/alibabacloud.go
  pkg/types/alibabacloud/validation/platform.go
Labels: approved, lgtm, jira/valid-reference

#7371 gather: Use `journalctl -o with-unit`
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm

#7385 OCPBUGS-17397: backport openstack UPI for ansible 2.10
  docs/user/openstack/install_upi.md
  images/openstack/Dockerfile.ci
  upi/openstack/bootstrap.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/down-bootstrap.yaml
  upi/openstack/down-compute-nodes.yaml
  upi/openstack/down-containers.yaml
  upi/openstack/down-control-plane.yaml
  upi/openstack/down-load-balancers.yaml
  upi/openstack/down-network.yaml
  upi/openstack/down-security-groups.yaml
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7395 OpenStack: Fix user docs for additional network with IPv6
  docs/user/openstack/connect_nodes_to_ipv6_network.md
Labels: approved, lgtm

#7400 openstack: Test zero replicas in worker machine-pool
  pkg/asset/machines/openstack/machinesets.go
  scripts/openstack/manifest-tests/zero-workers/install-config.yaml
  scripts/openstack/manifest-tests/zero-workers/test_cpms.py
  scripts/openstack/manifest-tests/zero-workers/test_machines.py
Labels: approved, lgtm

#7312 MGMT-13628: add support for confidential VMs on Azure
  data/data/azure/bootstrap/main.tf
  data/data/azure/cluster/main.tf
  data/data/azure/cluster/master/master.tf
  data/data/azure/cluster/master/variables.tf
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/main.tf
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/machines/azure/machines.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/disk.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
  vendor/github.com/openshift/api/config/v1/custom.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/custom.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/custom.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machinehealthcheck.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_olm-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_olm-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/custom.olm.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/register.go
  vendor/github.com/openshift/api/operator/v1alpha1/techpreview.olm.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_olm.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/custom.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/techpreview.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/shurcooL/httpfs/LICENSE
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7362 CORS-2764: AWS Shared VPC Backport [release-4.13]
  data/data/aws/cluster/main.tf
  data/data/aws/cluster/route53/base.tf
  data/data/aws/cluster/route53/variables.tf
  data/data/aws/variables-aws.tf
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/cluster/aws/aws.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/aws/mock/awsroute53_generated.go
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/route53.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/installconfig/vsphere/mock/tagmanager_generated.go
  pkg/asset/manifests/dns.go
  pkg/destroy/aws/aws.go
  pkg/destroy/aws/shared.go
  pkg/explain/printer_test.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/metadata.go
  pkg/types/aws/platform.go
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
  pkg/types/validation/installconfig.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7393 OCPBUGS-17246: azurestack: do not use gen2 images
  pkg/asset/machines/azure/machines.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7401 maintenance: update openshift/api
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/custom.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/0000_10_config-operator_01_backup-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1alpha1/register.go
  vendor/github.com/openshift/api/config/v1alpha1/techpreview.backup.testsuite.yaml
  vendor/github.com/openshift/api/config/v1alpha1/types_backup.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/00_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.console.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/stable.ingresscontroller.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_01_etcdbackup-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/register.go
  vendor/github.com/openshift/api/operator/v1alpha1/techpreview.etcdbackup.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_etcdbackup.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/stable.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#7404 PowerVS: Update listCOSInstances to continue querying
  go.mod
  go.sum
  pkg/destroy/powervs/cloudobjectstorage.go
  vendor/github.com/IBM/go-sdk-core/v5/core/utils.go
  vendor/github.com/IBM/go-sdk-core/v5/core/version.go
  vendor/github.com/IBM/platform-services-go-sdk/common/version.go
  vendor/github.com/IBM/platform-services-go-sdk/iamidentityv1/iam_identity_v1.go
  vendor/github.com/IBM/platform-services-go-sdk/iampolicymanagementv1/iam_policy_management_v1.go
  vendor/github.com/IBM/platform-services-go-sdk/resourcecontrollerv2/resource_controller_v2.go
  vendor/github.com/IBM/platform-services-go-sdk/resourcemanagerv2/resource_manager_v2.go
  vendor/github.com/asaskevich/govalidator/validator.go
  vendor/github.com/go-openapi/strfmt/.golangci.yml
  vendor/github.com/go-openapi/strfmt/date.go
  vendor/github.com/go-openapi/strfmt/format.go
  vendor/github.com/go-openapi/strfmt/time.go
  vendor/github.com/go-openapi/strfmt/ulid.go
  vendor/github.com/go-playground/validator/v10/README.md
  vendor/github.com/go-playground/validator/v10/baked_in.go
  vendor/github.com/go-playground/validator/v10/cache.go
  vendor/github.com/go-playground/validator/v10/country_codes.go
  vendor/github.com/go-playground/validator/v10/doc.go
  vendor/github.com/go-playground/validator/v10/errors.go
  vendor/github.com/go-playground/validator/v10/regexes.go
  vendor/github.com/go-playground/validator/v10/struct_level.go
  vendor/github.com/go-playground/validator/v10/util.go
  vendor/github.com/go-playground/validator/v10/validator.go
  vendor/github.com/go-playground/validator/v10/validator_instance.go
  vendor/github.com/leodido/go-urn/.gitignore
  vendor/github.com/leodido/go-urn/.travis.yml
  vendor/github.com/leodido/go-urn/README.md
  vendor/github.com/leodido/go-urn/makefile
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/modules.txt
Labels: approved, lgtm

#7408 OCPBUGS-13408: Log message and add integration test
  cmd/openshift-install/testdata/agent/agentconfigtemplate/agent-config-template.txt
  pkg/asset/agent/agentconfig/agent_config.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7392 OCPBUGS-13408: $ openshift-install agent create agent-config-template --dir=./foo gives nothing in the INFO log-level
  pkg/asset/agent/agentconfig/agent_config.go
Labels: do-not-merge/hold, approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7407 azure: validation: machinepool: sort slice before comparing
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
Labels: approved, lgtm

#7394 Add baremetal capability validation
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#7409 OCPBUGS-16776: update RHCOS 4.14 bootimage metadata to 414.92.202308032115-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7410 OCPBUGS-16777: update RHCOS 4.13 bootimage metadata to 413.92.202307260246-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7126 CFE-688: Update install-config CRD to support gcp labels and tags
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#7288 CORS-2700: Make bootstrap S3 bucket optional during bootstrap destroy
  data/data/aws/bootstrap/main.tf
  data/data/aws/cluster/main.tf
  data/data/aws/variables-aws.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/explain/printer_test.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/platform.go
Labels: approved, lgtm, jira/valid-reference

#7313 OCPBUGS-11999: upkeep: updated description to remove techpreview
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7153 CFE-687: Apply user defined labels on created gcp resources
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/cluster/dns/base.tf
  data/data/gcp/cluster/dns/variables.tf
  data/data/gcp/cluster/main.tf
  data/data/gcp/cluster/master/main.tf
  data/data/gcp/cluster/master/variables.tf
  data/data/gcp/post-bootstrap/main.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#7138 CFE-686: Generate Infrastructure CR with the GCP user defined tags & labels
  pkg/asset/manifests/infrastructure.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#7420 OCPBUGS-16778: bump RHCOS 4.12 bootimage metadata to 412.86.202308081039-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7357 OCPBUGS-16640: [release-4.13] Update azure cli version to 2.49.0
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7397 CORS-2660: GCP: deprecate the licenses field
  data/data/gcp/cluster/main.tf
  data/data/gcp/variables-gcp.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, jira/valid-reference

#7250 Destroy startironic.sh forever
  data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-dnsmasq.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-httpd.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-inspector.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-ramdisk-logs.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.volume
  data/data/bootstrap/baremetal/files/etc/ironic-network.env.template
  data/data/bootstrap/baremetal/files/etc/ironic.env.template
  data/data/bootstrap/baremetal/files/usr/local/bin/build-ironic-env.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/dhcp-filter.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/prov-iptables.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/setup-image-data.sh.template
  data/data/bootstrap/baremetal/files/usr/local/bin/start-provisioning-nic.sh
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  data/data/bootstrap/baremetal/files/usr/local/bin/stopironic.sh
  data/data/bootstrap/baremetal/systemd/units/build-ironic-env.service.template
  data/data/bootstrap/baremetal/systemd/units/extract-machine-os.service
  data/data/bootstrap/baremetal/systemd/units/ironic.service
  data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service
  data/data/bootstrap/baremetal/systemd/units/provisioning-interface.service.template
  data/data/bootstrap/baremetal/systemd/units/wait-iptables-init.service
Labels: approved, lgtm, platform/baremetal

#7424 OCPBUGS-16779: bump RHCOS 4.11 bootimage metadata to 411.86.202308081056-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7434 OCPBUGS-17869: azure: put NAT gateway behind TechPreviewNoUpgrade
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/printer_test.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7388 OCPBUGS-17227: gcp: fix validation of custom instance types
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/machines/gcp/zones.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#7430 OCPBUGS-17940: Add COS endpoint to proxy server (Power VS)
  data/data/powervs/cluster/dns/templates/cloud-init.yaml.tpl
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7405 OCPBUGS-17860: OpenStack: Remove NodePorts range 0.0.0.0/0 rules
  data/data/openstack/masters/sg-master.tf
  data/data/openstack/masters/sg-worker.tf
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7414 OCPBUGS-15659: IPI pre-check for MachineAPI capability
  pkg/asset/installconfig/platformprovisioncheck.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7425 OCPBUGS-18046: update govc version to v0.30.7
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7352 OCPBUGS-16204: aws: attach additional security groups to controlPlane
  data/data/aws/cluster/main.tf
  data/data/aws/variables-aws.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/aws/aws.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#7320 OSDOCS-6880: Adding 64-bit ARM GCP instance types to documentation
  docs/user/gcp/tested_instance_types_arm.md
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#7423 [release-4.13] OCPBUGS-14432: Replica validations
  cmd/openshift-install/testdata/agent/image/validations/compact_too_many_masters.txt
  cmd/openshift-install/testdata/agent/image/validations/compact_too_many_workers.txt
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7431 OCPBUGS-17823: CORS-2445: GCP: Add osImage to the install config
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/machines/gcp/machines.go
  pkg/types/gcp/machinepools.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7455 OCPBUGS-17869: azure: fix setting outboundType
  pkg/tfvars/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7433 OCPBUGS-7690: azure: destroy: dns records leak if permissions missing
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#7426 OCPBUGS-17770: azure: use marketplace image plan's publisher
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only
