Repository openshift/installer, pull requests merged in 2023-04, with the labels that each got.

#7066 AGENT-275: Add new agent graph command to output agent internal dependency graph
  cmd/openshift-install/agent.go
  cmd/openshift-install/graph.go
  cmd/openshift-install/testdata/agent/graph/graph.txt
Labels: approved, lgtm, jira/valid-reference

#7002 gcp: add confidential compute support for boostrap TF
  data/data/gcp/bootstrap/main.tf
Labels: approved, lgtm

#7072 docs: gcp: upi: update obtaining RHCOS source image
  docs/user/gcp/install_upi.md
Labels: approved, lgtm

#7073 PowerVS: fix human readable group-id
  pkg/asset/installconfig/powervs/client.go
Labels: approved, lgtm

#6235 [OCPNODE-1258] Add imageDigestSources, deprecate imageContentSources
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/agent/mirror/registriesconf.go
  pkg/asset/agent/mirror/registriesconf_test.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/ignition/bootstrap/registries.go
  pkg/asset/ignition/bootstrap/registries_test.go
  pkg/asset/manifests/imagedigestmirrorset.go
  pkg/asset/manifests/imagesourcepolicy.go
  pkg/asset/manifests/operators.go
  pkg/explain/printer_test.go
  pkg/types/conversion/installconfig.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#7075 OCPBUGS-11479: Upgrade libnmstate version used
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7084 OCPBUGS-11662: AWS - Remove ACLs from s3 ign
  data/data/aws/bootstrap/main.tf
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7085 OCPBUGS-11663: AWS - Remove ACLs from s3 ign
  data/data/aws/bootstrap/main.tf
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7011 OCPBUGS-10673: [Alibaba] update the bandwidth value of EIP
  data/data/alibabacloud/cluster/vpc/eip.tf
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7060 OCPBUGS-4998: Log additional info when status is pending-user-action
  pkg/agent/cluster.go
  pkg/agent/waitfor.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7074 pkg: rhcos: use Errorf instead of Error
  pkg/rhcos/ami_regions.go
Labels: approved, lgtm

#7093 OCPBUGS-11789: update RHCOS 4.13 bootimage metadata to 413.92.202304131328-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7076 OCPBUGS-8449: Azure: don't set default subscriptionID for disk encryption sets
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/azure/validation/disk.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7092 OCPBUGS-11788: update RHCOS 4.14 bootimage metadata to 414.92.202304131328-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7098 OCPBUGS-9081: openstack: Bump Gophercloud
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/README.md
  vendor/github.com/gophercloud/gophercloud/RELEASE.md
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/quotasets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/oauth1/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/pagination/pager.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7103 OWNERS_ALIASES: offboard Sohan from CoreOS
  OWNERS_ALIASES
Labels: approved, lgtm

#7070 OCPBUGS-10767: Fix and improve locking session and AWS Metadata access
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7099 OpenStack: enable ingress traffic for dual-stack installations
  data/data/openstack/masters/sg-master.tf
  data/data/openstack/masters/sg-worker.tf
Labels: approved, lgtm

#7095 OCPBUGS-11801: Fix agent-tui libnmstate dependency name
  cmd/openshift-install/agent_internal_integration_test.go
  cmd/openshift-install/testdata/agent/image/assets/default_assets.txt
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/cpio.go
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7110 OCPBUGS-11999: fix: remove feature flag for cpu partitioning no longer needed
  pkg/asset/manifests/topologies.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7114 OCPBUGS-12196: bump CVO to stable-4.14
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7113 [release-4.13] OCPBUGS-12179: agent: copy also symbolic link when storing agent-tui related files into the agent ISO
  cmd/openshift-install/agent_internal_integration_test.go
  cmd/openshift-install/testdata/agent/image/assets/default_assets.txt
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/cpio.go
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7010 OCPBUGS-5140: [Alibaba] update the bandwidth value of EIP
  data/data/alibabacloud/cluster/vpc/eip.tf
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7118 OCPBUGS-12748: use python3 for cloud sdk
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7089 OCPBUGS-12869: fix nmstate related unit tests
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7134 OCPBUGS-12776: GCP XPN Private Cluster Fails with no Public Zone
  pkg/asset/cluster/tfvars.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7142 OCPBUGS-12904: openstack: Add netcat to the Installer image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#6990 pass featuregate args to config-operator to get rendered featuregates
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  pkg/asset/manifests/featuregate.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
