Repository openshift/installer, pull requests merged in 2023-03, with the labels that each got.

#6905 OCPBUGS-7991: vSphere - only create RP when cluster is not empty
  pkg/types/vsphere/defaults/platform.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6901 OCPBUGS-7860: azure: session: fix unclear auth error messages
  go.mod
  go.sum
  pkg/asset/installconfig/azure/session.go
  vendor/github.com/Azure/go-autorest/autorest/azure/auth/LICENSE
  vendor/github.com/Azure/go-autorest/autorest/azure/auth/auth.go
  vendor/github.com/Azure/go-autorest/autorest/azure/auth/go_mod_tidy_hack.go
  vendor/github.com/Azure/go-autorest/autorest/azure/cli/LICENSE
  vendor/github.com/Azure/go-autorest/autorest/azure/cli/go_mod_tidy_hack.go
  vendor/github.com/Azure/go-autorest/autorest/azure/cli/profile.go
  vendor/github.com/Azure/go-autorest/autorest/azure/cli/token.go
  vendor/github.com/dimchansky/utfbom/.gitignore
  vendor/github.com/dimchansky/utfbom/.travis.yml
  vendor/github.com/dimchansky/utfbom/LICENSE
  vendor/github.com/dimchansky/utfbom/README.md
  vendor/github.com/dimchansky/utfbom/utfbom.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#6918 vsphere: Remove bostrt from approver/reviewer group
  OWNERS_ALIASES
Labels: approved, lgtm

#6853 GCP: conditionally create bootstrap service account
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/variables-gcp.tf
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/gcp/gcp.go
Labels: approved, lgtm

#6878 [release-4.12] OCPBUGS-7746: Convert platform type for AgentClusterInstall
  pkg/asset/agent/common.go
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6898 AGENT-502: Enable agent tui
  cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
  data/data/agent/files/etc/assisted/agent-installer.env.template
  data/data/agent/systemd/units/agent-interactive-console.service
  data/data/agent/systemd/units/set-hostname.service
  pkg/asset/agent/image/agentimage.go
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference

#6401 ARMOCP-417: enable arm64 for agent installer
  cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/baseiso_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/infraenv.go
Labels: approved, lgtm, jira/valid-reference

#6915 OCPBUGS-7015: Relax MachineCIDR check for vSphere, Nutanix
  pkg/asset/agent/installconfig_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6848 Azure: use managed storage account for boot logs
  data/data/azure/bootstrap/main.tf
  data/data/azure/cluster/main.tf
  data/data/azure/cluster/master/master.tf
  data/data/azure/cluster/master/variables.tf
  data/data/azure/cluster/variables.tf
Labels: approved, lgtm

#6856 Generate CSI driver manifests
  go.mod
  go.sum
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/manifests/aws/clustercsidriver.go
  pkg/asset/manifests/azure/clustercsidriver.go
  pkg/asset/manifests/clustercsidriver.go
  pkg/asset/manifests/gcp/clustercsidriver.go
  pkg/asset/manifests/operators.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#6881 OPNET-199: Allow v6-primary dual stack on baremetal
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-reference

#6371 RFE-2782: Create edge compute pool to support AWS Local Zones
  docs/user/aws/install_existing_vpc_local-zones.md
  pkg/asset/installconfig/aws/availabilityzones.go
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/subnet.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/aws/machinesets.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/machines/worker_test.go
  pkg/asset/manifests/network.go
  pkg/types/aws/availabilityzones.go
  pkg/types/aws/defaults/platform.go
  pkg/types/aws/defaults/platform_test.go
  pkg/types/aws/platform.go
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/defaults/machinepools.go
  pkg/types/defaults/machinepools_test.go
  pkg/types/installconfig.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig.go
  upi/aws/cloudformation/01.99_net_local-zone.yaml
  upi/aws/cloudformation/01_vpc.yaml
Labels: approved, lgtm, jira/valid-reference

#6916 openstack: consistent TechPreview-only feature validation
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
  pkg/types/openstack/validation/techpreview.go
  pkg/types/openstack/validation/techpreview_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#6926 OCPBUGS-8258: Specify filename for default registries.conf
  pkg/asset/agent/mirror/registriesconf.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6927 AGENT-356: Disable 'create pxe-files' command
  cmd/openshift-install/agent.go
  cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
Labels: approved, lgtm, jira/valid-reference

#6928 OCPBUGS-8305: Power VS: Add resourceGroup to infrastructure manifest
  pkg/asset/manifests/infrastructure.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#6923 OCPBUGS-5129: Pass Capabilites from install-config to cluster
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#6922 OCPBUGS-8203: Don't log password values
  pkg/asset/agent/installconfig.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#6917 OpenStack Failure domains
  data/data/install.openshift.io_installconfigs.yaml
  data/data/openstack/masters/main.tf
  data/data/openstack/masters/outputs.tf
  data/data/openstack/masters/private-network.tf
  data/data/openstack/variables-openstack.tf
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/openstack/ports.go
  pkg/types/openstack/machinepool.go
  pkg/types/openstack/validation/machinepool.go
  pkg/types/openstack/validation/machinepool_test.go
  pkg/types/openstack/validation/techpreview.go
  scripts/openstack/manifest-tests/failure-domains/install-config.yaml
  scripts/openstack/manifest-tests/failure-domains/test_machines.py
Labels: approved, lgtm

#6925 OCPBUGS-7262: Disable systemd status while TUI showing
  data/data/agent/systemd/units/agent-interactive-console.service
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6929 openstack-manifest: Show assets dir if persisted
  hack/openstack/test-manifests.sh
Labels: approved, lgtm

#6939 OCPBUGS-8353: Disable 'create pxe-files' command
  cmd/openshift-install/agent.go
  cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6886 update RHCOS 4.13 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm

#6940 OpenStack: support multiple API and ingress VIPs
  data/data/openstack/bootstrap/main.tf
  data/data/openstack/masters/private-network.tf
  data/data/openstack/variables-openstack.tf
  pkg/tfvars/openstack/openstack.go
Labels: approved, lgtm

#6963 data: libvirt: increase volume size to 32GB
  data/data/baremetal/bootstrap/main.tf
  data/data/libvirt/bootstrap/main.tf
Labels: approved, lgtm

#6949 OCPBUGS-8119: CVE-2023-25173: bump containerd
  go.mod
  go.sum
  terraform/providers/alicloud/go.mod
  terraform/providers/alicloud/go.sum
  terraform/providers/alicloud/vendor/modules.txt
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6966 openstack-manifests: Export JUnit results
  hack/openstack/test-manifests.sh
  scripts/openstack/manifest-tests/cinder-availability-zones/test_machines.py
  scripts/openstack/manifest-tests/cinder-availability-zones/test_machinesets.py
  scripts/openstack/manifest-tests/failure-domains/test_machines.py
  scripts/openstack/manifest-tests/lb-default-stable/install-config.yaml
  scripts/openstack/manifest-tests/lb-default-stable/test_cluster-infra.py
  scripts/openstack/manifest-tests/lb-default-techpreview/install-config.yaml
  scripts/openstack/manifest-tests/lb-default-techpreview/test_cluster-infra.py
  scripts/openstack/manifest-tests/lb-managed/install-config.yaml
  scripts/openstack/manifest-tests/lb-managed/test_cluster-infra.py
  scripts/openstack/manifest-tests/lb-unmanaged/install-config.yaml
  scripts/openstack/manifest-tests/lb-unmanaged/test_cluster-infra.py
  scripts/openstack/manifest-tests/nova-availability-zones/test_machines.py
  scripts/openstack/manifest-tests/nova-availability-zones/test_machinesets.py
  scripts/openstack/manifest-tests/server-groups/test_machines.py
  scripts/openstack/manifest-tests/server-groups/test_machinesets.py
Labels: approved, lgtm

#6947 OCPBUGS-8658: Pass Capabilites from install-config to cluster
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#6951 terraform: google: bump stringset dependency
  terraform/providers/google/go.mod
  terraform/providers/google/go.sum
  terraform/providers/google/vendor/bitbucket.org/creachadair/stringset/README.md
  terraform/providers/google/vendor/bitbucket.org/creachadair/stringset/bitbucket-pipelines.yml
  terraform/providers/google/vendor/bitbucket.org/creachadair/stringset/stringset.go
  terraform/providers/google/vendor/modules.txt
Labels: approved, lgtm

#6868 OCPBUGS-7063: vSphere - Remove regexs in terraform ova import
  terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6851 OCPBUGS-7469: [release-4.12] GCP XPN Featuregates
  pkg/asset/cluster/tfvars.go
  pkg/asset/machines/gcp/machines.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#6536 OCPBUGS-2968: bootstrap: Do not needlessly podman pull
  data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6757 Shorten SNO installation duration by releasing CVO lease
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
Labels: approved, lgtm

#6976 OCPBUGS-10394: Sort userTags in Machine and Machineset manifests
  pkg/asset/machines/aws/machines.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6950 OCPBUGS-8540: CVE: bump mongo-go-driver for fix
  go.mod
  go.sum
  terraform/providers/alicloud/go.mod
  terraform/providers/alicloud/go.sum
  terraform/providers/alicloud/vendor/gopkg.in/yaml.v3/decode.go
  terraform/providers/alicloud/vendor/gopkg.in/yaml.v3/parserc.go
  terraform/providers/alicloud/vendor/modules.txt
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/modules.txt
  vendor/github.com/go-stack/stack/LICENSE.md
  vendor/github.com/go-stack/stack/README.md
  vendor/github.com/go-stack/stack/stack.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/bsoncodec.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/default_value_decoders.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/empty_interface_codec.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/map_codec.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/registry.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonrw/extjson_parser.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonrw/value_reader.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonrw/value_writer.go
  vendor/go.mongodb.org/mongo-driver/bson/decoder.go
  vendor/go.mongodb.org/mongo-driver/bson/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/marshal.go
  vendor/go.mongodb.org/mongo-driver/bson/registry.go
  vendor/go.mongodb.org/mongo-driver/bson/unmarshal.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/bson_documentbuilder.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/bsoncore.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/document.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/document_sequence.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6987 Bump mongo-driver from 1.10 to 1.11.2
  go.mod
  go.sum
  terraform/providers/alicloud/go.mod
  terraform/providers/alicloud/go.sum
  terraform/providers/alicloud/vendor/modules.txt
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bson.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/doc.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/registry.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/struct_tag_parser.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsonoptions/doc.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/doc.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/primitive/decimal.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/primitive/objectid.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/primitive/primitive.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/document_sequence.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/value.go
  terraform/providers/ibm/vendor/modules.txt
  vendor/go.mongodb.org/mongo-driver/bson/bson.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/registry.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/struct_tag_parser.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonoptions/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/primitive/decimal.go
  vendor/go.mongodb.org/mongo-driver/bson/primitive/objectid.go
  vendor/go.mongodb.org/mongo-driver/bson/primitive/primitive.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/document_sequence.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/value.go
  vendor/modules.txt
Labels: approved, lgtm

#6977 OCPBUGS-10313: fix agent tui showing up multiple times
  data/data/agent/systemd/units/agent-interactive-console.service
  data/data/agent/systemd/units/agent-tui.path
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6998 OCPBUGS-7954: openstack: Provide manual instructions for invalid certificates
  docs/user/openstack/invalid-https-certificates.md
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6986 OCPBUGS-10499: [release-4.13] CVE: bump mongo-go-driver for fix
  go.mod
  go.sum
  terraform/providers/alicloud/go.mod
  terraform/providers/alicloud/go.sum
  terraform/providers/alicloud/vendor/gopkg.in/yaml.v3/decode.go
  terraform/providers/alicloud/vendor/gopkg.in/yaml.v3/parserc.go
  terraform/providers/alicloud/vendor/modules.txt
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bson.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/doc.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/registry.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/struct_tag_parser.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/bsonoptions/doc.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/doc.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/primitive/decimal.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/primitive/objectid.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/bson/primitive/primitive.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/document_sequence.go
  terraform/providers/ibm/vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/value.go
  terraform/providers/ibm/vendor/modules.txt
  vendor/github.com/go-stack/stack/LICENSE.md
  vendor/github.com/go-stack/stack/README.md
  vendor/github.com/go-stack/stack/stack.go
  vendor/go.mongodb.org/mongo-driver/bson/bson.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/bsoncodec.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/default_value_decoders.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/empty_interface_codec.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/map_codec.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/registry.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/struct_tag_parser.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonoptions/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonrw/extjson_parser.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonrw/value_reader.go
  vendor/go.mongodb.org/mongo-driver/bson/bsonrw/value_writer.go
  vendor/go.mongodb.org/mongo-driver/bson/decoder.go
  vendor/go.mongodb.org/mongo-driver/bson/doc.go
  vendor/go.mongodb.org/mongo-driver/bson/marshal.go
  vendor/go.mongodb.org/mongo-driver/bson/primitive/decimal.go
  vendor/go.mongodb.org/mongo-driver/bson/primitive/objectid.go
  vendor/go.mongodb.org/mongo-driver/bson/primitive/primitive.go
  vendor/go.mongodb.org/mongo-driver/bson/registry.go
  vendor/go.mongodb.org/mongo-driver/bson/unmarshal.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/bson_documentbuilder.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/bsoncore.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/document.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/document_sequence.go
  vendor/go.mongodb.org/mongo-driver/x/bsonx/bsoncore/value.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6960 OCPBUGS-9949: Verify output file exists when `oc image extract` is run
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6967 OCPBUGS-7015: vsphere, nutanix survey: relax vip in machine cidr
  pkg/asset/installconfig/nutanix/nutanix.go
  pkg/asset/installconfig/vsphere/vsphere.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6971 OCPBUGS-10207: Do not always output warning msg when releaseImage is digest
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/mirror/registriesconf.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6993 OSDOCS-5240: doc/fix-aws-localzones: replace jq to aws --query
  docs/user/aws/install_existing_vpc_local-zones.md
Labels: approved, lgtm, jira/valid-reference

#6994 OCPBUGS-10570: openstack: No master primarySubnet control-plane if portTarget is set
  pkg/asset/machines/openstack/machines.go
  scripts/openstack/manifest-tests/failure-domains/install-config.yaml
  scripts/openstack/manifest-tests/failure-domains/test_machines.py
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7001 openstack: Remove version info, update lb FIP -> API FIP
  docs/user/openstack/README.md
Labels: approved, lgtm

#6907 [release-4.12] OCPBUGS-7481: Fix file check for loading openshift manifests
  pkg/asset/machines/master.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6997 OCPBUGS-10585: rhcos: Update to 413.92.202303190222-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6989 [release-4.13] OCPBUGS-10597: fix agent tui showing up multiple times
  data/data/agent/systemd/units/agent-interactive-console.service
  data/data/agent/systemd/units/agent-tui.path
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6981 OCPBUGS-6727: Nutanix Hostname of the VM is not set when using DHCP network config
  data/data/nutanix/cluster/main.tf
  pkg/terraform/stages/nutanix/stages.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6850 PowerVS: Add capacity checks before installation
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/quota/quota.go
Labels: approved, lgtm

#6965 OCPBUGS-9982: bootstrap-pivot: skip pivot in SCOS Live ISO
  data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6945 OCPBUGS-8509: baremetal: do not use port 80 for httpd
  data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6924 OCPBUGS-7973: IBMCloud set dnsrecords offset
  pkg/destroy/ibmcloud/dns.go
  pkg/destroy/ibmcloud/ibmcloud.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7019 OCPBUGS-10740: bump RHCOS 4.12 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6944 OCPBUGS-8035: IBMCloud: Fix SSH Private bootstrap
  data/data/ibmcloud/bootstrap/main.tf
  data/data/ibmcloud/bootstrap/variables.tf
  data/data/ibmcloud/network/outputs.tf
  data/data/ibmcloud/network/vpc/outputs.tf
  data/data/ibmcloud/network/vpc/security-groups.tf
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7017 OCPBUGS-9081: openstack/destroy: BulkDelete more objects at once
  pkg/destroy/openstack/openstack.go
  pkg/destroy/openstack/semaphore.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6952 OCPGUS-2363: IBMCloud: Use direct COS endpoint
  data/data/ibmcloud/bootstrap/main.tf
Labels: approved, lgtm

#7005 OCPBUGS-10638: Properly handle invalid agent command
  cmd/openshift-install/agent.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7018 OCPBUGS-10728 add project filter to gcp usage api requests
  pkg/quota/gcp/usage.go
Labels: approved, lgtm

#7032 OCPBUGS-8349: Kubelet Client Cert should include system:serviceaccounts group
  pkg/asset/tls/kubelet.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6973 OCPBUGS-2130: vSphere - finding networks use full path cluster
  pkg/asset/installconfig/vsphere/client.go
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/installconfig/vsphere/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6991 OCPBUGS-7966: Do not remove host default configuration unless network configuration is provided for it
  pkg/asset/agent/manifests/network-scripts.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#7042 [azure] update tested instance type on 4.13
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm

#7036 OCPBUGS-11039: remove container-runtime flag from kubelet config
  data/data/bootstrap/files/usr/local/bin/kubelet.sh.template
  docs/user/customization.md
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6975 OCPBUGS-8449: pkg/asset/installconfig: set subscriptionID
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/azure/disk.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7047 terraform: don't run zip if building provider binary failed
  terraform/Makefile
Labels: approved, lgtm

#7052 openstack: Bump CI base image to v4.14
  images/openstack/Dockerfile.ci
Labels: approved, lgtm

#7025 OCPBUGS-10845: Use 100 GB as minimum disk size in validations
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6885 MULTIARCH-2517: PowerVS: create install-config improvements
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/asset/installconfig/powervs/platform.go
  pkg/asset/installconfig/powervs/regions.go
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/quota/quota.go
  pkg/destroy/powervs/powervs.go
Labels: approved, lgtm, jira/valid-reference

#7057 OCPBUGS-7954: openstack: Only check HTTPS certs on public endpoints
  docs/user/openstack/invalid-https-certificates.md
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference
