Repository openshift/installer, pull requests merged in 2023-10, with the labels that each got.

#7545 OWNERS: Remove obsolete agent reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#7549 OCPBUGS-20058: Use updated ansible-core for Openstack image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7540 OCPBUGS-15844: Enable FIPS in agent ISO
  pkg/asset/agent/image/kargs.go
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/agentclusterinstall.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7541 OCPBUGS-19835: Enable FIPS in agent ISO
  pkg/asset/agent/image/kargs.go
  pkg/asset/agent/manifests/agentclusterinstall.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7535 Inefficient wait for all clusteroperators
  cmd/openshift-install/create.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/build.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/console.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/imagecontentpolicy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/imagedigestmirrorset.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/imagetagmirrorset.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/network.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/node.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/project.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1alpha1/insightsdatagather.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1alpha1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/build.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/console.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/image.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/imagecontentpolicy.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/imagedigestmirrorset.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/imagetagmirrorset.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/network.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/node.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/project.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/listers/config/v1alpha1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1alpha1/insightsdatagather.go
  vendor/modules.txt
Labels: approved, lgtm

#7557 Disable pxe sno arm integration test
  cmd/openshift-install/testdata/agent/pxe/configurations/sno_arm.txt
Labels: approved, lgtm

#7559 OCPBUGS-20141: [release-4.13] Use updated ansible-core for Openstack image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7560 OCPBUGS-20145: [release-4.12] Use updated ansible-core for Openstack image
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7544 PowerVS: Remove deprecated errors package
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/dns.go
  pkg/asset/installconfig/powervs/metadata.go
  pkg/asset/installconfig/powervs/regions.go
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/machines/powervs/machines.go
  pkg/asset/machines/powervs/machinesets.go
  pkg/destroy/powervs/cloud-instance.go
  pkg/destroy/powervs/cloud-sshkey.go
  pkg/destroy/powervs/dhcp.go
  pkg/destroy/powervs/dns-dns.go
  pkg/destroy/powervs/dns-resource.go
  pkg/destroy/powervs/image.go
  pkg/destroy/powervs/job.go
  pkg/destroy/powervs/loadbalancer.go
  pkg/destroy/powervs/power-instance.go
  pkg/destroy/powervs/power-sshkey.go
  pkg/destroy/powervs/powervs.go
  pkg/destroy/powervs/publicgateway.go
  pkg/destroy/powervs/securitygroup.go
  pkg/destroy/powervs/serviceinstance.go
  pkg/destroy/powervs/subnet.go
  pkg/destroy/powervs/vpc.go
  pkg/terraform/stages/powervs/stages.go
Labels: approved, lgtm

#7563 PowerVS: MULTIARCH-3790 Remove zones that only have CCs with exceptions
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/types/powervs/powervs_regions.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm

#7498 OCPBUGS-19320: [release-4.13] for vsphere ipi add cluster domain to the uploaded vm configs so that…
  data/data/vsphere/bootstrap/main.tf
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7556 Docs: Fix openstack command for image update in upi installation
  docs/user/openstack/install_upi.md
Labels: approved, lgtm

#7422 OCPBUGS-17757: check credentials type to handle different gcp authentication methods
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/types/gcp/doc.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7548 OSASINFRA-3199: Configure User-Agent for OpenStack API calls
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validvaluesfetcher.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/destroy/openstack/glance.go
  pkg/destroy/openstack/openstack.go
  pkg/tfvars/openstack/bootstrap_ignition.go
  pkg/tfvars/openstack/openstack.go
  pkg/tfvars/openstack/rhcos_image.go
  pkg/types/openstack/defaults/client.go
Labels: approved, lgtm, jira/valid-reference

#7555 OCPBUGS-20110: Add an unit test - at least one interface must be defined for each node
  pkg/asset/agent/agentconfig/agent_config_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7259 OpenStack: enable IPv6 primary dual-stack cluster
  data/data/openstack/masters/sg-master.tf
  data/data/openstack/masters/sg-worker.tf
  pkg/types/validation/installconfig.go
Labels: approved, lgtm

#7486 OCPBUGS-18552: Truncate vlan names defined in nmstate if > 15 chars
  pkg/asset/agent/manifests/network-scripts.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7533 OCPBUGS-18455: Unable to disable external CCM for platform external
  cmd/openshift-install/testdata/agent/image/configurations/external_compact.txt
  cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt
  cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt
  cmd/openshift-install/testdata/agent/image/configurations/sno_external_platform.txt
  cmd/openshift-install/testdata/agent/pxe/configurations/compact_external.txt
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7485 OCPBUGS-16666: Change where AdditionalTrustBundle is set
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/infraenv.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7539 [release-4.14] OCPBUGS-19922: Do not start agent-tui if no graphical console available
  data/data/agent/systemd/units/agent-interactive-console.service
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#7492 OCPBUGS-19086: Check if nmstatectl executable exists in the system
  pkg/asset/agent/manifests/staticnetworkconfig/generator.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#6606 docs: Described process of adding vGPU capable nodes.
  docs/user/openstack/README.md
  docs/user/openstack/vgpu.md
Labels: approved, lgtm

#7516 OCPBUGS-19552: Fixed DNS issues in OKD/FCOS due to split dns in systemd-resolved
  data/data/bootstrap/baremetal/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7564 PowerVS: MULTIARCH-3791 Remove cloud connection reuse functionality
  data/data/install.openshift.io_installconfigs.yaml
  data/data/powervs/cluster/main.tf
  data/data/powervs/cluster/power_network/pi_network.tf
  data/data/powervs/variables-powervs.tf
  pkg/asset/cluster/tfvars.go
  pkg/asset/quota/quota.go
  pkg/tfvars/powervs/powervs.go
  pkg/types/powervs/platform.go
Labels: approved, lgtm

#7438 Remove unused method
  pkg/asset/agent/image/agentartifacts.go
Labels: approved, lgtm

#7577 OpenStack: Adapt nodePorts range 0.0.0.0/0 sg rules
  data/data/openstack/masters/sg-master.tf
Labels: approved, lgtm

#7506 OCPBUGS-19444: Use changes to AgentClusterInstall during loading
  pkg/asset/agent/manifests/agentclusterinstall.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7582 OCPBUGS-20440: Warn about host and target compatibility
  pkg/hostcrypt/hostcrypt.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#7583 [release-4.14] OCPBUGS-20441: Warn about host and target compatibility
  pkg/hostcrypt/hostcrypt.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7591 Enforcing the serial execution of the integration tests
  hack/go-integration-test.sh
Labels: approved, lgtm

#7512 OCPBUGS-19093: skip agent-tui on OCI
  pkg/asset/agent/image/agentartifacts.go
Labels: approved, lgtm, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#7575 OCPBUGS-20350: vSphere,segfault on version check
  pkg/asset/installconfig/vsphere/validation.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7561 Revert skipping integration test agent sno arm
  cmd/openshift-install/testdata/agent/pxe/configurations/sno_arm.txt
Labels: approved, lgtm

#7596 OCPBUGS-21781: Rectify GCP label key validation check
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7594 [release-4.14] OCPBUGS-20396: Unable to disable external CCM for platform external
  cmd/openshift-install/testdata/agent/image/configurations/external_compact.txt
  cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt
  cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt
  cmd/openshift-install/testdata/agent/image/configurations/sno_external_platform.txt
  cmd/openshift-install/testdata/agent/pxe/configurations/compact_external.txt
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#7443 OCPBUGS-5471: Try to select rendezvousIP among non-worker hosts
  cmd/openshift-install/testdata/agent/image/validations/no-rendezvousip.txt
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7428 OCPBUGS-13664: Add KMS encryption keys if provided
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/platformpermscheck.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7589 OCPBUGS-20525: aws: use security groups from defaultMachinePlatform
  pkg/asset/cluster/tfvars.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7618 OCPBUGS-20357: update RHCOS 4.14 bootimage metadata to 414.92.202310170514-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7616 OCPBUGS-20356: update RHCOS 4.15 bootimage metadata to 415.92.202310170229-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7488 CORS-2836: Refactor Stages, encapsulate terraform
  cmd/openshift-install/gather.go
  pkg/asset/cluster/cluster.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/provider.go
  pkg/terraform/stage.go
  pkg/terraform/stages/split.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, jira/valid-reference

#6813 OCPBUGS-21720: images/libvirt/Dockerfile.ci: Use centos stream instead centos:7
  images/libvirt/Dockerfile.ci
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7580 OCPBUGS-4038: bootstrap: Enable gatewayd units only on RHCOS
  data/data/bootstrap/systemd/common/units/approve-csr.service
  data/data/bootstrap/systemd/common/units/bootkube.service
  data/data/bootstrap/systemd/common/units/crio-configure.service.template
  data/data/bootstrap/systemd/common/units/kubelet.service.template
  data/data/bootstrap/systemd/common/units/progress.service
  data/data/bootstrap/systemd/common/units/release-image-pivot.service.template
  data/data/bootstrap/systemd/common/units/release-image.service
  data/data/bootstrap/systemd/common/units/systemd-journal-gatewayd.service.d/certs.conf
  data/data/bootstrap/systemd/common/units/zincati.service.d/okd-machine-os-disabled.conf
  data/data/bootstrap/systemd/rhcos/units/chown-gatewayd-key.service
  data/data/bootstrap/systemd/rhcos/units/systemd-journal-gatewayd.socket
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7030 OCPBUGS-10906: check extracted base iso coreos version is in sync
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/oc.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#7625 Revert #7428 "OCPBUGS-13664: Add KMS encryption keys if provided"
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/platformpermscheck.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7593 AGENT-718: Add vSphere credentials to install-config overrides
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_no-credentials.txt
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt
  cmd/openshift-install/testdata/agent/image/validations/vsphere_with-partial-credentials.txt
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/types/vsphere/conversion/installconfig.go
  pkg/types/vsphere/validation/platform.go
Labels: approved, lgtm, jira/valid-reference

#7613 OCPVE-740: bump openshift/api
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_openshift-controller-manager-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.build.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7552 openstack: dual stack UPI - create security group rules for IPv6
  upi/openstack/inventory.yaml
  upi/openstack/security-groups.yaml
Labels: approved, lgtm

#7627 [release-4.12] OCPBUGS-22288: Don't log password values
  pkg/asset/agent/installconfig.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#7531 AGENT-713: Use BM hosts in install-config if not defined in agent-config
  pkg/agent/rest.go
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
  pkg/asset/agent/agentconfig/agenthosts.go
  pkg/asset/agent/agentconfig/agenthosts_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/valid-reference

#7629 OCPBUGS-4038: bootstrap: Skip gatewayd units only on OKD agent-installer
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7639 [azure] update tested x86 instance type on 4.14
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm

#7636 bootkube.sh: drop final mention of `machine-os-content`
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm

#7644 OCPBUGS-22655: Bump Fedora CoreOS to latest stable
  data/data/coreos/fcos.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7635 hack/go-lint: update golanci-lint to v1.53.1
  .golangci.yaml
  hack/go-lint.sh
Labels: approved, lgtm

#7537 OCPBUGS-18986: Skip the deletion of instance profiles marked shared
  pkg/destroy/aws/aws.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7643 OCPBUGS-22489: destroy: gcp: fix destroying regional disks
  pkg/destroy/gcp/disk.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7469 OCPBUGS-18387: Add Azure ConfidentialVM capability and DiskEncryptionSet validations
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
