Repository openshift/installer, pull requests merged in 2023-11, with the labels that each got.

#7638 Bug OCPBUGS-22298: OpenStack: Fix IPv6 address configuration for bootstrap
  data/data/bootstrap/openstack/files/etc/NetworkManager/conf.d/02-ipv6.conf
  data/data/bootstrap/openstack/files/etc/NetworkManager/system-connections/nmconnection.template
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7599 OCPBUGS-19922: Release 4.14 skip agent tui on external oci platform
  pkg/asset/agent/image/agentartifacts.go
  pkg/asset/agent/image/kargs.go
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/manifests/agentclusterinstall.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#7653 OCPBUGS-22773: PowerVS: fix removeFromLoadBalancers
  pkg/terraform/stages/powervs/stages.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#6863 OCPBUGS-17866: check GOOGLE_APPLICATION_CREDENTIALS env var
  pkg/asset/installconfig/gcp/session.go
Labels: approved, lgtm, ok-to-test, qe-approved, jira/valid-bug, jira/valid-reference

#7576 OCPBUGS-20403: OpenStack: add SG rules for compact clusters on UPI
  docs/user/openstack/install_upi.md
  upi/openstack/inventory.yaml
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7654 OCPBUGS-22757: update RHCOS 4.15 bootimage metadata to 415.92.202310310037-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7608 OCPBUGS-22113: Do not generate azure-cloud-provider in manual mode for aro builds
  pkg/asset/manifests/openshift.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#7663 OCPBUGS-22830: fix google cli verson to 447.0.0
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7655 OCPBUGS-22758: update RHCOS 4.14 bootimage metadata to 414.92.202310210434-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7668 OCPBUGS-19398: IBMCloud: Add eu-es region
  pkg/types/ibmcloud/validation/platform.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7671 OCPBUGS-22772: return Terraform statefile on error
  pkg/terraform/terraform.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7413 CORS-2877: Install Config Feature Gate Validation
  pkg/asset/manifests/featuregate.go
  pkg/types/featuregates/featuregate.go
  pkg/types/featuregates/featuregates.go
  pkg/types/gcp/validation/featuregates.go
  pkg/types/installconfig.go
  pkg/types/validation/featuregate_test.go
  pkg/types/validation/installconfig.go
  pkg/types/vsphere/validation/featuregates.go
Labels: approved, lgtm, jira/valid-reference

#7656 CORS-2835: use build tags to produce installer with alternate infrastructure providers
  cmd/openshift-install/gather.go
  hack/build.sh
  pkg/asset/cluster/cluster.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
Labels: approved, lgtm, jira/valid-reference

#7570 OSASINFRA-3237: move controlPlanePort API to GA
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/openstack/deploy_dual_stack_cluster.md
  pkg/types/openstack/platform.go
  pkg/types/openstack/validation/techpreview.go
  pkg/types/openstack/validation/techpreview_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-reference

#7687 CORS-2428: images: add Dockerfile for a terraform-providers image
  images/terraform-providers/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#7681 [release-4.14] OCPBUGS-22945: Update gcloud version to 447.0.0
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7695 MULTIARCH-2590: PowerVS create service instance
  data/data/install.openshift.io_installconfigs.yaml
  data/data/powervs/bootstrap/iaas/iaas.tf
  data/data/powervs/bootstrap/iaas/outputs.tf
  data/data/powervs/bootstrap/iaas/variables.tf
  data/data/powervs/bootstrap/iaas/versions.tf
  data/data/powervs/bootstrap/main.tf
  data/data/powervs/cluster/iaas/iaas.tf
  data/data/powervs/cluster/iaas/outputs.tf
  data/data/powervs/cluster/iaas/variables.tf
  data/data/powervs/cluster/iaas/versions.tf
  data/data/powervs/cluster/main.tf
  data/data/powervs/cluster/power_network/pi_network.tf
  data/data/powervs/cluster/power_network/variables.tf
  data/data/powervs/iaas/variables.tf
  data/data/powervs/variables-powervs.tf
  pkg/asset/cluster/powervs/powervs.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/platform.go
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/machines/powervs/machines.go
  pkg/asset/machines/powervs/machinesets.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/powervs/cloudproviderconfig.go
  pkg/asset/quota/quota.go
  pkg/destroy/powervs/powervs.go
  pkg/tfvars/powervs/powervs.go
  pkg/types/powervs/metadata.go
  pkg/types/powervs/platform.go
  pkg/types/powervs/validation/platform.go
  pkg/types/powervs/validation/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#7708 OCPBUGS-23170: Revert #7418 "SPLAT-1141: implement vSphere control plane machinesets"
  go.mod
  go.sum
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/master.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/machines/vsphere/machines_test.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/vsphere/infrastructure.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/custom.controlplanemachineset.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.aws.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.azure.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.gcp.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/techpreview.controlplanemachineset.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7664 OSASINFRA-3280: openstack: document etcd on local disk
  docs/user/openstack/customization.md
  docs/user/openstack/etcd-ephemeral-disk.md
Labels: approved, lgtm, jira/valid-reference

#7694 Bug OCPBUGS-19462: OpenStack: Fix dual-stack machines Spec to contain network
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7711 CORS-2876: images/installer-altinfra: initial Dockerfile
  images/installer-altinfra/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference

#7677 OCPBUGS-22933: [release-4.12]: vsphere: fix validation of CPUS and CoresPerSocket
  pkg/types/vsphere/validation/machinepool.go
  pkg/types/vsphere/validation/machinepool_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#7706 OCPBUGS-23141: Specify google cloud CLI to version 447.0.0
  images/installer/Dockerfile.upi.ci
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7696 MULTIARCH-3789: Power VS: Remove cloud connection support
  data/data/powervs/cluster/power_network/pi_network.tf
  data/data/powervs/cluster/power_network/variables.tf
  pkg/asset/installconfig/powervs/session.go
  pkg/destroy/powervs/cloudconnection.go
  pkg/destroy/powervs/powervs.go
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7676 CORS-2830: Provision AWS Infrastructure with SDK
  pkg/destroy/aws/aws.go
  pkg/destroy/aws/ec2helpers.go
  pkg/destroy/aws/errortracker.go
  pkg/destroy/aws/iamhelpers.go
  pkg/destroy/aws/shared.go
  pkg/infrastructure/aws/aws.go
  pkg/infrastructure/aws/bootstrap.go
  pkg/infrastructure/aws/compute.go
  pkg/infrastructure/aws/controlplane.go
  pkg/infrastructure/aws/destroy.go
  pkg/infrastructure/aws/dns.go
  pkg/infrastructure/aws/instance.go
  pkg/infrastructure/aws/loadbalancer.go
  pkg/infrastructure/aws/provision_test.go
  pkg/infrastructure/aws/securitygroup.go
  pkg/infrastructure/aws/vpc.go
  pkg/infrastructure/platform/platform_altinfra.go
  pkg/tfvars/aws/aws.go
  pkg/tfvars/tfvars.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/elbv2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/route53/route53iface/interface.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7675 OSASINFRA-3229: Remove support for Kuryr
  docs/user/openstack/README.md
  docs/user/openstack/customization.md
  docs/user/openstack/deploy_baremetal_workers.md
  docs/user/openstack/deploy_sriov_workers.md
  docs/user/openstack/install_upi.md
  docs/user/openstack/known-issues.md
  docs/user/openstack/kuryr.md
  docs/user/openstack/privileges.md
  pkg/asset/quota/openstack/openstack.go
  pkg/asset/quota/quota.go
  pkg/destroy/openstack/openstack.go
  pkg/types/validation/installconfig.go
  upi/openstack/README.md
  upi/openstack/common.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/down-compute-nodes.yaml
  upi/openstack/down-control-plane.yaml
  upi/openstack/down-load-balancers.yaml
  upi/openstack/down-network.yaml
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/urls.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7724 AGENT-337: Support both VIP and VIPs in AgentClusterInstall
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_no-credentials.txt
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7732 no-jira: Stop rendering networks.config CRD
  data/data/manifests/openshift/cluster-networkconfig-crd.yaml
  pkg/asset/manifests/network.go
  pkg/asset/templates/content/openshift/cluster-network-crds.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7737 OCPBUGS-23376: vSphere - when using RP network path is incorrect
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/vsphere/client.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#7716 no-jira: images: rename terraform- > infrastructure-providers
  images/infrastructure-providers/Dockerfile
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7743 OSASINFRA-3294: OpenStack: fix script to update bootstrap ignition shim
  docs/user/openstack/install_upi.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7747 [release-4.11] OCPBUGS-23478: Specify google cloud CLI to version 256.0.0
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7723 OSASINFRA-3295: OpenStack: fix client used to list flavors
  pkg/asset/installconfig/openstack/validvaluesfetcher.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7617 OCPCLOUD-2130: Fix Failuredomains check on manifests test
  go.mod
  go.sum
  pkg/asset/machines/aws/machines.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/gcp/machines.go
  pkg/asset/machines/openstack/machines.go
  scripts/openstack/manifest-tests/base-case/test_cpms.py
  scripts/openstack/manifest-tests/zero-workers/test_cpms.py
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7750 no-jira: destroy/azure: avoid cancelling main context
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7758 no-jira: destroy/azure: fix dropped negation from error comparison
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7704 MULTIARCH-3964: Power VS: Control SMT level with machineconfig
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/machines/machineconfig/powersmt.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/powervs/machinepools.go
  pkg/types/powervs/validation/machinepool.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7721 OCPBUGS-22840: ic/azure: validate field Plan when for marketplace images
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#7632 CORS-2933: IBMCloud: Basic service endpoint override
  data/data/ibmcloud/bootstrap/common.tf
  data/data/ibmcloud/bootstrap/ignition.tf
  data/data/ibmcloud/master/common.tf
  data/data/ibmcloud/network/common.tf
  data/data/ibmcloud/network/image/main.tf
  data/data/ibmcloud/network/image/variables.tf
  data/data/ibmcloud/network/main.tf
  data/data/ibmcloud/variables-ibmcloud.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/ibmcloud/ibmcloud.go
  pkg/asset/cluster/metadata.go
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/dns.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/metadata_test.go
  pkg/asset/installconfig/ibmcloud/validation.go
  pkg/asset/installconfig/ibmcloud/validation_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/machines/ibmcloud/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/ibmcloud/cloudproviderconfig.go
  pkg/asset/manifests/ibmcloud/cloudproviderconfig_test.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/openshift.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/destroy/ibmcloud/ibmcloud.go
  pkg/terraform/stages/ibmcloud/stages.go
  pkg/tfvars/ibmcloud/ibmcloud.go
  pkg/types/ibmcloud/metadata.go
  pkg/types/ibmcloud/platform.go
  pkg/types/ibmcloud/platform_test.go
  pkg/types/ibmcloud/validation/platform.go
  pkg/types/ibmcloud/validation/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#7674 OCPBUGS-21777: baremetal: populate customDeploy in advance
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7745 CORS-2835: pkg/infrastructure: remove ARO build tag
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
Labels: approved, lgtm, jira/valid-reference

#7762 no-jira: go.mod: remove unused terraform-providers-nutanix import
  go.mod
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7761 CORS-2775: destroy: azure: remove deprecated `errors` package
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, jira/valid-reference

#7730 SPLAT-1272: Support Nutanix Failure Domains
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/installconfig/nutanix/validation.go
  pkg/asset/machines/nutanix/machines.go
  pkg/asset/machines/nutanix/machinesets.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/nutanix/infrastructure.go
  pkg/types/nutanix/machinepool.go
  pkg/types/nutanix/platform.go
  pkg/types/nutanix/validation/platform.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7749 OCPBUGS-24026: Add owner for user provided client CA bundle
  data/data/manifests/bootkube/machine-config-server-tls-secret.yaml.template
  pkg/asset/manifests/additionaltrustbundleconfig.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7763 CORS-2428: terraform: add build information to binaries
  terraform/Makefile
Labels: approved, lgtm, jira/valid-reference

#7777 no-jira: destroy: azure: store session in the destroy object
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, jira/valid-reference

#7779 OCPBUGS-24031: Bump Fedora CoreOS to latest stable
  data/data/coreos/fcos.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7666 Skip cluster config
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: do-not-merge/hold, approved

#7719 AGENT-670: Add assisted-db data to agent-gather
  data/data/agent/files/usr/local/bin/agent-gather
Labels: approved, lgtm, jira/valid-reference

#7772 OSASINFRA-3303: OpenStack: remove generation of trunks name
  upi/openstack/common.yaml
Labels: approved, lgtm, jira/valid-reference

#7780 SPLAT-1277: unrevert PR 7418; implement vSphere control plane machinesets
  pkg/asset/machines/master.go
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/machines/vsphere/machines_test.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/vsphere/infrastructure.go
Labels: approved, lgtm, jira/valid-reference

#7520 CORS-2845: azure: Enable storage account encryption
  data/data/azure/bootstrap/main.tf
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/main.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/explain/printer_test.go
  pkg/tfvars/azure/azure.go
  pkg/tfvars/tfvars.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#7631 CORS-2798: GCP: User Configured DNS solution to update the bootstrap node with the Load Balancer Information
  cmd/openshift-install/create.go
  data/data/gcp/cluster/main.tf
  data/data/gcp/cluster/outputs.tf
  data/data/gcp/variables-gcp.tf
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/kubeconfig/remote.go
  pkg/asset/lbconfig/lbconfig.go
  pkg/terraform/stage.go
  pkg/terraform/stages/gcp/stages.go
  pkg/terraform/stages/split.go
  pkg/terraform/terraform.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/platform.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
