Repository openshift/installer, pull requests merged in 2024-11, with the labels that each got.

#9129 OCPBUGS-43513: day2 set UserManageNetworking for none/external platforms
  cmd/node-joiner/nodejoiner_integration_test.go
  cmd/node-joiner/testdata/add-nodes-usermanagednetworking-external.txt
  cmd/node-joiner/testdata/add-nodes-usermanagednetworking-none.txt
  cmd/node-joiner/testdata/add-nodes.txt
  cmd/openshift-install/testdata/agent/image/configurations/baremetal_host_bmc_config.txt
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_no-credentials.txt
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt
  pkg/asset/agent/common.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/joiner/importclusterconfig.go
  pkg/asset/agent/joiner/importclusterconfig_test.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9123 no-jira: Collect bootstrap logs when control plane provisioning fails
  cmd/openshift-install/create.go
  cmd/openshift-install/gather.go
  pkg/asset/asset.go
  pkg/infrastructure/clusterapi/clusterapi.go
  pkg/utils/baremetal/bootstrap.go
Labels: approved, lgtm, jira/valid-reference

#9108 OCPBUGS-42544: support additionalNTPSources in node-joiner tool
  cmd/node-joiner/testdata/add-nodes-chrony-conf.txt
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/joiner/clusterinfo_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9166 OCPBUGS-44162: PowerVS: Fix destroy persistent TG
  pkg/destroy/powervs/cloud-transit-gateways.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9168 NO-ISSUE: Add mresvanis to imagebased approvers
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9135 OCPBUGS-43760: azure: use filter when listing SKUs
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation_test.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/2018-03-01/compute/mgmt/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinesizes.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9122 OCPBUGS-39586: Add C4A instance types
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/installconfig/gcp/validation.go
  pkg/explain/fields_lookup_test.go
  pkg/explain/printer_test.go
  pkg/types/gcp/machinepools.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/services/tags/tagservice.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/services/tags/tagservice_mock.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/util/gcp_machine_architecture.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/util/gcp_tags_labels.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/flatten.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/package.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/priority.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/register.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/topology.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/genall.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/output.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/loader.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/refs.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/collect.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/zip.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/version/version.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference

#9161 MGMT-19200: Adding NodeLabels param for image-based-configuration iso
  pkg/asset/imagebased/configimage/clusterconfiguration.go
  pkg/asset/imagebased/configimage/clusterconfiguration_test.go
  pkg/asset/imagebased/configimage/util_test.go
  pkg/types/imagebased/imagebased_config_types.go
  pkg/types/imagebased/seedreconfiguration.go
Labels: approved, lgtm, jira/valid-reference

#9149 MGMT-19191: Provide a way to add coreos installer params for installation phase
  go.mod
  pkg/asset/imagebased/image/ignition.go
  pkg/asset/imagebased/image/imagebased_config.go
  pkg/asset/imagebased/image/imagebased_config_test.go
  pkg/types/imagebased/imagebased_config_types.go
Labels: approved, lgtm, jira/valid-reference

#8999 [release-4.16] OCPBUGS-41885: vSphere - If template is defined skip downloading
  pkg/infrastructure/vsphere/clusterapi/clusterapi.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9139 AGENT-974: Add integration test for agent minimal ISO
  cmd/openshift-install/internal_integration_test.go
  cmd/openshift-install/testdata/agent/image/configurations/compact_minimal_iso.txt
  internal/tshelpers/custom_commands.go
Labels: approved, lgtm, jira/valid-reference

#9046 OSASINFRA-3516: Document correlated observability
  docs/user/openstack/README.md
  docs/user/openstack/observability.md
Labels: approved, lgtm, jira/valid-reference

#9167 OCPBUGS-44167: Ensure rendezvousIP is checked against host IP
  pkg/asset/agent/agentconfig/agenthosts.go
  pkg/asset/agent/agentconfig/agenthosts_test.go
  pkg/asset/agent/common.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9164 OCPBUGS-42670: Allow AdditionalTrustBundlePolicy to be set
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9013 OCPBUGS-41642: vendor: Update openshift/api to pick up v4.17 capability sets
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9143 MULTIARCH-5150: Pass IAM endpoint override to PowerVS CloudProviderConfig
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/powervs/cloudproviderconfig.go
Labels: approved, lgtm, jira/valid-reference

#9170 OCPBUGS-39404: Enable TLS by default between Metal3's httpd server and the BMC (for serving virtual media images)
  pkg/asset/ignition/bootstrap/baremetal/template.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9097 AGENT-859: Support for PXE files in day 2
  cmd/node-joiner/main.go
  cmd/node-joiner/testdata/add-nodes-pxe.txt
  internal/tshelpers/fakeregistry.go
  pkg/asset/agent/image/agentartifacts.go
  pkg/asset/agent/joiner/addnodesconfig.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/nodejoiner/addnodes.go
  pkg/nodejoiner/monitoraddnodes.go
Labels: approved, lgtm, jira/valid-reference

#9152 [release-4.17] OCPBUGS-43972: Cherrypick oci ccm fix to 4.17
  cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt
  cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#8704 CORS-3571: permissions: add new create command and asset
  cmd/openshift-install/create.go
  go.mod
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/permissions/permissions.go
  pkg/asset/targets/targets.go
Labels: approved, lgtm, jira/valid-reference

#9154 AGENT-990: Allow control planes with 5 and 4 replicas
  cmd/openshift-install/testdata/agent/image/configurations/control-plane-4-replicas.txt
  cmd/openshift-install/testdata/agent/image/configurations/control-plane-5-replicas.txt
  cmd/openshift-install/testdata/agent/image/validations/compact_invalid_controlPlane_replicas.txt
  docs/user/agent/control-plane-replicas.md
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9146 AGENT-965: improve node-joiner create command troubleshooting
  cmd/node-joiner/testdata/add-nodes-report.txt
  docs/dev/workflow_report.md
  pkg/asset/agent/image/agentartifacts.go
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/baseiso.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/manifests/agent.go
  pkg/asset/agent/workflow/commons.go
  pkg/asset/agent/workflow/report/context.go
  pkg/asset/agent/workflow/report/report.go
  pkg/asset/agent/workflow/report/report_interfaces.go
  pkg/asset/agent/workflow/report/report_test.go
  pkg/asset/agent/workflow/report/stage.go
  pkg/asset/agent/workflow/report/stageid.go
  pkg/nodejoiner/addnodes.go
Labels: approved, lgtm, jira/valid-reference

#9153 OCPBUGS-30292: If agent proxy defined, add MachineNetwork to noProxy
  cmd/openshift-install/testdata/agent/image/configurations/compact.txt
  cmd/openshift-install/testdata/agent/image/configurations/control-plane-4-replicas.txt
  cmd/openshift-install/testdata/agent/image/configurations/control-plane-5-replicas.txt
  cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
  data/data/agent/files/etc/systemd/system.conf.d/10-default-env.conf.template
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/common.go
  pkg/asset/agent/manifests/infraenv.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9172 AGENT-967: Improve monitoring output for multi-node
  cmd/node-joiner/main.go
  pkg/agent/cluster.go
  pkg/agent/logging.go
  pkg/agent/monitoraddnodes.go
  pkg/agent/monitoraddnodes_test.go
  pkg/agent/validations.go
  pkg/agent/validations_test.go
Labels: approved, lgtm, jira/valid-reference

#9190 MULTIARCH-5162: Power VS: Bump openshift/api to include https://github.com/openshift/api/pull/2076
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/legacyfeaturegates.go
  vendor/github.com/openshift/api/features/util.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_olm.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9188 [release-4.16] OCPBUGS-44348: Cherrypick oci ccm fix to 4.16
  cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt
  cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9171 OCPBUGS-44171: Validate aws userTags when supplied
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9198 No-Issue: Temporarily set none authenticator
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
Labels: approved, lgtm, jira/valid-reference

#9197 OCPBUGS-44199: Allow spaces in the aws tags
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9106 OCPBUGS-43439: permissions: add ec2:DescribeInstanceTypes requirement
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/permissions_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9191 CORS-3748: IBMCloud: Setup IBM Cloud CAPI InfraReady step
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/ibmcloud.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/metadata_test.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/asset/manifests/ibmcloud/loadbalancers.go
  pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
Labels: approved, lgtm, jira/valid-reference

#9184 OCPBUGS-44261: Ensure rendezvousIP is checked against host IP
  pkg/asset/agent/agentconfig/agenthosts.go
  pkg/asset/agent/agentconfig/agenthosts_test.go
  pkg/asset/agent/common.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8886 AGENT-959: iSCSI Boot
  data/data/agent/files/usr/local/bin/oci-eval-user-data.sh
  data/data/agent/systemd/units/iscsistart.service
  data/data/agent/systemd/units/oci-eval-user-data.service
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/image/unconfigured_ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#9193 CORS-3680: update docs to include C4/C4A machine types
  docs/user/gcp/tested_instance_types.md
  docs/user/gcp/tested_instance_types_arm.md
Labels: approved, lgtm, jira/valid-reference

#9208 OCPBUGS-44580: Agent handle IPv6 correctly in net.Dial
  pkg/agent/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9039 AGENT-950: Implement Separate JWT Tokens for Different User Personas
  cmd/node-joiner/testdata/add-nodes.txt
  data/data/agent/files/usr/local/bin/add-node.sh
  data/data/agent/files/usr/local/bin/agent-auth-token-status.sh
  data/data/agent/files/usr/local/bin/common.sh
  data/data/agent/files/usr/local/bin/start-agent.sh
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/systemd/units/agent-auth-token-status.service
  data/data/agent/systemd/units/agent-import-cluster.service.template
  data/data/agent/systemd/units/agent-register-cluster.service.template
  data/data/agent/systemd/units/agent-register-infraenv.service.template
  data/data/agent/systemd/units/apply-host-config.service
  pkg/agent/cluster.go
  pkg/agent/rest.go
  pkg/asset/agent/gencrypto/auth_utils.go
  pkg/asset/agent/gencrypto/auth_utils_test.go
  pkg/asset/agent/gencrypto/authconfig.go
  pkg/asset/agent/gencrypto/authconfig_test.go
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#9181 OCPBUGS-44230: Add C4A instance types
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/installconfig/gcp/validation.go
  pkg/explain/fields_lookup_test.go
  pkg/explain/printer_test.go
  pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/services/tags/tagservice.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/services/tags/tagservice_mock.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/util/gcp_machine_architecture.go
  vendor/github.com/openshift/machine-api-provider-gcp/pkg/cloud/gcp/actuators/util/gcp_tags_labels.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/genall.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/output.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/loader.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/collect.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/zip.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9187 OCPBUGS-44312: Power VS: Add new zones
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8030 OCPBUGS-29109: IBMCloud: RG delete failure details
  pkg/destroy/ibmcloud/resourcegroup.go
Labels: approved, lgtm, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#8811 OCPBUGS-29067: Prepend resolv.conf on the bootstrap node of GCP with custom-dns
  data/data/bootstrap/gcp/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/ignition/bootstrap/gcp/template.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9196 OPRUN-3588: Add OperatorLifecycleManagerV1 capability
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/awsplatformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/nodespec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9199 CORS-3474: IBMCloud: Add CAPI Ignition for bootstrap node.
  pkg/asset/ignition/bootstrap/ibmcloud/storage.go
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
Labels: approved, lgtm, jira/valid-reference

#9201 CORS-3753: Allow mocking of the Azure client everywhere
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/metadata.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/azure/cluster.go
Labels: approved, lgtm, jira/valid-reference

#9085 CORS-3709: GCP: Update Master pointer Ignition with API-Int IP
  pkg/asset/cluster/cluster.go
  pkg/asset/tls/certkey.go
  pkg/asset/tls/mcscertkey.go
  pkg/infrastructure/aws/clusterapi/aws.go
  pkg/infrastructure/aws/clusterapi/ignition.go
  pkg/infrastructure/clusterapi/clusterapi.go
  pkg/infrastructure/clusterapi/ignition.go
  pkg/infrastructure/clusterapi/types.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/ignition.go
Labels: approved, lgtm, jira/valid-reference

#9207 CORS-3754: AWS: With UserProvisionedDNS, keep resolv.conf on the bootstrap node updated
  data/data/bootstrap/aws/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
  pkg/asset/ignition/bootstrap/aws/template.go
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9165 MULTIARCH-5161: Power VS: Create VPEs as needed for Disconnected install
  pkg/asset/cluster/metadata.go
  pkg/asset/cluster/powervs/powervs.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/metadata.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/powervs/cloudproviderconfig.go
  pkg/clusterapi/system.go
  pkg/infrastructure/powervs/clusterapi/powervs.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9215 AGENT-901: update agent docs for add-nodes workflow
  docs/user/agent/agent-services.md
  docs/user/agent/agent_installer_services-add_nodes_workflow.png
  docs/user/agent/agent_installer_services-install_workflow.png
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9133 CORS-3741: [Nutanix] support multiple subnets
  go.mod
  go.sum
  pkg/types/nutanix/validation/platform.go
  pkg/types/nutanix/validation/platform_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_olm.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9114 OCPBUGS-43453: permissions: add ec2:DescribeInstanceTypeOfferings req
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/permissions_test.go
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9212 CORS-2754: ipv4.internalJoinSubnet Support
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/manifests/network.go
  pkg/asset/manifests/network_test.go
  pkg/asset/manifests/ovnkubeconfig.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9210 AGENT-1028: Day2 - Save and manage authentication tokens as cluster secrets
  pkg/agent/cluster.go
  pkg/asset/agent/gencrypto/authconfig.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9213 AGENT-965: add ClusterInfo report result
  pkg/asset/agent/joiner/clusterinfo.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9214 AGENT-1022: add node-joiner --config-iso flag
  cmd/node-joiner/main.go
  pkg/asset/agent/joiner/addnodesconfig.go
  pkg/nodejoiner/addnodes.go
  pkg/nodejoiner/monitoraddnodes.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9217 MGMT-19292: align image based extraPartitionlabel with var-lib-containers partition label
  pkg/asset/imagebased/image/ignition_test.go
  pkg/asset/imagebased/image/imagebased_config.go
  pkg/asset/imagebased/image/imagebased_config_test.go
  pkg/types/imagebased/imagebased_config_types.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9202 OCPBUGS-44193: Reduce Server Side Filtering of Resources
  pkg/destroy/gcp/address.go
  pkg/destroy/gcp/backendservice.go
  pkg/destroy/gcp/bucket.go
  pkg/destroy/gcp/bucketobject.go
  pkg/destroy/gcp/cloudcontroller.go
  pkg/destroy/gcp/disk.go
  pkg/destroy/gcp/filestore.go
  pkg/destroy/gcp/firewall.go
  pkg/destroy/gcp/forwardingrule.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/healthcheck.go
  pkg/destroy/gcp/httphealthcheck.go
  pkg/destroy/gcp/image.go
  pkg/destroy/gcp/instance.go
  pkg/destroy/gcp/instancegroup.go
  pkg/destroy/gcp/network.go
  pkg/destroy/gcp/route.go
  pkg/destroy/gcp/router.go
  pkg/destroy/gcp/subnetwork.go
  pkg/destroy/gcp/targetTCPProxies.go
  pkg/destroy/gcp/targetpool.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9226 OCPBUGS-43625: Bump Azure Machine Timeout
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#9209 OCPBUGS-44611: [release-4.17] capi/aws: set Node Port Service CIDR override
  pkg/asset/manifests/aws/cluster.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8928 METAL-1136: user defined additional provisioning NPT servers
  data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
  data/data/bootstrap/baremetal/files/etc/ironic.env.template
  data/data/install.openshift.io_installconfigs.yaml
  data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
  pkg/asset/agent/agentconfig/agent_config.go
  pkg/asset/agent/agentconfig/agent_config_test.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/manifests/infraenv.go
  pkg/asset/agent/manifests/util_test.go
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/imagebased/configimage/imagebased_config.go
  pkg/asset/imagebased/configimage/imagebased_config_test.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9219 [release-4.17] CORS-3753: Allow mocking of the Azure client everywhere
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/metadata.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/azure/cluster.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9229 ARO-12457: data/data: include bootkube files in go module
  data/data/tools.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only

#9231 OCPBUGS-44922: Power VS: SetDefaultPrivateServiceEndpoints mistakenly called for External deploys
  pkg/asset/manifests/cloudproviderconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#9220 [release-4.16] CORS-3753: Allow mocking of the Azure client everywhere
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/azure/metadata.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9221 [release-4.15] CORS-3753: Allow mocking of the Azure client everywhere
  pkg/asset/cluster/tfvars.go
  pkg/asset/installconfig/azure/metadata.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9116 OCPBUGS-43561: add zsh completion
  cmd/openshift-install/completions.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9169 OCPBUGS-44193: move GCP zone filtering client-side
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/machines/gcp/zones.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9233 OCPBUGS-44924: aws: add missing ec2:GetConsoleOutput perm requirement
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/valid-reference

#9136 NO-ISSUE: imagebasedinstaller: support json files in extramanifests directory
  cmd/openshift-install/testdata/imagebased/configimage/manifests/extra_manifests.txt
  pkg/asset/imagebased/configimage/extramanifests.go
  pkg/asset/imagebased/configimage/extramanifests_test.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#9247 [release-4.16] OCPBUGS-45181: add chrony.conf file when additional NTP sources are configured
  cmd/openshift-install/testdata/agent/image/assets/with_additional_ntp_sources.txt
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
