Repository openshift/installer, pull requests merged in 2024-03, with the labels that each got.

#7997 AGENT-853: Add ClusterInfo asset
  cmd/node-joiner/main.go
  pkg/asset/agent/joiner/addnodesconfig.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/workflow/agentworkflow.go
  pkg/asset/agent/workflow/agentworkflowaddnodes.go
  pkg/asset/agent/workflow/commons.go
  pkg/nodejoiner/addnodes.go
Labels: approved, lgtm, jira/valid-reference

#7279 CFE-857: Apply user defined tags on created gcp resources
  data/data/gcp/bootstrap/main.tf
  data/data/gcp/cluster/main.tf
  data/data/gcp/cluster/master/main.tf
  data/data/gcp/cluster/master/variables.tf
  data/data/gcp/variables-gcp.tf
  go.mod
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/gcp/mock/usertags_mock.go
  pkg/asset/installconfig/gcp/usertags.go
  pkg/asset/installconfig/gcp/usertags_test.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/machines/gcp/machines.go
  pkg/tfvars/gcp/gcp.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  vendor/google.golang.org/api/cloudresourcemanager/v3/cloudresourcemanager-api.json
  vendor/google.golang.org/api/cloudresourcemanager/v3/cloudresourcemanager-gen.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, jira/valid-reference

#8077 CORS-3259: GCP CAPI Infra: auth with service account
  pkg/infrastructure/gcp/clusterapi/dns.go
  pkg/infrastructure/gcp/clusterapi/service.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#7969 CORS-3251: Create capz machine manifests
  go.mod
  pkg/asset/machines/azure/azuremachines.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/manifests/azure/cluster.go
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#8055 CORS-3274: GCP: add africa-south1 region to the survey as supported region
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#8092 OCPBUGS-30135: fix "OpenShiftSDN deprecated" error message
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7789 no-jira: Missing permission from vsphere docs
  docs/user/vsphere/privileges.md
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#8069 MULTIARCH-4153: Incorporating Eltorito Boot Loader fix for Agent
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-image-service/pkg/isoeditor/isoutil.go
  vendor/github.com/openshift/assisted-image-service/pkg/isoeditor/stream.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#8083 OCPBUGS-30057: Don't auto create subnets for CAPG
  pkg/asset/manifests/gcp/cluster.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference

#8038 OCPBUGS-29627: update RHCOS 4.13 bootimage metadata to 413.92.202402131523-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8079 OCPBUGS-30058: GCP: The CAPG bootstrap machine IP should be set according to the publish strategy
  pkg/asset/machines/gcp/gcpmachines.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference

#8098 MULTIARCH-4159: Updated libvirt installer to include multi-arch yq and symlink for backwards compatibility
  images/libvirt/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference

#8081 SPLAT-1423: Added static ip support to CAPI installer.
  pkg/asset/machines/vsphere/capimachines.go
  pkg/utils/vmware.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1/conversion.go
  vendor/sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1/doc.go
  vendor/sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1/groupversion_info.go
  vendor/sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1/ipaddress_types.go
  vendor/sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1/ipaddressclaim_types.go
  vendor/sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1/zz_generated.conversion.go
  vendor/sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, jira/valid-reference

#8070 OCPBUGS-29469: fix Azure API SKU calls timing out - part 2
  pkg/asset/installconfig/azure/client.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8085 no-jira: capi: aws: report all conflicting user tags at once
  pkg/asset/machines/aws/awsmachines.go
Labels: approved, lgtm, jira/valid-reference

#8097 SPLAT-1468: Added log message for import vsphere ova progress during CAPI install.
  pkg/infrastructure/vsphere/clusterapi/import.go
Labels: approved, lgtm, jira/valid-reference

#8044 SPLAT-1460: Make vSphere default ResourcePool formatting not contain double slash.
  cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt
  pkg/asset/agent/installconfig_test.go
  pkg/types/vsphere/defaults/platform.go
  pkg/types/vsphere/defaults/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#8090 CORS-3281: IBMCloud: initial CAPI infrastructure
  pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
Labels: approved, lgtm, jira/valid-reference

#8031 CORS-2900: CAPI AWS IAM
  pkg/asset/manifests/clusterapi/cluster.go
  pkg/infrastructure/aws/clusterapi/aws.go
  pkg/infrastructure/aws/clusterapi/iam.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/iam/api/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/iam/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#8103 OCPBUGS-30259: PowerVS remove ibm cloud/bluemix go 4.14
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/installconfig/powervs/session.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/accounts.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/api_service.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/paginate.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8104 OSASINFRA-3362: Fix CAPI bootstrap deletion
  pkg/infrastructure/clusterapi/clusterapi.go
Labels: approved, lgtm, jira/valid-reference

#8112 OCPBUGS-29388: upi: aws: fix typo in worker templates
  upi/aws/cloudformation/06_cluster_worker_node.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8107 METAL-871: baremetal: bootstrap: rename master label
  data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
Labels: approved, lgtm, jira/valid-reference

#8120 no-jira: machines/aws: fix subnet filter comment
  pkg/asset/machines/aws/machines.go
Labels: approved, lgtm, jira/valid-reference

#8111 OCPBUGS-30641: Enable deploy by Service ID on PowerVS
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/metadata.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8117 METAL-871: baremetal: remove ironic tf files
  data/data/baremetal/masters/main.tf
  data/data/baremetal/masters/outputs.tf
  data/data/baremetal/variables-baremetal.tf
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
Labels: approved, lgtm, jira/valid-reference

#8131 OCPBUGS-30547,OCPBUGS-29437: Run kubelet directly
  data/data/bootstrap/files/usr/local/bin/kubelet.sh.template
  docs/user/customization.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8066 CORS-3257: Create GCP ServiceAccounts and assign to machines
  pkg/asset/machines/gcp/gcpmachines.go
  pkg/asset/machines/gcp/gcpmachines_test.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/iam.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#8121 OCPBUGS-30600: update RHCOS 4.16 bootimage metadata to 416.94.202403071059-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8082 OCPBUGS-25462: Validate control plane replicas
  cmd/openshift-install/testdata/agent/image/validations/compact_invalid_controlPlane_replicas.txt
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8145 OCPBUGS-30836: Power VS: Fix wait_for_workspace
  data/data/powervs/cluster/iaas/iaas.tf
  data/data/powervs/cluster/iaas/outputs.tf
  data/data/powervs/variables-powervs.tf
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8086 [release-4.15] OCPBUGS-29964: fix Azure API SKU calls timing out
  pkg/asset/installconfig/azure/client.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8150 CORS-2892: capi/aws: add user tags to CAPA cluster
  pkg/asset/manifests/aws/cluster.go
Labels: approved, lgtm, jira/valid-reference

#7908 SPLAT-1390: remove feature gate for vSphere control plane machinesets
  pkg/asset/machines/master.go
  pkg/asset/machines/vsphere/machines.go
  pkg/types/vsphere/validation/platform.go
Labels: approved, lgtm, jira/valid-reference

#8159 [release-4.15] OCPBUGS-30854: Power VS: Fix wait_for_workspace
  data/data/powervs/cluster/iaas/iaas.tf
  data/data/powervs/cluster/iaas/outputs.tf
  data/data/powervs/variables-powervs.tf
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8132 CORS-3303: GCP: Add me-central2 (Dammam, Saudi Arabia, Middle East) region to the survey as supported region
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, jira/valid-reference

#8102 OPNET-476: GA Load balancer feature for Nutanix
  pkg/types/nutanix/validation/platform.go
  pkg/types/nutanix/validation/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#8158 no-jira: Power VS: Fix comment on default for wait_for_workspace
  data/data/powervs/variables-powervs.tf
Labels: approved, lgtm, jira/valid-reference

#8122 OCPBUGS-30601: update RHCOS 4.15 bootimage metadata to 415.92.202402201450-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8101 OPNET-476: GA Load balancer feature for vSphere and Baremetal
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#8165 NO-JIRA: OWNERS: pkg/infrastructure/openstack
  pkg/infrastructure/openstack/OWNERS
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8036 CORS-3215: capi: implement bootstrap gather
  pkg/infrastructure/clusterapi/clusterapi.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, capi

#8017 CORS-3213: Tweak GCPCluster Failure Domain Logic
  pkg/asset/manifests/gcp/cluster.go
Labels: approved, lgtm, platform/google, jira/valid-reference, acknowledge-critical-fixes-only

#8149 CORS-2902: capi/aws: add ext-LB as CAPA secondary LB
  pkg/asset/manifests/aws/cluster.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8148 CORS-3307: add 'A2' as tested machine types on GCP
  docs/user/gcp/tested_instance_types.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8169 CORS-3417: capa bump fallout
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta1/awscluster_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta1/awsclustertemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta1/zz_generated.conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awscluster_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsclustertemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmachine_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmachine_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmachinetemplate_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/groupversion_info.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/network_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/feature/feature.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/iam/api/v1beta1/types.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8142 CORS-2894,CORS-3051: Create DNS resources and PHZ for CAPI/aws
  pkg/asset/installconfig/aws/route53.go
  pkg/infrastructure/aws/clusterapi/aws.go
Labels: approved, lgtm, platform/aws, jira/valid-reference, acknowledge-critical-fixes-only

#8099 CNF-10170: bootkube.sh: Render kernel boot arguments for SNO
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8177 OCPBUGS-31013: Fix vsi image missing
  data/data/powervs/cluster/dns/dns.tf
  data/data/powervs/cluster/dns/variables.tf
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#7987 OCPBUGS-28870: IBMCloud: Restrict CIS and DNS Service lookup
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/metadata_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8166 CORS-3142: capi: write manifests to disk during create manifests
  pkg/asset/machines/aws/awsmachines.go
  pkg/asset/machines/azure/azuremachines.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/gcp/gcpmachines.go
  pkg/asset/machines/gcp/gcpmachines_test.go
  pkg/asset/machines/openstack/openstackmachines.go
  pkg/asset/machines/powervs/powervsmachines.go
  pkg/asset/machines/vsphere/capimachines.go
  pkg/asset/manifests/aws/cluster.go
  pkg/asset/manifests/azure/cluster.go
  pkg/asset/manifests/clusterapi/cluster.go
  pkg/asset/manifests/gcp/cluster.go
  pkg/asset/manifests/openstack/cluster.go
  pkg/asset/manifests/vsphere/cluster.go
  pkg/asset/store/assetcreate_test.go
  pkg/asset/targets/targets.go
  pkg/infrastructure/clusterapi/clusterapi.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8176 OCPBUGS-30882: GCP capg distribute instances across zones
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/gcp/gcpmachines.go
Labels: approved, lgtm, platform/google, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8195 Bug OCPBUGS-30154: OpenStack: enable 30000:32767 nodePort IPv6 traffic
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8113 CORS-3256: GCP destroy updates for CAPG
  pkg/destroy/gcp/backendservice.go
  pkg/destroy/gcp/bucket.go
  pkg/destroy/gcp/bucketobject.go
  pkg/destroy/gcp/cloudcontroller.go
  pkg/destroy/gcp/firewall.go
  pkg/destroy/gcp/forwardingrule.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/targetTCPProxies.go
Labels: approved, lgtm, platform/google, jira/valid-reference, acknowledge-critical-fixes-only

#7349 OCPBUGS-15941: ABI - Validate release image arch, add cpu_architectures to RELEASE_IMAGES
  pkg/asset/agent/common.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/image/releaseextract.go
  pkg/asset/agent/image/releaseimage.go
  pkg/asset/agent/image/releaseimage_test.go
  pkg/asset/agent/image/unconfigured_ignition.go
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/installconfig_test.go
  pkg/asset/agent/oc.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7871 OCPBUGS-26052: aws: altinfra: fix role creation in C2S
  pkg/infrastructure/aws/aws.go
  pkg/infrastructure/aws/bootstrap.go
  pkg/infrastructure/aws/compute.go
  pkg/infrastructure/aws/controlplane.go
  pkg/infrastructure/aws/instance.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8180 OCPBUGS-31050: openstack: Honour worker server group policy
  data/data/openstack/masters/main.tf
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8192 OCPBUGS-31209: CAPG - Fix setting ServiceAccount role bindings for GCP
  pkg/infrastructure/gcp/clusterapi/iam.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8193 no-jira: capi/aws: reuse GenerateMachines for bootstrap
  pkg/asset/machines/aws/awsmachines.go
  pkg/asset/machines/clusterapi.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8179 CORS-2905: capi/aws: destroy CAPA resources
  pkg/asset/cluster/aws/aws.go
Labels: approved, lgtm, jira/valid-reference

#8152 CORS-2898: capi/aws: configure IMDS
  pkg/asset/machines/aws/awsmachines.go
Labels: approved, lgtm, jira/valid-reference

#8187 OSASINFRA-3420: openstack: Decouple OpenStack API calls from Machine generation
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/asset/machines/openstack/openstackmachines.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, jira/valid-reference

#8128 METAL-855: baremetal: remove ironic-inspector
  data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-httpd.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-inspector.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/metal3-baremetal-operator.container
  data/data/bootstrap/baremetal/files/opt/metal3/auth/ironic-inspector/auth-config.template
  data/data/bootstrap/baremetal/files/opt/metal3/auth/ironic-rpc/auth-config.template
  data/data/bootstrap/baremetal/files/opt/metal3/auth/ironic/auth-config.template
  docs/user/metal/install_ipi.md
Labels: approved, lgtm, jira/valid-reference

#8206 OCPBUGS-27848: If host is offline or disconnected don't check ver
  pkg/asset/installconfig/vsphere/validation.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8184 CORS-3428,CORS-2901: pkg/types/aws: limit additionalSecurityGroups to 10
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/aws/machinepool.go
  pkg/types/aws/validation/machinepool.go
  pkg/types/aws/validation/machinepool_test.go
Labels: approved, lgtm, jira/valid-reference

#8105 AGENT-868: Generate ECDSA public private keys and pass it to assisted service
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  pkg/asset/agent/gencrypto/authconfig.go
  pkg/asset/agent/gencrypto/authconfig_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#8194 no-jira: infra: aws: move SDK provisioner to its own dir
  pkg/infrastructure/aws/sdk/aws.go
  pkg/infrastructure/aws/sdk/bootstrap.go
  pkg/infrastructure/aws/sdk/compute.go
  pkg/infrastructure/aws/sdk/controlplane.go
  pkg/infrastructure/aws/sdk/destroy.go
  pkg/infrastructure/aws/sdk/dns.go
  pkg/infrastructure/aws/sdk/instance.go
  pkg/infrastructure/aws/sdk/loadbalancer.go
  pkg/infrastructure/aws/sdk/provision_test.go
  pkg/infrastructure/aws/sdk/securitygroup.go
  pkg/infrastructure/aws/sdk/vpc.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
Labels: approved, lgtm, jira/valid-reference

#8209 OSASINFRA-3421: OpenStack: Customizable clientOpts for CheckNetworkEx…
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, jira/valid-reference

#8200 CORS-3431: CAPI: Add firewall rule for worker nodes
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/firewallrules.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#8163 [release-4.15] OCPBUGS-30922: coreos-installer iso kargs show broken on Agent ISO
  pkg/asset/agent/image/agentimage.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8045 CORS-3071: Create DNS entries for CAPZ implementation
  go.mod
  go.sum
  pkg/asset/manifests/azure/cluster.go
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/dns.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime/policy_register_rp.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime/policy_trace_namespace.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/core.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/doc.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported/pipeline.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported/response_error.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/shared.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/policy/policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/pager.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/pipeline.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_bearer_token.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_http_trace.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_key_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_logging.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_sas_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_telemetry.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/request.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/transport_default_http_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/tracing/tracing.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/internal/errorinfo/errorinfo.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/client_factory.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/recordsets_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/resourcereference_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/zones_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/client_factory.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/privatezones_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/recordsets_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/virtualnetworklinks_client.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#8156 CORS-2895: aws/capi: setting zones to when creating cluster
  pkg/asset/manifests/aws/cluster.go
  pkg/asset/manifests/aws/zones.go
  pkg/asset/manifests/aws/zones_test.go
Labels: approved, lgtm, jira/valid-reference

#8190 no-jira: pkg/asset/machines: remove static ip log lines
  pkg/asset/machines/master.go
Labels: approved, lgtm, jira/valid-reference

#8214 no-jira: this clusterprofile isn't actually used
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-reference

#8080 AGENT-874: use AddNodesConfig asset
  pkg/asset/agent/agentconfig/agenthosts.go
  pkg/asset/agent/agentconfig/agenthosts_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/joiner/addnodesconfig.go
  pkg/asset/agent/joiner/addnodesconfig_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm, jira/valid-reference

#8134 OCPBUGS-31546: azure: use filter when listing SKUs
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/installconfig/gcp/mock/usertags_mock.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/2018-03-01/compute/mgmt/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/virtualmachinesizes.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference
