Repository openshift/installer, pull requests merged in 2024-12, with the labels that each got.

#9249 OCPBUGS-45175: Ironic external url port should change based on protocol
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/ignition/bootstrap/baremetal/template_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9248 ARO-12457: Include bootstrap docker config file in go module
  data/data/tools.go
Labels: approved, lgtm, jira/valid-reference

#9254 OCPBUGS-45286: PowerVS: Listen to machineNetwork
  pkg/asset/manifests/powervs/cluster.go
  pkg/types/defaults/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9266 OCPBUGS-44938: Handle multiple mirror entries for source
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/image/oc_test.go
  pkg/asset/agent/image/releaseextract.go
  pkg/asset/agent/image/unconfigured_ignition_test.go
  pkg/asset/agent/mirror/registriesconf.go
  pkg/asset/agent/mirror/registriesconf_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9273 OCPBUGS-45491: Align vSphere UPI haproxy config with IPI
  upi/vsphere/lb/haproxy.erb.tmpl
  upi/vsphere/lb/haproxy.tmpl
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9204 OCPBUGS-44523: Remove unused variable from ASH arm template 06_workers.json
  upi/azurestack/06_workers.json
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9234 OCPBUGS-44925: aws: add ec2:AllocateAddress perm requirement.
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/valid-reference

#9237 OCPBUGS-44327: Update RHCOS 4.18 bootimage metadata to 418.94.202411221729-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9263 OCPBUGS-45289: capi/aws: use LB name when finding Hosted Zone ID
  pkg/infrastructure/aws/clusterapi/aws.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9245 OCPBUGS-45685: Power VS: Create region-zone-sysType hierarchy
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/regions.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/machines/worker.go
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9274 OCPBUGS-45162: Delete tagged disks
  pkg/destroy/gcp/disk.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#9104 [release-4.16] OCPBUGS-41813: Validate MTU for custom network
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9270 OCPBUGS-43779: Destroy all private cluster backend service resources
  pkg/destroy/gcp/cloudcontroller.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#9287 OCPBUGS-45807: aws: fix sts:AssumeRole perm requirement
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/permissions_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9291 OCPBUGS-45855: If vCenter cluster has no esxi hosts fail with sane msg
  pkg/infrastructure/vsphere/clusterapi/import.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9281 OCPBUGS-45669: [release-4.16] capi/aws: remove allow-all Node Port Service
  pkg/infrastructure/aws/clusterapi/aws.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9216 OCPBUGS-44641: GCP placing *.apps record in wrong managed zone
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/manifests/dns.go
  pkg/infrastructure/gcp/clusterapi/dns.go
Labels: approved, lgtm, platform/google, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#9280 OCPBUGS-45317: node-joiner PXE artifacts should be prefixed "node"
  cmd/node-joiner/testdata/add-nodes-pxe.txt
  pkg/asset/agent/image/agentartifacts.go
  pkg/asset/agent/image/agentimage.go
  pkg/asset/agent/image/agentpxefiles.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9301 OCPBUGS-45984: IBMCloud Fix VPC-COS IAM Auth
  pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#9230 OCPBUGS-44834: aws: include permissions for edge compute
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/permissions_test.go
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/valid-reference

#9295 OCPBUGS-46363: Remove narrow timeout from etcd bootstrap member removal gate.
  cmd/openshift-install/create.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9299 OCPBUGS-45280: Allow more time for Service Account Creation
  pkg/infrastructure/gcp/clusterapi/iam.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9312 OCPBUGS-45669: aws: fix Node Port Service rule removal
  pkg/infrastructure/aws/clusterapi/aws.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9323 OCPBUGS-44560: Add note about additional networks using IPv6
  docs/user/openstack/deploy_dual_stack_cluster.md
  docs/user/openstack/deploy_single_stack_ipv6_cluster.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9307 OCPBUGS-46035: fix skew support for node-joiner
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/joiner/clusterinfo_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9317 OCPBUGS-46470: Power VS: ResourceManager also to override for Internal deploy
  pkg/asset/installconfig/powervs/metadata.go
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/powervs/cloudproviderconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9256 OCPBUGS-45218: aws: fix perm requirement for edge nodes
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/permissions_test.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9310 OCPBUGS-46144: azure: use separate /var to avoid growfs timeouts
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/node.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#9189 METAL-1137: Enable TLS for ironic API in the bootstrap VM
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-httpd.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/metal3-baremetal-operator.container
  data/data/bootstrap/baremetal/files/etc/metal3.env.template
  data/data/bootstrap/baremetal/files/usr/local/bin/build-ironic-env.sh
  pkg/asset/ignition/bootstrap/baremetal/template.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9335 OCPBUGS-47504: Power VS: Private DNS service endpoint URL must end with /v1
  pkg/asset/installconfig/powervs/metadata.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
