Repository openshift/installer, pull requests merged in 2024-01, with the labels that each got.

#7833 OCPBUGS-25132: Fixes for the OpensStack UPI playbooks.
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7843 OCPBUGS-25440: ic: aws: add iam:TagInstanceProfile permission requirement
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7835 OCPBUGS-25600: aws: validate instance arch
  pkg/asset/installconfig/aws/availabilityzones.go
  pkg/asset/installconfig/aws/basedomain.go
  pkg/asset/installconfig/aws/instancetypes.go
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/platform.go
  pkg/asset/installconfig/aws/route53.go
  pkg/asset/installconfig/aws/session.go
  pkg/asset/installconfig/aws/subnet.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7864 CORS-2852: cmd/create: allow clean shutdown of resources
  cmd/openshift-install/create.go
  pkg/asset/cluster/cluster.go
Labels: approved, lgtm, jira/valid-reference

#7872 OCPBUGS-24862: Updating ose-installer-altinfra-container image to be …
  images/installer-altinfra/Dockerfile.ci
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7867 OCPBUGS-26048: Bump default channel to stable-4.16
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7698 OSASINFRA-3280: OpenStack: clarify root volume size requirements
  docs/user/openstack/customization.md
Labels: approved, lgtm, jira/valid-reference

#7875 OCPBUGS-24956: Add cloud credential capability validation
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7865 ARO-4744: Do not run platform validation on ARO
  pkg/asset/installconfig/installconfig.go
Labels: approved, lgtm, jira/valid-reference

#7876 OCPBUGS-25841: preserve category name when trying to find tag category
  pkg/destroy/vsphere/client.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7883 OCPBUGS-26511: Bump default channel to 4.15
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#7884 OCPBUGS-24956: Add cloud credential capability validation
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7870 MULTIARCH-4072: Power VS: Add eu-de-1, eu-de-2, sao04, and wdc07 as supported zones
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, jira/valid-reference

#7888 CORS-3190: GCP: Add load balancer info to cluster infra
  pkg/terraform/stages/gcp/stages.go
  pkg/terraform/stages/ignition.go
Labels: approved, lgtm, jira/valid-reference

#7890 [release-4.15]OCPBUGS-26495: Add cloud credential capability validation
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7859 OCPBUGS-26399: Support singular VIP in ACI for BareMetal
  cmd/openshift-install/testdata/agent/image/configurations/baremetal_host_bmc_config.txt
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7814 METAL-829: Set node cpu_arch from bmh
  pkg/tfvars/baremetal/baremetal.go
Labels: approved, lgtm, jira/valid-reference

#7720 CORS-2950: Remove openshift-sdn as an install-time option
  pkg/asset/agent/installconfig_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#7898 OCPBUGS-25996: baremetal: correct external_http_url for v6-only BMCs
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7854 OCPBUGS-27092: baremetal: gather all recently refactored services
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7873 OCPBUGS-26434: Redact platform passwords in agent-gather output
  data/data/agent/files/usr/local/bin/agent-gather
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7896 OCPBUGS-14257: normalize ISO files extensions to three chars
  pkg/asset/agent/image/agentimage.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7893 OCPBUGS-24303: Check provided sha for agent ISO download
  pkg/asset/agent/image/baseiso.go
  pkg/rhcos/cache/cache.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7915 OCPBUGS-24956: Fix typo in CloudCredential validation
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7851 no-jira: Add AWS m6a to tested instance types
  docs/user/aws/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-reference

#7901 OCPBUGS-25835: Validate baremetal capability is set for baremetal platform
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#7891 no-jira: images/altinfra: allow CAPI ARG
  images/installer-altinfra/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference

#7911 OCPBUGS-27192: remove retired serial NCv2 from azure tested instance type list on x86
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7924 OCPBUGS-27366: set the --cluster-profile flag for openshift/api rendering
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7914 OCPBUGS-27241: baremetal: correct external_http_url for v6-only BMCs
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#7941 OCPBUGS-27788: PowerVS: COS region configurable
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/rhcos/image.go
  pkg/destroy/powervs/powervs.go
  pkg/tfvars/powervs/powervs.go
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7860 OCPBUGS-25453: duplicate failure domains in CMPS
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/machines/vsphere/machines_test.go
  pkg/types/vsphere/validation/machinepool.go
  pkg/types/vsphere/validation/machinepool_test.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7725 no-jira: azure: add metadata info to resource group tags
  data/data/azure/variables-azure.tf
  data/data/azure/vnet/main.tf
  pkg/asset/cluster/azure/azure.go
  pkg/destroy/azure/azure.go
  pkg/tfvars/azure/azure.go
  pkg/types/azure/metadata.go
Labels: approved, lgtm, jira/valid-reference

#7947 NO-JIRA: Minor fixes
  data/data/manifests/openshift/90-okd-sca-pull-disable.yaml.template
  data/data/manifests/openshift/cloud-creds-secret.yaml.template
  data/data/manifests/openshift/kubeadmin-password-secret.yaml.template
  data/data/manifests/openshift/role-cloud-creds-secret-reader.yaml.template
  docs/dev/cluster-api.md
  pkg/asset/machines/clusterapi.go
  pkg/asset/manifests/clusterapi/cluster.go
  pkg/clusterapi/system.go
Labels: approved, lgtm, jira/valid-reference

#7954 NO-ISSUE: test fix to support slightly different nmstate error messages
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#7942 OCPBUGS-27507: bump containerd for vulnerability fix
  go.mod
  go.sum
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7804 OCPBUGS-24521: set vmType in azure cloud config [release-4.14]
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
  pkg/asset/manifests/azure/types.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7824 CORS-3139: Move CAPI behind infrastructure provider interface
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/metadata.go
  pkg/asset/cluster/metadata/metadata.go
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/manifests/capiutils/manifest.go
  pkg/asset/manifests/clusterapi/cluster.go
  pkg/asset/targets/targets.go
  pkg/destroy/bootstrap/bootstrap.go
  pkg/destroy/destroyer.go
  pkg/gather/gather.go
  pkg/infrastructure/aws/aws.go
  pkg/infrastructure/clusterapi/clusterapi.go
  pkg/infrastructure/clusterapi/helpers.go
  pkg/infrastructure/clusterapi/types.go
  pkg/infrastructure/provider.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, jira/valid-reference

#7920 OCPBUGS-23499: update RHCOS 4.13 bootimage metadata to 413.92.202401100947-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7961 OCPBUGS-28705: [azure] update tested x86 instance type on 4.15
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7692 CNF-10170: bootkube.sh: Render kernel boot arguments for SNO
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7925 OCPBUGS-27263: Bump golang 1.21
  .ci-operator.yaml
  .golangci.yaml
  go.mod
  go.sum
  hack/build.sh
  hack/go-fmt.sh
  hack/go-genmock.sh
  hack/go-sec.sh
  hack/go-test.sh
  hack/go-vet.sh
  hack/verify-codegen.sh
  hack/verify-vendor.sh
  images/baremetal/Dockerfile.ci
  images/infrastructure-providers/Dockerfile
  images/installer-altinfra/Dockerfile.ci
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.upi.ci
  images/libvirt/Dockerfile.ci
  images/openstack/Dockerfile.ci
  terraform/Makefile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#7934 OCPBUGS-27453: baremetal: correct external_http_url for v6-only BMCs
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#7956 OCPBUGS-28643: PowerVS: Add dal12 region
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7965 OCPBUGS-28708: update tested Azure Arm64 instance type on 4.15
  docs/user/azure/tested_instance_types_aarch64.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7945 OCPBUGS-27737: aws-edge-zones preventing err before discovering
  pkg/asset/installconfig/aws/availabilityzones.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference
