Repository openshift/installer, pull requests merged in 2024-02, with the labels that each got.

#7932 OCPBUGS-27156: GCP Destroy cleanup correct zones/records
  pkg/asset/cluster/gcp/gcp.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7940 CORS-3208: Create the GCP infrastructure controller
  pkg/clusterapi/system.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#7944 CORS-3207: Generate GCP machine manifests for CAPI
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/gcp/gcpmachines.go
  pkg/asset/machines/gcp/gcpmachines_test.go
  pkg/types/gcp/platform.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#7958 AGENT-848: add node-joiner cli tool main
  cmd/node-joiner/main.go
  cmd/openshift-install/create.go
  pkg/asset/store/assetsfetcher.go
  pkg/nodejoiner/addnodes.go
  pkg/nodejoiner/monitoraddnodes.go
Labels: approved, lgtm, jira/valid-reference

#7907 OCPBUGS-2135: Include CAPG objects in uninstall filter
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7979 CNF-10170: Revert "bootkube.sh: Render kernel boot arguments for SNO"
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-reference

#7733 CORS-3240: add OWNERS_ALIASES madhu-pillai
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#7957 OCPBUGS-28546: [release-4.15] Bump containerd for vulnerability fix
  go.mod
  go.sum
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7604 OPNET-357: Populate network configuration at install-time
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/vsphere/infrastructure.go
  pkg/types/utils.go
  pkg/types/utils_test.go
Labels: approved, lgtm, jira/valid-reference

#7861 CORS-3242: PowerVS: Replace deprecated primary_ipv4_address with primary_ip list item
  data/data/powervs/cluster/dns/dns.tf
  data/data/powervs/cluster/dns/outputs.tf
Labels: approved, lgtm, jira/valid-reference

#7905 SPLAT-1387: enable additional tags to be associated with vsphere machines
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/machines/vsphere/machines.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/custom.authentication.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.authentication.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.authentication.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1alpha1/register.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#7967 OSASINFRA-3371: Pass rhcosImage and manifests to the PreProvision hook
  pkg/infrastructure/clusterapi/clusterapi.go
  pkg/infrastructure/clusterapi/types.go
Labels: approved, lgtm, jira/valid-reference

#7972 OCPBUGS-28827: do not rename boot.catalog for arm64 iso
  pkg/asset/agent/image/agentimage.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7515 OCPBUGS-20085: IBMCloud: Handle disk delete errors
  pkg/destroy/ibmcloud/disk.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7991 OCPBUGS-29067: Copy GCP manifests within MCO bootstrap to the correct location
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7986 OCPBUGS-29068: GCP: Skip validation of public and private zones for terraform vars
  pkg/asset/cluster/tfvars/tfvars.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7985 OCPBUGS-29114: Fixed control plane machine set handling of static IPs when AddressesFromPools is not in use.
  pkg/asset/machines/vsphere/machines.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7992 NO-ISSUE: integrationt tests support for env vars substitution
  cmd/openshift-install/agent_internal_integration_test.go
  cmd/openshift-install/testdata/agent/configimage/manifests/default_manifests.txt
  cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/configurations/from-ztp-manifests.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/manifests/default_manifests.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/missing-cluster-image-set-allowed.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/missing-infraenv.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/missing-pull-secret.txt
Labels: approved, lgtm, jira/valid-reference

#7998 Bug OCPBUGS-29198: OpenStack: fix controlPlanePort validation
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8010 OCPBUGS-29425: PowerVS Fix next start search
  pkg/destroy/powervs/cloud-sshkey.go
  pkg/destroy/powervs/cloud-transit-gateways.go
  pkg/destroy/powervs/publicgateway.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8015 OCPBUGS-29441: update RHCOS 4.16 bootimage metadata to 416.94.202402130130-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8016 OCPBUGS-29442: update RHCOS 4.15 bootimage metadata to 415.92.202402130021-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8006 CORS-2890: aws/machines: add CAPI sg, subnet filters
  pkg/asset/machines/aws/machines.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#7917 CORS-3213: Create the GCP cluster manifest
  pkg/asset/manifests/clusterapi/cluster.go
  pkg/asset/manifests/gcp/cluster.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#8011 CORS-3220: Initiate CAPG installation
  pkg/asset/cluster/cluster.go
  pkg/infrastructure/clusterapi/clusterapi.go
  pkg/infrastructure/clusterapi/types.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#7889 OCPBUGS-28203: Power VS: Add sleep to allow workspace to configure PER
  data/data/powervs/cluster/iaas/iaas.tf
  data/data/powervs/cluster/iaas/variables.tf
  data/data/powervs/cluster/main.tf
  data/data/powervs/variables-powervs.tf
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8002 OCPBUGS-28590: gcp: better error msg when service accnt missing
  pkg/asset/machines/gcp/machines.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#7874 CORS-3185: update default release image
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference

#8012 CORS-2890: pkg/infrastructure/aws: add initial CAPI provider
  pkg/infrastructure/aws/clusterapi/aws.go
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
Labels: approved, lgtm, jira/valid-reference

#8029 OCPBUGS-29584: PowerVS: handle composite_instance
  pkg/destroy/powervs/powervs.go
  pkg/destroy/powervs/serviceinstance.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7931 OCPBUGS-22410: vsphere-fix convert if only provided name
  pkg/asset/installconfig/vsphere/mock/vsphere_sim.go
  pkg/types/vsphere/conversion/installconfig.go
  pkg/types/vsphere/conversion/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8033 OCPBUGS-29587: Power VS: Fix service instance list
  pkg/asset/installconfig/powervs/client.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8014 CORS-3259: GCP: Create DNS records and internal load balancer for CAPG Install
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/dns.go
  pkg/infrastructure/gcp/clusterapi/gcp.go
  pkg/infrastructure/gcp/clusterapi/labels.go
  pkg/infrastructure/gcp/clusterapi/network.go
  pkg/infrastructure/gcp/clusterapi/operation.go
  pkg/infrastructure/gcp/clusterapi/service.go
Labels: approved, lgtm, platform/google, jira/valid-reference, acknowledge-critical-fixes-only

#8028 Bug OCPBUGS-29084: OpenStack: Fix dualstack with external load-balancer
  data/data/openstack/masters/private-network.tf
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#8037 OCPBUGS-29626: update RHCOS 4.14 bootimage metadata to 414.92.202402130420-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8004 OCPBUGS-29429: feat: add check for SNO bootstrap condition
  cmd/openshift-install/create.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8053 SPLAT-1462: capv - Remove unneeded auth env vars
  pkg/clusterapi/system.go
Labels: approved, lgtm, jira/valid-reference

#7900 OCPBUGS-27454: baremetal: correct external_http_url for v6-only BMCs
  pkg/asset/cluster/tfvars.go
  pkg/tfvars/baremetal/baremetal.go
  pkg/tfvars/baremetal/baremetal_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8054 SPLAT-1465: capv - add additional extra configs
  pkg/asset/machines/vsphere/capimachines.go
Labels: approved, lgtm, jira/valid-reference

#8008 no-jira: images: libvirt: add oc to libvirt CI image
  images/libvirt/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#7983 SPLAT-1434: aws: add support of BYO public ipv4 pool
  data/data/aws/bootstrap/main.tf
  data/data/aws/cluster/main.tf
  data/data/aws/cluster/vpc/master-elb.tf
  data/data/aws/cluster/vpc/variables.tf
  data/data/aws/cluster/vpc/vpc-public.tf
  data/data/aws/variables-aws.tf
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/aws/custom_public_ipv4.md
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/aws/ec2.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
  pkg/explain/printer_test.go
  pkg/tfvars/aws/aws.go
  pkg/types/aws/platform.go
Labels: approved, lgtm, jira/valid-reference

#8058 OCPBUGS-29895: PowerVS: Add debugging to ServiceInstanceNameToGUID
  pkg/destroy/powervs/powervs.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#8042 SPLAT-1459: capv machines only full clone
  pkg/asset/machines/vsphere/capimachines.go
Labels: approved, lgtm, jira/valid-reference

#8046 OCPBUGS-29469: fix Azure API SKU calls timing out
  pkg/asset/installconfig/azure/client.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8060 MULTIARCH-4158: pkg/infrastructure/powervs: add initial CAPI provider
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
  pkg/infrastructure/powervs/clusterapi/powervs.go
Labels: approved, lgtm, jira/valid-reference

#8072 OCPBUGS-30005: remove github.com/IBM-Cloud/bluemix-go/api/account/accountv2
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/installconfig/powervs/session.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/accounts.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/api_service.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/paginate.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8076 [release-4.15] OCPBUGS-30011: PowerVS: remove IBM-Cloud/bluemix-go/api/account/accountv2 in 4.15
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/installconfig/powervs/session.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/accounts.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/api_service.go
  vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/paginate.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8084 CORS-3273: capi system: don't log env vars
  pkg/clusterapi/system.go
Labels: approved, lgtm, jira/valid-reference

#7501 SPLAT-1173: Enhance vSphere Installer to use IPAddressClaims for static IP
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/machines/master.go
  pkg/asset/machines/vsphere/capimachines.go
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/machines/vsphere/machines_test.go
  pkg/asset/machines/vsphere/machinesets.go
  pkg/asset/machines/worker.go
  pkg/tfvars/vsphere/vsphere.go
Labels: approved, lgtm, jira/valid-reference
