Repository openshift/installer, pull requests merged in 2024-09, with the labels that each got.

#8920 OCPBUGS-39206: Update GCP Disk Types 4.16
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/destroy/gcp/gcp.go
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/gcp/validation/machinepool_test.go
  pkg/types/validation/machinepools_test.go
Labels: approved, lgtm, cherry-pick-approved, platform/google, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8919 OCPBUGS-39285: Fix var_files syntax to work on older version of ansible
  upi/openstack/common.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8943 OCPBUGS-39411: Added yq to ci image
  images/installer/Dockerfile.upi.ci.rhel8
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8591 OCPBUGS-35054: capi/aws/byo-vpc/multi-cidr: fix group rules
  pkg/asset/manifests/aws/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#8940 OSASINFRA-3571: OpenStack: enable config-drive for single-stack IPv6
  pkg/asset/machines/openstack/openstackmachines.go
Labels: approved, lgtm, jira/valid-reference

#8819 OCPBUGS-36283: Enable TLS for virtual media in initial ironic deployment
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-httpd.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.container.template
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/ignition/bootstrap/baremetal/template_test.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/tls/ironictls.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8869 OCPBUGS-38069: Remove firewall rules created by CAPG
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/firewallrules.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8945 OCPBUGS-39431: dropping this warning as the move from terraform is transparent to the end user
  pkg/asset/cluster/tfvars/tfvars.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8916 OCPBUGS-37442: azure: Pick the next available IP address for internal LB
  pkg/asset/installconfig/azure/client.go
  pkg/asset/manifests/azure/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8955 [release-4.16] OCPBUGS-39468: Enable TLS for virtual media in initial ironic deployment
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-httpd.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.container.template
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/ignition/bootstrap/baremetal/template_test.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/tls/ironictls.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8887 OCPBUGS-38070: Azure: Add master and worker VM IPs to both the backend pools API LoadBalancer
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/network.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8921 OCPBUGS-39081: Bump extract-machine-os timout to 20m
  data/data/bootstrap/baremetal/systemd/units/extract-machine-os.service
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8942 OCPBUGS-39402: Fix IPv6 security group rule for schedulable master
  upi/openstack/security-groups.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8963 OSASINFRA-3571: openstack: refactor ConfigDrive & add it for workers
  pkg/asset/machines/openstack/machines.go
  pkg/asset/machines/openstack/machinesets.go
  pkg/asset/machines/openstack/openstackmachines.go
  pkg/asset/machines/openstack/openstackmachines_test.go
Labels: approved, lgtm, jira/valid-reference

#8355 OCPBUGS-33324: baremetal: wait before retrying ListWatch
  pkg/utils/baremetal/cache.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#8959 OCPBUGS-36196: pkg/infrastructure/azure: set correct cloud for BYO vnet
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#8974 OCPBUGS-41259: update RHCOS 4.18 bootimage metadata to 418.94.202409050217-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8967 OCPBUGS-36670: Azure CAPI: Set SecurityType as a Feature while creating Gallery Image
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/compute.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#8905 [release-4.16] OCPBUGS-38956: failed to install Nutanix OCP 4.16 cluster with DHCP
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/machines/nutanix/capimachines.go
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/clusterapi/clusterapi.go
  pkg/infrastructure/clusterapi/types.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/nutanix/clusterapi/clusterapi.go
  pkg/infrastructure/openstack/clusterapi/clusterapi.go
  pkg/types/nutanix/helpers.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8845 OCPBUGS-37628: vSphere conversion log when deprecated and support fields are used
  pkg/types/vsphere/conversion/installconfig.go
  pkg/types/vsphere/conversion/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8973 OCPBUGS-41257: pass k8s version to kube-apiserver render during bootstrap
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8939 OCPBUGS-36861: Updates GCP terraform worker role
  data/data/gcp/cluster/iam/main.tf
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8975 OCPBUGS-41283: update RHCOS 4.17 bootimage metadata to 417.94.202408270355-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8944 OCPBUGS-37506: Fix Azure storage account's public access
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/storage.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8982 OCPBUGS-36670: Azure CAPI: Look for SecuirtyType in DefaultMachinePlatform
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#8978 OCPBUGS-38719: Filter peering zones out
  pkg/asset/installconfig/gcp/client.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8980 [release-4.17] OCPBUGS-41539: Pick the next available IP address for internal LB
  pkg/asset/installconfig/azure/client.go
  pkg/asset/manifests/azure/cluster.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8984 [release-4.17] OCPBUGS-41542: Azure CAPI: Fix storage account and vhd container public access
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/storage.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8430 OCPBUGS-32792: update resolv.conf every time on bootstrap node
  data/data/bootstrap/baremetal/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
  data/data/bootstrap/nutanix/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/openstack/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/ovirt/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender
  data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/severity-important, jira/valid-reference

#8938 OCPBUGS-36861: Updates GCP CAPI worker role
  pkg/infrastructure/gcp/clusterapi/iam.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#8830 OCPBUGS-30811: OpenStack: Install CI dependencies from rpm
  docs/user/openstack/install_upi.md
  images/openstack/Dockerfile.ci
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8996 OCPBUGS-41776: Add AWS c7g,m7g,r8g to tested instance types
  docs/user/aws/tested_instance_types_aarch64.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8894 CFE-1105: Remove featureGate checks on GCP userLabels and userTags configs
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/featuregates.go
  pkg/types/validation/featuregate_test.go
Labels: approved, lgtm, jira/valid-reference

#8890 SPLAT-1750: Add support for multiple NICs for vSphere day 0
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/manifests/vsphere/infrastructure.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/featuregates.go
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/imagespec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/imagestatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/node.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/nodestatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/machine/v1beta1/machinesetstatus.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/common/config/config.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/common/config/config_ini_legacy.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/common/config/config_yaml.go
  vendor/k8s.io/cloud-provider-vsphere/pkg/common/config/types_common.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9001 OCPBUGS-37506: Azure CAPI: Update publicAccess for Blob Containers
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9000 OCPBUGS-36670: Azure CAPI: Improve handling of security features configured on the MachinePools and OSDisk
  pkg/asset/machines/azure/azuremachines.go
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9014 NO-ISSUE: docs/dev/dependencies: Mention install-config YAML generation
  docs/dev/dependencies.md
Labels: approved, lgtm, jira/valid-reference

#8789 OCPBUGS-38499: Fix integration tests
  cmd/openshift-install/internal_integration_test.go
  cmd/openshift-install/testdata/agent/configimage/manifests/default_manifests.txt
  cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/configurations/from-ztp-manifests.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/manifests/default_manifests.txt
  pkg/asset/agent/manifests/clusterimageset.go
  pkg/asset/agent/manifests/clusterimageset_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9011 OSASINFRA-3607: OpenStack: validate combination of externalNetwotk with single stack v6
  pkg/asset/installconfig/openstack/validation/platform.go
  pkg/asset/installconfig/openstack/validation/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#8250 CORS-3457: Remove pborman/uuid dependency
  go.mod
  go.sum
  pkg/asset/imagebased/configimage/clusterid.go
  pkg/asset/installconfig/clusterid.go
  pkg/destroy/gcp/gcp.go
  vendor/github.com/pborman/uuid/.travis.yml
  vendor/github.com/pborman/uuid/CONTRIBUTING.md
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/README.md
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#8932 OCPBUGS-41852: add tested IBMCloud instance types in 4.17 test
  docs/user/ibmcloud/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8961 OCPBUGS-41184: Add validation for gcp disk and instance types
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/types/gcp/machinepools.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference

#8989 OCPBUGS-41538: Remove bindings for XPN installs
  pkg/destroy/gcp/policybinding.go
  pkg/destroy/gcp/serviceaccount.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/valid-reference

#9015 OCPBUGS-39340: Remove destroy search for regional target tcp proxies
  pkg/destroy/gcp/targetTCPProxies.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9017 OCPBUGS-38498: Set default release image to 4.17
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9027 OCPBUGS-42086: update RHCOS 4.18 bootimage metadata to 418.94.202409162337-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8936 OCPBUGS-39287: Fix var_files syntax to work on older version of ansible
  upi/openstack/common.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8902 CORS-3663: Authentication tech debt for agent based installer
  pkg/asset/agent/gencrypto/auth_utils_test.go
  pkg/asset/agent/gencrypto/authconfig.go
  pkg/asset/agent/gencrypto/authconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9029 OCPBUGS-42123: Add GCP N4 Machine Series to tested instances for OCP
  docs/user/gcp/tested_instance_types.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8774 OCPBUGS-37588: PowerVS: Add support for persistent Transit Gateways
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/powervs/powervs.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/manifests/powervs/cluster.go
  pkg/destroy/powervs/cloud-instance.go
  pkg/destroy/powervs/cloud-sshkey.go
  pkg/destroy/powervs/cloud-subnet.go
  pkg/destroy/powervs/cloud-transit-gateways.go
  pkg/destroy/powervs/cloudobjectstorage.go
  pkg/destroy/powervs/dhcp.go
  pkg/destroy/powervs/dns-dns.go
  pkg/destroy/powervs/dns-resource.go
  pkg/destroy/powervs/image.go
  pkg/destroy/powervs/job.go
  pkg/destroy/powervs/loadbalancer.go
  pkg/destroy/powervs/power-instance.go
  pkg/destroy/powervs/power-sshkey.go
  pkg/destroy/powervs/power-subnet.go
  pkg/destroy/powervs/powervs.go
  pkg/destroy/powervs/publicgateway.go
  pkg/destroy/powervs/securitygroup.go
  pkg/destroy/powervs/serviceinstance.go
  pkg/destroy/powervs/vpc.go
  pkg/types/powervs/metadata.go
  pkg/types/powervs/platform.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9038 OSASINFRA-3614: OpenStack: remove creation of IPv4 rules on Single stack IPv6 cluster
  pkg/infrastructure/openstack/preprovision/securitygroups.go
Labels: approved, lgtm, jira/valid-reference

#9047 [release-4.15] OCPBUGS-42011 OCPBUGS-39288: Openstack UPI - Reintroduce unique resource names
  docs/user/openstack/install_upi.md
  upi/openstack/bootstrap.yaml
  upi/openstack/common.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
  upi/openstack/security-groups.yaml
  upi/openstack/update-network-resources.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9040 OCPBUGS-42180: Add AWS r8g to arm tested instance types
  docs/user/aws/tested_instance_types_aarch64.md
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8738 MULTIARCH-4813: Make CPMS active by default for Power VS platform
  pkg/asset/machines/powervs/machines.go
Labels: approved, lgtm, jira/valid-reference

#9049 CORS-3598: bump release image to 4.18
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference

#9037 OCPBUGS-42012: Systemd Fails to Parse Multiline EC Keys
  pkg/asset/agent/gencrypto/authconfig.go
  pkg/asset/agent/gencrypto/authconfig_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#9044 OSASINFRA-3615: OpenStack: Add installation steps for single stack IPv6 clusters
  docs/user/openstack/customization.md
  docs/user/openstack/deploy_dual_stack_cluster.md
  docs/user/openstack/deploy_single_stack_ipv6_cluster.md
Labels: approved, lgtm, jira/valid-reference

#8992 [release-4.14] OCPBUGS-25508: Update Golang SSH package version update to 0.17.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.s
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9021 OCPBUGS-36670: Azure CAPI: Provide Image ID while creating different image versions
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/compute.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9019 OCPBUGS-41622: update RHCOS 4.17 bootimage metadata to 417.94.202409120353-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
