Repository openshift/installer, pull requests merged in 2024-07, with the labels that each got.

#8632 OCPBUGS-35818: baremetal: bootstrap: bind icc to localhost
  data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8677 OCPBUGS-36316: Power VS: Allow pending network for internal publishing strategy
  pkg/asset/installconfig/powervs/client.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8690 OCPBUGS-36318: update RHCOS 4.17 bootimage metadata to 417.94.202407010929-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8270 AGENT-871: Authenticate wait for
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  go.mod
  pkg/agent/cluster.go
  pkg/agent/rest.go
  pkg/asset/agent/gencrypto/auth_utils.go
  pkg/asset/agent/gencrypto/authconfig.go
  pkg/asset/agent/gencrypto/authconfig_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#8685 OSASINFRA-3402: Use Gophercloud v2.0.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#8650 AGENT-925: retrieve ignition endpoint to add a new node
  data/data/agent/systemd/units/agent-import-cluster.service.template
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/joiner/clusterinfo_test.go
Labels: approved, lgtm, jira/valid-reference

#8686 OCPBUGS-36453: PowerVS: add .ssh directory
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8643 SPLAT-1670: install pwsh from ci mirrored image
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, jira/valid-reference

#8687 [release-4.15]: OCPBUGS-36400: PowerVS: add ibmcloud plugins
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8393 AGENT-876: Authenticate systemd services and curl requests
  data/data/agent/files/usr/local/bin/add-node.sh
  data/data/agent/files/usr/local/bin/common.sh
  data/data/agent/files/usr/local/bin/start-cluster-installation.sh
  data/data/agent/files/usr/local/bin/wait-for-assisted-service.sh
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/systemd/units/agent-register-cluster.service.template
  data/data/agent/systemd/units/agent-register-infraenv.service.template
  data/data/agent/systemd/units/apply-host-config.service
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#8421 CORS-3296: CAPG - configure Internal LoadBalancer in the provider
  pkg/asset/manifests/gcp/cluster.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/network.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#8708 OCPBUGS-36660: CORS-3591: 4.17 default channel incorrectly points to stable-4.16
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8692 OCPBUGS-36324: update RHCOS 4.16 bootimage metadata to 416.94.202406282145-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8703 OCPBUGS-34708: CORS-3582: capi: remove unused feature gates
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
  pkg/terraform/stages/aws/OWNERS
  pkg/terraform/stages/aws/stages.go
  pkg/terraform/stages/nutanix/OWNERS
  pkg/terraform/stages/nutanix/stages.go
  pkg/terraform/stages/openstack/OWNERS
  pkg/terraform/stages/openstack/stages.go
  pkg/types/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8395 AGENT-875: Authenticate agents
  data/data/agent/files/usr/local/bin/start-agent.sh
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#8714 CORS-3590: releaseimage: update default version
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference

#8599 OCPBUGS-35542: Cleanup capi artifacts
  cmd/openshift-install/destroy.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#8666 OCPBUGS-36142: azure: Fix HyperVGeneration for gen2 images.
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#8706 OCPBUGS-35262: Skip firewall rule creation if permission is missing
  pkg/infrastructure/gcp/clusterapi/firewallrules.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/severity-important, jira/valid-reference

#8515 MULTIARCH-4568: Print release image arch and default arch when the payload is multi
  cmd/openshift-install/version.go
  pkg/version/version.go
Labels: approved, lgtm, jira/valid-reference

#8477 OCPBUGS-33973: Openstack UPI - Reintroduce unique resource names.
  docs/user/openstack/install_upi.md
  upi/openstack/bootstrap.yaml
  upi/openstack/common.yaml
  upi/openstack/compute-nodes.yaml
  upi/openstack/control-plane.yaml
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
  upi/openstack/security-groups.yaml
  upi/openstack/update-network-resources.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8720 CORS-2775: cmd: destroy: remove deprecated github.com/pkg/errors
  cmd/openshift-install/destroy.go
Labels: approved, lgtm, jira/valid-reference

#8693 OCPBUGS-36378: capi: start controllers after WaitGroup is created
  pkg/clusterapi/system.go
  pkg/infrastructure/clusterapi/clusterapi.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#8652 CORS-3485: Azure: modify control plane outbound LB into submission as an API LB
  pkg/asset/manifests/azure/cluster.go
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/network.go
Labels: approved, lgtm, jira/valid-reference

#8709 MGMT-17226: Add imagebased installer skeleton
  OWNERS_ALIASES
  cmd/openshift-install/imagebased.go
  cmd/openshift-install/main.go
  cmd/openshift-install/testdata/imagebased/OWNERS
  data/data/imagebased/OWNERS
  pkg/asset/imagebased/OWNERS
  pkg/types/imagebased/OWNERS
Labels: approved, lgtm, jira/valid-reference

#8722 OCPBUGS-36713: CAPG use existing subnets and VPC
  pkg/asset/manifests/gcp/cluster.go
Labels: approved, lgtm, platform/google, jira/valid-bug, jira/severity-important, jira/valid-reference

#8669 CORS-3302: port forward SSH to bootstrap host
  pkg/asset/installconfig/azure/session.go
  pkg/asset/machines/azure/azuremachines.go
  pkg/asset/machines/azure/machines.go
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/network.go
  pkg/infrastructure/azure/storage.go
Labels: approved, lgtm, jira/valid-reference

#8649 OCPBUGS-34638: destroy/gcp: set value for DiscardLocalSsd
  pkg/destroy/gcp/instance.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#8596 OCPBUGS-35440: capi/aws: bump provider for ingress rules fix
  cluster-api/providers/aws/go.mod
  cluster-api/providers/aws/go.sum
  cluster-api/providers/aws/vendor/modules.txt
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/OWNERS_ALIASES
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta1/zz_generated.conversion.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awscluster_webhook.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/network_types.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/securitygroup/securitygroups.go
  data/data/cluster-api/aws-infrastructure-components.yaml
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta1/zz_generated.conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awscluster_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/network_types.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8726 OCPBUGS-36890: [release-4.16] capi: start controllers after WaitGroup is created
  pkg/clusterapi/system.go
  pkg/infrastructure/clusterapi/clusterapi.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#8514 MGMT-17842: Add image-based installer create config ISO
  cmd/openshift-install/imagebased.go
  go.mod
  pkg/asset/imagebased/configimage/cabundle.go
  pkg/asset/imagebased/configimage/cabundle_test.go
  pkg/asset/imagebased/configimage/clusterconfiguration.go
  pkg/asset/imagebased/configimage/clusterconfiguration_test.go
  pkg/asset/imagebased/configimage/clusterid.go
  pkg/asset/imagebased/configimage/configiso.go
  pkg/asset/imagebased/configimage/extramanifests.go
  pkg/asset/imagebased/configimage/extramanifests_test.go
  pkg/asset/imagebased/configimage/imagebased_config.go
  pkg/asset/imagebased/configimage/imagebased_config_test.go
  pkg/asset/imagebased/configimage/imagedigestsources.go
  pkg/asset/imagebased/configimage/imagedigestsources_test.go
  pkg/asset/imagebased/configimage/ingressoperatorsigner.go
  pkg/asset/imagebased/configimage/installconfig.go
  pkg/asset/imagebased/configimage/installconfig_test.go
  pkg/asset/imagebased/configimage/util_test.go
  pkg/asset/kubeconfig/imagebased.go
  pkg/types/imagebased/imagebased_config_types.go
  pkg/types/imagebased/seedreconfiguration.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8662 CORS-3073: azure: Allow for installs in existing vnets
  pkg/asset/manifests/azure/cluster.go
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8699 STOR-1353: Attempt to cleanup GCP Filestore instances on destroy
  pkg/asset/installconfig/gcp/validation.go
  pkg/destroy/gcp/filestore.go
  pkg/destroy/gcp/gcp.go
  vendor/google.golang.org/api/file/v1/file-api.json
  vendor/google.golang.org/api/file/v1/file-gen.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8684 OCPBUGS-36748: Add yq-v4 to the upi-installer image for CI
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8697 OCPBUGS-37107: Power VS: Disable SNAT when specifying imageContentSources
  pkg/asset/manifests/powervs/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#8745 OCPBUGS-37164: Handle empty config for image-based create image
  pkg/asset/imagebased/image/ignition.go
  pkg/asset/imagebased/image/registriesconf.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8746 OCPBUGS-37067: update RHCOS 4.15 bootimage metadata to 415.92.202407091355-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8739 OCPBUGS-37104: openstack: Validate controlPlanePort has subnet
  pkg/types/openstack/validation/platform.go
  pkg/types/openstack/validation/platform_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8753 no-jira: Revert "Merge pull request #8714 from r4f4/bump-default-release-4.17"
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8698 MULTIARCH-4569: aws: support multi-arch nodes
  pkg/asset/cluster/openstack/openstack.go
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/master_test.go
  pkg/asset/machines/worker.go
  pkg/asset/machines/worker_test.go
  pkg/asset/manifests/clusterapi/cluster.go
  pkg/asset/manifests/openshift.go
  pkg/asset/rhcos/bootstrap_image.go
  pkg/asset/rhcos/image.go
  pkg/infrastructure/aws/clusterapi/ami.go
  pkg/infrastructure/nutanix/clusterapi/clusterapi.go
  pkg/infrastructure/openstack/clusterapi/clusterapi.go
  pkg/infrastructure/vsphere/clusterapi/clusterapi.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, platform/aws, jira/valid-reference, acknowledge-critical-fixes-only

#8731 CORS-3569: UDR for Capz
  pkg/asset/manifests/azure/cluster.go
  pkg/infrastructure/azure/azure.go
  pkg/infrastructure/azure/network.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8521 METAL-1039: Allow baremetal platform without MAPI
  data/unpack_test.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/baremetal/validation/platform_test.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8644 AGENT-910: node-joiner multi-arch support
  pkg/asset/agent/joiner/addnodesconfig.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/joiner/clusterinfo_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8681 OCPBUGS-35406: Use service CIDRs to determine bootstrap kubelet IP family
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8701 MULTIARCH-4777: gcp: support multi-arch nodes
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/types/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#8754 CORS-3607: Azure CAPI Installs within Tech Preview featureset
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8485 no-jira: docs/user/azure: fix byo vnet security groups
  docs/user/azure/customization.md
Labels: approved, lgtm, jira/valid-reference

#8728 OCPBUGS-36917: openstack: Fix apiVIPs and ingressVIPs docs
  docs/user/openstack/customization.md
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#8737 MGMT-18364: Add image-based config ISO integration tests
  cmd/openshift-install/integration_test.go
  cmd/openshift-install/internal_integration_test.go
  cmd/openshift-install/testdata/imagebased/configimage/assets/default_assets.txt
  cmd/openshift-install/testdata/imagebased/configtemplate/config-template.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8748 OCPBUGS-37068: update RHCOS 4.14 bootimage metadata to 414.92.202407091253-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8752 OCPBUGS-37226: Persist image-based config manifests from state instead of template
  pkg/asset/imagebased/configimage/configiso.go
  pkg/asset/imagebased/configimage/imagebased_config.go
  pkg/asset/imagebased/image/ignition.go
  pkg/asset/imagebased/image/image.go
  pkg/asset/imagebased/image/imagebased_config.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8762 no-jira: Replace Equal with ErrorContains for image-based nmstatectl unit tests
  pkg/asset/imagebased/configimage/imagebased_config_test.go
  pkg/asset/imagebased/image/imagebased_config_test.go
Labels: approved, lgtm, jira/valid-reference

#8730 OCPBUGS-36904: aws: bump CAPA for subnet tagging fix
  cluster-api/providers/aws/go.mod
  cluster-api/providers/aws/go.sum
  cluster-api/providers/aws/vendor/modules.txt
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2/launchtemplate.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network/subnets.go
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#8715 AGENT-922: Remove misleading inClusterConfig warning
  pkg/agent/kube.go
  pkg/agent/ocp.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#8761 MULTIARCH-4814: ic: add release arch validation for multi-arch clusters
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-reference

#8688 OCPBUGS-36390: aws: do not require create permissions when BYO IAM role
  pkg/asset/cluster/aws/aws.go
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/permissions_test.go
  pkg/asset/installconfig/platformpermscheck.go
Labels: approved, lgtm, platform/aws, jira/severity-low, jira/valid-bug, jira/valid-reference

#8757 OCPBUGS-36913: openstack: Fix security group tagging
  pkg/infrastructure/openstack/preprovision/securitygroups.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8734 OCPBUGS-36968: [release-4.16]: capi/aws: bump provider for ingress rules fix
  cluster-api/providers/aws/go.mod
  cluster-api/providers/aws/go.sum
  cluster-api/providers/aws/vendor/modules.txt
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/OWNERS_ALIASES
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta1/zz_generated.conversion.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awscluster_webhook.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/network_types.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/securitygroup/securitygroups.go
  data/data/cluster-api/aws-infrastructure-components.yaml
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta1/zz_generated.conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awscluster_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/network_types.go
Labels: approved, lgtm, platform/aws, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#8744 OCPBUGS-36780: ic: fix typo in warning message
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#8727 CORS-3566: Azure CAPI: disable natgw by setting node subnet id
  pkg/asset/manifests/azure/cluster.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only

#8756 OCPBUGS-36302: pkg/asset/machines/azure: Don't set disk encryption set to nil
  pkg/asset/machines/azure/azuremachines.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#8750 CORS-3568: Support GCP pre-created Service Accounts for CAPG
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/machines/gcp/gcpmachines.go
  pkg/asset/machines/gcp/gcpmachines_test.go
  pkg/asset/machines/gcp/machines.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/validation/machinepools_test.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#8760 AGENT-900: enable fips for add-nodes workflow
  hack/build-node-joiner.sh
  pkg/asset/agent/image/kargs.go
  pkg/asset/agent/image/kargs_test.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/joiner/clusterinfo_test.go
Labels: approved, lgtm, jira/valid-reference

#8740 AGENT-854: day2 add-nodes workflow validations
  pkg/asset/agent/installconfig.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/joiner/clusterinfo_test.go
  pkg/asset/agent/manifests/nmstateconfig.go
  pkg/asset/agent/manifests/nmstateconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#8507 AGENT-862: Extend monitor-add-nodes to support multiple nodes
  pkg/agent/cluster.go
  pkg/agent/monitoraddnodes.go
  pkg/agent/rest.go
  pkg/nodejoiner/monitoraddnodes.go
Labels: approved, lgtm, jira/valid-reference

#8582 OCPBUGS-35366: Update upi references to api-internal
  docs/user/gcp/install_upi.md
  upi/gcp/02_lb_int.py
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#8758 OCPBUGS-37356: vSphere validation fails if dc is in a folder
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8759 OCPBUGS-37427: bootstrap gather fails in vsphere, only ipv6 address used
  pkg/infrastructure/clusterapi/clusterapi.go
  pkg/infrastructure/clusterapi/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#8763 OCPBUGS-37217: CAPI GCP - retry SetIAMPolicy
  pkg/infrastructure/gcp/clusterapi/iam.go
Labels: approved, lgtm, platform/google, qe-approved, jira/valid-bug, jira/valid-reference

#8775 no-jira: Azure: remove stale DNS migration images
  docs/user/azure/images/azure-migrate-dns-1.png
  docs/user/azure/images/azure-migrate-dns-2.png
  docs/user/azure/images/azure-migrate-dns-3.png
  docs/user/azure/images/azure-migrate-dns-4.png
  docs/user/azure/images/azure-migrate-dns-5.png
  docs/user/azure/images/azure-migrate-dns-6.png
  docs/user/azure/images/azure-migrate-dns-7.png
Labels: approved, lgtm, jira/valid-reference

#8773 CORS-3580: Update GCP Disk Types
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/destroy/gcp/gcp.go
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/gcp/validation/machinepool_test.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#8741 no-jira: bootstrap: add shellcheck directives to follow sourced files
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
  data/data/bootstrap/files/usr/local/bin/kubelet.sh.template
Labels: approved, lgtm, jira/valid-reference

#8691 CORS-3209: Set UserTags on CAPG resources
  pkg/asset/machines/gcp/gcpmachines.go
  pkg/asset/machines/gcp/gcpmachines_test.go
  pkg/asset/manifests/gcp/cluster.go
Labels: approved, lgtm, platform/google, jira/valid-reference

#8667 OCPBUGS-35959: azure: Fix Accelerated network enablement
  pkg/asset/machines/azure/azuremachines.go
  pkg/asset/machines/clusterapi.go
Labels: approved, lgtm, platform/azure, jira/valid-bug, jira/severity-important, jira/valid-reference

#8717 AGENT-919: Authenticate day2 operations
  data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
  data/data/agent/systemd/units/agent-import-cluster.service.template
  pkg/agent/cluster.go
  pkg/agent/rest.go
  pkg/asset/agent/gencrypto/auth_utils.go
  pkg/asset/agent/gencrypto/auth_utils_test.go
  pkg/asset/agent/gencrypto/authconfig.go
  pkg/asset/agent/gencrypto/authconfig_test.go
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/image/ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#8783 AGENT-862: Change day-2 monitor timeout back to 90 minutes
  pkg/agent/monitoraddnodes.go
Labels: approved, lgtm, jira/valid-reference

#8772 OCPBUGS-37510: [release-4.16] aws: bump CAPA for subnet tagging fix
  cluster-api/providers/aws/go.mod
  cluster-api/providers/aws/go.sum
  cluster-api/providers/aws/vendor/modules.txt
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2/launchtemplate.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network/subnets.go
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#8779 AGENT-928: allow user to specify sshKey via config file
  pkg/asset/agent/joiner/addnodesconfig.go
  pkg/asset/agent/joiner/addnodesconfig_test.go
  pkg/asset/agent/joiner/clusterinfo.go
  pkg/asset/agent/joiner/clusterinfo_test.go
Labels: approved, lgtm, jira/valid-reference
