Repository openshift/installer, pull requests merged in 2025-06, with the labels that each got.

#9224 AGENT-997: Internal dev docs for authentication-authorization
  docs/user/agent/authentication-authorization.md
Labels: approved, lgtm, jira/valid-reference

#9767 OCPBUGS-51299: Set default project and location for KMS key manifest
  pkg/asset/manifests/clustercsidriver.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9751 OCPBUGS-56658: Prompt User for AWS Creds when none are found
  pkg/asset/installconfig/aws/ec2.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9769 OCPBUGS-57021: Use less permissive access for /var/lib/etcd for SNO
  data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9740 CORS-4057: migrate EC2 quota checking code AWS SDK v2
  pkg/asset/quota/aws/instancetypes.go
  pkg/asset/quota/quota.go
Labels: approved, lgtm, jira/valid-reference

#9789 CORS-3795: Updating the release image to 4.20
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference

#9790 CORS-3796: Update CVO channel to latest
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, jira/valid-reference

#9784 no-jira: Update Generated Files
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
Labels: approved, lgtm, jira/valid-reference

#9785 OCPBUGS-57192: Checking for selected PE retrieved data and returning errors for missing values
  pkg/asset/installconfig/nutanix/nutanix.go
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference

#9783 OCPBUGS-57348: add MCO operator manifest for boot image management
  data/data/manifests/manifests/90_cluster-mco-02-config.yaml.template
  pkg/asset/manifests/mco.go
  pkg/asset/manifests/mco_test.go
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/templates/content/helper.go
  pkg/asset/templates/content/manifests/cluster-mco-config.go
Labels: approved, lgtm, tide/merge-method-squash, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9724 OCPBUGS-18510: Refactor removing loadbalancer in OpenStack.
  pkg/destroy/openstack/openstack.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/loadbalancer/v2/apiversions/doc.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/loadbalancer/v2/apiversions/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/loadbalancer/v2/apiversions/results.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/loadbalancer/v2/apiversions/urls.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9787 OCPBUGS-41879: vSphere - if regions are the same cannot dup zones
  pkg/types/vsphere/validation/platform.go
  pkg/types/vsphere/validation/platform_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
