Repository openshift/installer, pull requests merged in 2025-09, with the labels that each got.

#9922 OCPBUGS-61111: Allow user to BYO private zone without specifying name
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/manifests/dns.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/dns.go
  pkg/types/gcp/dns.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, verified

#9929 OCPBUGS-61373: Fix shellcheck issues in bootstrap
  data/data/bootstrap/baremetal/files/usr/local/bin/build-metal3-env.sh
  data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh
  data/data/bootstrap/files/usr/local/bin/installer-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#9934 MGMT-21586: Add an option in image-based installation to specify architecture
  pkg/asset/imagebased/image/baseiso.go
  pkg/asset/imagebased/image/baseiso_test.go
  pkg/asset/imagebased/image/imagebased_config.go
  pkg/asset/imagebased/image/imagebased_config_test.go
  pkg/types/imagebased/imagebased_config_types.go
Labels: approved, lgtm, jira/valid-reference, verified

#9944 CORS-4162: Remove GCPClusterHostedDNSInstall featuregate
  pkg/types/gcp/validation/featuregates.go
  pkg/types/validation/featuregate_test.go
Labels: approved, lgtm, jira/valid-reference, verified

#9940 CORS-3550: add ability to opt out of the sigstore signing requirement
  pkg/asset/ignition/bootstrap/cvoignore.go
Labels: approved, lgtm, jira/valid-reference, verified

#9950 OCPBUGS-61901: Update explain for Publish
  data/data/install.openshift.io_installconfigs.yaml
  pkg/explain/fields_lookup_test.go
  pkg/explain/printer_test.go
  pkg/types/installconfig.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, verified

#9967 OCPBUGS-62293: Set default for PrivateDNSZone Project ID
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, verified

#9968 OCPBUGS-62297: Set default for PrivateDNSZone Project ID
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference, verified

#9935 OCPBUGS-61514: Add check for gcp firewall deletion permission
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/firewallrules.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#9954 CORS-4107: Update default release image to 4.21
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference, verified
