Repository openshift/installer, pull requests merged in 2025-04, with the labels that each got.

#9395 CORS-3923, CORS-3927: Support confidential cluster installation on SEV-SNP and TDX nodes on GCP
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/machinepools.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/gcp/validation/machinepool_test.go
Labels: approved, lgtm, ok-to-test, qe-approved, jira/valid-reference

#9556 no-jira: Add Johan-Liebert1 to coreos-reviewers and coreos-approvers
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9571 OCPBUGS-53140: Validation for API and Ingress VIPs when using user-managed load balancer
  pkg/types/openstack/defaults/platform.go
  pkg/types/openstack/defaults/platform_test.go
  scripts/openstack/manifest-tests/lb-default-stable/test_cluster-infra.py
  scripts/openstack/manifest-tests/lb-unmanaged/install-config.yaml
Labels: approved, lgtm, platform/openstack, jira/valid-bug, jira/valid-reference

#9614 OCPBUGS-54367: IBMCloud: Move to IBM TF openshift fork
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/.travis.yml
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/data_source_ibm_cis_dns_records.go
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/resource_ibm_cis_dns_record.go
  terraform/providers/ibm/vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9577 OCPBUGS-53303: Revert: Power VS: Disallow platform.powervs.clusterOSImage in install-config
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/machines/powervs/machines.go
  pkg/asset/rhcos/image.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9625 CORS-3883: Remove user-assigned identity from ARM template
  upi/azure/04_bootstrap.json
  upi/azure/05_masters.json
  upi/azure/06_workers.json
Labels: approved, lgtm, jira/valid-reference

#9628 NO-JIRA: OWNERS_ALIASES - Add user as coreos-approvers / coreos-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9586 OCPBUGS-53067: Updating the file names in generic.ins file for s390x ABI for pxe Artifacts
  pkg/asset/agent/image/agentpxefiles.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9631 NO-JIRA: Add jcapiitao to CoreOS approvers and reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9617 OCPBUGS-52473: aarch64 kernel is no longer zipped
  pkg/asset/agent/image/agentpxefiles.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9629 OCPEDGE-1701: fix: update tnf validation to account for tna install config
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9603 OCPBUGS-54232: Azure Move BYO VNET SG creation to InfraReady
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9605 OCPBUGS-54264: IBMCloud: Move to IBM TF openshift fork
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/data_source_ibm_cis_dns_records.go
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/resource_ibm_cis_dns_record.go
  terraform/providers/ibm/vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9144 OCPBUGS-43724: Fix Load balancer IP setup
  pkg/asset/manifests/azure/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9632 OCPBUGS-54541: Update RHCOS 4.19 bootimage metadata to 9.6.20250402-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9606 CORS-3883: remove SystemAssigned ID
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/machines/azure/azuremachines.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/featuregates.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
  pkg/types/validation/featuregate_test.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#9638 SPLAT-2121: vsphere - if no host group found, append not found
  pkg/asset/installconfig/vsphere/validation.go
  pkg/asset/installconfig/vsphere/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#9600 CORS-3908: Update gcp cloud provider config map to include new endpoints
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig.go
  pkg/asset/manifests/gcp/cloudproviderconfig_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9624 OCPEDGE-1506: Add Platform based validation to fencing credentials
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9642 NO-JIRA: add Roshan-R to CoreOS approvers and reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9639 NO-JIRA: fix the platform test assertions to check expected err message
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/aws/platform.go
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
  pkg/types/conversion/installconfig.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9650 OCPBUGS-53439: fix inconsistent subnet role name for bootstrap node
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/aws/platform.go
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9315 OCPBUGS-46375: Allow spaces in the aws tags [release-4.17]
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9627 AGENT-1159: agent docs update
  docs/user/agent/agent-services.md
  docs/user/agent/agent_installer_services-add_nodes_workflow.png
  docs/user/agent/agent_installer_services-install_workflow.png
  docs/user/agent/agent_installer_services-interactive.png
  docs/user/agent/agent_installer_services-unconfigured_ignition_and_config_image_flow.png
Labels: approved, lgtm, jira/valid-reference

#9608 OCPBUGS-54319: oci-eval-user-data uses dmidecode which is not supported on ppc64le or s390x
  data/data/agent/files/usr/local/bin/oci-eval-user-data.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9648 CORS-3886: azure: Set use managed identity to false
  pkg/asset/manifests/azure/cloudproviderconfig.go
  pkg/asset/manifests/azure/cloudproviderconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9655 CORS-3867: fix CRD descriptor to mention required BootstrapNode role
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/aws/platform.go
  pkg/types/aws/validation/platform.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9652 CORS-3278: Switch IBMCloud to CAPI
  pkg/infrastructure/platform/platform.go
  pkg/infrastructure/platform/platform_altinfra.go
  pkg/types/installconfig.go
Labels: approved, lgtm, jira/valid-reference

#9125 CORS-3854: Enable option to set boot diagnostics
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/installconfig/azure/client.go
  pkg/asset/installconfig/azure/mock/azureclient_generated.go
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/machines/azure/azuremachines.go
  pkg/asset/machines/azure/machines.go
  pkg/asset/machines/azure/machinesets.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/gather/azure/azure.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/machinepool.go
Labels: approved, lgtm, jira/valid-reference

#9636 CORS-3278: IBMCloud: Add DestroyBootstrap for leftover CAPI resources
  go.sum
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/ibmcloud.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/asset/manifests/ibmcloud/cluster.go
  pkg/infrastructure/ibmcloud/clusterapi/bootstrap.go
  pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
  pkg/types/ibmcloud/platform.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/util/conditions/doc.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/getter.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/matcher.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/matchers.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/merge.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/merge_strategies.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/patch.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/setter.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/unstructured.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/aggregate.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/doc.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/getter.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/matcher.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/merge_strategies.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/mirror.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/options.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/patch.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/setter.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/sort.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/summary.go
  vendor/sigs.k8s.io/cluster-api/util/patch/doc.go
  vendor/sigs.k8s.io/cluster-api/util/patch/options.go
  vendor/sigs.k8s.io/cluster-api/util/patch/patch.go
  vendor/sigs.k8s.io/cluster-api/util/patch/utils.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#9653 OCPBUGS-54606: convert OVNKubernetes networkType to correct format
  pkg/types/conversion/installconfig.go
  pkg/types/conversion/installconfig_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9599 CORS-3870: add validations for subnets field with AWS API
  pkg/asset/installconfig/aws/metadata.go
  pkg/asset/installconfig/aws/permissions_test.go
  pkg/asset/installconfig/aws/subnet.go
  pkg/asset/installconfig/aws/tags.go
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9661 OCPEDGE-1749: [TNF] Updated bare-metal init sequence to detach control-plane nodes in Two Node OpenShift.
  data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9663 CORS-3870: validate duplicate AZs if no subnet roles at all or only for subnets of the same role
  pkg/asset/installconfig/aws/validation.go
  pkg/asset/installconfig/aws/validation_test.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9657 NO-JIRA: Update SCOS 4.19 bootimage metadata to 9.0.20250411-0
  data/data/coreos/scos.json
Labels: approved, lgtm, jira/valid-reference

#9656 OCPBUGS-54902: Custom-DNS: Update Kubeconfig and Infra CR based on private or public cluster
  cmd/openshift-install/create.go
  pkg/infrastructure/aws/clusterapi/ignition.go
  pkg/infrastructure/gcp/clusterapi/ignition.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#9124 CORS-3855: Remove ARO build flag from installer
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/openshift.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/platform.go
  pkg/types/azure/validation/platform_test.go
Labels: approved, lgtm, jira/valid-reference

#9597 OCPBUGS-52203: Find GCP KMS keys
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#9676 OCPBUGS-55324: fix nil field access when describing security groups
  pkg/asset/installconfig/aws/validation.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9643 OCPBUGS-55193: data/manifests/bootkube/cvo-overrides: Default to eus-4.14
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9680 no-jira: IBI nmstate unit test fix
  pkg/asset/imagebased/configimage/imagebased_config_test.go
  pkg/asset/imagebased/image/imagebased_config_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
