Repository openshift/installer, pull requests merged in 2025-05, with the labels that each got.

#9662 OCPBUGS-55492: sort zone slices extracted from map of byo subnets
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#9673 CORS-3960: Remove Terraform from Dockerfiles
  images/installer-artifacts/Dockerfile.rhel
  images/installer/Dockerfile.ci
  images/installer/Dockerfile.upi.ci
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9225 CORS-3633: Fail the install when there are expired certs
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9488 OCPBUGS-45805: Check for nil in case of proxy crash/deleted
  pkg/destroy/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9683 no-jira: azure: add tested instance types for CORS-3634 and CORS-3771
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-reference

#9640 OCPEDGE-1707: Add Disable Certificate Verification API
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/machinepools.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9644 OCPBUGS-53116: AWS Destroy use AWS SDK v2
  pkg/destroy/aws/aws.go
  pkg/destroy/aws/ec2helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#9669 no-jira: fixes to get shellcheck to pass
  data/data/agent/files/usr/local/bin/install-status.sh
  data/data/agent/files/usr/local/bin/set-node-zero.sh
Labels: approved, lgtm, jira/valid-reference

#9686 OCPBUGS-55722: azure stack: switch cloud provider to standard lb
  pkg/asset/manifests/azure/cloudproviderconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9637 OCPBUGS-54566: Apply defaults then validate confidentialCompute
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/types/gcp/validation/machinepool.go
  pkg/types/gcp/validation/machinepool_test.go
Labels: approved, lgtm, ok-to-test, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9689 OCPBUGS-54502: ensure ctrplane nodes can access bootstrap MCS
  pkg/asset/manifests/aws/cluster.go
Labels: approved, lgtm, platform/aws, jira/valid-bug, jira/valid-reference

#9687 no-jira: add PeaceRebel (Bipin) to coreos approvers & reviewers list
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9697 no-jira: add jcpowermac to nutanix review/approve groups
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9691 OCPBUGS-55772: Add support for Azure TDX confidential VM type
  pkg/asset/installconfig/azure/validation.go
  pkg/asset/installconfig/azure/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9696 OCPBUGS-55817: add Lsv4 and Lasv4 series as tested
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9693 OCPBUGS-47719: [Nutanix] nil error displayed when setting a not exist value in preloadedOSImageName field
  pkg/types/nutanix/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9635 OCPEDGE-1673: [TNF] Render secret manifests from fencing credentials block.
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/machines/master.go
  pkg/asset/machines/master_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9562 OCPBUGS-53107: Set appropriate KillMode for systemd services
  data/data/agent/systemd/units/agent-add-node.service
  data/data/agent/systemd/units/agent-import-cluster.service.template
  data/data/agent/systemd/units/agent-register-cluster.service.template
  data/data/agent/systemd/units/agent-register-infraenv.service.template
  data/data/agent/systemd/units/agent-start-ui.service.template
  data/data/agent/systemd/units/apply-host-config.service
  data/data/agent/systemd/units/pre-network-manager-config.service
  data/data/agent/systemd/units/set-hostname.service
  data/data/agent/systemd/units/start-cluster-installation.service
  data/data/bootstrap/baremetal/systemd/units/extract-machine-os.service
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9708 OCPBUGS-56079: apply fixes for yaml-lint errors
  .golangci.yaml
  scripts/openstack/manifest-tests/lb-unmanaged/install-config.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9714 OKD-251: Update SCOS 4.19 bootimage metadata to 9.0.20250510-0
  data/data/coreos/scos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9716 OCPBUGS-56262: Added better logging for vSphere destroy
  pkg/destroy/vsphere/client.go
  pkg/destroy/vsphere/mock/vsphereclient_generated.go
  pkg/destroy/vsphere/vsphere.go
  pkg/destroy/vsphere/vsphere_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9702 OCPBUGS-56006: [release-4.19] CORS-3634, CORS-3771, CORS-3772: Azure doc: add support for Lsv4, Lasv4, Dxv6, NDs and NV series
  docs/user/azure/tested_instance_types_x86_64.md
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9721 OCPBUGS-55068: Update RHCOS 4.19 bootimage metadata to 9.6.20250513-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9720 OCPBUGS-55905: Update RHCOS 4.20 bootimage metadata to 9.6.20250513-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9723 NO-JIRA: add the instance types which test PASS
  docs/user/ibmcloud/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-reference

#9733 OCPBUGS-56008: don't expect identity on ASH
  pkg/types/utils.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9732 no-jira: Update team osasinfra
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9717 OCPBUGS-56268: pkg/types/azure: remove SystemAssignedID docs
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/azure/machinepool.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9739 OCPBUGS-56008: Remove unnecessary validation
  pkg/infrastructure/azure/azure.go
  pkg/types/azure/validation/machinepool.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9741 OCPBUGS-56645: Update RHCOS 4.20 bootimage metadata to 9.6.20250523-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9725 OCPBUGS-55672: Remove MultiArchInstallGCP featuregate
  pkg/types/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9048 OCPBUGS-6508: Update Control Plane replica validation for Single Node OpenShift
  pkg/asset/machines/master.go
  pkg/asset/machines/master_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9744 no-jira: add unit tests for vsphere VIPS/machinenetworks population
  pkg/asset/manifests/infrastructure_test.go
Labels: approved, lgtm, jira/valid-reference

#9749 OCPBUGS-56808: Remove configv1.GCPServiceEndpointNameTagManager references
  pkg/types/gcp/validation/platform.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9728 OCPBUGS-54413: Make swift containers removal not fatal for UPI.
  upi/openstack/down-containers.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
