Repository openshift/installer, pull requests merged in 2025-03, with the labels that each got.

#9159 OCPEDGE-1310: feat: add arbiter node support to installer
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/agent/installconfig.go
  pkg/asset/cluster/cluster.go
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/ignition/bootstrap/baremetal/template.go
  pkg/asset/ignition/bootstrap/baremetal/template_test.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/ignition/machine/arbiter.go
  pkg/asset/ignition/machine/arbiter_ignition_customizations.go
  pkg/asset/ignition/machine/arbiter_ignition_customizations_test.go
  pkg/asset/ignition/machine/arbiter_test.go
  pkg/asset/machines/arbiter.go
  pkg/asset/machines/arbiter_test.go
  pkg/asset/machines/baremetal/hosts.go
  pkg/asset/machines/baremetal/hosts_test.go
  pkg/asset/manifests/topologies.go
  pkg/asset/store/assetcreate_test.go
  pkg/asset/targets/targets.go
  pkg/explain/printer_test.go
  pkg/types/baremetal/platform.go
  pkg/types/baremetal/validation/platform.go
  pkg/types/installconfig.go
  pkg/types/machinepools.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-reference

#9516 OCPBUGS-51204: bootstrap/node-image-pull.sh: handle PXE boots as well
  data/data/bootstrap/files/usr/local/bin/node-image-pull.sh.template
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9503 OCPBUGS-50534: Fix error messages in available IP code
  pkg/asset/manifests/azure/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9415 OCPBUGS-46051: IBMCloud: Fix CAPI AZ handling
  pkg/asset/manifests/ibmcloud/cluster.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#9505 CORS-3869: static validation for new vpc.subnets field
  pkg/types/aws/platform.go
  pkg/types/aws/validation/platform.go
  pkg/types/aws/validation/platform_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9385 OCPBUGS-47652: IBMCloud: Set CAPI boot volumes
  pkg/asset/machines/ibmcloud/capimachines.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#9397 OCPBUGS-47459: IBMCloud: CAPI add permitted network
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/metadata.go
  pkg/asset/installconfig/ibmcloud/metadata_test.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#9425 SPLAT-1995: vsphere on destroy remove cns volumes
  go.sum
  pkg/destroy/vsphere/client.go
  pkg/destroy/vsphere/mock/vsphereclient_generated.go
  pkg/destroy/vsphere/vsphere.go
  vendor/github.com/vmware/govmomi/cns/.gitignore
  vendor/github.com/vmware/govmomi/cns/client.go
  vendor/github.com/vmware/govmomi/cns/cns_util.go
  vendor/github.com/vmware/govmomi/cns/methods/methods.go
  vendor/github.com/vmware/govmomi/cns/methods/unreleased.go
  vendor/github.com/vmware/govmomi/cns/types/enum.go
  vendor/github.com/vmware/govmomi/cns/types/if.go
  vendor/github.com/vmware/govmomi/cns/types/types.go
  vendor/github.com/vmware/govmomi/cns/types/unreleased_types.go
  vendor/github.com/vmware/govmomi/cns/unreleased_client.go
  vendor/github.com/vmware/govmomi/vsan/vsanfs/types/enum.go
  vendor/github.com/vmware/govmomi/vsan/vsanfs/types/types.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9497 OCPBUGS-50961: Power VS: Log accurate error when deploying Internal with no vpcName
  pkg/asset/installconfig/powervs/metadata.go
  pkg/asset/manifests/powervs/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9508 NO-JIRA: bootstrap: add CLUSTER_PROFILE_ANNOTATION variable to auth-api bootstrapping stage
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-reference

#9510 OCPBUGS-51350: PowerVS: Extra network routes for disconnected install
  pkg/asset/machines/machineconfig/routes.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/types/powervs/defaults/platform.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9517 CORS-3917: Add install config validation for service endpoints
  go.mod
  go.sum
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  vendor/github.com/jarcoal/httpmock/.gitignore
  vendor/github.com/jarcoal/httpmock/LICENSE
  vendor/github.com/jarcoal/httpmock/README.md
  vendor/github.com/jarcoal/httpmock/any.go
  vendor/github.com/jarcoal/httpmock/doc.go
  vendor/github.com/jarcoal/httpmock/env.go
  vendor/github.com/jarcoal/httpmock/file.go
  vendor/github.com/jarcoal/httpmock/internal/error.go
  vendor/github.com/jarcoal/httpmock/internal/route_key.go
  vendor/github.com/jarcoal/httpmock/internal/stack_tracer.go
  vendor/github.com/jarcoal/httpmock/internal/submatches.go
  vendor/github.com/jarcoal/httpmock/match.go
  vendor/github.com/jarcoal/httpmock/response.go
  vendor/github.com/jarcoal/httpmock/transport.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9522 No-ISSUE: (dep) Bump openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9527 OCPBUGS-39583: Remove tmp directory used for agent pxe files
  pkg/asset/agent/image/agentpxefiles.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9530 OCPEDGE-1635: Set default values for arbiter
  pkg/types/defaults/installconfig.go
  pkg/types/defaults/installconfig_test.go
  pkg/types/defaults/machinepools.go
  pkg/types/defaults/machinepools_test.go
Labels: approved, lgtm, jira/valid-reference

#9421 OCPBUGS-49623: IBMCloud: Missing ca-mon region due to static region list
  pkg/asset/installconfig/ibmcloud/client.go
  pkg/asset/installconfig/ibmcloud/ibmcloud.go
  pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
  pkg/types/ibmcloud/validation/platform.go
  pkg/types/ibmcloud/validation/platform_test.go
  vendor/github.com/IBM/platform-services-go-sdk/globalcatalogv1/global_catalog_v1.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#9489 OCPBUGS-47724: AWS: Copy static MCO resources needed for custom-dns
  data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9531 OCPBUGS-50637: Remove error logging when determining image arch
  pkg/asset/agent/common.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9227 OCPBUGS-44840: Mount the user-ca-bundle into ICC
  data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9524 OCPBUGS-51378: Change vsphere conversion govmomi err to be clear
  pkg/types/vsphere/conversion/installconfig.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9223 CORS-2508: aws: remove unused autoscaling:DescribeAutoScalingGroups perm
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9451 OCPBUGS-49737: Custom-DNS: Update master and worker user data secrets
  pkg/asset/machines/arbiter.go
  pkg/asset/machines/master.go
  pkg/asset/machines/userdata.go
  pkg/asset/machines/worker.go
  pkg/infrastructure/clusterapi/ignition.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#9526 OCPBUGS-36553: VSphere: add vips to machinenetwork
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/infrastructure_test.go
  pkg/asset/manifests/vsphere/infrastructure.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9120 OCPBUGS-33370: Improve baremetal gather error message
  pkg/infrastructure/baremetal/variables.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9529 AGENT-1113: enhance the unconfigured-ignition command to support the interactive workflow
  cmd/openshift-install/agent.go
  cmd/openshift-install/agent/contextwrapper.go
  cmd/openshift-install/testdata/agent/unconfigured-ignition/configurations/interactive.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/manifests/default_manifests.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/missing-infraenv.txt
  cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/unsupported-install-config.txt
  data/data/agent/systemd/units/agent-register-cluster.service.template
  data/data/agent/systemd/units/agent-register-infraenv.service.template
  data/data/agent/systemd/units/agent-start-ui.service.template
  data/data/agent/systemd/units/load-config-iso@.service.template
  pkg/asset/agent/agentconfig/agenthosts.go
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/image/unconfigured_ignition.go
  pkg/asset/agent/image/unconfigured_ignition_test.go
  pkg/asset/agent/manifests/agent_test.go
  pkg/asset/agent/manifests/clusterimageset.go
  pkg/asset/agent/manifests/infraenv.go
  pkg/asset/agent/manifests/infraenv_test.go
  pkg/asset/agent/manifests/infraenvfile.go
  pkg/asset/agent/manifests/infraenvfile_test.go
  pkg/asset/agent/mirror/cabundle.go
  pkg/asset/agent/mirror/registriesconf.go
  pkg/asset/agent/workflow/agentworkflow.go
  pkg/asset/agent/workflow/commons.go
Labels: approved, lgtm, jira/valid-reference

#9532 OCPBUGS-6271: Adding VIPs Validation for agent based vsphere installation
  pkg/asset/agent/installconfig_test.go
  pkg/types/validation/installconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9533 OCPBUGS-51209: Changed kernelFileType name from kernel.img to vmlinuz for s390x
  pkg/asset/agent/image/agentpxefiles.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9555 NO-JIRA: OWNERS: add thuan
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9300 OCPBUGS-45692: Modified ova template name to use failure domain name
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  pkg/asset/machines/vsphere/capimachines.go
  pkg/asset/machines/vsphere/machines.go
  pkg/asset/machines/vsphere/machines_test.go
  pkg/asset/machines/vsphere/machinesets.go
  pkg/asset/machines/vsphere/machinesets_test.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/vsphere/infrastructure.go
  pkg/infrastructure/vsphere/clusterapi/import.go
  pkg/utils/vmware.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9534 OCPEDGE-1513: feat(topologies): add DualReplica topology mode
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/manifests/topologies.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9553 SPLAT-2072: Removed VSphereMultiVCenters feature gate
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/types/validation/featuregate_test.go
  pkg/types/vsphere/platform.go
  pkg/types/vsphere/validation/featuregates.go
Labels: approved, lgtm, jira/valid-reference

#9541 OCPBUGS-39146: Validate sgdisk partition start in image based installer config
  pkg/asset/imagebased/image/imagebased_config.go
  pkg/asset/imagebased/image/imagebased_config_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9557 AGENT-537: Add agent command to generate certificates
  cmd/openshift-install/agent.go
  cmd/openshift-install/testdata/agent/image/assets/tls_assets.txt
Labels: approved, lgtm, jira/valid-reference

#9572 OCPBUGS-53210: PowerVS: remove system pools
  pkg/asset/installconfig/powervs/session.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/quota/quota.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9551 OCPBUGS-53280: PowerVS: Re-enable disconnected installs
  pkg/asset/manifests/powervs/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9547 OCPBUGS-52191: [release-4.16] capi/aws: bump provider for LB DNS lookup fix
  cluster-api/providers/aws/go.mod
  cluster-api/providers/aws/go.sum
  cluster-api/providers/aws/vendor/modules.txt
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/bootstrap/eks/controllers/eksconfig_controller.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/controllers/awscluster_controller.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/controllers/awsmachine_controller.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/controlplane/rosa/controllers/rosacontrolplane_controller.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/devbox.json
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/devbox.lock
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/exp/api/v1beta2/awsmanagedmachinepool_webhook.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/exp/controllers/awsmachinepool_controller.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/exp/controllers/rosamachinepool_controller.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/scope/fargate.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/scope/managednodegroup.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/scope/rosamachinepool.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/scope/session.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/autoscaling/autoscalinggroup.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2/bastion.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2/launchtemplate.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/eks/eks.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/eks/fargate.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/eks/nodegroup.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/elb/loadbalancer.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network/network.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network/subnets.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/securitygroup/securitygroups.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/internal/cidr/cidr.go
  cluster-api/providers/aws/vendor/sigs.k8s.io/cluster-api-provider-aws/v2/pkg/rosa/helpers.go
  data/data/cluster-api/aws-infrastructure-components.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9560 SPLAT-2078: Removed VSphereStaticIPs feature gate
  pkg/types/validation/featuregate_test.go
  pkg/types/vsphere/validation/featuregates.go
Labels: approved, lgtm, jira/valid-reference

#8784 OCPBUGS-52959: Issue short lived certificates if ShortCertRotation featuregate is enabled
  go.mod
  go.sum
  pkg/asset/imagebased/configimage/ingressoperatorsigner.go
  pkg/asset/tls/adminkubeconfig.go
  pkg/asset/tls/aggregator.go
  pkg/asset/tls/apiserver.go
  pkg/asset/tls/certkey_test.go
  pkg/asset/tls/ironictls.go
  pkg/asset/tls/journalcertkey.go
  pkg/asset/tls/kubecontrolplane.go
  pkg/asset/tls/kubelet.go
  pkg/asset/tls/mcscertkey.go
  pkg/asset/tls/root.go
  pkg/asset/tls/tls.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/types_insights.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/internal/httpcommon/headermap.go
  vendor/golang.org/x/net/internal/httpcommon/request.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/text/language/parse.go
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/merge/update.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/typed.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9574 AGENT-537: Run agent installer command to create certificates
  data/data/agent/files/usr/local/bin/set-node-zero.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9584 AGENT-467: show the agent ui url when available
  cmd/openshift-install/testdata/agent/unconfigured-ignition/configurations/interactive.txt
  data/data/agent/files/usr/local/bin/install-status.sh
  data/data/agent/systemd/units/agent-start-ui.service.template
  data/data/agent/systemd/units/install-status.service
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9582 OCPBUGS-53379: Update RHCOS 4.19 bootimage metadata to 9.6.20250319-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#9579 OCPEDGE-1513: Fixed topology logic for 2-node installs and added unit tests
  pkg/asset/manifests/topologies.go
  pkg/asset/manifests/topologies_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9593 OCPBUGS-53465: Update RHCOS 4.19 bootimage metadata to 9.6.20250321-0
  data/data/coreos/rhcos.json
Labels: jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9569 NO-JIRA: CVE-2025-22868 bump oauth2 pkg to v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/jws/jws.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9563 OCPBUGS-53106: Create ConfigMap to reference baremetal-installer image
  images/baremetal/Dockerfile.ci
  images/baremetal/manifests/0000_90_baremetal-installer_01_images.configmap.yaml
  images/baremetal/manifests/image-references
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9598 NO-JIRA: update OWNER_ALIASES for azure and aws
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9482 [release-4.16] OCPBUGS-50547: aws/edge/byovpc: tag edge subnets with shared value
  pkg/asset/cluster/aws/aws.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9194 OSASINFRA-3730: Add support for storing OpenStack CA bundles
  data/data/manifests/openshift/cloud-creds-secret.yaml.template
  pkg/asset/manifests/openshift.go
  pkg/asset/manifests/openstack/cloudproviderconfig.go
  pkg/asset/manifests/template.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9604 OCPBUGS-54263: IBMCloud: Move to IBM TF openshift fork
  terraform/providers/ibm/go.mod
  terraform/providers/ibm/go.sum
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/.travis.yml
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/data_source_ibm_cis_dns_records.go
  terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/resource_ibm_cis_dns_record.go
  terraform/providers/ibm/vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9602 OCPBUGS-54260: vsphere-fix convert if only provided name
  pkg/asset/installconfig/vsphere/mock/vsphere_sim.go
  pkg/types/vsphere/conversion/installconfig.go
  pkg/types/vsphere/conversion/installconfig_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9546 OCPEDGE-1496: [TNF] Collect pacemaker, pcsd, and corosync logs and journals in installer-masters-gather.sh
  data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Labels: approved, lgtm, jira/valid-reference
