Repository openshift/installer, pull requests merged in 2025-07, with the labels that each got.

#9763 OCPBUGS-58216: allow to deploy single nodes with UPI
  pkg/asset/machines/master.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9803 OCPBUGS-57923: When AWS_PROFILE is invalid ask for credentials
  pkg/asset/installconfig/aws/ec2.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9778 [release-4.17] OCPBUGS-57293: sort zone slices extracted from map of byo subnets
  go.mod
  go.sum
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/master.go
  vendor/github.com/daixiang0/gci/README.md
  vendor/github.com/daixiang0/gci/cmd/gci/gcicommand.go
  vendor/github.com/daixiang0/gci/cmd/gci/list.go
  vendor/github.com/daixiang0/gci/cmd/gci/root.go
  vendor/github.com/daixiang0/gci/main.go
  vendor/github.com/daixiang0/gci/pkg/config/config.go
  vendor/github.com/daixiang0/gci/pkg/gci/gci.go
  vendor/github.com/daixiang0/gci/pkg/gci/testdata.go
  vendor/github.com/daixiang0/gci/pkg/io/file.go
  vendor/github.com/daixiang0/gci/pkg/io/search.go
  vendor/github.com/daixiang0/gci/pkg/parse/parse.go
  vendor/github.com/daixiang0/gci/pkg/section/alias.go
  vendor/github.com/daixiang0/gci/pkg/section/parser.go
  vendor/github.com/daixiang0/gci/pkg/section/prefix.go
  vendor/github.com/daixiang0/gci/pkg/section/standard_list.go
  vendor/github.com/daixiang0/gci/pkg/utils/constants.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#7678 OCPBUGS-18658 OCPBUGS-45256: Unify agent install-complete with installer
  cmd/openshift-install/agent/waitfor.go
  cmd/openshift-install/command/gather.go
  cmd/openshift-install/command/waitfor.go
  cmd/openshift-install/create.go
  cmd/openshift-install/gather.go
  cmd/openshift-install/main.go
  cmd/openshift-install/waitfor.go
  pkg/agent/cluster.go
  pkg/agent/kube.go
  pkg/agent/ocp.go
  pkg/agent/waitfor.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9810 SPLAT-2294: Azure - add mpool datadisks
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/machines/azure/azuremachines.go
  pkg/asset/machines/azure/machines.go
  pkg/types/azure/machinepool.go
  pkg/types/azure/validation/featuregates.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
  pkg/types/azure/validation/platform.go
  pkg/types/validation/machinepools.go
Labels: approved, lgtm, jira/valid-reference

#8711 OCPBUGS-36677: Power VS: Enable incoming traffic on port 5000 during installation in a restricted network
  data/data/powervs/cluster/loadbalancer/sg.tf
  data/data/powervs/cluster/loadbalancer/variables.tf
  data/data/powervs/cluster/main.tf
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9438 OSASINFRA-3238: Improve API and Ingress VIPs validation
  pkg/asset/agent/installconfig_test.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#9825 OCPBUGS-58352: Increase timeout on gcp wait for operation
  pkg/infrastructure/gcp/clusterapi/operation.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9760 CORS-4054: Migrate from SDK v1 to v2 in installconfig
  pkg/asset/installconfig/basedomain.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9762 CORS-4053: Migrate AWS SDK to v2 in cluster/aws
  go.mod
  pkg/asset/cluster/aws/aws.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9759 CORS-4062: Migrate endpoints in pkg/types/aws/platform.go to sdk v2
  pkg/asset/installconfig/aws/permissions.go
  pkg/asset/installconfig/aws/regions.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/tls/cloudprovidercabundle.go
  pkg/types/aws/platform.go
Labels: approved, lgtm, platform/aws, jira/valid-reference

#9815 MGMT-20992: feat: update determineTopologies function
  pkg/asset/manifests/topologies.go
  pkg/asset/manifests/topologies_test.go
Labels: approved, lgtm, jira/valid-reference

#9816 OCPBUGS-57527: Add descriptions back to the aws survey
  pkg/asset/installconfig/aws/platform.go
  pkg/types/aws/regions.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9823 OCPBUGS-57732: Catch gcp destroy cases where the operation is nil
  pkg/destroy/gcp/gcp.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9818 OCPBUGS-59678: PowerVS Support VPC and TG ids
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/powervs/powervs.go
  pkg/asset/installconfig/powervs/client.go
  pkg/asset/installconfig/powervs/metadata.go
  pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
  pkg/asset/installconfig/powervs/mock/powervsmetadata_generated.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/powervs/cluster.go
  pkg/destroy/powervs/cloud-transit-gateways.go
  pkg/destroy/powervs/powervs.go
  pkg/types/powervs/metadata.go
  pkg/types/powervs/platform.go
  pkg/types/powervs/validation/machinepool_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9103 OCPBUGS-39416: OpenStack: Install CI dependencies from rpm
  docs/user/openstack/install_upi.md
  images/openstack/Dockerfile.ci
  upi/openstack/inventory.yaml
  upi/openstack/network.yaml
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9535 CORS-3916, CORS-3920: Use gcp custom endpoints in the installer
  data/data/cluster-api/gcp-infrastructure-components.yaml
  pkg/asset/cluster/gcp/gcp.go
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/ignition/bootstrap/gcp/storage.go
  pkg/asset/installconfig/basedomain.go
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/dns.go
  pkg/asset/installconfig/gcp/services.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/installconfig/installconfig.go
  pkg/asset/installconfig/platformcredscheck.go
  pkg/asset/installconfig/platformpermscheck.go
  pkg/asset/machines/clusterapi.go
  pkg/asset/machines/gcp/zones.go
  pkg/asset/machines/master.go
  pkg/asset/machines/worker.go
  pkg/asset/manifests/cloudproviderconfig.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/gcp/cluster.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/infrastructure_test.go
  pkg/asset/quota/gcp/client.go
  pkg/asset/quota/quota.go
  pkg/destroy/gcp/bucket.go
  pkg/destroy/gcp/bucketobject.go
  pkg/destroy/gcp/gcp.go
  pkg/gather/gcp/gcp.go
  pkg/infrastructure/gcp/clusterapi/clusterapi.go
  pkg/infrastructure/gcp/clusterapi/dns.go
  pkg/infrastructure/gcp/clusterapi/firewallrules.go
  pkg/infrastructure/gcp/clusterapi/iam.go
  pkg/infrastructure/gcp/clusterapi/ignition.go
  pkg/infrastructure/gcp/clusterapi/network.go
  pkg/infrastructure/gcp/clusterapi/operation.go
  pkg/infrastructure/gcp/clusterapi/service.go
  pkg/quota/gcp/gcp.go
  pkg/types/gcp/metadata.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
  vendor/google.golang.org/api/cloudresourcemanager/v1/cloudresourcemanager-api.json
  vendor/google.golang.org/api/cloudresourcemanager/v1/cloudresourcemanager-gen.go
  vendor/google.golang.org/api/serviceusage/v1/serviceusage-api.json
  vendor/google.golang.org/api/serviceusage/v1/serviceusage-gen.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9850 no-jira: images: bump images to go 1.24
  images/installer-altinfra/Dockerfile.ci
  images/installer/Dockerfile.upi.ci
  images/libvirt/Dockerfile.ci
  images/openstack/Dockerfile.ci
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9844 OCPBUGS-59630: Update RHCOS 4.20 bootimage metadata to 9.6.20250701-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9706 SPLAT-2295: Setup additional disks via machine configs
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/machines/machineconfig/disks.go
  pkg/asset/machines/machineconfig/disks_test.go
  pkg/asset/machines/master.go
  pkg/asset/machines/util.go
  pkg/asset/machines/worker.go
  pkg/types/azure/validation/machinepool.go
  pkg/types/azure/validation/machinepool_test.go
  pkg/types/defaults/validation/featuregates.go
  pkg/types/machinepools.go
  pkg/types/validation/machinepools.go
  pkg/types/validation/machinepools_test.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/legacyfeaturegates.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9859 CORS-3992: skip dns zone validation with custom DNS
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
Labels: approved, lgtm, jira/valid-reference
