Repository openshift/installer, pull requests merged in 2025-08, with the labels that each got.

#9862 no-jira: OWNERS: add splat team as approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#9864 OCPBUGS-59542: Generated Nutanix MachineSets for Autoscaling with Failure Domains
  pkg/asset/machines/nutanix/machinesets.go
  pkg/asset/machines/nutanix/machinesets_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#9861 CORS-4083, CORS-4084, CORS-4085: Add Azure custom-dns support in Tech Preview
  cmd/openshift-install/create.go
  data/data/bootstrap/azure/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
  data/data/install.openshift.io_installconfigs.yaml
  go.mod
  go.sum
  pkg/asset/ignition/bootstrap/azure/template.go
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/manifests/dns.go
  pkg/asset/manifests/infrastructure.go
  pkg/asset/manifests/infrastructure_test.go
  pkg/explain/printer_test.go
  pkg/types/azure/platform.go
  pkg/types/azure/validation/featuregates.go
  pkg/types/validation/featuregate_test.go
  pkg/types/validation/installconfig_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machineconfiguration/v1/types.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9863 SPLAT-2355: Added vSphere support for disk setup
  pkg/asset/machines/machineconfig/disks.go
  pkg/asset/machines/master.go
  pkg/asset/machines/util.go
  pkg/asset/machines/vsphere/disks.go
  pkg/asset/machines/worker.go
Labels: approved, lgtm, jira/valid-reference

#9828 AGENT-1205: Extract agent-tui during boot for interactive workflow
  data/data/agent/files/usr/local/bin/agent-extract-tui.sh
  data/data/agent/files/usr/local/bin/get-container-images.sh
  data/data/agent/systemd/units/agent-extract-tui.service
  data/data/agent/systemd/units/agent-interactive-console-serial@.service
  data/data/agent/systemd/units/agent-interactive-console.service
  docs/user/agent/agent-services.md
  docs/user/agent/agent_installer_services-interactive.png
  pkg/asset/agent/image/ignition_test.go
  pkg/asset/agent/image/unconfigured_ignition.go
  pkg/asset/agent/image/unconfigured_ignition_test.go
Labels: approved, lgtm, jira/valid-reference

#9874 OCPBUGS-60240: baremetal: always set external v6 URL on dualstack
  pkg/asset/ignition/bootstrap/baremetal/template.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9887 no-jira: dev docs - add rr capi debugging
  docs/dev/rr-debugging.md
  docs/dev/rr-debugging.patch
Labels: approved, lgtm, jira/valid-reference

#9594 OCPBUGS-53473: Validate clusterNetwork hostPrefix
  pkg/asset/agent/manifests/agentclusterinstall.go
  pkg/asset/agent/manifests/agentclusterinstall_test.go
  pkg/asset/agent/manifests/util_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#9896 AGENT-1205: Update agent-installer-ui tar path
  data/data/agent/systemd/units/agent-extract-tui.service
Labels: approved, lgtm, jira/valid-reference

#9900 OCPBUGS-54598: Update the RHCOS 4.18 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9898 OCPBUGS-60545: Azure: change LB and pubic IP skus to Standard
  upi/azurestack/03_infra.json
  upi/azurestack/04_bootstrap.json
  upi/azurestack/05_masters.json
  upi/azurestack/06_workers.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9902 OCPBUGS-54599: Update the RHCOS 4.17 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9895 [4.18] OCPBUGS-60592: baremetal: always set external v6 URL on dualstack
  pkg/asset/ignition/bootstrap/baremetal/template.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#9912 SPLAT-2463: Added ability to configure CoresPerSocket
  upi/vsphere/powercli/upi-functions.ps1
  upi/vsphere/powercli/upi.ps1
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9915 OCPBUGS-60925: Update the RHCOS 4.19 bootimage metadata
  data/data/coreos/rhcos.json
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9792 CORS-4044, CORS-4045, CORS-4046, CORS-4047, CORS-4048, CORS-4049, CORS-4050, CORS-4051: Add private dns zone section to GCP install config
  data/data/install.openshift.io_installconfigs.yaml
  pkg/asset/cluster/gcp/gcp.go
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/gcp/client.go
  pkg/asset/installconfig/gcp/dns.go
  pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
  pkg/asset/installconfig/gcp/validation.go
  pkg/asset/installconfig/gcp/validation_test.go
  pkg/asset/manifests/dns.go
  pkg/destroy/gcp/dns.go
  pkg/destroy/gcp/gcp.go
  pkg/infrastructure/gcp/clusterapi/dns.go
  pkg/infrastructure/gcp/clusterapi/labels.go
  pkg/types/gcp/dns.go
  pkg/types/gcp/metadata.go
  pkg/types/gcp/platform.go
  pkg/types/gcp/validation/platform.go
  pkg/types/gcp/validation/platform_test.go
Labels: approved, lgtm, platform/google, jira/valid-reference, acknowledge-critical-fixes-only
