Repository openshift/installer, pull requests merged in 2025-01, with the labels that each got.

#9314 OCPBUGS-46260: CVE-2024-45337 bump crypto pkg to v0.31.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#9309 MCO-1457: Clean up MCS CA & TLS cert objects for management
  data/data/manifests/bootkube/machine-config-server-ca-configmap.yaml.template
  data/data/manifests/bootkube/machine-config-server-ca-secret.yaml.template
  data/data/manifests/bootkube/machine-config-server-tls-secret.yaml.template
  go.mod
  go.sum
  pkg/asset/manifests/operators.go
  pkg/asset/manifests/template.go
  pkg/asset/targets/targets.go
  pkg/asset/templates/content/bootkube/machine-config-server-ca-configmap.go
  pkg/asset/templates/content/bootkube/machine-config-server-ca-secret.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/release.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vspherefailuredomainhostgroup.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vspherefailuredomainregionaffinity.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vspherefailuredomainzoneaffinity.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vsphereplatformfailuredomainspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/utils.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/machine/v1/controlplanemachinesetspec.go
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#9304 NO-ISSUE: Deprecate node-joiner scripts
  docs/user/agent/add-node/add-nodes.md
  docs/user/agent/add-node/node-joiner-monitor.sh
  docs/user/agent/add-node/node-joiner.sh
Labels: approved, lgtm, jira/valid-reference

#9238 OCPBUGS-29067: Update MCS Cert and Key files within bootstrap Ignition with UserProvisionedDNS
  pkg/infrastructure/clusterapi/ignition.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#9337 NO-JIRA: remove the types which failed by RHEL-59521 and add the new gpu vm type
  docs/user/ibmcloud/tested_instance_types_x86_64.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9353 NO-ISSUE: Fix owning component name in machine config templates
  data/data/manifests/bootkube/machine-config-server-ca-configmap.yaml.template
  data/data/manifests/bootkube/machine-config-server-ca-secret.yaml.template
  data/data/manifests/bootkube/machine-config-server-tls-secret.yaml.template
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9343 OCPBUGS-47156: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#9319 [release-4.17] OCPBUGS-46432: Power VS: Create region-zone-sysType hierarchy
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/regions.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/machines/worker.go
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9346 OCPBUGS-48119: Always set AllowCrossTenantReplication parameter to false
  pkg/infrastructure/azure/storage.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9321 OCPBUGS-45999: Always set cross_tenant_replication_enabled parameter to false
  data/data/azure/vnet/main.tf
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9265 [release-4.17] OCPBUGS-45344: support additionalNTPSources in node-joiner tool
  pkg/asset/agent/image/ignition.go
  pkg/asset/agent/joiner/clusterinfo.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#9360 no-jira: images: UPI: use ART repo dir
  images/installer/Dockerfile.upi.ci
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9358 no-jira: Remove myself from reviewers list
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9355 no-jira: gather: allow unconditional gather in CI
  cmd/openshift-install/create.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only

#9302 OCPBUGS-46010: wait for at least 3 kube-apiserver instances
  data/data/bootstrap/files/usr/local/bin/wait-for-ha-api.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9369 [release-4.16] OCPBUGS-48442: Ensure rendezvousIP is checked against host IP
  pkg/asset/agent/agentconfig/agenthosts.go
  pkg/asset/agent/agentconfig/agenthosts_test.go
  pkg/asset/agent/common.go
  pkg/asset/agent/manifests/nmstateconfig.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9373 OTA-1310: data/manifests/bootkube/cvo-overrides: Default to eus-4.12
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9359 OCPBUGS-48437: PowerVS: limit by resourceGroupID
  pkg/destroy/powervs/cloud-instance.go
  pkg/destroy/powervs/cloud-sshkey.go
  pkg/destroy/powervs/cloud-subnet.go
  pkg/destroy/powervs/cloudobjectstorage.go
  pkg/destroy/powervs/powervs.go
  pkg/destroy/powervs/publicgateway.go
  pkg/destroy/powervs/securitygroup.go
  pkg/destroy/powervs/serviceinstance.go
  pkg/destroy/powervs/vpc.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#9374 CORS-3721: bump default release image to 4.19
  pkg/asset/releaseimage/default.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9375 CORS-3722: bump default channel to stable-4.19
  data/data/manifests/bootkube/cvo-overrides.yaml.template
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9338 OCPBUGS-47663: [release-4.16] Power VS: Create region-zone-sysType hierarchy
  pkg/asset/cluster/tfvars/tfvars.go
  pkg/asset/installconfig/platformprovisioncheck.go
  pkg/asset/installconfig/powervs/regions.go
  pkg/asset/installconfig/powervs/validation.go
  pkg/asset/installconfig/powervs/validation_test.go
  pkg/asset/machines/worker.go
  pkg/types/powervs/powervs_regions.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9356 OCPBUGS-48256: Run iscsiadm for agent-based iSCSI installations
  data/data/agent/systemd/units/iscsiadm.service
  docs/user/agent/agent-services.md
  docs/user/agent/agent_installer_services-install_workflow.png
  pkg/asset/agent/image/ignition.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#8742 COS-3013: overlay node image before bootstrapping if necessary
  data/data/bootstrap/files/etc/systemd/system-generators/node-image-overlay-generator
  data/data/bootstrap/files/etc/systemd/system/node-image-finish.service
  data/data/bootstrap/files/etc/systemd/system/node-image-overlay.service
  data/data/bootstrap/files/etc/systemd/system/node-image-overlay.target
  data/data/bootstrap/files/etc/systemd/system/node-image-pull.service
  data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
  data/data/bootstrap/files/usr/local/bin/node-image-overlay.sh
  data/data/bootstrap/files/usr/local/bin/node-image-pull.sh.template
  data/data/bootstrap/systemd/common/units/crio-configure.service.template
  data/data/bootstrap/systemd/common/units/kubelet.service.template
  data/data/bootstrap/systemd/common/units/release-image-pivot.service.template
  pkg/asset/ignition/bootstrap/common.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9341 OCPBUGS-46596: aws/permissions - defaults ec2:DescribeInstanceTypeOfferings
  pkg/asset/installconfig/aws/permissions.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#9387 OCPBUGS-48719: Add new tested azure arm instance type to doc
  docs/user/azure/tested_instance_types_aarch64.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9292 no-jira: docs(user): fix grammer in upi install step
  docs/user/metal/install_upi.md
Labels: approved, lgtm, ok-to-test, jira/valid-reference, acknowledge-critical-fixes-only

#9377 OCPBUGS-48570:[Nutanix] Installation failed with timeout when uploading images to PC
  data/data/install.openshift.io_installconfigs.yaml
  pkg/infrastructure/nutanix/clusterapi/clusterapi.go
  pkg/types/nutanix/defaults/platform.go
  pkg/types/nutanix/defaults/platform_test.go
  pkg/types/nutanix/helpers.go
  pkg/types/nutanix/platform.go
  pkg/types/nutanix/validation/platform.go
  pkg/types/nutanix/validation/platform_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9333 OCPBUGS-47477: aws: skip dead zones on us-east-1 when discovering AZs
  pkg/asset/installconfig/aws/availabilityzones.go
  pkg/types/aws/defaults/platform.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9391 MGMT-19771: Convert IDS to proper IDMS manifest
  pkg/asset/imagebased/configimage/configiso.go
  pkg/asset/imagebased/configimage/imagedigestmirrorset.go
  pkg/asset/imagebased/configimage/imagedigestmirrorset_test.go
  pkg/asset/imagebased/configimage/imagedigestsources.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9384 OCPBUGS-47489: pkg/gcp/destroy: add waits to prevent leaks during heavy load
  pkg/destroy/gcp/address.go
  pkg/destroy/gcp/backendservice.go
  pkg/destroy/gcp/cloudresource.go
  pkg/destroy/gcp/disk.go
  pkg/destroy/gcp/firewall.go
  pkg/destroy/gcp/forwardingrule.go
  pkg/destroy/gcp/gcp.go
  pkg/destroy/gcp/healthcheck.go
  pkg/destroy/gcp/httphealthcheck.go
  pkg/destroy/gcp/image.go
  pkg/destroy/gcp/instance.go
  pkg/destroy/gcp/instancegroup.go
  pkg/destroy/gcp/network.go
  pkg/destroy/gcp/route.go
  pkg/destroy/gcp/router.go
  pkg/destroy/gcp/subnetwork.go
  pkg/destroy/gcp/targetTCPProxies.go
  pkg/destroy/gcp/targetpool.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#9381 OCPBUGS-48645: azure: use separate /var to avoid growfs timeouts
  pkg/asset/ignition/bootstrap/common.go
  pkg/asset/ignition/machine/master.go
  pkg/asset/ignition/node.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9406 OCPBUGS-49362: [Nutanix] Installation failed with timeout when uploading images to PC
  data/data/install.openshift.io_installconfigs.yaml
  pkg/infrastructure/nutanix/clusterapi/clusterapi.go
  pkg/types/nutanix/defaults/platform.go
  pkg/types/nutanix/defaults/platform_test.go
  pkg/types/nutanix/helpers.go
  pkg/types/nutanix/platform.go
  pkg/types/nutanix/validation/platform.go
  pkg/types/nutanix/validation/platform_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#9409 [release-4.17] OCPBUGS-41300: Azure: Update SecurityType passed in at Image creation
  pkg/infrastructure/azure/azure.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#9361 OCPBUGS-48228: Envtest: Configure IPv6 service network for API Service
  pkg/clusterapi/localcontrolplane.go
  pkg/clusterapi/system.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#9326 OSASINFRA-2571: Add quota validation for server group
  pkg/asset/installconfig/openstack/validation/cloudinfo.go
  pkg/asset/quota/openstack/openstack.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#9408 CORS-3830: Add missing supported platforms in top-level README
  README.md
  docs/dev/libvirt/OWNERS
  docs/dev/libvirt/README.md
  docs/dev/libvirt/customization.md
  docs/dev/libvirt/load_balancer.md
  docs/user/ovirt/OWNERS
  docs/user/ovirt/customization.md
  docs/user/ovirt/images/oVirt-logo.png
  docs/user/ovirt/install_ipi.md
  docs/user/ovirt/install_upi.md
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only

#9398 OCPBUGS-48089: validate hostPrefix to be the same when multiple clusternetwork CIDRs are present
  data/data/install.openshift.io_installconfigs.yaml
  docs/user/customization.md
  pkg/types/installconfig.go
  pkg/types/validation/installconfig.go
  pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#9392 OCPBUGS-46549: Update RHCOS 4.19 bootimage metadata to 9.6.20250121-0
  data/data/coreos/rhcos.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only
