Repository openshift/installer, pull requests merged in 2025-10, with the labels that each got.

#9991 CORS-4256: Add PSC Endpoint to the installconfig
  data/data/install.openshift.io_installconfigs.yaml
  pkg/types/gcp/platform.go
Labels: approved, lgtm, jira/valid-reference, verified

#9956 OCPBUGS-60538: Update assisted-service dependencies
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/LICENSE
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/client/installer/get_detailed_supported_features_parameters.go
  vendor/github.com/openshift/assisted-service/client/installer/get_detailed_supported_features_responses.go
  vendor/github.com/openshift/assisted-service/client/installer/installer_client.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_register_disconnected_cluster_parameters.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_register_disconnected_cluster_responses.go
  vendor/github.com/openshift/assisted-service/client/operators/operators_client.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_parameters.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_responses.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_parameters.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_responses.go
  vendor/github.com/openshift/assisted-service/models/boot.go
  vendor/github.com/openshift/assisted-service/models/bundle.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/connectivity_remote_host.go
  vendor/github.com/openshift/assisted-service/models/custom.go
  vendor/github.com/openshift/assisted-service/models/disconnected_cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/disk_encryption.go
  vendor/github.com/openshift/assisted-service/models/feature.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/fencing_credentials_params.go
  vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  vendor/github.com/openshift/assisted-service/models/host.go
  vendor/github.com/openshift/assisted-service/models/host_role.go
  vendor/github.com/openshift/assisted-service/models/host_role_update_params.go
  vendor/github.com/openshift/assisted-service/models/host_update_params.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/image_type.go
  vendor/github.com/openshift/assisted-service/models/incompatibility_reason.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/github.com/openshift/assisted-service/models/load_balancer.go
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  vendor/github.com/openshift/assisted-service/models/mtu_report.go
  vendor/github.com/openshift/assisted-service/models/operator.go
  vendor/github.com/openshift/assisted-service/models/secure_boot_state.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  vendor/github.com/openshift/assisted-service/models/validations/dns_validation.go
  vendor/github.com/openshift/assisted-service/models/versioned_host_requirements.go
  vendor/github.com/openshift/assisted-service/pkg/validations/validations.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#8986 OCPBUGS-41567: Clean up baremetal bootstrap systemd dependencies
  data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-dnsmasq.container
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-httpd.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.container.template
  data/data/bootstrap/baremetal/files/etc/containers/systemd/metal3-baremetal-operator.container
  data/data/bootstrap/baremetal/systemd/units/wait-iptables-init.service
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, verified
